### ISSUE TITLE
[ENDPOINT] Proposed design change for <GetShopReceiptTransactionsByReceipt> 

### ISSUE THREAD

**Issue by NicholasPegler-LW** [etsy/open-api#101]
**Current Endpoint Design**
The new v3 response does not match that of the v2, there are some missing elements.

**Proposed Endpoint Design Change**
* Variations node is missing
  * Not able to determine any Personalization options 
* Does not appear to be an endpoint to retrieve the data 

**Why are you proposing this change?**
To match existing functionality

**Comment by knotheory** [comment]
Yes please! We need this.

**Comment by Gareth064** [comment]
These two bits of information needs to be in the API, like v2, otherwise my app becomes useless.

**Comment by Gareth064** [comment]
@harjas @etsyachristensen @ataetsy @capndesign 
Hi Guys, can any of you please comment on this or one any of the issues at the end of this comment, regarding getting the Variations and Personalization text when you retrieve and order/receipt/transaction etc. I really need this or my app becomes useless as it's all about helping people manage their orders of personalised items.
#111
#142

**Comment by main24** [comment]
Variations and personalization in transactions is one of stoppers for our migration.

Without variations it's not 100% possible to identify which variant was ordered. Transactions do have `product_id`, but `product_id` is being changed in the listing on every update of listing's inventory via API, thus there will be the following situation:
1. a variant with id **X** of a listing **Y** has been ordered (order **№1**);
2. executed API request for update inventory of any variant of the listing **Y** -- all ids of variants now changed, **X** becomes **X1**;
3. requested transactions of the order 1 via API;

Order **№1** still points at **X** in the `product_id` attribute and now it's not possible to get product data by **X** anymore. I'm afraid it's not 100% possible to track down all changes of `product_id` with all updates of inventory as it looks like there might be other edge cases which lead to missing one or more revisions, so the chain of updates would be broken and it would be not possible to identify variants in previously created orders.

**Comment by joaquin102** [comment]
This is literally the most important feature of the api. Without it, most of us won't be able to migrate to V3. Please Etsy consider to keep this from V2.

**Comment by Gareth064** [comment]
@harjas @etsyachristensen @ataetsy @capndesign 
Anybody able to comment on the state of getting variation and personalization data? This is starting to panic me, and others it seems, as it is going to ruin our apps if we can't get this before v2 is turned off.

**Comment by harjas** [comment]
Hey everyone! Sorry for the delay in getting back to y'all but we've been a bit short-staffed. We're hard at work trying to accommodate as much of your feedback as possible. We're a small team and we can only work on so many issues in parallel 😅  but we hear you about variations and personalization. We'll do our best to get variations out ASAP

**Comment by shoecake** [comment]
I just had to +1 this issue. 

I have been extending our in house order management system exclusively with the V3 API ready for our etsy launch. If the above is true re product_id then this is a complete show stopper. I don't want to imagine the chaos if we started printing invoices with the wrong or no sku on them.

IMO the whole API should be more SKU orientated. Any seller of a decent size will be organising their products / stock via SKUs, there is no other logical way.

**Comment by timalin** [comment]
Same here, I opened a separate topic because this one was buried.

The current implementation in v2 works perfectly: while calling for Receipts I can include Transactions, which have product_data with SKU and other information.
As it stands now with v3, I would need to call Receipts, then call Transactions, which only has some product_id, which apparently cannot be used anyway.

**Comment by shoecake** [comment]
I am starting to wonder if I should shelve all of my code and start again with the V2 API. We were going to launch with around 1,000 products next week, I doubt that will be happening now.

**Comment by timalin** [comment]
You should be able to modify the code to work with v2 rather quickly. There's no set date for when v2 will stop working, but it won't happen until 2022.

**Comment by WheelerCC** [comment]
I agree with all of the above ^.^ I think realistically, getShopReceipts, getShopReceiptTransactionsByReceipt, and getListingProduct for the SKUs of the receipt could all be provided under a single endpoint.

https://github.com/etsy/open-api/issues/111#issuecomment-898775695

**Comment by etsyachristensen** [comment]
This is done. We pushed this out last week I believe. Sorry for not replying back. Been a busy time.

When you call the `getShopReceiptTransactionsByShop` or `getShopReceiptTransaction` endpoint you will get the `variations` array in the transaction object. Since the receipt endpoints now also include the transactions, this information will show up in those endpoints as well. For example:
![image](https://user-images.githubusercontent.com/83842847/134531157-5892b811-b969-48c2-b52c-611e0c5929d5.png)

I'm still working on adding the SKU to the transaction endpoints but it's complicated by the fact that a sku could be tied to a variation and not just a listing.
