### ISSUE TITLE
getListings - listing object should include sku array

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#104]
**Current Endpoint Design**
According to the documentation, the [getListing](https://www.etsy.com/openapi/developers#operation/getListings) API returns a listing object without a list of skus, which was a field that existed in the [v2 API](https://www.etsy.com/developers/documentation/reference/listing) 

**Proposed Endpoint Design Change**
Add the sku field to the returned json object

**Why are you proposing this change?**
The field is used as part of the logic of my app.

**Comment by etsyachristensen** [comment]
@assaflei The skus can be fetched from the `getListingInventory` endpoint. It's an extra call but it is possible to get the skus there. The `sku` field is on each product in the products array. We may revisit the possibility of adding the skus to the `getListing` endpoint but that change would affect several things so we have to plan it out a bit.

**Comment by assaflei** [comment]
@etsyachristensen this proposal is highly problematic with my scenario
getListingInventory is an API call designed per one listing
In my logic I need to get details for bulk of listings (can be tens and hundreds of shop's listings)
This means that I need to use several calls to get shop listings and than iterate on each listing to get its SKU details
Rate limits and response times make this approach impossible to use in my processes... 
What is your suggestion for bulk retrieval of such kind?

**Comment by assaflei** [comment]
@etsyachristensen this issue had been left aside for some time, any chance of getting it back to the table?
The new design will cause hard rate limit problems since there is a need to perform an API call for each listing to get its related SKUs, pretty unreasonable change to the API, especially when all this functionality existed on the previous version

**Comment by etsyachristensen** [comment]
@assaflei We are actually working on adding the SKU to the getListing endpoint (and other endpoints that return listing data). Since the SKU is considered private data, we have to do this in a way that won't require a scope but will only expose the SKU to apps authorized on that shop. We will update as soon as we have something for you to see.

**Comment by assaflei** [comment]
Is the issue of privacy of this data new to V3? I don't remember it was on the V2 version, but I might have just didn't notice it...
Just verifying, the API of findAllActiveListingsByShop will enjoy this addition, right?
