### ISSUE TITLE
[DOCS] Documentation seems to be broken.

### ISSUE THREAD

**Issue by Dmarcotrigiano** [etsy/open-api#113]
**Link to Documentation Issue**
https://developer.etsy.com/documentation/reference

**What would you like to change?**
Something went wrong...
Error downloading https://www.etsy.com/openapi/generated/oas/3.0.0.json Failed to fetch
Stack trace

ReDoc Version: 2.0.0-rc.48
Commit: 7b78e75

**Why are you proposing this change?**
I cannot see the documentation for the API on the website.

**Comment by capndesign** [comment]
Ah, good catch @Dmarcotrigiano! The link should actually be https://developers.etsy.com/documentation/reference (developers with an `s` at the end). We’ll update that redirect so it works as expected. I’ll reply here when that’s fixed, but the link I provided should work fine.

**Comment by Dmarcotrigiano** [comment]
Wonderful, happy to help. Does this mean I can have my intake form looked
at? :-)

**Comment by capndesign** [comment]
@Dmarcotrigiano It’s hard to map GitHub usernames to Etsy apps, but I’d be happy to help get you sorted. These comments are probably not the best place to do it, but if you mention me by name in your support issue, I can take a look.

I’ll close this issue out once the fix is deployed.

**Comment by SEPAHL** [comment]
For me also the link with the "s" https://developers.etsy.com/documentation/reference/  shows the same issue

Something went wrong...
Error downloading https://www.etsy.com/openapi/generated/oas/3.0.0.json NetworkError when attempting to fetch resource.

Stack trace
ReDoc Version: 2.0.0-rc.48
Commit: 7b78e75

**Comment by turboturtleD** [comment]
Both of the links you provided above work fine for me.  Maybe blow away your cookies and cache?

**Comment by Dmarcotrigiano** [comment]
A fix has been pushed, they work now.

**Comment by harjas** [comment]
closing this issue since this seems to be fixed
