### ISSUE TITLE
[FEATURE] Critical need to automate migrating existing oAuth v1 tokens to v2

### ISSUE THREAD

**Issue by mattkingshott** [etsy/open-api#114]
**Is your feature request related to a problem?**

The documentation states:

```
We currently do not support converting an OAuth 1.0 token into an OAuth 2.0 token.
```

This is a critical problem as outlined below...

I have many customers that have connected their shops to my application using oAuth V1. Many of these users have also added multiple shops. In addition, I have background tasks that use their tokens to fetch new data.

Manually migrating to oAuth V2 will cause a lot of friction, as every existing oAuth V1 token will need to be replaced, which will require the user to complete the handshake agreement for all of their shops. Further, if they fail to do so, the background tasks will start to fail once the V2 API is retired.

**Describe the solution you'd like**

Create a migration API endpoint that allows us to supply the following parameters:

1. The application API keystring.
2. The shop ID.
3. The oAuth V1 consumer key.
4. The oAuth V1 consumer secret.
5. The shop's oAuth V1 token supplied for all private API V2 requests.

The endpoint would validate this information against its oAuth V1 database, and then return a valid oAuth V2 access token response as [documented here](https://developers.etsy.com/documentation/essentials/oauth2/#step-3-request-an-access-token):

```json
{
    "access_token": "12345678.O1zLuwveeKjpIqCQFfmR-PaMMpBmagH6DljRAkK9qt05OtRKiANJOyZlMx3WQ_o2FdComQGuoiAWy3dxyGI4Ke_76PR",
    "token_type": "Bearer",
    "expires_in": 3600,
    "refresh_token": "12345678.JNGIJtvLmwfDMhlYoOJl8aLR1BWottyHC6yhNcET-eC7RogSR5e1GTIXGrgrelWZalvh3YvvyLfKYYqvymd-u37Sjtx"
}
```

Doing this would allow the application to migrate all users without requiring them to do anything.

**Describe alternatives you've considered**

The only alternative would be to require the users to do the re-authentication process manually. In addition, if they failed to do so before the sunsetting of API V2, the application and its background tasks would cease to function.

**Comment by capndesign** [comment]
Hi @mattkingshott! This is a great idea and we have it on our roadmap. We’ll have something to share in the next few weeks.

Thanks for taking the time to write up this detailed request. It’ll make implementation a lot easier for us.

**Comment by etsyachristensen** [comment]
@mattkingshott If you haven't seen already, we've added a token_exchange grant type to allow for automated exchange of OAuth1 to OAuth2 tokens. Here's the documentation: https://developers.etsy.com/documentation/essentials/authentication#exchange-oauth-10-token-for-oauth-20-token
