### ISSUE TITLE
[BUG] Version 3 is crippled with no support for fields or includes

### ISSUE THREAD

**Issue by mattkingshott** [etsy/open-api#115]
**Describe the bug**

The documentation states:

```
We no longer support fields nor includes query parameters to return partial resources or additional associated resources in responses.
```

Why?! This is a critical component to the API. It would be absurd to send hundreds, if not thousands of separate API requests to fetch related data. I'd hit the API limit well before finishing data imports with some shops.

However, Since this seems to be the setup for v3, all I can do is make a plea to keep v2 running parallel to v3 and not to sunset it in the future, or at least allow existing apps to use v2. Otherwise, I'm going to have to close down my business / app as there will be no way to make it viable.

**Comment by benjymouse** [comment]
I believe the Etsy developers are looking into a solution for associations. You should check out this issue: https://github.com/etsy/open-api/issues/96 - you might want to add which ones are most important for your app ;)

**Comment by mattkingshott** [comment]
Thanks @benjymouse. 

I've added my requirements, but I'm not holding out much hope. They say they're working on a solution, and yet I received an email saying that they were, more-or-less, feature complete with v3. Given the impact / testing that would need to be done to add associations, it seems a bit late in the game, but you never know...

Personally, I was hoping that v3 would add a whole bunch of missing / much-needed functionality, but it seems like they've primarily stripped critical functionality from it.

**Comment by mattkingshott** [comment]
Not trying to be overly negative, just very worried!

**Comment by etsyachristensen** [comment]
@mattkingshott We've added support for associations on listings for Images, Shop and User objects on the getListing and getListingsByListingIds.

**Comment by mattkingshott** [comment]
Thank you @etsyachristensen. It’s a good start, but what about other associations? I have outlined my needs on #96.
