### ISSUE TITLE
Refreshed Access Token Expires In 3600 (not 90 days like documentation states) [BUG] 

### ISSUE THREAD

**Issue by johnvoncolln** [etsy/open-api#116]
**Describe the bug**
When you get a refreshed access token, it is valid for only 3600 seconds. Documentation states it should be 90 days.

**To Reproduce**
Go through Oauth2 Process, then request a new token through the refresh_token grant

**Expected behavior**
returned response should have 'expires_in' should equal '7,776,000' ?

**Comment by turboturtleD** [comment]
The access token is only good for 1 hour (3600 seconds), the refresh token is good for 90 days.  You need to get a new access token using your refresh token once that hour window has lapsed - the new token will contain a new access token (good for another 1 hour) as well as a new refresh token (good for 90 days).

https://www.etsy.com/developers/documentation/getting_started/oauth2#section_phase_2_obtain_access_and_refresh_token

*The access token is what you use to make requests to the Etsy API, and has a relatively short lifetime (1 hour). The refresh token can be used to obtain a new access token through the refresh_token grant, and has a longer lifetime (90 days).*

**Comment by johnvoncolln** [comment]
Ahh, got it.  The wording made me think that the initial access token was good for an hour and the token received by using the refresh token was good for 90 days.  

Thanks for clearing that up for me!

**Comment by craggamuffin** [comment]
How do the developers of the API think that it's practical to have to refresh every hour?

**Comment by akvadrako** [comment]
> How do the developers of the API think that it's practical to have to refresh every hour?

I think the idea is to use the refresh_token like a normal access token, and before each "session" just get a new access token.
