### ISSUE TITLE
[Enhancement] Allow production partner when creating a listing

### ISSUE THREAD

**Issue by Kevchan85** [etsy/open-api#118]
**Describe the bug**
When creating a listing with 'another company or person', 'finished product' and something within either the ['made to order' or 'recently'] sections then it will say I cannot sell that product

**To Reproduce**
use Listing api to create a product with said attributes above.

**Expected behavior**
I expect to be able to pass production partners, through to clear this error.

**Screenshots**
Here is the create listing console from Etsy where I am able to select a production partner 
![Screen Shot 2021-06-22 at 11 59 54 AM](https://user-images.githubusercontent.com/17604489/122984058-7396b380-d351-11eb-83fd-83400ea147bd.png)

**Additional context**
None

**Comment by etsyachristensen** [comment]
@Kevchan85 just wanted to update you on this. This is on our priority list of things to do. I don't have an ETA at this time but it's very near the top of the list so we hope to have this out soon.

**Comment by etsyachristensen** [comment]
This was done last month. Sorry for the delay in letting you know.
