### ISSUE TITLE
[BUG] CORS Headers not present

### ISSUE THREAD

**Issue by rkara** [etsy/open-api#119]
**Describe the bug**
POST requests made to `https://api.etsy.com/v3/public/oauth/token`, as part of authentication, are not being made successfully due to CORS errors on client-side.

**To Reproduce**
Perform a POST request to `https://api.etsy.com/v3/public/oauth/token` from within a web application such as Angular.

**Expected behavior**
When the OPTIONS request to `https://api.etsy.com/v3/public/oauth/token` is made, an `Access-Control-Allow-Origin` header should be in the response, which should allow the POST request to be made from within a Web Application.

This same header should be available when retrieving data from the new v3 API endpoints as well.  

**Screenshots**

**Additional context**
[Source Code](https://github.com/rkara/etsy) for a demo application is available on [Git Hub](https://github.com/rkara/etsy).

The [AppAuthenticationService](https://github.com/rkara/etsy/blob/main/src/app/shared/services/authentication.service.ts) handles authentication, and the keystring is set within the [environment.ts](https://github.com/rkara/etsy/blob/main/src/environments/environment.ts) file.

**Comment by rkara** [comment]
After further investigation, it appears that the headers are not included in any of the API endpoints.

**Comment by harjas** [comment]
Hi @rkara! Some of the controls we have on the OAuth2 flow (for example, require state and PKCE), are not particularly useful in an application without hidden state (on the client-side, for instance). So at this moment, we only have support for the OAuth flow via the server and don't plan on supporting it via the client. 

Even for OpenAPI v2, we didn't support CORS for OAuth. I hope this gives you some clarity and helps you adjust your approach!
