### ISSUE TITLE
[DOCS] 404 from link on V3 API Documentation

### ISSUE THREAD

**Issue by Dmarcotrigiano** [etsy/open-api#121]
**Link to Documentation Issue**
https://developers.etsy.com/documentation/reference/#section/Authentication
Broken Link: ...can be found<a href="https://developers.etsy.com/developers/documentation/getting_started/oauth2"> here </a>

**What would you like to change?**
Fix the routing to the correct endpoint.

**Why are you proposing this change?**
So that developers may better diagnose oauth2 issues without running into 404s on the documentation.

**Comment by harjas** [comment]
@Dmarcotrigiano what page did you find this broken link in? 

We actually are in the process of finishing our documentation tirekick and will be fixing some other broken links we found too. Curious if this is one of them or something we may have missed.

**Comment by Dmarcotrigiano** [comment]
@harjas The link is found at the link provided: https://developers.etsy.com/developers/documentation/getting_started/oauth2
on the line "...can be found here"

**Comment by harjas** [comment]
Ah! good catch! We'll get this fix out asap! thanks for letting us know!

**Comment by harjas** [comment]
@Dmarcotrigiano this is now fixed! Let us know if you find any other broken links :)
