### ISSUE TITLE
[FEATURE] Please bring back title in Transaction endpoints

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#123]
**Is your feature request related to a problem? Please describe.**
Our app tracks the title field in the responses from the Transaction endpoints. This helps our client keep an audit trail of changes they make to a listing over its lifetime.

**Describe the solution you'd like**
Title to be included in the Transaction responses.

**Describe alternatives you've considered**
Use v2 API until it is sunset, making additional API calls to the Listings endpoints.

**Additional context**

**Comment by harjas** [comment]
Hey @benjymouse! Thanks for letting us know. Our intent here was that the title and description was being returned with every transaction and they belonged to the same listing, so in some ways making that information redundant. 

We just pushed the change to add the title and description back in. Let us know if this works as expected for you!

**Comment by benjymouse** [comment]
That's awesome.  Thanks @harjas much appreciated. I'll let you know if any issue.

**Comment by benjymouse** [comment]
It's working as expected again, thanks @harjas :)
