### ISSUE TITLE
[BUG] Having trouble accessing the V3 endpoints

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#128]
**Describe the bug**
Hi I am currently trying to access the v3 endpoints but I am unable to do so. I don't have any permissions but since we're in Q3, is Etsy's api public?

**Comment by turboturtleD** [comment]
You will likely need to post more specifics for anyone to be able to help you out with this.

Have you registered a callback URL for you app?
Are you able to complete the OAuth2 flow?

The v3 API is now considered open as far as I understand and should be open to any developers who have created credentials on the Etsy developers page.

**Comment by amandalik** [comment]
@turboturtleD I'm having an issue completing the auth flow with the error saying that my redirect uri is not permitted. I'm not sure where (and if) I should register the redirect uri.

**Comment by turboturtleD** [comment]
You need to register your callback/redirect URL before you can use it (which you can do yourself).  Check this post, I registered a new one yesterday and it worked perfectly:

https://github.com/etsy/open-api/issues/126#issuecomment-872368628

**Comment by amandalik** [comment]
Figured it out, closing ticket!
