### ISSUE TITLE
[BUG] getShopReceiptTransactionsByListing

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#13]
**Link to Documentation Issue**
https://www.etsy.com/openapi/developers#operation/getShopReceiptTransactionsByListing

**What would you like to change?**
Change image_listing_id to listing_image_id 

**Why are you proposing this change?**
Assumption is that we can lookup the image for a transaction using the https://www.etsy.com/openapi/developers?#operation/getListingImage endpoint. If true, then for consistency they should be named the same.

**Comment by harjas** [comment]
@benjymouse Closing this since this seems to have been fixed
