### ISSUE TITLE
[BUG] should_auto_renew not saving when updating listing

### ISSUE THREAD

**Issue by MrPetFtz** [etsy/open-api#130]
**Describe the bug**
When running a PUT request to update a listing's `should_auto_renew` field to `False`, it remains `True`, and the following error is returned:
`{'error': 'There was a problem with /quantity : cannot be greater than 999'}`

**To Reproduce**
**IN PYTHON:**

```
import requests

shop_id = {SHOP_ID}

listing_id = {LISTING_ID}

h = {'x-api-key': '{API_KEY}', 'authorization': 'Bearer {TOKEN}'}

d = {'should_auto_renew': False}

r = requests.put(f'https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}', data=d,
                   headers=h)
print(r.json())
```

**Expected behavior**
`should_auto_renew` should be set to `False` for the indicated listing_id

**Screenshots**
N/A

**Additional context**
Changing the `should_auto_renew` field should not be dependent on any other listing field.

**Comment by Jonathansw** [comment]
Hey @MrPetFtz could you email developers@etsy.com with the `shop_id` and the `listing_id` you used here and mention your github issue id.  I can take a look at this issue!

**Comment by MrPetFtz** [comment]
> Hey @MrPetFtz could you email [developers@etsy.com](mailto:developers@etsy.com) with the `shop_id` and the `listing_id` you used here and mention your github issue id. I can take a look at this issue!

Hi @Jonathansw I have just emailed with that information. Thank you for the quick reply here!

**Comment by etsyachristensen** [comment]
@MrPetFtz We deployed an update late last week that hopefully has fixed this issue. Can you please test again and confirm. If it's working please close this issue. Thanks!

**Comment by MrPetFtz** [comment]
Confirmed. Closing. Thanks so much!

**Comment by MrPetFtz** [comment]
Reopening because the `should_auto_renew` JSON value returned when sending the PUT request does not reflect the change from the request. Fore example the code:

```
import requests

shop_id = {SHOP_ID}

listing_id = {LISTING_ID}

h = {'x-api-key': '{API_KEY}', 'authorization': 'Bearer {TOKEN}'}

d = {'should_auto_renew': False}

r = requests.put(f'https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}', data=d,
                   headers=h)
print(r.json()['should_auto_renew'])
```
returns
`True`

While it should return
`False`

**Comment by etsyachristensen** [comment]
@MrPetFtz Is the listing you are having issues with the same one you emailed us a couple weeks ago? I want to see if I can duplicate this. I was able to test it successfully with a listing and only modified the should_auto_renew variable.

**Comment by etsyachristensen** [comment]
@MrPetFtz Is it possible for you to ouput the full curl query that's being sent to the API? You can email this to at developers@etsy.com and reference Bug report #130. Thanks!

**Comment by MrPetFtz** [comment]
> @MrPetFtz Is the listing you are having issues with the same one you emailed us a couple weeks ago? I want to see if I can duplicate this. I was able to test it successfully with a listing and only modified the should_auto_renew variable.

It's every listing including that one. The original issue is resolved, however in the JSON that's returned by the API, it still shows the 'should_auto_renew' key's value as the value it was before the PUT request.

**Comment by etsyachristensen** [comment]
I updated the title, just so it's easier to keep track of these things. We will get back to this issue as soon as possible. It's a bit of a head scratcher at the moment because it should be showing you the change immediately on the response. It's on the list though and we'll resolve it as soon as possible.

**Comment by MrPetFtz** [comment]
Thank you @etsyachristensen I was able to build the prototype with the fix you guys implemented, so much appreciated. I'll check back here for the final fix when we're ready to bring this feature into production.

**Comment by etsyachristensen** [comment]
Ok this issue is fixed now. All fields should save and should appear correctly in the returned data.
