### ISSUE TITLE
[ENDPOINT] Proposed design change for getShopReceiptTransactionsByShop

### ISSUE THREAD

**Issue by nafberger** [etsy/open-api#131]
**Current Endpoint Design**
currently if u want to get the orders for a shop you have to get them all, since day 1, this is a bit insane, we would love to get only the transactions after a certain date. this is how it is with all modern api's

**Comment by etsyachristensen** [comment]
@nafberger I think you're looking at the wrong endpoint. To get the orders for a shop you would use [getShopReceipts](https://developers.etsy.com/documentation/reference#operation/getShopReceipts) and then use the `min_created`/`max_created` or `min_last_modified`/`max_last_modified` inputs to set the date ranges for what you want to retrieve.
