### ISSUE TITLE
[BUG] Cannot activate listings - Listings must have a complete translation in the shop's primary language

### ISSUE THREAD

**Issue by Kimmax** [etsy/open-api#132]
### Describe the bug
Activating listings (Created via API) fails with the message:
> Listings must have a complete translation in the shop's primary language: de

Fair enough, however when I try to create said translation (Using the `createListingTranslation` endpoint) I get another fail:
> Cannot create or delete Translations in a Shop's primary language

The shop's primary language is indeed `de`.

###  To Reproduce
Create listing using the `createDraftListing` endpoint. Following fields are populated:
- quantity = 999
- title
- description
- price
- who_made = i_did
- when_made = made_to_order
- taxonomy_id = 1988
- shipping_profile_id
- materials
- processing_min = 1
- processing_max = 2
- recipient = unisex_adults
- styles
- tags
- is_personalizable = true

Create variations using the `updateListingInventory` endpoint. Following fields are populated:
- products
  - property_values
    - property_id = 501
    - values
  - sku
  - offerings
    - price
    - quantity = 999
    - is_enabled = 1
- quantity_on_property = []
- price_on_property = 501

Upload images using the `uploadListingImage` endpoint (x6). Following fields are populated:
- overwrite = true
- rank
- image

Finally, try to activate the listing using the `updateListing` endpoint. Following fields are populated:
- should_auto_renew = true
- state = 'active'

```
REQUEST=[
    requestMethod=PUT,
    requestUri=https://openapi.etsy.com/v3/application/shops/23690785/listings/1036032376,
    requestHeaders=[
        Content-Type: application/x-www-form-urlencoded,
        Authorization: xxxxxx,
        x-api-key: xxxxxxxx
    ],
    requestBody=should_auto_renew=1&state=active
    ], 
    RESPONSE=[
        statusCode=400,
        responseHeaders=[
            server: Apache,
            x-cloud-trace-context: bc09c5b88061a3d553f7d98342be3b8d/16542350068897502134;o=1,
            x-etsy-request-uuid: EuxZcGNR-siA58n6pv-9q0oT6Ga9,
            x-limit-per-second: 10,
            x-remaining-this-second: 9,
            x-limit-per-day: 10000,
            x-remaining-today: 6827,
            content-length: 119,
            content-type: application/json,
            date: Mon, 12 Jul 2021 09:30:52 GMT,
            set-cookie: user_prefs=xxxxx; expires=Tue, 12-Jul-2022 09:30:51 GMT; Max-Age=31536000; path=/; domain=.etsy.com
        ],
    responseBody={
        "error": "There was a problem with \/ : Listings must have a complete translation in the shop's primary language: de"
    }                                                                                                                                                                                   
]
```

### Expected behavior
Listing changes into the active state.

### Additional context
ShopID: **23690785**
Original failing ListingID: **1036032376** (Has since been activated using the UI)
~~Still failing ListingID: **862055768** (I'll keep this listing in the failing state for investigations)~~ _Activated it by accident, sry!_

Activating the same listings via the ShopManager UI works fine.

Thanks!

**Comment by harjas** [comment]
Hey @Kimmax! Thanks for reporting this and giving us detailed info to repro. We'll look into this and get back to you as soon as possible!

**Comment by Jonathansw** [comment]
Hey @Kimmax, is it possible to send us the payload that you used for `createListingTranslation` as well?

**Comment by etsyachristensen** [comment]
@Kimmax we deployed a change yesterday that should fix your issue. Can you give it another try and report back?

**Comment by Kimmax** [comment]
@etsyachristensen sry, completely missed the request! I'll try again tomorrow, thanks!
