### ISSUE TITLE
[BUG] CreateReceiptShipment not showing tracking URL

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#135]
**Describe the bug**
I am sending a request with
"Content-Type":"application/x-www-form-urlencoded",
"data":"{\"tracking_code\":\"FAKE TRACKING NUMBER\",\"carrier_name\":\"FAKE CARRIER\",\"send_bcc\":false}",
"params":{}
For a receipt but I am not seeing the tracking URL on the order itself. It partially works (marks the order as shipped) but does not show any tracking information. I understand that Etsy does not support "FAKE CARRIER" but I still expected to see "FAKE TRACKING NUMBER" on the order.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by harjas** [comment]
@amandalik we support specific carrier names for shipping profiles (the list of supported carrier names can be found [here](https://developers.etsy.com/documentation/tutorials/fulfillment#tracking-updates-for-shipping-carriers) so its entirely likely that because you passed in FAKE_CARRIER_NAME, the tracking number never got updated because we don't support FAKE_CARRIER_NAME. Could you try with a supported carrier name instead and let us know if that works?

**Comment by amandalik** [comment]
Hi @harjas thanks for the quick response. I tried this again with "fedex" and tracking_number "425892168382" and encountered the same issue. Our authentication is valid (confirmed since the order is getting marked shipped)> Please let me know what the next steps should be.

`data":"{\"tracking_code\":\"425892168382\",\"carrier_name\":\"fedex\",\"send_bcc\":false}`

**Comment by amandalik** [comment]
@harjas I know that tracking code doesn't work, I tried with a tracking code that does work and was unable to get it working via the api. Same request body, except the tracking code was active. However, I was able to get this tracking code (425892168382) and an active one to work when I directly added the tracking information on the order in shop management UI.

**Comment by harjas** [comment]
Just to confirm your problem, you're passing in a carrier name and tracking_code but the response does not contain the carrier_name or tracking_code in the response body? Am I understanding this correctly?
 
Could you share the request you're sending and the response object you're getting back?

**Comment by amandalik** [comment]
Hi @harjas 

REQUEST:
`
"Content-Type":"application/x-www-form-urlencoded"},"data":"{\"tracking_code\":\"281444293057\",\"carrier_name\":\"FedEx\",\"send_bcc\":false}"
`

RESPONSE:
`
{"receipt_id":2115689271,"receipt_type":0,"seller_user_id":485604492,"buyer_user_id":511561147,"name":"Ameya Mandalik","first_line":"2182 Paseo del Oro","second_line":"","city":"San Jose","state":"CA","zip":"95124","formatted_address":"Ameya Mandalik\n2182 Paseo del Oro\nSAN JOSE, CA 95124\nUnited States","country_iso":"US","payment_method":"cc","payment_email":"","message_from_payment":null,"message_from_seller":null,"message_from_buyer":"","is_shipped":true,"is_paid":true,"create_timestamp":1626218669,"update_timestamp":1626282098,"gift_message":"","grandtotal":{"amount":122,"divisor":100,"currency_code":"USD"},"subtotal":{"amount":20,"divisor":100,"currency_code":"USD"},"total_price":{"amount":20,"divisor":100,"currency_code":"USD"},"total_shipping_cost":{"amount":100,"divisor":100,"currency_code":"USD"},"total_tax_cost":{"amount":2,"divisor":100,"currency_code":"USD"},"total_vat_cost":{"amount":0,"divisor":100,"currency_code":"USD"},"discount_amt":{"amount":0,"divisor":100,"currency_code":"USD"},"gift_wrap_price":{"amount":0,"divisor":100,"currency_code":"USD"},"shipments":[{"receipt_shipping_id":null,"shipment_notification_timestamp":1626282098,"carrier_name":"","tracking_code":""},{"receipt_shipping_id":null,"shipment_notification_timestamp":1626280164,"carrier_name":"","tracking_code":""},{"receipt_shipping_id":null,"shipment_notification_timestamp":1626279089,"carrier_name":"","tracking_code":""},{"receipt_shipping_id":null,"shipment_notification_timestamp":1626220735,"carrier_name":"","tracking_code":""}
`

** I am happy to provide more details if necessary like the api keystring etc in a more private setting

**Comment by harjas** [comment]
Could you try `fedex` instead of `FedEx` for the `carrier_name` field?

**Comment by amandalik** [comment]
I've done both, neither has been successful!=.

**Comment by amandalik** [comment]
@harjas please let me know if this is an issue we should solve privately, as I cannot provide keystring and other values here.

**Comment by amandalik** [comment]
@harjas  following up on this as we are completely blocked on not being able to provide a tracking URL

**Comment by etsyachristensen** [comment]
@amandalik I am taking this over. Sorry for the delay. We had some shifts in staffing and Harjas is now on a new team. I'm picking up the threads here and want to check in with you on this. I've used your example tracking code and carrier above to hit the `createReceiptShipment` end point on a test receipt. It did give me back the shipment information as shown here:
![image](https://user-images.githubusercontent.com/83842847/132722087-9d41aa90-22e8-4d84-a8c9-e86be6264126.png)
Can you confirm if this is now working for you? If not, please let me know so we can work together to get it fixed.
