### ISSUE TITLE
[ENDPOINT] Proposed design change for <getShopReceipt> #BuyerEmail

### ISSUE THREAD

**Issue by ulandj** [etsy/open-api#136]
**Current Endpoint Design**
> What in the current endpoint design do you think is missing or find confusing?

In [**Receipt**](https://www.etsy.com/developers/documentation/reference/receipt#section_fields) endpoint of the Etsy API V2  we can get **buyer_email** and **seller_email** from the response. But they do not exist anymore in the `getShopReceipt` endpoint responses of `API V3`. 

We also requested to [**getUser**](https://developers.etsy.com/documentation/reference/#operation/getUser) endpoint of `API V3` passing the **buyer_user_id** parameter received from `getShopReceipt` endpoint but user's(buyer) `"primary_email"` still empty whereas it exists in `Receipt` response from `API V2`.

**Proposed Endpoint Design Change**
> Add information about your proposed change.

Add **buyer_email** and **seller_email** attributes to `getShopReceipt` endpoint response.

**Why are you proposing this change?**
> Please provide a reason for the change you're proposing.

Etsy sellers require this data in 3rd party applications.

**Comment by etsyachristensen** [comment]
@ulandj Can you provide some user ids from some receipts that we can do some digging on? We need to confirm why you are not getting the primary_email values. The endpoint for `getShopReceipt` is currently correct in only returning the ids. We can investigate adding the emails to the resulting data set, but we need to ensure that the `getUser` endpoint returns the correct information.

**Comment by ulandj** [comment]
@etsyachristensen 
> Can you provide some user ids from some receipts that we can do some digging on?

```
"receipt_id" => 2118050123
"buyer_user_id" => 389777229
```

> The endpoint for getShopReceipt is currently correct in only returning the ids. We can investigate adding the emails to the resulting data set,

It would be awesome to get `buyer_email` and `seller_email` in `getShopReceipt` responses

**Comment by ulandj** [comment]
@etsyachristensen `getShopReceipt` response doesn't contain `shipping_method` attribute also whereas `Receipt` response from API V2 does: `shipping_details: { shipping_method:"Standard Shipping }`. Do I need to create another issue for this?

Thanks

**Comment by etsyachristensen** [comment]
@ulandj we have deployed a change to add the buyer email and seller email to the receipt. We already have a thread for the shipping method so I'm closing this issue out.
