### ISSUE TITLE
[ENDPOINT] Proposed design change for <endpoint name here> 

### ISSUE THREAD

**Issue by mounirone** [etsy/open-api#139]
**Current Endpoint Design**
What in the current endpoint design do you think is missing or find confusing?

**Proposed Endpoint Design Change**
Add information about your proposed change.

**Why are you proposing this change?**
Please provide a reason for the change you're proposing.
POST /v3/application/shops/12345/listings HTTPS/1.3
Host: openapi.etsy.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8

**Comment by harjas** [comment]
@mounirone can you provide more details for your issue? Seems like you didn't provide any information in the template
