### ISSUE TITLE
No way to view listing shipping info 'publicly'

### ISSUE THREAD

**Issue by sampok** [etsy/open-api#140]
**Describe the bug**
In v2 API it is easy to view where a listing can be shipped to, by including 'ShippingInfo':
`https://openapi.etsy.com/v2/listings/[listing-ids]?includes=ShippingInfo`

In v3 this seems to be impossible: (1) ShippingInfo is not [one of the supported associations (includes)](https://developers.etsy.com/documentation/reference/#operation/getListingsByListingIds) for listings. (2) The `shipping_profile_id` is available in the listing, but `getShopShippingProfile` requires `shops_r` scope permission (i.e. shop owner authorization), making shipping info 'publicly' unavailable.

**Expected behavior**
A way to to view public listings' shipping info in one way or another:
- Is there really any private information in shopShippingProfile? Maybe 'origin_postal_code' is the only thing that exposes some additional private info about the shop? Would it make to sense to make the resource public, and without oauth omit 'origin_postal_code' (if that's the reason)?
- Being able to request shipping info as an association for listings would make getting the information more efficient.

**Comment by etsyachristensen** [comment]
@sampok We are looking into our options on this side of things. While I can't guarantee at this time that we can/will make that info available, we are discussing and will respond back as soon as we have more info. Thanks for bringing this to our attention.

**Comment by etsyachristensen** [comment]
@sampok We've been discussing this internally and we need to know a bit more about what your need is. What data specifically would be needing to get from the ShippingInfo? We are attempting to determine if the correct approach is to leave the find query as-is and require 3rd party apps to re-authorize with the shops_r auth scope, or to add the very basic shipping info to the find query and if deeper details are required then force the scope update.

There are reasons for segregating data out as we've done and we have to balance plugging things back against security, timelines, efficiency etc.

If you can give me some more info I can work with the team to determine when/if we can get this into the listing data.

**Comment by sampok** [comment]
Thank you @etsyachristensen !

We would need the list of countries the listing is shipped to (which also helps us figure out where it is not shipped). An array of destination countries/country groups that exists in v2 ShippingInfo association is great. The specific fields in v2 ShippingInfo association array elements are:
- `origin_country_id`
- `origin_country_name`
- `destination_country_id`
- `destination_country_name`

Looking at [v3 getShopShippingProfile](https://developers.etsy.com/documentation/reference/#operation/getShopShippingProfile) docs fields, the specific fields would be:
- `origin_country_iso`
- `shipping_profile_destinations` array
  - `destination_country_iso`
  - `destination_region`

In the future we might also be interested in accessing the shipping cost for each destination. But that's not yet certain. The shipping cost info exists in v2 ShippingInfo association and v3 getShopShippingProfile.

**Comment by sampok** [comment]
Closing as `Shipping` is now one of the supported includes 🎉.
