### ISSUE TITLE
[BUG] findAllActiveListingsByShop 

### ISSUE THREAD

**Issue by IamSantosh** [etsy/open-api#141]
**Describe the bug**
I was using "findAllShopListingsActive" (https://www.etsy.com/developers/documentation/reference/listing#method_findallshoplistingsactive) API on v2 and on the response it provides the images Array, taxonomy_id and taxonomy_path along with other fields. 
**Example :** "https://openapi.etsy.com/v2/shops/{shop_id}/listings/active?includes=Images&sort_on=created&sort_order=up&offset=0&limit=1&api_key=XYZ"
**Response** : {"listing_id":656959363, "state":"active", "category_id":nil, "title":"T-shirt", "description":"girls tees",  "price":"0.49", "currency_code":"USD", "quantity":1, "url":"https://www.etsy.com/listing/656959363/t-shirt?utm_source=outfy&utm_medium=api&utm_campaign=api", "views":403,  **"taxonomy_id":559, "taxonomy_path":["Clothing", "Women's Clothing", "Tops & Tees", "T-shirts"]**, "used_manufacturer":false, "is_vintage":false, **"Images":[**{"listing_image_id":2194564424, "listing_id":656959363, "rank":1,"url_fullxfull":"https://i.etsystatic.com/12047831/r/il/e7262f/2194564424/il_fullxfull.2194564424_p7wk.jpg", "full_height":794, "full_width":794}]}

In the above response, I've removed most of the fields to make it short but as we can see, it provides images Array, taxonomy_id and taxonomy_path.

But on hitting the **alternative API on v3 "findAllActiveListingsByShop"** (https://developers.etsy.com/documentation/reference/#operation/findAllActiveListingsByShop), **_the response it provides doesn't have images Array, taxonomy_id and taxonomy_path_**.
**Example :** "https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/active"
query = { 'limit' => 1, 'offset' => 0,'includes' => 'Images', 'sort_on' => 'created','sort_order' => 'up' }
header = {'x-api-key' => 'XYZ'}
**Response :** {"listing_id":656959363, "title":"T-shirt", "description":"girls tees", "state":"active", "quantity":1, "shop_section_id":null, "featured_rank":-1, "url":"https://www.etsy.com/listing/656959363/t-shirt", "price":{"amount":49, "divisor":100, "currency_code":"USD"}}

**To Reproduce**
Run query in v2 API : https://openapi.etsy.com/v2/shops/{shop_id}/listings/active?includes=Images&sort_on=created&sort_order=up&offset=0&limit=1&api_key=XYZ

and Run this query in v3 API : https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/active
query = { 'limit' => 1, 'offset' => 0,'includes' => 'Images', 'sort_on' => 'created','sort_order' => 'up' }
header = {'x-api-key' => 'XYZ'}

**Expected behavior**
An images array, taxonomy_id and taxonomy_path also comes along with other fields.

**Screenshots**
on v2 : 
![Screenshot from 2021-07-15 16-52-52](https://user-images.githubusercontent.com/19526862/125780501-ddf86b71-c8f4-4e9f-a266-834fedba000a.png)

on v3 : 
![Screenshot from 2021-07-15 16-52-58](https://user-images.githubusercontent.com/19526862/125780525-765a9827-5bb0-43ab-8676-d0976b18f451.png)

**Additional context**
n/a

**Comment by harjas** [comment]
Hey @IamSantosh! We don't support associations via the `includes` parameter in API v3 anymore. There are _some_ endpoints that support associations - see the update on this in #96 but the `findAllActiveListingsByShop` endpoint does not support Image associations anymore.

**Comment by IamSantosh** [comment]
Thanks @harjas for the quick response. Yes, I can get images association via **"getListing"** endpoint but I was hoping to get it with the **"findAllActiveListingsByShop"** endpoint as well so that we don't have to hit another API for images only.
Apart from this, can you please tell me how can I get **taxonomy_id and taxonomy_path** for the Listing as it was not coming in any response of Listing.

**Comment by harjas** [comment]
`findAllActiveListingsByShop` was mentioned in issue #96 as well and we can try and make that the next association we work on but we can't promise when that work would be done. 

As for the `taxonomy_id`, you can get taxonomy_ids from the [getSellerTaxonomyNodes](https://developers.etsy.com/documentation/reference/#operation/getSellerTaxonomyNodes) endpoint

**Comment by IamSantosh** [comment]
Using "getSellerTaxonomyNodes", I can get all the taxonomy presents on Etsy but there's no Listing API that can tell us which taxonomy is associated with each Listing.
**getSellerTaxonomyNodes Response** : {"id"=>2, "level"=>2, "name"=>"Belts & Suspenders", "parent_id"=>1, "children"=>[{"id"=>3, "level"=>3, "name"=>"Belt Buckles", "parent_id"=>2, "children"=>[], "full_path_taxonomy_ids"=>[1, 2, 3]}, {"id"=>4, "level"=>3, "name"=>"Belts", "parent_id"=>2, "children"=>[], "full_path_taxonomy_ids"=>[1, 2, 4]}], "full_path_taxonomy_ids"=>[1, 2]}

API v2 : on using this API "https://openapi.etsy.com/v2/shops/{shop_id}/listings/active",  it gives associated taxonomy on each listing.
{"listing_id":656959363, "state":"active", "category_id":nil, "title":"T-shirt", "description":"girls tees", "price":"0.49", "currency_code":"USD", "url":"https://www.etsy.com/listing/656959363/t-shirt?utm_source=outfy&utm_medium=api&utm_campaign=api", **"taxonomy_id":559, "taxonomy_path":["Clothing", "Women's Clothing", "Tops & Tees", "T-shirts"]**}

API v3 : there's no information regarding taxonomy_id & taxonomy_path.

On our Project where we use Etsy APIs, we show user's Products based on Taxonomy selection.

**Comment by sampok** [comment]
Getting taxonomy id / path (i.e. listing category) of a listing is important for our use case too to be able to migrate to v3.

**Comment by etsyachristensen** [comment]
@IamSantosh and @sampok I see what you mean about the taxonomy id. Without that being present in the listing queries, you can't fetch the taxonomy path from the getSellerTaxonomyNodes endpoint. We'll add this to our list of internal discussion topics. Will reply back as soon as we have a resolution plan.

**Comment by etsyachristensen** [comment]
@IamSantosh and @sampok We have a fix being prepared now. It's currently in review. I hope to have it in production soon. Just wanted to keep you updated.

**Comment by etsyachristensen** [comment]
@IamSantosh and @sampok We put out a change so that all queries that return a "listing" object will have the taxonomy_id included in the result. From there you can get the taxonomy path from the getSellerTaxonomyNodes endpoint. Please let us know if you have any issues with the change.

**Comment by sampok** [comment]
This is great, thank you for the quick improvement @etsyachristensen!!

**Comment by IamSantosh** [comment]
Thank you so much @etsyachristensen for this quick fix. I just need your help with one more thing. Can you please add **"taxonomy_path":["Clothing", "Women's Clothing", "Tops & Tees", "T-shirts"]** also in response like in v2 API and apart from this, can you also add support for **includes=Images** in findAllActiveListingsByShop, so that we can get Images array also in the same API and don't have to hit another API for only Images list. It'll help us in reducing more API calls.
