### ISSUE TITLE
[FEATURE] get personalization by orderID

### ISSUE THREAD

**Issue by Daktery** [etsy/open-api#142]
**Is your feature request related to a problem? Please describe.**
------------------------------------------------------------------------

We are currently exporting orders and listings from our shop through the etsy API, to feed into our ERP system. Our shop features the option to personalize our goods, for example with a name or a short sentence. Its crucial for our production to export the personalization field as accurate as possible and as far as we know, we havent noticed any interface in the API which communicates the data from the field (in a certain order) to our backend.

**Describe the solution you'd like**
-----------
A simple function to export the personalization bundled with the order ID into our backend. 

**Additional context**
-------------------
We have worked with the Etsy V2 Api before and we just made the switch to V3, awesome what you guys are doing and we hope we can find a solution for our problem ASAP.

Edit: formating

**Comment by Gareth064** [comment]
I haven't started porting my app over to v3 yet but if it's true that you can't get the personalization text from and order item then this will be a massive blow to the functionality of my app.

**Comment by main24** [comment]
Yep, personalization is missing in the transactions response as well as 'variants' attribute (which is also important to identify exact ordered variant).
The problem was reported previously, though no updates so far:
* https://github.com/etsy/open-api/issues/101
* https://github.com/etsy/open-api/issues/111

**Comment by Gareth064** [comment]
These need to be in the API, without both Variation and Personalisation details, my app becomes instantly useless. My app is used for people with more than one Etsy Store and want to see their orders, in full detail including variations and personalization, in one place.

**Comment by turboturtleD** [comment]
Can't really migrate until this basic functionality is addressed.

**Comment by Kimmax** [comment]
Crucial feature! +1

**Comment by joaquin102** [comment]
Wow this literally will make us to avoid the Etsy v3 all together. This is the most important feature that we use from V2.
Please Etsy consider this.

**Comment by etsyachristensen** [comment]
Variations are now included in the Transaction object (shown in the transaction and receipt endpoints). Personalization is now provided in the transaction object inside the `variations` array.
