### ISSUE TITLE
[BUG] findShops endpoint returns "result" not "results"

### ISSUE THREAD

**Issue by FireTiger9527** [etsy/open-api#143]
When the Redirect URI is https://rtmtest.fjrh.cn/#/login, the page jumps to
An error occurred
The requested redirect URL is not permitted.

When the Redirect URI is https://rtmtest.fjrh.cn/login, the page jumps to the Redirect URI page without user authorization

Are special characters like # allowed in the Redirect URI? But my Redirect Page is developed by VUE, and his routing address is with #. Can this be supported?
Ignore the authorization page when the Redirect URI does not have a # sign. Is it because it has been authorized in V2?

In addition, I found an incorrect description in the document. The document description of the findShops method returns "results", but the real call returns "result"

**Comment by etsyachristensen** [comment]
@FireTiger9527 I believe you've already had the '#' issue all worked out. I'm going to modify this ticket to reflect only the issue on the `findShops` endpoint.

**Comment by etsyachristensen** [comment]
This is fixed now. findShops now returns "results"
