### ISSUE TITLE
[DOCS] V3 Oauth - Supported Flow for owner/client credentials?

### ISSUE THREAD

**Issue by bcstodds** [etsy/open-api#146]
I've been working to migrate a local tool that I'm working on to the v3 API, but have run into some trouble with the documentation around OAuth.

[The docs](https://developer.etsy.com/documentation/essentials/oauth2/#step-2-grant-access) currently available appear to only be aimed at an [authorization code grant](http://tools.ietf.org/html/rfc6749#section-4.1) where the app/site redirect to etsy for a user to confirm access before the token is sent as part of the callback process.

I'd like to be able to use a [client credentials grant](https://www.npmjs.com/package/client-oauth2#client-credentials-grant) where this local tool is being run by a shop owner using their Etsy key. The aim is for the tool to be able to periodically check in on inventory using the shop owner's credentials (since it's being run by them).

Using the [client-oauth2](https://www.npmjs.com/package/client-oauth2) library to do this though results in a message that "The authorization grant type is not supported by the authorization server". Is there a different way I should be expected to authenticate in this use case? Is there any documentation I'm missing?

Thanks!

**Comment by turboturtleD** [comment]
As far as I understand, Authorization Code Grant is the only accepted means of Auth for the v3 API.  I do not believe that they currently support Client Credentials Grant or any others, I believe this is in the documentation.

**Comment by turboturtleD** [comment]
Maybe my test project will help get you off the ground in regards to authentication?  https://github.com/turboturtleD/etsy-v3-oauth2-nodeJS

**Comment by bcstodds** [comment]
Thanks for the project pointer, I have read through that template a few
times in the past couple weeks.

I was unable to find any part of the documentation that stated that only
specific grant types are supported (although I'll have to look again).

It seems like this is a gap in the API that wouldn't allow automated tools
to interact with V3 though, unless I am misunderstanding how the
authorization code grant can be used in this case without an active and
interacting user.

Thanks for the link!

**Comment by turboturtleD** [comment]
There is currently no programatic means to authenticate without a user interaction.  There is discussion of creating a means to do a token migration from v2 to v3 programatically though this has not yet been implemented as far as I am aware.

**Comment by bcstodds** [comment]
Ok, hopefully there will be some updates to support this in the future.

It's at least nice to have this email chain out there so that anyone else looking around will have a reference for if something opens up down the line.

**Comment by turboturtleD** [comment]
If you mean to close the thread, yes, you should be able to close the thread.  If anyone adds to it in the future, I'm pretty sure you will be notified.

**Comment by bcstodds** [comment]
I was hoping to close it with a link to a discussion bug if one exists, but if there isn't I'll just close it on this comment.

Thanks.

**Comment by npike** [comment]
Has there been any changes on this?

**Comment by bennodev19** [comment]
any updates on this? :)
