### ISSUE TITLE
[BUG] getPublicUserFeedback

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#15]
**Describe the bug**
In v2 API the only the original user feedback is returned in the response. 

**To Reproduce**
n/a

**Expected behavior**
The revised user feedback, if applicable, is included in the response.

**Screenshots**
n/a

**Additional context**
Buyers are known the revise feedback from negative to positive (and vice versa) and change their comments after resolving issues with sellers. It would be ideal to get the most recent version of feedback rather than the first version of feedback that was left by a buyer.

**Comment by harjas** [comment]
@benjymouse we've deprecated the user feedback endpoints in favor of review endpoints (as etsy has pivoted away from feedback to reviews in the recent years). Let me know if that works and we'll close this issue.
