### ISSUE TITLE
[ENDPOINT] Proposed design change for <uploadListingImage> 

### ISSUE THREAD

**Issue by IamSantosh** [etsy/open-api#152]
**Current Endpoint Design**
I'm using "**uploadListingImage**" (https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/images) API for uploading new images to Listing and its working as expected.

**Proposed Endpoint Design Change**
Please add the same feature for Videos also or if there's any API for that, please let me know. I tried the "**uploadListingFile**" API, but it's applicable for Digital products.

**Why are you proposing this change?**
Along with **Images**, I also want to **upload Videos** to my listing via API.

**Comment by etsyachristensen** [comment]
The listing video management has just been added: https://developers.etsy.com/documentation/reference#tag/ShopListing-Video
