### ISSUE TITLE
[BUG] Incorrect remaining rate limit calculation

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#154]
**Describe the bug**
When accessing public resources with OAuth2 access token the rate limit is calculated as if the API call is made with API key authorization only. This way the number of calls to public resources is limited to a total of 10,000 per day, no matter how many different access tokens are used.

**To Reproduce**
1. Make a request to a publicly available resource, for example https://openapi.etsy.com/v3/application/listings/active
2. Use public key authorization, i.e. no OAuth2 access token
3. Observe that the X-Remaining-Today in the response says 9999
4. Execute the same request with included OAuth2 access token
5. Observe that the X-Remaining-Today in the response says 9998

**Expected behavior**
The second request should use the fresh rate limit of the access token instead of the limit of the API key. So, the X-Remaining-Today limit in step 5 should be 9999.

**Additional context**
Note that the OAuth2 authorization seems to be ignored whatsoever. You can include any string as an OAuth2 access token and the request would be processed successfully. This also explains why the rate limit is calculated based on the API key.

**Comment by etsyachristensen** [comment]
@VasilVelikov We have reviewed your post above. We did some testing and have determined that the behavior is actually in line with the V2 API. Public endpoints that do not require the api key/oauth credentials will decrement the remaining number whether you pass the api key or not. We aren't able to change this at this time.

**Comment by VasilVelikov** [comment]
Maybe I didn't explain the issue well enough. For sure the behaviors of v2 and v3 differ.

What I am saying is that
**In v3 the OAuth rate limit per user is not used for public resources**
This means that if I have 100 users connected to the app I can only make 10,000 requests to public resources. In other words, my public resource allowance does not scale with the number of users.

In v2 of the API, however, the rate limit to the public resources is 10,000 **per user**. This means that if I have 100 connected users I am able to make 1mln requests to public resources, i.e. the transaction allowance scales linearly with the users.

This is easily reproducible with the example above.

I believe that scaling of the public allowance by the number of connected users is critical for any reasonable use of the API.

Even more, if I make a v3 GET request to a public resource with an OAuth2 token included, the token is completely disregarded. I can pass any sequence of characters and the request will be successful (and will use the public rate limit). If I do the same thing in v2 with a wrong OAuth1 token, the request will get rejected.

If this is not clear enough, please let me know and I will provide a sample bash script to illustrate the problem (per email).

**Comment by etsyachristensen** [comment]
@VasilVelikov Thanks for explaining this deeper. We will dig into this ASAP and see if we can figure out why you are experiencing this. Our internal testing didn't bear this out so we need to be sure we are on the same page as you.

**Comment by x-bass** [comment]
This is true. We experienced the same problem.

**Comment by etsyachristensen** [comment]
@VasilVelikov and @x-bass I believe we have a fix for this issue. It's related to #155 and I'm hoping to have the fix published by the end of the week.

**Comment by etsyachristensen** [comment]
@VasilVelikov and @x-bass I have deployed a fix for this. Please re-open if you still have issues.

**Comment by VasilVelikov** [comment]
Hi @etsyachristensen,

Unfortunately I still have the exact same problem. The OAuth2 access token is completely disregarded for the https://openapi.etsy.com/v3/application/listings/active endpoint and the request limit is deducted from the global limit. No matter how many access tokens I have, the total number of calls per day to this resource I can make is 10,000.

**Comment by x-bass** [comment]
Hi @etsyachristensen 

In addition to the above, I always hit the rate limit. I performed queries against public API endpoints with the following rates, but it return 429 status code - exceeded daily rate limit.
- 1 request per second
- 1 request per 5 seconds
- 1 request per 25 seconds

Though, it gets reset every two-hour but still not ready for production use.
