### ISSUE TITLE
[BUG] Remaining public calls limit is always decreased by 2

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#155]
**Describe the bug**
Each call to a public resource is counted as 2 instead of 1. This way the rate limit for public resources is effectively 5000.

**To Reproduce**
1. Make several calls consecutive to https://openapi.etsy.com/v3/application/listings/active without OAuth2 access token
2. Observe that the X-Remaining-Today header in the response decreased by 2 with each call.

**Expected behavior**
The remaining calls should decrease by 1.

**Comment by etsyachristensen** [comment]
@VasilVelikov We did some initial testing on our end and we weren't able to duplicate this behavior. Can you provide the api key and shop id (via email to developers@etsy.com) so we can try to duplicate with your credentials?

**Comment by etsyachristensen** [comment]
I've found the issue I believe @VasilVelikov. I hope to have a fix out (pending review from the core team) by end of the week.

**Comment by etsyachristensen** [comment]
@VasilVelikov I have deployed a fix for this issue. Please check it out. If you have any issues with this fix, please reopen this issue.
