### ISSUE TITLE
[BUG] Updating title or description with updateListing does not work

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#156]
**Describe the bug**
Currently it is not possible to update the title or the description of a listing with the updateListing request, in the v3 version. The method seem to work for other listing attributes, for example tags.

**To Reproduce**
1. Execute an updateListing request: PUT /v3/application/shops/{shop_id}/listings/{listing_id}
2. The body of the request should contain a single element: title. The body should be passed as 'application/x-www-form-urlencoded'
3. Observe that the request completes successfully with status code 200. The response contains the full listing information. The title element in the response contains the new value.
4. Perform a GET /v3/application/listings/{listing_id} request, or open the listing on etsy.com
5. Observe that the old value of title is returned / displayed

The exact same bug occurs for description.
On the other hand, updating the tags with the same steps works correctly.

**Expected behavior**
Obviously, the expected behavior is one of the following:
1. If the request is indeed successful, the listing data should be updated and the change should be immediately visible with the GET request in step 4
2. If the request has actually failed, the response in step 3 should not be with status code 200

**Comment by turboturtleD** [comment]
I tested this with just changing the title and experienced the same behavior.  The returned data shows the change, but the listing data itself remains unchanged.  Plan to poke at this a little more and see which (if any) other fields display the same behavior.

**Comment by turboturtleD** [comment]
quantity: fails to update
price: fails to update
title: fails to update
description: did not test, but according to @VasilVelikov this does not work
materials:  success
should_auto_renew: *works besides bug 130.1 https://github.com/etsy/open-api/issues/130#issuecomment-883150126
shipping_profile_id: did not test
shop_section_id: fails to update
item_weight: pass (docs should elaborate that item_weight_unit must also be set)
item_length: *works besides bug 130.1 https://github.com/etsy/open-api/issues/130#issuecomment-883150126
item_height: *works besides bug 130.1 https://github.com/etsy/open-api/issues/130#issuecomment-883150126
item_width: *works besides bug 130.1 https://github.com/etsy/open-api/issues/130#issuecomment-883150126
item_dimensions_unit: *works besides bug 130.1 https://github.com/etsy/open-api/issues/130#issuecomment-883150126
is_taxable: not tested
taxonomy_id: fails to update
tags: not tested, success according to @VasilVelikov 
who_made: not tested
when_made: not tested
featured_rank: fails to update
is_personalizable: *works, but that field isn't even in the data returned
state: *works, but upon making inactive returns a state of "edit" (which is not a valid state according to docs).  Further, in the response sample documentation, it shows "state" : "0", which is confusing at best.  Expected to return "inactive" per docs.
is_supply: not tested
type: not tested
channels: not tested, according to docs "wholesale" is a possibility, but my understanding is that Etsy wholesale is dead.  (like dead dead)

**Comment by harjas** [comment]
@VasilVelikov @turboturtleD we discovered this issue too and are already trying to get fix out ASAP. Thanks for bringing this too our attention. We'll let you know when the fix is out.

**Comment by etsyachristensen** [comment]
Thanks @turboturtleD we've deployed a fix to the updateListing endpoint.

### Notes:
**Channels** - disregard as this will be removed in the near future
**State** - We are aware of the inconsistency in the naming of the status. The "edit" status is the same as "inactive". In our system being inactive means it's editable. The "edit" status is something inherited from legacy. We may update this in the future.
**is_personalizable** - You are correct. We don't support doing personalization via the V3 api at this time, but you are able to toggle option on and off via the update endpoint.

**Comment by VasilVelikov** [comment]
I confirm that the bug has been fixed. Thank you.
