### ISSUE TITLE
updateListingInventory is not working [BUG] 

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#159]
**Describe the bug**
The currently flow I am using
```
var listing = getListingInventory(listingID)
listing.products[0].offerings[0].quantity = 100
updateListingInventory(listing)
```
I am getting a 400 Error with UKNOWN_ERROR description and I am not sure why.

**To Reproduce**

follow the logic above.

**Expected behavior**
Inventory should update for the specified product

**Screenshots**

**Additional context**

**Comment by turboturtleD** [comment]
Do you have different prices for variations?  Or SKUs for variations?  Or quantity variations?  You would need to pass parameters for each one that applies if that is the case.  Example:

price_on_property : [513]

**Comment by amandalik** [comment]
Yes I do!

**Comment by amandalik** [comment]
The issues are really random in my opinion like for the propery_values, they don't want the scale_name to in the request object, for offerings, they want the price to be a float not the object as provided by the getListingInventory endpoint, they also don't want the is_deleted field and the product_id field to show in the products array.

**Comment by etsyachristensen** [comment]
@amandalik Can you share the full Curl or query you are using to submit the inventory update information?

**Comment by etsyachristensen** [comment]
@amandalik please see the comment thread on #168 to continue conversation. I'll close this ticket out to reduce having too many threads.
