### ISSUE TITLE
[BUG]  findAllListingsActive

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#16]
**Describe the bug**
The count value is limited to 50,100.

**To Reproduce**
Run query in v2 API for a keyword like https://openapi.etsy.com/v2/listings/active?api_key=API_KEY_GOES_HERE&keywords=gift

**Expected behavior**
A count value that is similar to what can be seen on the website. In the "gift" example, the expected count would be around 25.6M

**Screenshots**
n/a

**Additional context**
n/a

**Comment by capndesign** [comment]
Thanks for the feedback! Could this be solved by the suggestion proposed in Issue #25?

**Comment by benjymouse** [comment]
Any time!

That appears to be a separate issue. The `/listings/active` attempts to return the count for ALL elements (which is expected), however it caps out at 50,100. For the most part, our users don't expect to paginate through 50k+ results, however an accurate count would be greatly appreciated.

**Comment by benjymouse** [comment]
Thanks for fixing, now works as expected in v3 API.
