### ISSUE TITLE
[BUG] API getShopReceipt can not get cancelled receipt

### ISSUE THREAD

**Issue by punky97** [etsy/open-api#160]
**Describe the bug**
I have a canceled order, then I call `getShopReceipt` API to get its information but I received an error message ( below) but the `getShopReceiptTransactionsByReceipt` still works ok.
The error message:
```
Could not find a Shop Receipt with receipt_id = 2121439520 associated with shop_id = 27652660.
```

**To Reproduce**
 - Buy items to create a new order.
 - Get order's information by `getShopReceipt` => still work
 - Cancel the order
 - Call `getShopReceipt` again => receive not found message

**Expected behavior**
I expect that I can still get order information through the `getShopReceipt` API

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/35791941/126955877-857d438c-0932-4ff3-8e71-580b9af0d246.png)

**Additional context**

**Comment by WheelerCC** [comment]
I'd be interested in adding the documentation tag to this issue, as I believe that (based on the old API) you're correct in thinking getShopReceipt should still return the receipt. See https://www.etsy.com/developers/documentation/reference/receipt. In particular, the note for the findAllShopReceipts endpoint - "Please note that cancelled orders will only be surfaced when making direct requests to the receipt_id.", which is what you're attempting to do. 

Perhaps my query would be better suited to a different issue, but I think there's a lot of room for documentation regarding the effect of cancelled orders on endpoints like this. e.g. if a previously retrieved receipt was saved by us, and later on it was cancelled, am I correct in thinking the only way to find this out would be to look for missing receipts..? e.g. the previous call returned list of receipts [...receipt A, receipt B, receipt C, ...], most recent call returned [...receipt A, receipt C, ...] therefore we assume receipt B was cancelled? 

Perhaps a better behaviour would be for any endpoints which return a list of receipts to continue returning cancelled receipts, and instead have the cancellation state stored within the receipt (e.g. is_cancelled=true,false)

**Comment by zoborg** [comment]
This is a problematic issue - it's a showstopper for fully migrating to V3, any ETA of a solution?

**Comment by etsyachristensen** [comment]
@zoborg @Killerkiss @WheelerCC and @punky97 we are evaluating an approach for adding the cancelled receipts into the API calls. Will update you when we have a solution.

**Comment by zoborg** [comment]
@etsyachristensen - do you have an approx eta?

**Comment by amitshuklaCedcoss** [comment]
> Perhaps my query would be better suited to a different issue, but I think there's a lot of room for documentation regarding the effect of cancelled orders on endpoints like this. e.g. if a previously retrieved receipt was saved by us, and later on it was cancelled, am I correct in thinking the only way to find this out would be to look for missing receipts..? e.g. the previous call returned list of receipts [...receipt A, receipt B, receipt C, ...], most recent call returned [...receipt A, receipt C, ...] therefore we assume receipt B was cancelled?
> 
> Perhaps a better behaviour would be for any endpoints which return a list of receipts to continue returning cancelled receipts, and instead have the cancellation state stored within the receipt (e.g. is_cancelled=true,false)

@WheelerCC @etsyachristensen I'm using V3 API to update order status and request single receipt_id data, but still getting same error 

request call : [https://developers.etsy.com/documentation/reference/#operation/getShopReceipt](https://developers.etsy.com/documentation/reference/#operation/getShopReceipt)

and response : **`[error] => Could not find a Shop Receipt with receipt_id = {receipt_id} associated with shop_id = {shop_id}.`**

from my past experience with Etsy API, 3 cases are generated
case 1: Either requested receipt_id  is in_valid
case 2: Receipt_id is canceled
case 3: Receipt_id is refunded (on v2 API we are getting adjusted_grandtotal:0.00)

@etsyachristensen my clients are daily reporting issues with order status sync (not getting proper data from Etsy). 
plz let us know any ETA when this will be resolved. 
thanks

**Comment by etsyachristensen** [comment]
Hi All. We've now enabled the `getShopReceipt` endpoint to return canceled order details.

**Comment by Gareth064** [comment]
@etsyachristensen this ticket has been mentioned in the latest release posted. But your previous comment here said the change has been pulled.

Which one is the truth 😂

**Comment by etsyachristensen** [comment]
Apologies. I forgot to re-updated. I did push the fix. I had to change how I'd done it.
