### ISSUE TITLE
[BUG] Getting server error when creating draft listing

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#162]
**Describe the bug**
When invoking create listing api (https://openapi.etsy.com/v3/application/shops/{shop_id}/listings) this message is returned: {"error":"Server Error"}
Despite this result, the listing is being created

**To Reproduce**
Create a draft listing (you can review the listing created for me with id 1057981203)

**Expected behavior**
Listing will be created and API will return a success result

**Comment by harjas** [comment]
Hey @assaflei! Thanks for reporting this. Is there any chance you can share the request body that you sent to create this listing? We'd love to dig into this further.

**Comment by assaflei** [comment]
Sure @harjas 

title=Lovely%20dress%20duplicate&description=description%20of%C2%A0this%20test%20here%C2%A0shop%0A(new%20line%20here)%20inactive%0Aanother%20line%0Aanother%20line%202%0Ahttps%3A%2F%2Fgoogle.com%C2%A0&price=0.50&quantity=8&tags=&item_weight=0&item_weight_unit=kg&is_taxable=true&who_made=i_did&when_made=made_to_order&taxonomy_id=1&shipping_profile_id=99550176528&is_supply=true

Maybe you could use any logs of the listing that was eventually created as well: 1057981203

**Comment by etsyachristensen** [comment]
@assaflei I noticed your item weight is 0. When I try this same query and change item_weight to 1 it works fine. Can you retry?

**Comment by assaflei** [comment]
You are correct, setting weight greater than zero solves the error
According to the documentation, item weight can be set to zero so is this a bug or the correct behavior?

> number <float> [ 0 .. 1.79769313486e+308 ] Nullable
> The numeric weight of the product measured in units set in 'item_weight_unit'. Default value is null.
(https://developers.etsy.com/documentation/reference/#operation/createDraftListing, item_weight property)

**Comment by etsyachristensen** [comment]
@assaflei You are correct. There's a combination of issues here.

1. We need to modify the documentation to be 1 or greater for the various item dimensions and weights.
2. The documentation maybe isn't clear, but if you don't want to put in the item weight and dimensions, those values are nullable, so simply passing no value or removing that parameter from you update post should also work.

**Comment by assaflei** [comment]
> We need to modify the documentation to be 1 or greater for the various item dimensions and weights.

the value can be less than 1, like 0.5 so when documentation is updated it should consider these float values as well

**Comment by etsyachristensen** [comment]
@assaflei You are correct. It has to be greater than zero, but may be less than one. I had forgotten it was a float field. The correction is coming up soon.

**Comment by etsyachristensen** [comment]
@assaflei The issue has been resolved. If you attempt to post 0 for any of the item dimensions (weight, height, length or width) it will result in a 400 error, not a 500 error. But you can post decimals as well as long as it's greater than 0.
