### ISSUE TITLE
[DOCS] Link to create listing API broken

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#163]
**Link to Documentation Issue**
Please add a link here for which part of the documentation you're reporting an issue.
Page: https://developers.etsy.com/documentation/migration/summary-changes/#shoplisting
v3 Endpoint link is not correct (https://developers.etsy.com/documentation/reference#operation/createListing) - getting redirected to top of page

**What would you like to change?**
I think that the link to point to https://developers.etsy.com/documentation/reference/#operation/createDraftListing

**Why are you proposing this change?**
Link doesn't seem correct

**Comment by etsyachristensen** [comment]
This has been fixed @assaflei. Thank you for bringing this to our attention!
