### ISSUE TITLE
[BUG] No way to determine when an order must be delivered by

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#165]
**Describe the bug**
I am currently building out a fulfillment service using the V3 api but I don't see any way to determine the order delivery due date or even the shipping method which the buyer decided at checkout in the getShopReceipt endpoint. Where can this value be found?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by etsyachristensen** [comment]
Thanks @amandalik. We have this concern high on the priority list. There's already a thread for this [#124](https://github.com/etsy/open-api/issues/124) . So I'm going to close this one out to reduce confusion.
