### ISSUE TITLE
[ENDPOINT] Proposed design change for getListing

### ISSUE THREAD

**Issue by anhladang** [etsy/open-api#166]
**Current Endpoint Design**
All the get listing api are missing information about the listing's views. That information is extremely important

**Proposed Endpoint Design Change**
Add information about views to the listing api

**Why are you proposing this change?**
We need this information to make viewership information for customers to manage their products product

**Comment by lehoangnnx** [comment]
I am also having the same problem. My system is also needing the listing's view count field.

**Comment by harjas** [comment]
Hello @anhladang and @lehoangnnx! We're aware that this is something developers need. There's already an existing thread about this in #122 where I describe what the current state of the `views` field is. We're in the process of prioritizing our post-launch work right now and supporting `views` is high up on that list. 

We'll update #122 when we have any updates. Closing this thread for now and you can follow along in the other issue.
