### ISSUE TITLE
[ENDPOINT] Proposed design change for updateListing endpoint

### ISSUE THREAD

**Issue by turboturtleD** [etsy/open-api#167]
**Current Endpoint Design**
What in the current endpoint design do you think is missing or find confusing?

The field is_personalizable exists, and works, however the updateListing 200 server response does not include the value of this field, but does return the values of all of the other fields.

**Proposed Endpoint Design Change**
Include the is_personalizable boolean value in the 200 server response for the updateListing endpoint.

**Why are you proposing this change?**
Client validation and applicable use of server returned listing object.

**Comment by etsyachristensen** [comment]
@turboturtleD This is high on our priority list. Will update you as we have progress.

**Comment by turboturtleD** [comment]
@etsyachristensen I think you are assuming that I'm talking about the personalization data itself, and I'm glad to hear that is a high priority because that is super important data.

However, with the proposed design change I listed above, I'm actually referring to the boolean value itself that reflects the toggling of the is_personalizable value on and off (true or false) which is currently not reflected in the returned listing data.

**Comment by etsyachristensen** [comment]
Yes. I understand. We are wrapping all the personalization stuff, including the boolean, into a bundle of issues to handle at once.

**Comment by etsyachristensen** [comment]
@turboturtleD We just added the feature for setting and getting the following listing configuration settings:
1. is_personalizable (boolean) 
2. personalization_is_required (boolean)
3. personalization_instructions (string)
4. personalization_char_count_max (integer)

We should very soon be enabling the ability to receive the personalization that the buyer enters into the cart.
