### ISSUE TITLE
[BUG] updateListingInventory giving error Missing Input Parameter: [products]

### ISSUE THREAD

**Issue by nsanden** [etsy/open-api#168]
**Describe the bug**
Using the PHP Curl example found here: https://developer.etsy.com/documentation/tutorials/listings#updating-inventory I get an error of: `{"error":"Missing input parameter: [products]"}`

**To Reproduce**
Copy the PHP Curl example in and change the `listing_id` in the request URL, the application client ID, and the oAuth bearer token. Run it.

**Expected behavior**
Inventory to be updated.

**Additional context**
I noticed the example payload had at least one typo in it here: 
![image](https://user-images.githubusercontent.com/2072064/127562537-6a80f11d-bcc8-474c-b5e6-87f1ac6e8e93.png)

But fixing that did not seem to make any difference. Basically, I just want to be able to update the inventory on a listing. The docs example is not allowing me to do that. I also tried fetching the inventory on my existing listing, tweaking just a QTY value on it, and then doing a PUT update on the listing using exactly the same inventory json, but still same error.

**Comment by etsyachristensen** [comment]
Wow good catch @nsanden . We will get the documentation fixed ASAP.

That said, the data block for the products needs to be structured as shown in the example (except the price should be a decimal place value, not an array as you figured). Can you try again and post back the exact reponse you are getting from the API?

**Comment by nsanden** [comment]
Hi @etsyachristensen I tried again with `"price": 5` `"price": 5.00` `"price": 500` `"price": "5.00"` etc but nothing working. I'm always getting the same error `{"error":"Missing input parameter: [products]"}` unless I change something outside the payload like the client ID or auth token.

**Comment by turboturtleD** [comment]
If I submit the request body as below from the getListingInventory endpoint I get `{"error":"Missing input parameter: [products]"}`:

`[{"product_id":4595067177,...},{"product_id":4595067179,...}]`

If I submit the body request as below, I get `{"error":"Array contains invalid keys: product_id,is_deleted"}` (reference https://github.com/etsy/open-api/issues/159#issuecomment-886235153):

`{ products : [{"product_id":4595067177,...},{"product_id":4595067179,...}],
"price_on_property":[513],
"quantity_on_property":[],
"sku_on_property":[],
"listing":null }`

If I follow @amandalik 's instructions here https://github.com/etsy/open-api/issues/159#issuecomment-886235153 and remove the undesirable key value pairs including: scale_name, is_deleted, product_id, offering_id as well as change the value for "price" to a float ( "price" : 10.00 ) the update works.  Looks like there are some kinks to be worked out @etsyachristensen. 

Complete request bodies below:

Case 1 (wrong format):
`[{"product_id":4595067177,"sku":"","is_deleted":false,"offerings":[{"offering_id":4807956334,"quantity":985,"is_enabled":true,"is_deleted":false,"price":{"amount":"1099","divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"scale_name":null,"value_ids":[88975186335],"values":["As Pictured"]}]},{"product_id":4595067179,"sku":"","is_deleted":false,"offerings":[{"offering_id":4696350639,"quantity":985,"is_enabled":true,"is_deleted":false,"price":{"amount":"1595","divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"scale_name":null,"value_ids":[109781355221],"values":["Add Custom Engraving"]}]}]`

Case 2 (should be correct format - but doesn't work):
`{"products":[{"product_id":4595067177,"sku":"","is_deleted":false,"offerings":[{"offering_id":4807956334,"quantity":985,"is_enabled":true,"is_deleted":false,"price":{"amount":"1099","divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"scale_name":null,"value_ids":[88975186335],"values":["As Pictured"]}]},{"product_id":4595067179,"sku":"","is_deleted":false,"offerings":[{"offering_id":4696350639,"quantity":985,"is_enabled":true,"is_deleted":false,"price":{"amount":"1595","divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"scale_name":null,"value_ids":[109781355221],"values":["Add Custom Engraving"]}]}],"price_on_property":[513],"quantity_on_property":[],"sku_on_property":[],"listing":null}`

Case 3 (modified format per @amandalik):
`{"products":[{"sku":"","offerings":[{"quantity":985,"is_enabled":true,"price":10.99}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"value_ids":[88975186335],"values":["As Pictured"]}]},{"sku":"","offerings":[{"quantity":985,"is_enabled":true,"price":15.95}],"property_values":[{"property_id":513,"property_name":"Customization","scale_id":null,"value_ids":[109781355221],"values":["Add Custom Engraving"]}]}],"price_on_property":[513],"quantity_on_property":[],"sku_on_property":[],"listing":null}`

**Comment by etsyachristensen** [comment]
Ok all. Making some progress. The tutorial is incorrect so I will get that worked out hopefully today.

Here's an example of a working JSON string for updating 3 offerings in a shop that has sku and quantity affecting variations (size) as well as a price affecting variation (material).
{"products": [
    {
        "sku": "woodthing3",
        "offerings": [
            {
                "quantity": 33,
                "is_enabled": true,
                "price": 600
            }
        ],
        "property_values": [
            {
                "property_id": 100,
                "property_name": "Size",
                "scale_id": 327,
                "value_ids": [
                    18156809190
                ],
                "values": [
                    "3"
                ]
            },
            {
                "property_id": 507,
                "property_name": "Material",
                "scale_id": null,
                "value_ids": [
                    18163610620
                ],
                "values": [
                    "Walnut"
                ]
            }
        ]
    },
    {
        "sku": "woodthing3",
        "offerings": [
            {
                "quantity": 33,
                "is_enabled": true,
                "price": 600
            }
        ],
        "property_values": [
            {
                "property_id": 100,
                "property_name": "Size",
                "scale_id": 327,
                "value_ids": [
                    18156809190
                ],
                "values": [
                    "3"
                ]
            },
            {
                "property_id": 507,
                "property_name": "Material",
                "scale_id": null,
                "value_ids": [
                    18114616675
                ],
                "values": [
                    "Oak"
                ]
            }
        ]
    },
    {
        "sku": "woodthing3",
        "offerings": [
            {
                "quantity": 33,
                "is_enabled": true,
                "price": 600
            }
        ],
        "property_values": [
            {
                "property_id": 100,
                "property_name": "Size",
                "scale_id": 327,
                "value_ids": [
                    18156809190
                ],
                "values": [
                    "3"
                ]
            },
            {
                "property_id": 507,
                "property_name": "Material",
                "scale_id": null,
                "value_ids": [
                    18163610622
                ],
                "values": [
                    "Pine"
                ]
            }
        ]
    }
]}`

Note:
I removed the product_id, is_deleted, offering_id and scale_name entries.

**Comment by etsyachristensen** [comment]
Ok I've taken that a bit further and here's the full JSON for 3 different materials (walnut, oak and pine) each with a different price. Each one also has sku and quantity variations.
```{"products":[{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":8}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610620],"values":["Walnut"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":7}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18114616675],"values":["Oak"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610622],"values":["Pine"]}]},{"sku":"woodthing4","offerings":[{"quantity":44,"is_enabled":true,"price":8}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107494140],"values":["4"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610620],"values":["Walnut"]}]},{"sku":"woodthing4","offerings":[{"quantity":44,"is_enabled":true,"price":7}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107494140],"values":["4"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18114616675],"values":["Oak"]}]},{"sku":"woodthing4","offerings":[{"quantity":44,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107494140],"values":["4"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610622],"values":["Pine"]}]},{"sku":"woodthing5","offerings":[{"quantity":55,"is_enabled":true,"price":8}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107397735],"values":["5"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610620],"values":["Walnut"]}]},{"sku":"woodthing5","offerings":[{"quantity":55,"is_enabled":true,"price":7}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107397735],"values":["5"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18114616675],"values":["Oak"]}]},{"sku":"woodthing5","offerings":[{"quantity":55,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18107397735],"values":["5"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610622],"values":["Pine"]}]}],"price_on_property":[507],"quantity_on_property":[100],"sku_on_property":[100]}```

Here's the thing to remember. You can't update just one variation/sku etc. You have to pass back in the full products array (again with `product_id`, `is_deleted`, `offering_id` and `scale_name` removed from the array data).

**Comment by turboturtleD** [comment]
Is the plan to continue to need to remove product_id, is_deleted, offering_id and scale_name from the getInventoryListing data?  Just not getting if this is meant as a quick fix.  Seems strange to need to alter the object like that if this is the long term solution.

**Comment by etsyachristensen** [comment]
I'm evaluating if there's a way to just allow those fields to be in there but just ignore them. No promises, but at least we can see that the endpoint does in fact work. The challenge is in understanding how to make changes to the data array so that it's accepted by the endpoint. It's very unforgiving. I'm going to work on cleaning up some of the documentation around this endpoint to try to make it make more sense.

**Comment by nsanden** [comment]
> Ok all. Making some progress. The tutorial is incorrect so I will get that worked out hopefully today.
> 
> Here's an example of a working JSON string for updating 3 offerings in a shop that has sku and quantity affecting variations (size) as well as a price affecting variation (material).
> `{"products":[{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610620],"values":["Walnut"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18114616675],"values":["Oak"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610622],"values":["Pine"]}]}],"price_on_property":[507],"quantity_on_property":[100],"sku_on_property":[100]}`
> Note:
> I removed the product_id, is_deleted, offering_id and scale_name entries.

I am pretty new to working with Etsy API, so perhaps I'm just doing something silly, but using your JSON is not working on my existing listing. Why might that be, if its working fine on your end? Does my listing have to have the same inventory already there, before this PUT will go through or should this just overwrite any inventory I already have?

```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://openapi.etsy.com/v3/application/listings/10276516042/inventory',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'PUT',
    CURLOPT_POSTFIELDS => '{"products":[{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610620],"values":["Walnut"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18114616675],"values":["Oak"]}]},{"sku":"woodthing3","offerings":[{"quantity":33,"is_enabled":true,"price":6}],"property_values":[{"property_id":100,"property_name":"Size","scale_id":327,"value_ids":[18156809190],"values":["3"]},{"property_id":507,"property_name":"Material","scale_id":null,"value_ids":[18163610622],"values":["Pine"]}]}],"price_on_property":[507],"quantity_on_property":[100],"sku_on_property":[100]}',
    CURLOPT_HTTPHEADER => array(
        'Content-Type: application/x-www-form-urlencoded',
        'x-api-key: ' . Yii::$app->params['api']['oauth']['etsy']['client_id'],
        'Authorization: Bearer ' . Yii::$app->etsyUser->access_token
    ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

**Comment by turboturtleD** [comment]
Um... don't quote me if I'm wrong, but I think your content type header is wrong, needs to be application/json.

**Comment by etsyachristensen** [comment]
@nsanden I wouldn't necessarily expect my data set to work with your listing because the possible property_ids are based on the category you've added your listing to. So, in my example, I am using Material and Size as variations, but your listing category may not have those elements as possible properties.

Could you post the products json for your listing so I can see what you are passing in? That way I can see if anything is off on the data you are sending.

Also it came to our attention that the input type that we used in our tutorial example says that the Content-Type should be "application/x-www-form-urlencoded" but in fact it should be "application/json". I'm working on buffing up this tutorial to have far more information and correct that error.

**Comment by etsyachristensen** [comment]
> Um... don't quote me if I'm wrong, but I think your content type header is wrong, needs to be application/json.

Yep. Thanks @turboturtleD . That was something that came up this morning. Will hopefully have that fixed by tomorrow.

**Comment by nsanden** [comment]
It's working now with the content type change! Thanks guys. Looking forward to the improved documentation.

**Comment by etsyachristensen** [comment]
Didn't mean to close this out as it's our running thread in regard to inventory issues. Again trying to consolidate the github issues to make things less confusing.

**Comment by etsyachristensen** [comment]
Ok I think we can close this one out now. We introduced a few changes, one of which is to `updateListingInventory` allowing for empty `property_values` array for non-variant listings. You do still have to remove  `product_id`, `is_deleted`, `offering_id` and `scale_name`. We can't change that at this point unfortunately. If there's any continued concerns, please start a new issue in github. Thanks!
