### ISSUE TITLE
[BUG] Broken link to migration guide in documentation

### ISSUE THREAD

**Issue by annedirkse** [etsy/open-api#169]
**Describe the bug**
Your link to the migration plan page is broken. It goes to 

https://developers.etsy.com/documentation//migration/index
rather than https://developers.etsy.com/documentation/migration/index

**To Reproduce**
Go to https://developers.etsy.com/documentation/
Click Migration guide under getting started

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by etsyachristensen** [comment]
This is fixed.
