### ISSUE TITLE
[ENDPOINT] Proposed design change for getShopReceipts

### ISSUE THREAD

**Issue by mtj928** [etsy/open-api#176]
**Current Endpoint Design**
What in the current endpoint design do you think is missing or find confusing?

1: The receipts resource does not return an order number field (order_id in V2) that corresponds the order number the customer sees. 
2: The lack of ability to include transactions with the receipt resource necessitates a lot of extra, seemingly unnecessary requests that require rate throttling. 

**Proposed Endpoint Design Change**
1: Add the order number that the customer sees back into the receipts. 
2: Allow includes=transactions or include transactions with the receipt to reduce the number of requests.

**Why are you proposing this change?**
1: It is difficult to cross reference the customer facing order number with only receipt_id and name available.
2: Generating another request to get the needed information for each order (specifically, product_id and quantity) is a significant downgrade from V2 of the API.

**Comment by gemini133** [comment]
please check this issue #161
