### ISSUE TITLE
[BUG] sort_on=score removed from findAllListingsActive 

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#178]
**Describe the bug**

The ability to sort listings by score has been removed from v3 API. This is a v2 feature that is vital for our app. Can you please provide status update, thanks.

**To Reproduce**

We tried using `sort_on=score` with the findAllListingsActive end point.

**Expected behavior**
Resulting that are roughly sorted in a way similar to the Etsy website.

**Screenshots**

**Additional context**

@etsyachristensen https://github.com/etsy/open-api/issues/66

**Comment by VasilVelikov** [comment]
+1
Being able to sort by score is incredibly important for our application too. The API v2 sorting was not perfect but was working well most of the time. Would you consider bringing this to v3 as well?

**Comment by assaflei** [comment]
@VasilVelikov @benjymouse Can you shortly explain what exactly is this score data?

**Comment by benjymouse** [comment]
Heya @capndesign @etsyachristensen - is this still being worked on? For us, this is major missing part of the new API. Thanks guys.

**Comment by BoredGameGeek** [comment]
Same here - big missing piece here. Hopefully this will come soon.

**Comment by VasilVelikov** [comment]
@capndesign , @etsyachristensen - do you have any clarity whether sorting on score will be brought back?

**Comment by etsyachristensen** [comment]
@VasilVelikov @BoredGameGeek @benjymouse @assaflei The score option has been added back into the sort_on parameter.

**Comment by benjymouse** [comment]
@etsyachristensen Awesome!!!!  Thank you kind sir. We'll test it this evening.

**Comment by assaflei** [comment]
> @VasilVelikov @benjymouse Can you shortly explain what exactly is this score data?

Can someone answer this? @etsyachristensen @VasilVelikov

**Comment by etsyachristensen** [comment]
Sure! The score is basically "keyword relevance". Whatever your search terms/filters are, the results are ranked and assigned a "score". If you sort by score, it will return the most relevant results. We don't expose the score values, it's just an internal application.
