### ISSUE TITLE
[BUG] Cannot update a non-variation listing

### ISSUE THREAD

**Issue by RoeiKO** [etsy/open-api#183]
**Describe the bug**
I'm trying to update a single product which doesn't have any variations using PUT listings/{listing_id}/inventory.
Although it works for variation products - for non variation, single products I always get the error **Property values can't be empty**.
If I understand correctly, property_values should be added only when trying to add variations to the product - which is not the case here.

**To Reproduce**
GET listings/{listing_id}/inventory
Remove product_id, is_deleted, offering_id, scale_name.
Change price object to a decimal using the amount/divisor as a value.

Then modify the field you want, and use PUT listings/{listing_id}/inventory with the new object.

I've also came to notice that all *_on_property arrays should contain values when trying to update an SKU, so if I got only one array with a value (it happens) and the rest are empty arrays - I copy the value to the empty arrays as well. Else I recieve an error "all skus must be consistent across al products" or something simliar.

**Note**
It works with API v2, with the complete same body request. However on V2 it doesn't work for variations (which is the exact opposite of V3).

Thanks

**Comment by RoeiKO** [comment]
As a workaround I've added a fake property_values to the first element in my products array that contains just a single product:
{
property_id: 1,
values_ids: [1],
scale_id: 1,
property_string: "string",
values: ["string"]
}

It works, but it corrupts the product and now I'm unable to click "Edit varaitions" or "Link images" on the edit page of the product on Etsy.

**Comment by etsyachristensen** [comment]
@RoeiKO We posted a change yesterday that will now allow you to run updateListingInventory with empty property_values array. This will let you update the sku, price, quantity without having variants. Please give it a try when you get a change. You can reopen this issue if you are still having problems. Thanks!
