### ISSUE TITLE
OAuth2 callback request does not include the state exactly how it was sent

### ISSUE THREAD

**Issue by RicardoE105** [etsy/open-api#186]
**Describe the bug**

When doing the OAuth2 flow, the callback request does not include the state exactly how it was sent in the authorization URL.

For example: If you send `status=TESt`, in the callback request you get `status=test`. It does not respect the uppercase characters.

**To Reproduce**

Do the OAuth2 flow and send a state with a random string that includes an uppercase character, then compare that with what you receive in the callback request.

**Expected behavior**

The state included in the callback request should be exactly the same state that was sent in the authorization URL.

**Comment by RicardoE105** [comment]
Hey guys, was someone able to reproduce this issue?

**Comment by etsyachristensen** [comment]
@stickfigure and @RicardoE105 a fix for this issue has been made live. Please let me know if you still have problems with this particular issue. Thanks!

**Comment by RicardoE105** [comment]
@etsyachristensen thanks.
