### ISSUE TITLE
Personalization field data

### ISSUE THREAD

**Issue by Killerkiss** [etsy/open-api#187]
I am creating an integration of Etsy API V3 with my personal CRM system, which would combine data from different platforms in one place. Everything was fine until I saw that it was impossible to get the values of the Personalization field of each transaction. Perhaps I did not find it, but it seems to me that it does not exist at all. At the moment, it makes no sense to work with API without the value of this field. Can you add this field to the transaction data? I really look forward to your answer on the current decision or a decision in the near future. Thanks for what you are doing.

**Comment by stewielabs** [comment]
Same here. This is critical to my shop, so we can't fully move to V3 until this is available.

**Comment by Killerkiss** [comment]
Great News! Thank you! :)

**Comment by timalin** [comment]
> Ok good news! The `getShopReceipt` and `getShopReceipts` endpoints now return the Transaction along with the variations selected (including the personalization info as a variation).

Great news! Thanks!
Would it be possible to include sku of the variations? Using skus is universally the best way to handle variations between different platforms.

**Comment by etsyachristensen** [comment]
@timalin Adding SKUs is on our roadmap for the near future. I'll close this ticket out as it's about the personalization requests. If you wish to start a new issue, please feel free. However, there may already be an issue or two about this in the issues tab.
