### ISSUE TITLE
[ENDPOINT] Proposed schema change for getPublicUserFeedback

### ISSUE THREAD

**Issue by liamcrayden** [etsy/open-api#19]
**Current Endpoint Schema**
An array of UserFeedback resources is returned containing a "value" property, which is "The feedback's value; 1 is positive, -1 is negative, and 0 is neutral."

**Proposed Endpoint Schema** 
It would be useful, in addition to this information, to return the star rating attributed to the UserFeedback resource - an integer between 1 and 5.

**Why are you proposing this change?**
Whilst it is useful for know if the feedback is positive, negative or neutral, it would be more ideal to include the actual star rating of the feedback as presented on the Etsy frontend. This could then be used by sellers to monitor their reputation, and to get alerts about newly published positive and negative feedback.

**Comment by benjymouse** [comment]
+1

**Comment by etsyachristensen** [comment]
@liamcrayden and @benjymouse The `getReviewsByShop` endpoint returns the rating (1 - 5) as well as the review. Please let us know if there is anything else that is needed here.
