### ISSUE TITLE
[BUG] Server Error When Issuing PUT Request For Listing Field

### ISSUE THREAD

**Issue by MrPetFtz** [etsy/open-api#191]
**Describe the bug**
When issuing a `PUT` request to update a listing's `should_auto_renew` field an error is returned as follows:

`{'error': 'Server Error'}`

**To Reproduce**

**IN PYTHON**
```

import requests

shop_id = {SHOP_ID}

listing_id = {LISTING_ID}

h = {'x-api-key': '{API_KEY}', 'authorization': 'Bearer {TOKEN}'}

d = {'should_auto_renew': False}

r = requests.put(f'https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}', data=d,
                   headers=h)
print(r.json())


```
**Expected behavior**
The listing should be updated with `should_auto_renew` set to `False`

**Screenshots**
N/A

**Additional context**
Using the exact same code from issue #130 which should be fixed. But this is a new problem. Same shop ID and same listing ID that I emailed you guys on issue #130.

**Comment by MrPetFtz** [comment]
@etsyachristensen can you please provide the correct API call to reduce inventory for a listing? A simple example as I've tried it using the API reference and cannot get it to work. Thanks!

**Comment by etsyachristensen** [comment]
Are you attempting to update the quantity for a listing that has NO variations? Can you provide the listing id?

**Comment by MrPetFtz** [comment]
> Are you attempting to update the quantity for a listing that has NO variations?

Nope I am trying to update listings that have several variations. Each with their own quantity.

> Can you provide the listing id?
Sent via email.

**Comment by MrPetFtz** [comment]
To give more information. Here is how I am attempting to update the inventory via the API:

1) Issue a `getListingInventory` request for the listing_id
2) Modify the `quantity` value for each variant in the returned json from above `getListingInventory` request in the `products` key
3) Issue an `updateListingInventory` PUT request using the modified json from step 2 to update the inventory of the same listing_id from step 1

When I attempt to do this it returns the following error:
` {'error': 'Missing input parameter: [products]'}`

**Comment by MrPetFtz** [comment]
Can you tell me what's wrong with this JSON when issuing an updateListingInventory PUT?

`{
  "products": [
    {
      "sku": "PP.1852643",
      "property_values": [
        {
          "property_id": 510,
          "value_ids": [
            105172695356
          ],
          "scale_id": null,
          "property_name": "Style",
          "values": [
            "Backpack"
          ]
        },
        {
          "property_id": 100,
          "property_name": "Size",
          "scale_id": null,
          "value_ids": [
            188579687502
          ],
          "values": [
            "Adult (Ages 13+)"
          ]
        }
      ],
      "offerings": [
        {
          "quantity": 3,
          "price": "49.99",
          "is_enabled": true
        }
      ]
    },
    {
      "sku": "PP.1852644",
      "property_values": [
        {
          "property_id": 510,
          "value_ids": [
            105172695356
          ],
          "scale_id": null,
          "property_name": "Style",
          "values": [
            "Backpack"
          ]
        },
        {
          "property_id": 100,
          "property_name": "Size",
          "scale_id": null,
          "value_ids": [
            208975167066
          ],
          "values": [
            "Youth (Ages 8 to 12)"
          ]
        }
      ],
      "offerings": [
        {
          "quantity": 3,
          "amount": 49.99,
          "is_enabled": true
        }
      ]
    },
    {
      "sku": "PP.1852645",
      "property_values": [
        {
          "property_id": 510,
          "value_ids": [
            105172695356
          ],
          "scale_id": null,
          "property_name": "Style",
          "values": [
            "Backpack"
          ]
        },
        {
          "property_id": 100,
          "value_ids": [
            208975166924
          ],
          "scale_id": null,
          "property_name": "Size",
          "values": [
            "Child (Ages 4 to 7)"
          ]
        }
      ],
      "offerings": [
        {
          "quantity": 3,
          "amount": 49.99,
          "is_enabled": true
        }
      ]
    }
  ],
  "price_on_property": [
    510,
    100
  ],
  "quantity_on_property": [
    510,
    100
  ],
  "sku_on_property": [
    510,
    100
  ]
}`

**Comment by etsyachristensen** [comment]
There's a few things I can see that are off:

1. price should not be encased in "". This is in the first property values set.
2. In some places you have "amount" instead of "price".
3. It seems that neither Style or Size affect the price, so the price_on_property array should be empty.
4. It's not obvious if the quantity is affected by the variations. If not, then make the quantity_on_property should be empty.
5. The Style is the same value for all products, so the sku_on_property should only be [100].

Hope that helps. Sorry for the delay in responding earlier. I did get the emailed listing id. I'll look into that listing as soon as I can break free from some of these tasks.
