### ISSUE TITLE
[ENDPOINT] Proposed design change for every POST and PUT Endpoint

### ISSUE THREAD

**Issue by akowi-sknobloch** [etsy/open-api#194]
**Current Endpoint Design**
The different POST & PUT endpoints expect different Content-Types for the Request Body

**Proposed Endpoint Design Change**
Use the same Content-Type for all Endpoints
My Suggestion would be application/json as:
 * json data is already used for the responses
 * it's pretty much the standard for REST API's
 * it can handle all currently existing request body's

**Why are you proposing this change?**
The format for the Request Data was already a major annoyance for me while implementing our bindings for V2.
I hoped V3 would fix this by switching to the more standard approach of using JSON for everything.

**Comment by etsyachristensen** [comment]
As mentioned in #203 we can't make them all JSON. I am sorry we can't accommodate this request.
