### ISSUE TITLE
[BUG] updateListingInventory of non-multivariational product requires passing non-empty `property_values`

### ISSUE THREAD

**Issue by main24** [etsy/open-api#195]
**Describe the bug**

Properties define variations for multi-variational products, thus it's perfectly reasonable to pass them with inventory update to the `updateListingInventory` as they identify the entities (as described in the https://developer.etsy.com/documentation/tutorials/listings#how-to-fetch-property-values-for-the-products-array).

As product properties define variations it is expected that update of a simple (non-multivariational) product inventory wouldn't require them; even in the UI it's not required to fill in product properties, i.e. the default ones like 'Primary color' defined on the product level are optional. V2 API works correctly with simple products: API accepts `property_values: []` in the `updateListingInventory` as expected.

Though it turned out that V3 API requires passing property values along with simple (non-multivariational) products as well to the `updateListingInventory`: Otherwise in case of blank array it responds with status 400 and message `Property values can't be empty`.

**To Reproduce**

Given a simple product (example id 2423352262).
Update quantity via V2 API, note `\"property_values\":[]` in the request:
```
# V2 API
PUT /listings/2423352262/inventory
Body:
{
  products:
    "[{\"product_id\":2423352262,\"sku\":\"GRP6\",\"property_values\":[],\"offerings\":[{\"offering_id\":2279891189,\"price\":{\"amount\":50,\"divisor\":100,\"currency_code\":\"GBP\",\"currency_formatted_short\":\"£0.50\",\"currency_formatted_long\":\"£0.50 GBP\",\"currency_formatted_raw\":\"0.50\"},\"quantity\":10,\"is_enabled\":1,\"is_deleted\":0}],\"is_deleted\":0}]",
  price_on_property: [],
  quantity_on_property: [],
  sku_on_property: []
}
```
Works fine.

Now send the same payload to V3 API:
```
# V3 API
PUT /listings/:listing_id/inventory
Body:
{
  products: [
    {
      sku: "GRP6",
      offerings: [
        {
          price: 0.5,
          quantity: 10,
          is_enabled: 1
        }
      ],
      property_values: []
    }
  ],
  price_on_property: [],
  quantity_on_property: [],
  sku_on_property: []
}
```
Responds with a status 400 and a message `Property values can't be empty`

**Expected behavior**

`updateListingInventory` should accept blank array of `property_values` for simple products.

**Additional context**

1. `getListingInventory` responds with:
- blank array of property values for a simple product in both APIs which is expected;
- array of assigned property values for a multi-variantional product in both APIs which is expected as well.

2. That's a crucial functionality for any application that manages inventory, we can't really migrate without this being fixed. Is it expected to use [updateListing](https://developer.etsy.com/documentation/reference#operation/updateListing) for updating stock/price in the V3 API?

**Comment by main24** [comment]
@etsyachristensen Thanks, just checked on the listing id 603648225 -- update of quantity still fails with the same error:
> There was a problem with /inventory : inventory is not backwards compatible, cannot manually set price or quantity

Request body:
```
{"quantity":20}
```

**Comment by etsyachristensen** [comment]
Apologies @main24 . I've been buried in some other projects. I'm checking on this listing now.

**Comment by etsyachristensen** [comment]
@main24 I just went through this listing fairly thoroughly. Looking back through the history on this, it appears you did call to `updateListingInventory` several times. Once you submit an inventory update, it essentially creates new records in the variations system. Once a listing has content in the variations system, the fields for quantity, price and sku are not able to be updated on the `updateListing` endpoint. You have to use the `updateListingInventory` endpoint to manage those values.

**Comment by main24** [comment]
@etsyachristensen Exactly, that is the thing with this type of listing: it is impossible to update such simple listing (without properties = variants) via `updateListingInventory` because the latter requires `property_values` to be non-blank array, but for a simple listing `property_values` are always blank, otherwise this listing would be multi-variational. In the thread starter I've shared the way how I tried to update quantity of this listing via `updateListingInventory` and it does not work. Could please take a look and point at the place where the payload is incorrect?

**Comment by etsyachristensen** [comment]
Ok thanks @main24 let me consult with the right folks here on this as I think that maybe there's something I'm not aware of at the core level that we didn't account for in V3. I'll update as soon as I can.

**Comment by etsyachristensen** [comment]
@main24 We've made some corrections. You can now pass empty property_value arrays. This will let you update price, sku, quantity without having variations. Once you've done an updateListingInventory, the listing quantity and price become non-backwards compatible. This is by design in the system. But you should be good to go now. If you test and it works, please close this issue. Thanks!

**Comment by main24** [comment]
@etsyachristensen just checked and it works now. Thank you!
