### ISSUE TITLE
[DOCS] Rate Limits

### ISSUE THREAD

**Issue by chris-rogala** [etsy/open-api#198]
**Link to Documentation Issue**
https://developers.etsy.com/documentation/essentials/rate-limits

**What would you like to change?**
I created this issue because I did not find any documentation on the status code returned when an application was throttled: [https://github.com/etsy/open-api/issues/197](https://github.com/etsy/open-api/issues/197)

After doing my own testing, I was able to force the API to throttle my requests. The documentation does not mention the status code of 429 and this should be detailed in the rate-limits page of the documentation. I was able to cause the application to throttle by throwing 11 requests at the API all at once. I received a response with a 429 status code. I have the details of the response below for reference.

### Headers

> Server: Apache
> X-CLOUD-TRACE-CONTEXT: 23c9714bd0c7b937408b69e89de1403a/10155074964666118350;o=1
> X-Etsy-Request-Uuid: EuyfCEFb46oOcKQvLSs2_sNr1f3d
> X-Limit-Per-Second: 10
> X-Remaining-This-Second: 0
> Date: Tue, 24 Aug 2021 18:46:23 GMT
> Connection: keep-alive
> Set-Cookie: user_prefs=##removed##.; expires=Wed, 24-Aug-2022 18:46:23 GMT; Max-Age=31536000; path=/; domain=.etsy.com

### Body
```
{
  "error":"Exceeded per second rate limit"
}
```

**Why are you proposing this change?**
Based on this, I recommend updating the documentation to explain the `X-Limit-Per-Second` and `X-Remaining-This-Second` header values. What can a developer expect from those headers and how can they be used? Why are the `X-RateLimit-Limit `and `X-RateLimit-Remaining` missing when a 429 is returned? I expect that the headers are missing because of a rule is in place within the pipeline. That said, it would be advantageous to update the documentation to state that these headers will not be returned if response with the status code 429 is returned.

That said, it would be very helpful to have the standard `Retry-After` header returned. [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)

**Comment by etsyachristensen** [comment]
We added to the documentation.
