### ISSUE TITLE
[BUG] findShops not retrieving known shops

### ISSUE THREAD

**Issue by rthom654** [etsy/open-api#199]
**Describe the bug**
https://developers.etsy.com/documentation/reference#operation/findShops
Does not appear to return shops in developer mode.

**To Reproduce**
https://openapi.etsy.com/v3/application/shops?shop_name=testprinthotel
{'count': 0, 'results': []}

**Expected behavior**
Expect to retrieve the testprinthotel shop information.

**Additional context**

I am looking to retrieve the shop_id for this shop. Is there a better way for me to do so?

this works for v2:
https://openapi.etsy.com/v2/shops?shop_name=testprinthotel

**Comment by adri67** [comment]
@etsyachristensen @rthom654 Hello, I have the same problem with findShops not returning any result for a shop_name that exists.

**Comment by assaflei** [comment]
Any updates on this subject?
Just encountered it as well

**Comment by adri67** [comment]
+1, problem not solved

**Comment by etsyachristensen** [comment]
There is a fix going out on this soon. It's going through final review before being deployed into production.

**Comment by etsyachristensen** [comment]
@rthom654 @adri67 @assaflei The fix for this has been deployed. Please comment if you're still having issues with this.
