### ISSUE TITLE
[ENDPOINT] Proposed schema change for getShop

### ISSUE THREAD

**Issue by liamcrayden** [etsy/open-api#20]
**Current Endpoint Schema**
Whilst the total number of favorites is returned, it would be helpful to also include the total number of shop sales.

**Proposed Endpoint Schema** 
Include transaction_sold_count as part of the response.

**Why are you proposing this change?**
Although it is possible to obtain this information from /users/login_name/profile, it requires an extra unnecessary API call.

**Comment by benjymouse** [comment]
+1

**Comment by capndesign** [comment]
Hi @liamcrayden! Just to clarify, are you suggesting we include the same value listed on the shop page?

For example, here is [a shop](https://www.etsy.com/shop/Macramebeautiful) I found from Etsy’s homepage that shows they have 10,800 sales. Is this the correct value?

**Comment by liamcrayden** [comment]
> Hi @liamcrayden! Just to clarify, are you suggesting we include the same value listed on the shop page?
> 
> For example, here is [a shop](https://www.etsy.com/shop/Macramebeautiful) I found from Etsy’s homepage that shows they have 10,800 sales. Is this the correct value?

Hi @capndesign, yes that figure (the 10,800 sales in your example) would be very useful.

**Comment by harjas** [comment]
@liamcrayden we've added `transaction_sold_count` to the getShop endpoint! Give it a spin and let us know what you think. Closing the issue for now!
