### ISSUE TITLE
createReceiptShipment not updating carrier_name or tracking_code

### ISSUE THREAD

**Issue by Tilted-Software** [etsy/open-api#201]
**Describe the bug**
The createReceiptShipment call doesn't appear to be updating the carrier_name or the tracking_code

**To Reproduce**
POST https://openapi.etsy.com/v3/application/shops/27749334/receipts/2157070556/tracking HTTP/1.1
Accept: application/json
x-api-key: XXX
Authorization: Bearer XXX
Content-Type: application/x-www-form-urlencoded
Host: openapi.etsy.com
Content-Length: 75

{"tracking_code":"GB12345678","carrier_name":"royal-mail","send_bcc":false}

**Expected behavior**
Would expect the order to be updated with carrier and tracking, but it just gets marked as completed and the option to add tracking is on the order.  I get a 200 response with a shipment element created each time I post the above but none of them contain the information posted.

**Additional context**
Note that cleared out the Authorization and x-api-key header above, I'm using C# and built the integration around the json OpenAPI interface,

**Comment by Tilted-Software** [comment]
Hi there - any results from investigations?

**Comment by etsyachristensen** [comment]
@Tilted-Software I haven't been able to dig into this yet. I'll try to do so next week. We've been a bit short staffed lately. Trying to keep things rolling as fast as I can.

**Comment by etsyachristensen** [comment]
@Tilted-Software I am not able to duplicate this issue. It's possible that somewhere along the line, whatever was causing the issue has been fixed. Can you try it again? If it's working please close the issue out.

**Comment by Tilted-Software** [comment]
Hi

I tired again using the below request, again the order got marked as complete but no carrier and no tracking information applied:

**REQUEST**
POST https://openapi.etsy.com/v3/application/shops/27749334/receipts/2194156272/tracking HTTP/1.1
Accept: application/json
x-api-key: XXX
Authorization: Bearer XXX
Content-Type: application/x-www-form-urlencoded
Host: openapi.etsy.com
Content-Length: 77

{"tracking_code":"JC814397021GB","carrier_name":"royal-mail","send_bcc":true}

I haven't included the full response but I think the relevant part is:

"shipments":[{"receipt_shipping_id":null,"shipment_notification_timestamp":1632921580,"carrier_name":"","tracking_code":""}]

The timestamp on the above is about the time I posted the shipment so it seems to have been created from my post above but the carrier and tracking code are empty.

Perhaps I'm doing something totally wrong here so any help appreciated.

Thanks

Chris.

**Comment by KirstyPeace** [comment]
Hi @etsyachristensen can you please offer additional support? We may in a position where we stop taking orders because we simply cannot manage manually adding tracking to 100's orders each day. Thanks for your support,

**Comment by etsyachristensen** [comment]
@KirstyPeace @Tilted-Software We've deployed a change that we hope will help. This one is tricky because we are having trouble replicating it. We think this may be a cache issue so the fix should help with that. Please give it a shot again and let me know if you're still having an issue.

**Comment by Tilted-Software** [comment]
Hi Andrew

Unfortunately this still doesn’t seem to be working, request/response from live shipment below – have highlighted the missing carrier/tracking code in the response.

REQUEST
POST https://openapi.etsy.com/v3/application/shops/27749334/receipts/2236802984/tracking HTTP/1.1<https://openapi.etsy.com/v3/application/shops/27749334/receipts/2236802984/tracking>
Accept: application/json
x-api-key: xxx
Authorization: Bearer xxx
Content-Type: application/x-www-form-urlencoded
Host: openapi.etsy.com
Cookie: user_prefs=YfoWef2jY2zJLVoBC2MVi38JW6FjZACCxFYBURgdnVeak6NDHhHLAAA.
Content-Length: 77

{"tracking_code":"JC243137885GB","carrier_name":"royal-mail","send_bcc":true}

RESPONSE
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 2785
Server: Apache
X-CLOUD-TRACE-CONTEXT: 7eb0473d36fbcc03def1b941523ed103/12432654967126539892;o=0
X-Etsy-Request-Uuid: EuSclczDUolmxOCtSubJI5qBhF9d
X-Limit-Per-Second: 10
X-Remaining-This-Second: 4
X-Limit-Per-Day: 10000
X-Remaining-Today: 9349
Cache-Control: max-age=0, no-cache, no-store, private
X-Etsy-Generated: 1636110359.55
X-Resource-Type: Application_OpenAPI_Shop_Receipt
Content-Type: application/json
Via: 1.1 google, 1.1 varnish
Accept-Ranges: bytes
Date: Fri, 05 Nov 2021 11:05:59 GMT
X-Served-By: cache-lon4256-LON
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1636110359.773007,VS0,VE833
Vary: X-Detected-Locale,Accept-Encoding

***@***.******@***.***","name":"Matthew Pegg","first_line":"2 Hever Gardens","second_line":"","city":"Bromley","state":"Kent","zip":"BR1 2HU","status":"Completed","formatted_address":"Matthew Pegg\n2 Hever Gardens\nBROMLEY, Kent BR1 2HU\nUnited Kingdom","country_iso":"GB","payment_method":"cc","payment_email":"","message_from_payment":null,"message_from_seller":null,"message_from_buyer":"","is_shipped":true,"is_paid":true,"create_timestamp":1636049870,"update_timestamp":1636110359,"gift_message":"","grandtotal":{"amount":1799,"divisor":100,"currency_code":"GBP"},"subtotal":{"amount":1799,"divisor":100,"currency_code":"GBP"},"total_price":{"amount":1799,"divisor":100,"currency_code":"GBP"},"total_shipping_cost":{"amount":0,"divisor":100,"currency_code":"GBP"},"total_tax_cost":{"amount":0,"divisor":100,"currency_code":"GBP"},"total_vat_cost":{"amount":0,"divisor":100,"currency_code":"GBP"},"discount_amt":{"amount":0,"divisor":100,"currency_code":"GBP"},"gift_wrap_price":{"amount":0,"divisor":100,"currency_code":"GBP"},"shipments":[{"receipt_shipping_id":null,"shipment_notification_timestamp":1636110358,"carrier_name":"","tracking_code":""}],"transactions":[{"transaction_id":2694292154,"title":"Winter Forest Wreath Decorative Front Door Wreath Garland Dark Forest Green & Pine Cone Floral Christmas Xmas Party D\u00e9cor Wreath","description":"Made from natural wood with a midnight forest green finish complete with natural brown pine cone accents and white berries, this traditional winter wreath is ideal for adding an extra splash of seasonal colour to the home this fall whether simply decorating for the season or welcoming guests to the home for a festive party.\n\nLovingly designed in the heart of West Yorkshire and entirely hand made by our production partners to transform your door this season with an evergreen design to display and enjoy all season long. Suitable for indoor and outdoor use and delivered in a durable plastic packaging free reinforced storage box.","seller_user_id":445662765,"buyer_user_id":555698983,"create_timestamp":1636049870,"paid_timestamp":1636049886,"shipped_timestamp":1636110359,"quantity":1,"listing_image_id":3474857965,"receipt_id":2236802984,"is_digital":false,"file_data":"","listing_id":1071168820,"sku":"BM37","product_id":8008554460,"transaction_type":"listing","price":{"amount":1799,"divisor":100,"currency_code":"GBP"},"shipping_cost":{"amount":0,"divisor":100,"currency_code":"GBP"},"variations":[],"shipping_profile_id":156408518746,"min_processing_days":1,"max_processing_days":1,"shipping_method":null,"shipping_upgrade":null,"expected_ship_date":1636110359}]}

Thanks

Chris.

**Comment by etsyachristensen** [comment]
@Tilted-Software Are you posting the data points as form data? I see that you're using x-www-form-urlencoded which is correct, but we pulled up the logs and found your post but there's no value for tracking_code or carrier_name which is why it's not saving. I see the data you are passing in the post above but it's in JSON format.

**Comment by Tilted-Software** [comment]
Hi Andrew

It seems a combination of visual studio making the body of the post json when it attempted to build a set of services based on the open API and me not reading the actual spec resulted in this, I changed the carrier and tracking to actually be url encoded and it worked, thanks for pointing me in the right direction.

Chris.

**Comment by etsyachristensen** [comment]
I'm going to close this issue out. If anyone still has an issue, please feel free to comment.
