### ISSUE TITLE
[DOCS] Rate limit header documentation out of date

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#202]
**Link to Documentation Issue**
https://developers.etsy.com/documentation/essentials/rate-limits

**What would you like to change?**
The documentation shows the old headers `X-RateLimit-Limit` and `X-RateLimit-Remaining`. However, the rate limit headers are now called something else.

**Comment by etsyachristensen** [comment]
Thank you for the feedback @stickfigure ! I have applied the correction.
