### ISSUE TITLE
[ENDPOINT] Proposed design change for updateListingInventory

### ISSUE THREAD

**Issue by akowi-sknobloch** [etsy/open-api#203]
**Current Endpoint Design**
Does not return a proper error description for the products JSON

**Proposed Endpoint Design Change**
Return parsing and/or validation errors for the JSON

**Why are you proposing this change?**
The Endpoint does not provide useful information on whats wrong with the JSON.
It just responds with: "Not a valid JSON string" 
I have no idea if its a parsing or validation issue.
Checked my JSON for syntax and validity and it does not seam to be wrong.
```json
[{
  "property_values": [{
    "property_id": 513,
    "value_ids": [1],
    "property_name": "Variation",
    "scale_id": 30,
    "values": ["4XL Weiß"]
  }],
  "sku": "<our sku>",
  "offerings": [{
    "price": 19.9,
    "quantity": 8,
    "is_enabled": true
  }]
}, {
  "property_values": [{
    "property_id": 513,
    "value_ids": [1],
    "property_name": "Variation",
    "scale_id": 30,
    "values": ["5XL Schwarz"]
  }],
  "sku": "<our sku>",
  "offerings": [{
    "price": 19.9,
    "quantity": 8,
    "is_enabled": true
  }]
}]
```

**Comment by akowi-sknobloch** [comment]
Ok i found my specific problem with this endpoint.
I was assuming it to function similar to the v2 by using Content-Type "application/x-www-form-urlencoded".
Im now sending the whole Request as JSON and it works.
Does pretty much add to my issue #194 on why it would be better to have all Endpoints use JSON.

I will not close this issue because the problem still stands.
If the Endpoint would have given a proper validation error, i would have seen the problem much sooner.
Please provide proper messages on whats wrong with the Requests.

**Comment by etsyachristensen** [comment]
@akowi-sknobloch Unfortunately it's not feasible now to make all endpoints JSON. In that particular endpoint, the documentation does state the body schema. https://developers.etsy.com/documentation/reference#operation/getListingInventory

Every endpoint in the documentation does show the body schema.

![image](https://user-images.githubusercontent.com/83842847/135173654-b0c8ed11-8782-4af4-a4a7-dfc06667b6fd.png)
