### ISSUE TITLE
[ENDPOINT] Proposed design change for getShopReceipt

### ISSUE THREAD

**Issue by enna54** [etsy/open-api#204]
Hi, please add ship by dates to the API. Etsy has recently been creating lots of initiatives to encourage on-time shipping - like the Star Seller program. Adding ship by dates to the API will ensure sellers ship by their ship by dates like, for example, allowing ShipStation and other third party shipping services to pull in the ship by dates so sellers can more easily & quickly see when orders need to ship & create more happy customers.

**Comment by WheelerCC** [comment]
+1

Or if this isn't provided, documentation of how it's calculated when presented on the Etsy website to sellers. I'd assume it's using the listing fields processing_min (the minimum number of days required to process this listing) and/or processing_max (the maximum number of days required to process this listing).

**Comment by etsyachristensen** [comment]
We have now added the following fields to the transaction associations which are on the receipts:
"shipping_method"  - This will be "Standard Shipping" unless a shipping upgrade has been selected by the buyer.
"expected_ship_date" - This will be the date that the item is expected to be shipped out by based on the listing data. Returns null if the item is already shipped.
"actual_ship_date" - This is the date that the item was actually shipped.

Hopefully this helps @enna54 and @WheelerCC

**Comment by WheelerCC** [comment]
Awesome, thank you ❤️
