### ISSUE TITLE
[FEATURE] Send Emails Before Banning Accounts With Public Apps

### ISSUE THREAD

**Issue by JaggedJax** [etsy/open-api#205]
**Is your feature request related to a problem? Please describe.**
Etsy closed our account without a single email. Our account was not used to sell anything on Etsy, it was used to host a public app that is used by 100+ Etsy sellers daily.

**Describe the solution you'd like**
Please reach out to accounts before deactivating them to see if the issue can be resolved, or send a warning about the problem. I do not think the team that handles these account closures checks to see if the app is hosting a public app that many sellers may be depending upon. Closing one account can adversely affect hundreds or thousands of other accounts.

**Describe alternatives you've considered**
...

**Additional context**
In all seriousness, it is very problematic that no notice was sent out. Searching online, this seems to be an extremely common problem for Etsy sellers, and those hosting public Etsy apps seem to be just as vulnerable. In Addition the lack of any decent contact when this occurs other than a very slow ticketing system is problematic.

The weekend is upon us and I now fear there will be a lot of unhappy sellers if they are down for the rest of the weekend.

For reference, see Etsy support ticket: 6032873 or 6032861

**Comment by JaggedJax** [comment]
I haven't heard anything back from support in a day, so this suspension will probably last at least through the weekend. I believe this was triggered by an automated system within Etsy. If that's the case, I would recommend some sort of manual review before suspending longstanding accounts with an app that many sellers use and may depend on.

**Comment by JaggedJax** [comment]
My personal problem has now been resolved, but I do still think this would be a helpful improvement to relieve any worries developers may have of suddenly losing access without notice for days.

In our case we even followed all recommendations for how to perform testing with our account and still ran foul of the automated ban hammer.

**Comment by nsanden** [comment]
I'm glad to hear your app was reinstated. Thank you for reporting this as well, I am spending many hours developing my own app and that is always a concern I have, that all my work/time/money is wasted. It is risky when your business relies so much on a 3rd party such as Etsy. Would love to hear someone from Etsy chime in here. A warning email should definitely be sent at a minimum.

**Comment by kmcdermott17** [comment]
Hello, 

Thank you for getting in touch about your account suspension, and about the impact it has had on the users of your app. 

We are always working to ensure that Etsy remains a safe place for both buyers and sellers, and apologize that your account was caught by our system. 

I appreciate your comments about the benefit of reaching out prior to taking action on developer accounts and will share your suggestions with my team. We will use this feedback as an opportunity to improve our systems and our training for manual account review. 

As you noted in your report you were following our [API testing policies](https://www.etsy.com/legal/policy/api-testing-policy/169130941112). Although your account was still caught, following these policies remains the best way to avoid unwanted downtime.
