### ISSUE TITLE
[BUG] Not possible to upload Images or Files

### ISSUE THREAD

**Issue by AlejandroDot** [etsy/open-api#207]
**BUG DESCRIPTION:**
No matter what **file or image** I try to upload, I always get the same error(s):
- Either a valid listing_file_id or file must be provided.
- Either a valid listing_image_id or image must be provided.

**CODE SNIPPET:**
```
$request = curl_init();

    curl_setopt_array($request,
      array(

        CURLOPT_RETURNTRANSFER => 1, 
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,

        CURLOPT_URL => "https://api.etsy.com/v3/application/shops/" . $shop . "/listings/" . $listing . "/files", 
        CURLOPT_HTTPHEADER => array(
          "Authorization: Bearer " . $token, 
          "x-api-key: " . $apikey,
//        NONE OF THIS SCHEMAS:
            "Content-Type: multipart/form-data"
//          "Content-Type: application/x-www-form-urlencoded"
        ), 

        CURLOPT_CUSTOMREQUEST => "POST", 
        //  NONE OF THIS METHODS:
            CURLOPT_POSTFIELDS => "file=" . urlencode(file_get_contents($jpgpath))
        //  CURLOPT_POSTFIELDS => "file=" . rawurlencode(file_get_contents($jpgpath))
        //  CURLOPT_POSTFIELDS => "file=" . base64_encode(file_get_contents($jpgpath))
        //  CURLOPT_POSTFIELDS => "file=" . file_get_contents($jpgpath)
        //  CURLOPT_POSTFIELDS => "file=" . "http://domain.com/image.jpg"
        //  CURLOPT_POSTFIELDS => "file=" . "/image.jpg"
        //  CURLOPT_POSTFIELDS => "file=" . urlencode("http://domain.com/image.jpg")
        //  CURLOPT_POSTFIELDS => "file=" . urlencode("/image.jpg")

      )
    );

    $response = curl_exec($request);
    curl_close($request);

//  RESPONSE: {"error":"Either a valid listing_file_id or file must be provided."}
    var_dump(json_decode($response, true));
```

**AFFECTED ENPOINTS:**
- https://developers.etsy.com/documentation/reference#operation/uploadListingFile
- https://developers.etsy.com/documentation/reference#operation/uploadListingImage

**INCORRECT DOCUMENTATION:**
- https://developers.etsy.com/documentation/tutorials/listings#listing-a-digital-product-for-sale
- https://developers.etsy.com/documentation/tutorials/listings#adding-an-image-to-a-listing

**Comment by etsyachristensen** [comment]
@AlejandroDot The `CURLOPT_POSTFIELDS` line should look something like this:

`CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('/path/to/the/file/with/name.jpg'),'name' => 'name.jpg'),`

The file is actually an array of `file` and `name`. I used the CURLFILE method in the example above, but I believe you can also use `file_get_contents($jpgpath)` in place of that.

**Comment by etsyachristensen** [comment]
@AlejandroDot did the above help fix the issue you were having? Please close the issue if you're all good. If not, please provide any additional details if you have any.

**Comment by AlejandroDot** [comment]
**@Etsyachristensen thanks, using CURLFILE solved the issue.** Please note the documentation still not correct, specially the last two links (content-type and postfields):
- https://developers.etsy.com/documentation/reference#operation/uploadListingFile
- https://developers.etsy.com/documentation/reference#operation/uploadListingImage
- https://developers.etsy.com/documentation/tutorials/listings#listing-a-digital-product-for-sale
- https://developers.etsy.com/documentation/tutorials/listings#adding-an-image-to-a-listing

**Comment by nsanden** [comment]
Spent a frustrating hour debugging this same issue this morning and here is what it took to make it work:

```php
$image_url = ''; //this can be remote or local image
$params = [
   'image' => new CURLFile($image_src),
   'name' => basename($image_src),
];
curl_setopt($request, CURLOPT_POST, true);
curl_setopt($request, CURLOPT_POSTFIELDS, $params);
$headers[] = 'Content-Type: multipart/form-data';
$headers[] = 'x-api-key: ' . $client_id;
$headers[] = 'Authorization: Bearer ' . $access_token;
curl_setopt($request, CURLOPT_HTTPHEADER, $headers);
```

**Comment by nsanden** [comment]
@etsyachristensen if you want to replace the first PHP example here https://developer.etsy.com/documentation/tutorials/listings#adding-an-image-to-a-listing that would be wonderful

```php
<?php

$curl = curl_init();

//path to the image you want to upload
//can be local path or remote url
$image_url = '';

curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://openapi.etsy.com/v3/application/shops/12345678/listings/192837465/images',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => [
       'image' => new CURLFile($image_url),
       'name' => basename($image_url),
    ]
    CURLOPT_HTTPHEADER => array(
        'Content-Type: multipart/form-data',
        'x-api-key: 1aa2bb33c44d55eeeeee6fff',
        'Authorization: Bearer 12345678.jKBPLnOiYt7vpWlsny_lDKqINn4Ny_jwH89hA4IZgggyzqmV_bmQHGJ3HOHH2DmZxOJn5V1qQFnVP9bCn9jnrggCRz'
    ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```
