### ISSUE TITLE
[DOCS] Will getUserProfile be released?

### ISSUE THREAD

**Issue by liamcrayden** [etsy/open-api#21]
**Link to Documentation Issue**
The documentation currently only mentions a getUser method with minimal response. 

**What would you like to change?**
In OpenAPI v2, you can call /v2/users/USER_ID/profile and obtain: bio, gender, birth_month, birth_day, transaction_buy_count, transaction_sold_count, is_seller, first_name and last_name. If this endpoint will not be available in v3, will some of the contents of the v2 endpoint be included in getUser instead?

**Why are you proposing this change?**
I am just asking the question as to whether getUser will eventually return more information, whether getUserProfile will make an appearance, or whether this information will not longer be returned.

**Comment by capndesign** [comment]
Hi @liamcrayden! We’re leaning towards including the `UserProfile` data in the `getUser` response. It would be helpful to know if the fields you listed above – `bio, gender, birth_month, birth_day, transaction_buy_count, transaction_sold_count, is_seller, first_name and last_name` — are the only ones you need.

**Comment by etsyachristensen** [comment]
@liamcrayden We added those fields mentioned by @capndesign above to the `getUser` endpoint. Hopefully that is sufficient for your needs. Please feel free to re-open this issue if you feel there is something important missing from the user data.

**Comment by FailMelon** [comment]
Can we get user avatar previously found in v2 with UserProfile.image_url_75x75 and also __SELF__, mostly need the avatar but  having to split the accesstoken for userid is just mildly annoying.
