### ISSUE TITLE
[BUG] API Reference Page returning Error

### ISSUE THREAD

**Issue by chris-rogala** [etsy/open-api#210]
**Describe the bug**
Whenever I visit the documentation/reference page, I receive this error:

![image](https://user-images.githubusercontent.com/44238629/131395177-3a659208-a7e8-4917-a9ec-b2a130d5a585.png)

If I open a private browsing window, then the error disappears.

**To Reproduce**
It comes and goes. I don't know how to reproduce, but it happens often.

**Expected behavior**
Not return an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/44238629/131395531-5f8c8d49-9dc9-440f-8db9-88ad24411dbd.png)

**Additional context**
N/A

**Comment by etsyachristensen** [comment]
This is a known issue. The JSON file is periodically recreated in our system when updates happen. The documentation is dynamic from this file. A hard refresh usually helps. Sometimes simply waiting a few minutes and doing the hard refresh does as well. Unfortunately, we aren't able to address the problem at this time.

**Comment by chris-rogala** [comment]
@etsyachristensen was this fixed?

**Comment by etsyachristensen** [comment]
There's not anything we can do with it at this point. The issue comes down to a caching problem. Our internal system generates that documentation and sometimes the cache hasn't caught up.

**Comment by chris-rogala** [comment]
@etsyachristensen This is happening again and I cannot reference the documentation I need to process orders on Monday. We have over 300 orders scheduled to ship next week, and I really need access to the documentation. I have tried opening this in Edge and Chrome. I have tried incognito in both. It's been going on for a while tonight. I know you mentioned this is a cache issue, but it has now become an issue that is preventing us from processing our orders. Please help if you see this tonight. I will contact you all tomorrow by email if it is still not working.

**Comment by etsyachristensen** [comment]
It is usually solved by doing a hard refresh in your browser. Then go to the main developer documentation page here (https://developers.etsy.com/documentation/) and then click the API Reference link at the top.

It's working fine for me from every browser.

**Comment by chris-rogala** [comment]
I did that a few times. And then even tried Edge, so you know I was desperate. I'll try again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chris-rogala** [comment]
It finally loaded, but there is something odd going on. Cache should not be an issue if I open the page in a private browser window, and I did that in both Chrome and Edge.
