### ISSUE TITLE
[DOCS] State enum not fully documented on valid values for getListingsByShop

### ISSUE THREAD

**Issue by tythomas** [etsy/open-api#212]
**Link to Documentation Issue**
https://developers.etsy.com/documentation/reference#operation/getListingsByShop

**What would you like to change?**
The 'state' documentation lists an enum of 2 valid values (active, inactive), when more can be used.  "expired" is also valid.

**Why are you proposing this change?**
Clarification on the valid input values for the state of the listing wanting to be retrieved.

The error message lists these as valid values:
{"error":"Invalid value (sold out) for enum(0, 1, 2, 3, 4, 5, active, inactive, sold_out, draft, removed, expired, edit)"}

**Comment by etsyachristensen** [comment]
@tythomas This is indeed a documentation error. I will be working on resolving this soon.

**Comment by etsyachristensen** [comment]
This has been fixed.
