### ISSUE TITLE
[BUG] No country error for geonameids

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#213]
**Link to Documentation Issue**
https://developer.etsy.com/documentation/reference/#operation/getShopByOwnerUserId

**What would you like to change?**

**Why are you proposing this change?**
Please provide a reason for the change you're proposing.

**Describe the bug**
When i hit the endpoint using V2 (https://openapi.etsy.com/v2/users/421439134/shops) I got the shop: ✅ 
but when I hit V3 (https://openapi.etsy.com/v3/application/users/421439134/shops) I got an error: 🔴 
```
{
    "error": "No country exists for geoname_id: 6255148"
}
```

**To Reproduce**
Hit https://openapi.etsy.com/v3/application/users/421439134/shops to get the error

**Expected behavior**
A similar behavior of v2, or a better descriptive error

**Additional context**
I am trying to migrate my API from v2 to V3 using Oauth1 token, this endpoint doesn't need scope, same behavior is happening when I use the endpoints to get shop by Id
https://openapi.etsy.com/v3/application/shops/26937753 is getting the error 🔴 
https://openapi.etsy.com/v2/shops/26937753 is getting the shop ✅

**Comment by yovasx2** [comment]
CC @etsyachristensen

**Comment by etsyachristensen** [comment]
This bug showed up yesterday in a support ticket. We are working on a fix for it now.

**Comment by etsyachristensen** [comment]
This is corrected now. Thank you for the feedback!
