### ISSUE TITLE
[DOCS] Incorrect parameter name in auth token response

### ISSUE THREAD

**Issue by cwiley982** [etsy/open-api#215]
**Link to Documentation Issue**
[Authentication flow step 3](https://developers.etsy.com/documentation/essentials/authentication#step-3-request-an-access-token)

**What would you like to change?**
Under step 3 of the auth flow, the details of the response from Etsy back to the calling application shows the correct parameter name in the code snippet but a different name in the description below it. The `token_type` parameter is shown in the snippet but `access_type` is listed as the name for that parameter below. 

**Why are you proposing this change?**
After implementing the flow myself, I've found `token_type` to be the true value, so the docs should be updated to reflect that.

**Comment by etsyachristensen** [comment]
This has been corrected. Thank you for the feedback!
