### ISSUE TITLE
[FEATURE]  IOSS number and the amount for customs declaration

### ISSUE THREAD

**Issue by fi0** [etsy/open-api#216]
The IOSS number and the amount to be declared in EUR are provided in the Shop Manager.
Currently there's no way to get the data via the API.
The same data should be exposed via the API for automating the label generation.

**Comment by Killerkiss** [comment]
Yes, that would be a great feature. Or at least the euro rate to the main currency of the store, so that you can calculate it yourself.

**Comment by fi0** [comment]
Also, GBP will be required.

**Comment by etsyachristensen** [comment]
This has been discussed in our group and there's some challenges to retrieving that data and exposing it via the API. We are looking into solutions, but don't have an estimated timeline for delivering at this time. I'll leave this thread open so we can continue to discuss and update as things progress. Thanks @fi0 and @Killerkiss for your feedback!

**Comment by reisher** [comment]
Any news on IOSS?

**Comment by etsyachristensen** [comment]
Unfortunately I am told that we can not expose the IOSS via the API for legal reasons.

**Comment by fi0** [comment]
@etsyachristensen should we keep this open for the total Amount and Currency (or exchange rate) for customs declaration? or should I open another issue?

**Comment by fi0** [comment]
see https://github.com/etsy/open-api/issues/294

**Comment by assaflei** [comment]
@etsyachristensen can you elaborate the legal reason details, I have customers asking for this data and would like to understand and explain why its not possible

**Comment by etsyachristensen** [comment]
I don't know the reasons to be honest. It's coming from our legal department. You can email developers@etsy.com and ask the support team if they can get that information for you.

**Comment by assaflei** [comment]
Thanks I'll try this,
Could there an option to only have an indication telling whether this data is applied on an order or not? I understand it's related to countries out of EU?
