### ISSUE TITLE
[ENDPOINT] How can I get all translations for a listing?

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#218]
There doesn't appear to be any way to get a list of all Translations for a listing other than iterating all possible languages and fetching each Translation.

Ideally, Translations would simply be part of the Listing json. Alternatively, it could be included with the `include` query param. Worst case, a method to fetch all listings for a translation.

We sync translations into listings. This makes that process incredibly fetchy.

**Comment by etsyachristensen** [comment]
We have added "Translations" as an include on the `getListing` endpoint. Will work on adding it to `getListingsByListingIds` as well but this will take a few days to get worked on.

**Comment by stickfigure** [comment]
@etsyachristensen you guys are on a roll! It's great to watch the API make forward progress so quickly.
