### ISSUE TITLE
[ENDPOINT] Inconsistent requirement for shop_id parameter in URLs

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#219]
It is strange that sometimes we are required to provide the shop_id and other times we are not.

GET a listing: /application/listings/{listing_id}
GET a translation: /application/shops/{shop_id}/listings/{listing_id}/translations/{language}

Unless listings are not unique within shops (and it's pretty clear they are unique), please drop the requirement to prefix /shops/{shop_id} everywhere.

**Comment by etsyachristensen** [comment]
@stickfigure Sorry for the confusion. This is done by design. The routes where you have to include the shop_id are because those endpoints require the user to own the shop (or have read or write permissions on the shop). Unfortunately this isn't something we can change at this time.
