### ISSUE TITLE
[ENDPOINT] Proposed schema change for getListing

### ISSUE THREAD

**Issue by liamcrayden** [etsy/open-api#22]
**Current Endpoint Schema**
The current schema (and the same in v2) does not include a reference to the main listing image,

**Proposed Endpoint Schema** 
I am proposing to include a reference to the URL of first listing image - whether that be a thumbnail or full data on all available image sizes for that first image.

**Why are you proposing this change?**
Listing images are already available via the getListingImages endpoint. However this requires an extra API call. It is often necessary to only retrieve the first image (as seen in Etsy search results) when representing the listing. Including the URL to the first image saves on the extra API call. Additional images can still be returned via the getListingImages endpoint if required.

**Comment by benjymouse** [comment]
+1 this would be very desirable

**Comment by aabrodskiy** [comment]
+1 this would be very useful.

**Comment by harjas** [comment]
Thank you for the feedback @liamcrayden @benjymouse and @aabrodskiy! We hear you and this seems totally reasonable. We'll see what we can do!

**Comment by etsyachristensen** [comment]
@liamcrayden we added support for associations, specifically images, to the getListing endpoint (and several others). When you make your query to the endpoint(s) add "includes" parameter with the value of "Images" and you should receive an array of images. The image with rank of 1 should be the primary image for the listing. Please reopen this issue if you run into problems using the association.
