### ISSUE TITLE
[BUG] Translation removed when i published a listing

### ISSUE THREAD

**Issue by calunia** [etsy/open-api#222]
Hello,
I've a problem, when i published a listing, all the translations are removed.

My workflow:

i create a draft listing with https://openapi.etsy.com/v3/application/shops/{shop_id}/listings
i post my images with https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/images
i create my translation with https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/translations/{language}

All is good on my draft listing.

After, i get my offer with https://openapi.etsy.com/v3/application/listings/{listing_id}
I change the state to "active" and i post the updated listing with https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}.

And the translations are disappear 

Can you please check the problem ?

**Comment by etsyachristensen** [comment]
We have posted an update that fixes this issue.
