### ISSUE TITLE
[BUG] "should_auto_renew" flag not working when creating a draft listing

### ISSUE THREAD

**Issue by libelle** [etsy/open-api#224]
**Describe the bug**
Can't set the auto_renew flag to true for a listing via createDraftListing.

**To Reproduce**
Create a listing, set "should_auto_renew" parameter to "true". Result comes back with it false.

**Expected behavior**
I'd expect automatic renew to be set true.

**Screenshots**
POSTED:
Array(
   [CURLOPT_POSTFIELDS] => quantity=100&title=mytitle&description=description.&price=1.00&who_made=i_did&shipping_profile_id=**&when_made=2020_2021&taxonomy_id=***&is_supply=true&should_auto_renew=true&tags=tag1%2Ctag2&type=download
    [CURLOPT_URL] => https://openapi.etsy.com/v3/application/shops/***/listings
    [CURLOPT_HTTPHEADER] => Array
        (
            [0] => Content-type: application/x-www-form-urlencoded
            [1] => x-api-key: ***
            [2] => Authorization: Bearer ***
        )

    [CURLOPT_FOLLOWLOCATION] => 1
    [CURLE_TOO_MANY_REDIRECTS] => 1
    [CURLOPT_RETURNTRANSFER] => 1
    [CURLOPT_ENCODING] => 
    [CURLOPT_HTTP_VERSION] => 2
)

RESPONSE:
Array
(
    [url] => https://openapi.etsy.com/v3/application/shops/***/listings
    [content_type] => application/json
    [http_code] => 201
    [header_size] => 711
    [request_size] => 3650
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.864949
    [namelookup_time] => 0.001229
    [connect_time] => 0.019592
    [pretransfer_time] => 0.045828
    [size_upload] => 3286
    [size_download] => 4105
    [speed_download] => 4745
    [speed_upload] => 3799
    [download_content_length] => 4105
    [upload_content_length] => 3286
    [starttransfer_time] => 0.864681
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => [my IP]
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => [my IP]
    [local_port] => 50288
)
Created base listing
Array
(
    [listing_id] => ***
    [user_id] => ***
    [shop_id] => ***
    [title] => mytitle
    [description] => description.
    [state] => draft
    [creation_timestamp] => 1631918159
    [ending_timestamp] => 1642462559
    [original_creation_timestamp] => 1631918159
    [last_modified_timestamp] => 1631918159
    [state_timestamp] => 1631918159
    [quantity] => 100
    [shop_section_id] => 
    [featured_rank] => -1
    [url] => https://www.etsy.com/listing/***/[name]
    [num_favorers] => 0
    [non_taxable] => 
    [is_customizable] => 
    [is_personalizable] => 
    [personalization_is_required] => 
    [personalization_char_count_max] => 
    [personalization_instructions] => 
    [listing_type] => 0
    [tags] => Array
        (
            [0] => tag1
            [1] => tag2
        )

    [materials] => Array
        (
        )

    [shipping_profile_id] => ***
    [processing_min] => 1
    [processing_max] => 1
    [who_made] => i_did
    [when_made] => 2020_2021
    [is_supply] => 1
    [item_weight] => 
    [item_weight_unit] => 
    [item_length] => 
    [item_width] => 
    [item_height] => 
    [item_dimensions_unit] => 
    [is_private] => 
    [style] => Array
        (
        )

    [file_data] => 
    [has_variations] => 
    [should_auto_renew] => 
    [language] => en-US
    [price] => Array
        (
            [amount] => 100
            [divisor] => 100
            [currency_code] => USD
        )

    [taxonomy_id] => ***
    [production_partners] => Array
        (
        )

)

**Additional context**
That is all.

**Comment by etsyachristensen** [comment]
Ah ok so I see the problem here @libelle. The `should_auto_renew` really only applies to active listings, BUT I think we need to make sure it works because when the listing goes active, having that setting correct would be good. I'll look into it.

**Comment by yovasx2** [comment]
any update?

**Comment by etsyachristensen** [comment]
Yes. This has been fixed. Sorry. I thought I'd commented already.
