### ISSUE TITLE
[FEATURE] Listing images ALT tags read/write

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#227]
**Is your feature request related to a problem? Please describe.**
According to this article (https://help.etsy.com/hc/en-us/articles/4406604492823) Etsy now supports ALT TEXT for listing images (or will very soon).  It would be great if we can have the ability to view and edit these tags.

**Describe the solution you'd like**
Some endpoints that allow us to read and write alt tags. Ideally not just single image or listing, but multiple images and listings. (to reduce excessive api calls).

**Describe alternatives you've considered**
Meditating.

**Additional context**
https://help.etsy.com/hc/en-us/articles/4406604492823

**Comment by etsyachristensen** [comment]
Great question @benjymouse ! Will put this on the list of things to work on.

**Comment by benjymouse** [comment]
You rock man!

**Comment by etsyachristensen** [comment]
Support for alt_text has been added.
