### ISSUE TITLE
[BUG] updateListingImage [ListingImage already exists and is associated with the requested Listing]

### ISSUE THREAD

**Issue by putjie** [etsy/open-api#228]
**Describe the bug**
Adjust the order of pictures but get the error message "This ListingImage already exists and is associated with the requested Listing"
**To Reproduce**

**Expected behavior**
old images
[
	{
		"listing_image_id": 1,
		"rank": 1
	},
	{
		"listing_image_id": 2,
		"rank": 2
	},
	{
		"listing_image_id": 3,
		"rank": 3
	}
]

new images
[
	{
		"listing_image_id": 2,
		"rank": 1
	},
	{
		"listing_image_id": 1,
		"rank": 2
	},
	{
		"listing_image_id": 3,
		"rank": 3
	}
]

**Screenshots**

**Additional context**
request body
{
	"listing_image_id": 2,
	"rank": 1,
	"overwrite": true
}

**Comment by etsyachristensen** [comment]
@putjie I'm trying to go through all the old tickets here. Are you still experiencing this issue?

**Comment by etsyachristensen** [comment]
I am able to confirm that the error message is happening. I'll look into this further but as @stickfigure mentioned above, checkout issue #330 as it explains how to use image_ids as an input parameter on the `updateListing` endpoint to pass in the images in the order you want them in. It will replace the existing images with the new list.

**Comment by etsyachristensen** [comment]
This has been addressed and in production now. You can now send images ids that are already attached and it will sort them properly.
