### ISSUE TITLE
[BUG] Add `sort_on` and `sort_order` to findAllActiveListingsByShop and getFeaturedListingsByShop

### ISSUE THREAD

**Issue by BoredGameGeek** [etsy/open-api#229]
**Describe the bug**
Compare the query parameters section of these three endpoints:

- https://developers.etsy.com/documentation/reference/#operation/findAllActiveListingsByShop
- https://developers.etsy.com/documentation/reference/#operation/getFeaturedListingsByShop
- https://developers.etsy.com/documentation/reference/#operation/getListingsByShopSectionId

Notice how they are fairly consistent, but `findAllActiveListingsByShop` and `getFeaturedListingsByShop` do not have `sort_on` and `sort_order`

![image](https://user-images.githubusercontent.com/78888562/133958816-938c56ee-06f6-4c18-92a6-a4e8887a5180.png)

Can we please add these query parameters to `findAllActiveListingsByShop` and `getFeaturedListingsByShop` to make them consistent with `getListingsByShopSectionId`?

**Comment by etsyachristensen** [comment]
@BoredGameGeek We have added the `sort_on` and `sort_order` to the `findAllActiveListingsByShop` endpoint. We are not able to add that to the `getFeaturedListingsByShop` endpoint because the featured listings are already sorted automatically by rank.
