### ISSUE TITLE
[DOCS] OAuth2 access token parameter type is unclear

### ISSUE THREAD

**Issue by foxfriends** [etsy/open-api#23]
**Link to Documentation Issue**
https://www.etsy.com/developers/documentation/getting_started/oauth2#section_phase_2_obtain_access_and_refresh_token

**What would you like to change?**
It is not immediately clear what type of parameters these are, and how they should be encoded. Are they query parameters, a JSON body, or a form-urlencoded body? Being specific here will make things more clear.

Also, there is a hyperlink to the token URL, but that is of course not something to open in the browser. I think making that a link is unusual, maybe some other form of easily copied URL would be more suited?

**Why are you proposing this change?**
The documentation is not immediately clear, and could be better!

**Comment by jonbasebl5** [comment]
Hi @foxfriends ! Just wanted to let you know that these parameters are meant to be passed using the `application/x-www-form-urlencoded` format, and we've updated [the documentation](https://www.etsy.com/developers/documentation/getting_started/oauth2#section_phase_2_obtain_access_and_refresh_token) to reflect that as well as your other suggestion.

Thanks so much for raising this issue!
