### ISSUE TITLE
Add Inventory to the includes for getListingsByListingIds

### ISSUE THREAD

**Issue by chris-rogala** [etsy/open-api#236]
**Is your feature request related to a problem? Please describe.**
The SKU is very important to our process. We currently only apply the SKU at the listing level. This property was previously available at the listing level as an array which we did reference. Currently, we will have to call the inventory endpoint multiple times to get access to the SKU. Having Inventory as part of the getListingsByListingIds would be very useful and would greatly reduce the additional calls.

**Describe the solution you'd like**
The call to the batch endpoint would include Inventory so the cURL would look like this:

```
curl --location --request GET 'https://openapi.etsy.com/v3/application/listings/batch?listing_ids={{listingIds}}&includes=Inventory' \
--header 'x-api-key: {{apikey}}' \
--header 'Authorization: Bearer {{accessToken}}'
```

The result of this call would include the inventory:

```
{
    "listing_id": 123456789,
    "inventory": {
        "products": [
            ...
        ],
        "price_on_property": [
            100
        ],
        "quantity_on_property": [],
        "sku_on_property": [],
    }
    ...
}
```

**Describe alternatives you've considered**
The only way to access the SKU is to call the inventory endpoint for each individual listing which for our shop is 384 times.

**Additional context**
Originally mentioned in this design but separated the issue since multiple design requests were in one issue: https://github.com/etsy/open-api/issues/96

Image of SKU in Etsy

![image](https://user-images.githubusercontent.com/44238629/134539751-a2b32997-2f7b-404e-a711-e00030715ce4.png)

**Comment by bitcoinbullbullbull** [comment]
Yes, we have the same issue here and is making this API really time consuming.

**Comment by chanpory** [comment]
Yes, please add `Inventory` as an acceptable input for `getListingsByListingIds`—this already supports `Shipping`, `Images, `Shop, `User`, and `Translations`, so it would be a natural extension of this.

**Comment by creharmony** [comment]
v2 getListing was able to retrieve Inventory so would be great to keep this feature to avoid twice api call were only one could suffice. 🙏

**Comment by main24** [comment]
Same here, we heavily use `Inventory` association in V2, returning it back in V3 would be a great optimisation.

**Comment by etsyachristensen** [comment]
@main24 @creharmony @chanpory @samborambo305 @chris-rogala This has just been added!

**Comment by main24** [comment]
Thank you @etsyachristensen, really appreciate that!
