### ISSUE TITLE
[ENDPOINT] Proposed schema change for getShop - listings

### ISSUE THREAD

**Issue by BoredGameGeek** [etsy/open-api#24]
**Current Endpoint Schema**
[cannot find them]

**Proposed Endpoint Schema** 
Maybe I'm missing it, but I do not see an equivalent to the v2 endpoints to get public shop listings for a shop. For example,

- `shops/[shop name]/listings/featured`
- `shops/[shop name]/listings/active`
- `shops/[shop name]/sections/[section name]/listings/active`

**Why are you proposing this change?**
Previous functionality in v2.

**Comment by BoredGameGeek** [comment]
@harjas any update on this?

**Comment by etsyachristensen** [comment]
@BoredGameGeek you are correct. Those endpoints should cover you what you needed. I'll close the issue. Reopen if you run into any issues with these endpoints.

**Comment by BoredGameGeek** [comment]
@etsyachristensen thanks, there are some issues with consistency though - I opened a new issue: #229
