### ISSUE TITLE
[DOCS] Granting access to stores for private / custom apps or beta testers.

### ISSUE THREAD

**Issue by TWAH** [etsy/open-api#241]
**Link to Documentation Issue**
N/a

**What would you like to change?**
Documentation on how to grant access to a private/custom app for select stores. 

This functionality does already exist but I can't find it. I've used it for an app I developed for my partner's store but now I can't find the documentation I found previously. I believe there was 2 endpoints, one to post a shop ID to and one to see a list of shops with access.

**Why are you proposing this change?**
It's helpful to be able to use an app on your own store / a limited number of stores without having to get the app approved for public use.

**Comment by etsyachristensen** [comment]
@TWAH you should post your message in the Google Group: https://groups.google.com/g/etsy-api-v2.

This issues tab is really for reporting issues with the API. The community of developers out there will be able to answer your question much easier.

**Comment by TWAH** [comment]
Thanks, will do 

I still think this should be documented though
