### ISSUE TITLE
[DOCS] updateListing documentation incomplete

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#242]
https://developer.etsy.com/documentation/reference/#operation/updateListing

There's some ambiguity here. In the v2 API you could leave off some parameters and they wouldn't be updated. It's not clear if this same convention applies to the v3 API, and if so, it's not clear how to clear values.

For example, setting the `shop_section_id`

In v2, you could leave this parameter off and the value would remain unchanged (ie, activate listings by passing just the state parameter in). To clear the shop section, you pass in 0.

In v3 it's not clear how to clear the shop section (0, empty string, and `null` all produce errors).

**Comment by stickfigure** [comment]
The tutorial documentation suggests you can update one property (eg, state) without passing the other params:

https://developer.etsy.com/documentation/tutorials/listings#adding-an-image-to-a-listing

This seems to indicate that there's no way to clear the section id.

**Comment by etsyachristensen** [comment]
@stickfigure That's a great point. I'll dig into this soon and see if I can find a simple enough solution.

**Comment by etsyachristensen** [comment]
@stickfigure You can now set shop_section_id to 0 to remove the section from a listing.
