### ISSUE TITLE
[FEATURE] request for getShopReceipts  to return additional fields

### ISSUE THREAD

**Issue by Hytgarh** [etsy/open-api#243]
**Describe the solution you'd like**
Currently if i want to get the order, would have to make another call to payments, then products, then listimg images, that's 3 additional calls just to get an order. It's very inefficient and for shops with alot of orders, can easily exaust the api limits

**Additional context**

would also be helpful if getShopReceipts returned the following

1) adjusted_grandtotal (as it was available in V2). 
Now we have another request to 
shops/:shop_id/receipts/:receipt_id/payments
then cross check for any changes to the grandtotal

2) products associated with transaction:
for each transaction we have to make a call to get products
 listings/{transaction.listing_id}/inventory/products/{transaction.product_id}

3) image associated with transaction:
for each transaction we have to make a call to get the transaction image
shops/:shop_id/listings/{transaction.listing_id}/images/{transaction.listing_image_id}

**Comment by etsyachristensen** [comment]
@Hytgarh Few quick followups here:

1. Can you clarify what the changes to the grand total might be? What reason would it change? I have not worked on the V2 side so I'm not clear what this was for.
2. The product information should be included in the transactions array inside the receipt array. Is there something more that you aren't getting from that array?
3. Unfortunately this isn't something we can support at this time. We can add it to our list of things for the future.

**Comment by tk5446** [comment]
Hello,

Has there been any updates on request 3 here? 

> image associated with transaction:
> for each transaction we have to make a call to get the transaction image
> shops/:shop_id/listings/{transaction.listing_id}/images/{transaction.listing_image_id}

This is supported in v2 (var uri = Uri.parse('https://openapi.etsy.com:443/v2/shops/${shopName}/receipts?includes=Transactions/MainImage(url_75x75),Transactions`');)

Thanks,
Tom
