### ISSUE TITLE
[BUG] V3, Personalization instructions dupe 

### ISSUE THREAD

**Issue by pokermanx** [etsy/open-api#249]
**Describe the bug**
When pulling from `GetListingsByShop` (application/shops/{shop_id}/listings), listings in array seem to copy the `personalization_instructions` value from the first in order listing.

**Steps to reproduce**
Create a few listings. have personalization set for each one, get them with `GetListingsByShop`, `personalization_instructions` are the same string across all listings.

**Expected behavior**
Return valid `personalization_instructions `for each lisitng

**Comment by etsyachristensen** [comment]
I know it's been a while since you posted this. I'm attempting to duplicate this but haven't been able to. Are you still having this issue? If so, what shop are you getting this on?
