### ISSUE TITLE
[ENDPOINT] Proposed schema change for all list/paginated endpoints

### ISSUE THREAD

**Issue by foxfriends** [etsy/open-api#25]
**Current Endpoint Schema**
`{ count: <number>, results: [<result...>] }` (the general structure returned by all paginated endpoints.

**Proposed Endpoint Schema** 
`{ total: <number>, count: <number>, results: [<result...>] }` or even without the count `{ total: <number>, results: [<result...>] }`. 

Or you could keep it as `count` but make it reflect the total number of results that exist rather than the number of results in this response.

Alternatively, a simple `hasNextPage: <boolean>` would also provide the same benefit, if that is easier to implement.

**Why are you proposing this change?**
When needing to paginate this request, it would not be clear from a response whether another page should be loaded or not, since there is no indication of how many total elements there are in this list. Based on the [pagination](https://github.com/etsy/open-api/blob/main/docs/migration-guide.md#Pagination) section of the migration guide, it sounds like this `count` parameter is only the number of elements in the current response, which is... kind of useless because most parsers are able to parse JSON and then determine the length on their own. Could be that this is a documentation error though?

**Comment by etsyachristensen** [comment]
@foxfriends The endpoints for lists of listings/shops etc should already be returning `count` as a total of all results, not just what is returned on the page. Can you confirm that this is working correctly on your side? If not, please reopen this issue with a list of all endpoints where you are not getting the total count, but only a page count.

**Comment by foxfriends** [comment]
I believe the behaviour is correct, but the [documentation](https://developers.etsy.com/documentation/migration/summary-changes#responses) could still use an update

> In v3, endpoints that return lists of resources contain `count` and `results` fields, indicating the number of results in the response and the results themselves.

This makes it *sound* like the `count` field only contains the number of results in the response, despite actually containing the total number of results that exist.
