### ISSUE TITLE
Discrepancy between data returned by V3 and V2 receipt APIs

### ISSUE THREAD

**Issue by glukoid** [etsy/open-api#253]
**Describe the bug**
call to V3 API return less data for variation object of transaction (2 objects - 1 is missing).
same call to V2 receipt API will return more data (3 objects)

**To Reproduce**
V3 call to 
v3/application/shops/{shopName}/receipts/{orderId}

**Expected behavior**
all user entered personalization data should be returned for V3 API as it was done for V2 API.

**Screenshots**
3 entities returned for call to V2 API:
"variations": [{
							"property_id": 510,
							"value_id": 66583876471,
							"formatted_name": "Style",
							"formatted_value": "Bracelet"
						}, {
							"property_id": 500,
							"value_id": 532858040375,
							"formatted_name": "Finish",
							"formatted_value": "Silver - 1 side"
						}, {
							"property_id": 54,
							"value_id": null,
							"formatted_name": "Personalization",
							"formatted_value": "IL\/MD\/NE"
						}
					],

2 entities returned for call to V3 API:
"variations": [{
					"property_id": 510,
					"value_id": 66583876471,
					"formatted_name": "Style",
					"formatted_value": "Bracelet"
				}, {
					"property_id": 500,
					"value_id": 532858040375,
					"formatted_name": "Finish",
					"formatted_value": "Silver - 1 side"
				}
			],

**Comment by etsyachristensen** [comment]
@glukoid @tuan2195 and @ulandj We have deployed a fix for this. Please try again.
