### ISSUE TITLE
[BUG] Receipts variations have different property values than products one

### ISSUE THREAD

**Issue by ulandj** [etsy/open-api#254]
**Describe the bug**
Receipt variations have incorrect property values(`formatted_value`) if they are variants of listings.
In order to find an appropriate product for a specific order line item, we rely on specifics only, because variants' remote ids are inconstant and don't always have SKUs. That's why it is impossible to switch to `getShopReceipt` of V3 API.

**To Reproduce**
Example:

Etsy Shop ID: 17296999
Etsy Order ID: 2208876172
Etsy Listing ID: 889702922

the order transaction has 2 variations:
```
"variations": [
  {
    "property_id": 200,
    "value_id": 49974750678,
    "formatted_name": "Color",
    "formatted_value": "Green"
  },
  {
    "property_id": 52047899294,
    "value_id": 110653694015,
    "formatted_name": "Women's clothing size",
    "formatted_value": "14 UK women&#039;s"
  }
],
```
The appropriate variant details of the listing fetched using `getListing`:
```
{
  "product_id": 5598527328,
  "sku": "",
  "is_deleted": false,
  "offerings": [
    {
      "offering_id": 5570344098,
      "quantity": 0,
      "is_enabled": true,
      "is_deleted": false,
      "price": {
        "amount": 25,
        "divisor": 100,
        "currency_code": "GBP"
      }
    }
  ],
  "property_values": [
    {
      "property_id": 200,
      "property_name": "Primary color",
      "scale_id": null,
      "scale_name": null,
      "value_ids": [
        4
      ],
      "values": [
        "Green"
      ]
    },
    {
      "property_id": 52047899294,
      "property_name": "Size",
      "scale_id": 26,
      "scale_name": "UK",
      "value_ids": [
        1727
      ],
      "values": [
        "14"
      ]
    }
  ]
},
```

### So, the difference is:
**Order has variant properties:**
 `[{ property_id: 200,  formatted_value:  "Green"}, { property_id: 52047899294,  formatted_value: "14 UK women&#039;s" }]`

**Listing variant has properties:**
 `[{ property_id: 200,  formatted_value:  "Green"}, { property_id: 52047899294,  formatted_value: "14" }]`

**Expected behavior**
Variation property values of order should be the same as the listing variant's

**Screenshots**
Order response:
![api_order_response](https://user-images.githubusercontent.com/5810564/136966366-65e7de09-471c-49ca-945b-105b476ed25b.png)

Listing response:
![api_listing_response](https://user-images.githubusercontent.com/5810564/136966436-7cfdd57e-1c55-469b-a0e6-9f55461222ac.png)

Listing in a buyer UI(online store):
![variations_in_online_store_ui](https://user-images.githubusercontent.com/5810564/136966585-3341ecec-e872-400b-868e-a9b6eb308c8b.png)

**Additional context**
It seems that `getShopReceipt` takes variation property values from UI as they are.

**Comment by ulandj** [comment]
cc @harjas @capndesign @etsyachristensen

**Comment by etsyachristensen** [comment]
Working on this @ulandj. We added personalization last month so it *should* be there. Thank you for all that detail. It'll help us find the issue.

**Comment by etsyachristensen** [comment]
@ulandj Ok I now understand the issue. The main problem is that the receipt is giving the formatted string of the name and not the id that you get with the `getListing` or `getListingInventory` endpoints correct?

If so, I don't think that this is something that we will change, but we ARE working on getting the SKU added to the receipts as well. Would that solve your problem?

**Comment by main24** [comment]
> If so, I don't think that this is something that we will change, but we ARE working on getting the SKU added to the receipts as well. Would that solve your problem?

@etsyachristensen I'm afraid it doesn't solve the problem because several variants of the same product may have the same SKU (depending on `sku_on_property` value), therefore SKU in the line item won't point at the specific variant.

**Comment by main24** [comment]
@etsyachristensen Hi,

In addition to the above, looks like `value_ids` returned with variations inventory may change over time: now the listing `889702922` mentioned in the topic starter message does not contain value id of `49974750678` in the inventory response anymore. However the order still points at this value id. Therefore it doesn't seem like `value_id` of the `transactions.variations` can be used to find the exact variation either.

**Comment by ulandj** [comment]
> o, I don't think that this is something that we will change, but we ARE working on getting the SKU added to the receipts as well. Would that solve your problem?

Hi @etsyachristensen ,
As @main24 mentioned variants of the same listing may have identical SKU's and that's why we can't rely on SKU's to find required listing variant. 
If there are no plans to change then can you please show how to detect a right variant of listing in case they have no SKU's or have the same SKU's using Receipt response?

Thanks

**Comment by rpinedaetsy** [comment]
Sorry I'm a little confuse with this:

It is ok for you to return the exact same fields that the getListingInventory so the Receipt variations will look like this:

```
"variations": [
    {
      "property_id": 200,
      "property_name": "Primary color",
      "scale_id": null,
      "scale_name": null,
      "value_ids": [
        4
      ],
      "values": [
        "Green"
      ]
    },
    {
      "property_id": 52047899294,
      "property_name": "Size",
      "scale_id": 26,
      "scale_name": "UK",
      "value_ids": [
        1727
      ],
      "values": [
        "14"
      ]
    }
  ]
```

**Comment by main24** [comment]
@rpinedaetsy Yep, that would work for us!

Although I think it would be good to preserve `variations` and `product_data` attributes of a transaction from V2 API (with adjustments made to inventory data structure in V3), so API users can opt out unnecessary one.

**Comment by main24** [comment]
@rpinedaetsy the example you have provided above would work. I just suggested keeping `product_data` and `variations` attributes instead of changing `variations` attribute for the sake of backward compatibility and avoiding breaking changes if it makes sense (I guess other API users leverage `variations` in the current state). Basically I'd suggest to make transaction contain attributes like the following:
```
"variations": [
  {
    "property_id": 200,
    "value_id": 49974750678,
    "formatted_name": "Color",
    "formatted_value": "Green"
  },
  {
    "property_id": 52047899294,
    "value_id": 110653694015,
    "formatted_name": "Women's clothing size",
    "formatted_value": "14 UK women&#039;s"
  }
],
"product_data": [
    {
      "property_id": 200,
      "property_name": "Primary color",
      "scale_id": null,
      "scale_name": null,
      "value_ids": [
        4
      ],
      "values": [
        "Green"
      ]
    },
    {
      "property_id": 52047899294,
      "property_name": "Size",
      "scale_id": 26,
      "scale_name": "UK",
      "value_ids": [
        1727
      ],
      "values": [
        "14"
      ]
    }
  ]
```

So there are both attributes: `variations` and `product_data`. In the future I guess it will be possible to request only required attributes of an order/transaction, the same as it's possible with V2.

Another solution that would work is enriching variations data with original property name, value, and, probably, scale data, like:
```
"variations": [
  {
    "property_id": 200,
    "value_id": 49974750678,
    "formatted_name": "Color",
    "formatted_value": "Green",
    + "name": "Color",
    + "value": "Green",
    + "scale_id": null,
    + "scale_name": null,
  },
  {
    "property_id": 52047899294,
    "value_id": 110653694015,
    "formatted_name": "Women's clothing size",
    "formatted_value": "14 UK women&#039;s",
    + "name": "Size",
    + "value": "14",
    + "scale_id": 26,
    + "scale_name": "UK"
  }
]
```
Marked with `+` the attributes that we'd like to get.

Do you think if any of these approaches is possible? Thanks.

**Comment by rpinedaetsy** [comment]
Ok thank you for your suggestions. I will work this and I'll let you know once is done.

**Comment by rpinedaetsy** [comment]
Hey @main24 @ulandj just letting you know that this change is already in PROD you should see a new field product_data in the response for getShopReceipt v3 endpoint

**Comment by main24** [comment]
Hey @rpinedaetsy 
That's good news! Is it possible to do the same for [getShopReceipts](https://developer.etsy.com/documentation/reference/#operation/getShopReceipts) please? Usually we fetch list of orders updated/created since some period, with V2 we don't have to request every single order from that list to get complete information. So adding `product_data` to `getShopReceipts` will save a lot of requests and will be a huge optimisation.
Thanks!
