### ISSUE TITLE
Etsy "Too many Requests" error thrown after 150 requests made [BUG] 

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#256]
**Describe the bug**
I am getting a 429 error from Etsy for too many requests made, and the x-remaining-today header shows 0. I have only made calls to Etsy a maximum of 150 times (a liberal estimate). 

**To Reproduce**
Make any request to Etsy

**Expected behavior**
I should be able to make the allotted 5000 requests a day.

**Screenshots**
relevant headers in the request:
{"x-etsy-request-uuid":"EuzA4iCCqp3v62JqWmKaTsW24gb0","x-limit-per-second":"10","x-remaining-this-second":"9","x-limit-per-day":"10000","x-remaining-today":"0","retry-after":"86400"}

**Additional context**

**Comment by etsyachristensen** [comment]
@amandalik How many shops are using your app? Can you give me a shop id I can check and see what's going on? What is the app called?

**Comment by etsyachristensen** [comment]
@amandalik Have you been able to look into this on your end? Are you still running into the problem?
