### ISSUE TITLE
Transaction variation missing the personalisation information[BUG] 

### ISSUE THREAD

**Issue by sgangram** [etsy/open-api#260]
**Describe the bug**
in the latest V3 API transaction end point is not responding with personalization of each transaction

below variation information is missing in the V3 response. please refer the attached v2 and v3 response.

{
    "property_id": 54,
    "value_id": null,
    "formatted_name": "Personalization",
    "formatted_value": "Not requested on this item."
   }

**To Reproduce**
Steps to reproduce the behavior: get transaction for the transaction ID :2664255005

**Expected behavior**
expected to list all the variation related info including the personalisation message provided by the customer. but it is not responding with 

**Screenshots**
attached

**Additional context**

**Comment by etsyachristensen** [comment]
@sgangram and @waterzhaojun We have deployed a fix for this. Please test it again.
