### ISSUE TITLE
[ENDPOINT] Proposed design change for findAllActiveListingsByShop

### ISSUE THREAD

**Issue by s-plant** [etsy/open-api#264]
**Current Endpoint Design**
There is no sort parameter on `findAllActiveListingsByShop`.

**Proposed Endpoint Design Change**
Hi, I really need the two sort options (sort_on and sort_order) on this endpoint:
https://developers.etsy.com/documentation/reference/#operation/findAllActiveListingsByShop

Similar to how they are on this endpoint:
https://developers.etsy.com/documentation/reference/#operation/getListingsByShopSectionId

**Why are you proposing this change?**
Sorting is important on this endpoint just like it is on `getListingsByShopSectionId`.

--

(see https://groups.google.com/g/etsy-api-v2/c/Z5MGAj__XaI) Thank you!

**Comment by etsyachristensen** [comment]
This change has been added @s-plant . You can now add `sort_on` and `sort_order` to the get inputs.

**Comment by s-plant** [comment]
Thank you!
