### ISSUE TITLE
[ENDPOINT] Proposed design change for /application/shops/{shop_id}/receipts/{receipt_id}

### ISSUE THREAD

**Issue by LionDonath** [etsy/open-api#265]
**Current Endpoint Design**
Shop Receipt has "gift_wrap_price" and "gift_message" but no "is_gift"

**Proposed Endpoint Design Change**
Add "is_gift" to Shop Receipt

**Why are you proposing this change?**
If the customer only selects "send as gift" without gift wrapping or message, there is no way to know that it should be a gift

**Comment by Gareth064** [comment]
#161 gives the answer to this.

**Comment by etsyachristensen** [comment]
This was fixed in #270 .
