### ISSUE TITLE
[FEATURE] IS_GIFT Missing -- Gift_Message doesn't catch all gifts

### ISSUE THREAD

**Issue by colinmcgrath** [etsy/open-api#270]
It looks like v3 is missing the "is_gift" flag that is present in v2.  Can you add that back in?

**Comment by etsyachristensen** [comment]
We are going to add the is_gift boolean back into the data set to cover the gap. Not sure how soon this will happen but we've got it on our to-do list.

**Comment by etsyachristensen** [comment]
We have now added "is_gift" as a possible return value in the Receipt resource.
