### ISSUE TITLE
Getting null for shipping method on getShopReceipt endpoint [BUG] 

### ISSUE THREAD

**Issue by amandalik** [etsy/open-api#271]
**Describe the bug**
Seeing null instead of the shipping method on the getShopReceipt endpoint.

**To Reproduce**
Look at order ID 2225434794 for shop 29817675

**Expected behavior**
We should be able to see the shipping name

**Screenshots**

**Additional context**

**Comment by etsyachristensen** [comment]
The null would come up if the buyer didn't choose any shipping upgrades. You should have a shipping_profile_id for the shop that you can look up the shipping info. We initially were going to just have the shipping_method as a string value for all shipping but it became apparent we needed to modify this approach and so the shipping_method is more of a description when a shipping upgrade has been selected.

**Comment by breenyoung** [comment]
> The null would come up if the buyer didn't choose any shipping upgrades. You should have a shipping_profile_id for the shop that you can look up the shipping info. We initially were going to just have the shipping_method as a string value for all shipping but it became apparent we needed to modify this approach and so the shipping_method is more of a description when a shipping upgrade has been selected.

So then if shipping method is null we can infer there was no shipping upgrade done and is just considered 'Standard Shipping' (which is the string that used to populate this field in V2 when no upgrade was done)

**Comment by etsyachristensen** [comment]
Correct. We were getting feedback from other developers that "Standard Shipping" was too confusing and not descriptive enough.

**Comment by breenyoung** [comment]
Thanks for the clarification Andrew!
