### ISSUE TITLE
Upload an image from Python error "Either a valid image file or a listing_image_id must be provided"

### ISSUE THREAD

**Issue by FloderCC** [etsy/open-api#274]
Hello,
I am trying to upload an image of a listing as the documentation says and it always gives me the error: "Either a valid image file or a listing_image_id must be provided"

This is my Python code:
`      files = {
            "image": open(file_path, 'rb').read()
        }
        headers = {
            "Authorization": "Bearer " + user_token,
            "x-api-key": X_API_KEY,
            "Content-Type": "multipart/form-data"
        }

        return requests.post(url=url, headers=headers, files=files)
`

I already tried replacing files=files by data=files or removing .read() and I always get the same error

**Comment by etsyachristensen** [comment]
@FloderCC I'm no Python developer and unfortunately we couldn't really support your code, but one developer recently reported to us that when they remove the content-type header the upload works. I haven't had a chance to dig into this, nor do I think this *should* work but you might give it a try.

Not knowing python I can't say if this is right but using PHP as an example, using Curl, it would send the data as fields with `image` being a field and the file data as the value of that field. Not sure if it's the same thing there.

If you don't get any answers here, I'd suggest using the Google Group. While it is primarily a V2 OpenAPI group there are members there that are more active than here at the moment and they may have some Python experience.

**Comment by FloderCC** [comment]
Hello, I found the solution myself. The key to my problem was always that I was sending "Content-Type" and that was causing the error. I share it for if there is any Python user who does not go through the same thing. Thanks to @etsyachristensen who suggested that the problem could be related to my use of Python. My final code is:
files = {
"image": open(file_path, 'rb')
}
headers = {
"Authorization": "Bearer " + user_token,
"x-api-key": X_API_KEY
}
