### ISSUE TITLE
Identify calculated shipping profile?

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#276]
**Is your feature request related to a problem? Please describe.**
When getting shop's [shipping profiles list](https://developers.etsy.com/documentation/reference/#operation/getShopShippingProfiles) is there a way to understand which profile is a [calculated profile](https://help.etsy.com/hc/en-us/articles/115013946647-How-to-Set-Up-Calculated-Shipping-?segment=selling)?

**Describe the solution you'd like**
Have a field in the response for getting shipping profiles to indicate that

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by yovasx2** [comment]
the profile _type is for that:
            "profile_type": 0, (fixed)
            "profile_type": 1, (calculated)

**Comment by amitshuklaCedcoss** [comment]
[profile_type] => manual
[profile_type] => calculated

@assaflei @yovasx2 now profile_type returning string value.
