### ISSUE TITLE
Item dimensions required when shipping profile is not calculated.

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#278]
**Describe the bug**

Docs indicate createDraft and updateLisitng (https://developers.etsy.com/documentation/reference/#operation/createDraftListing, https://developers.etsy.com/documentation/reference/#operation/updateListing) say weight and dimensions are **nullable** fields but when I used the create draft endpoint sending them as `null` with a fixed shipping profile then I got an error: `"error": "Item weight must be greater than 0"`

**To Reproduce**
```
curl --location --request POST 'https://openapi.etsy.com/v3/application/shops/xxxxxxxxx/listings' \
--header 'x-api-key: xxxxxxxxx' \
--header 'Authorization: Bearer xxxxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxxxx.; user_prefs=xxxxxxxxx.' \
--data-raw '{
   "id":"15915948",
   "shop_id":27795,
   "listing_id":1099845780,
   "state":"draft",
   "last_modified_tsz":null,
   "title":"Tset",
   "description":"Test",
   "creation_tsz":null,
   "ending_tsz":null,
   "price":20,
   "quantity":1,
   "state_tsz":null,
   "taxonomy_id":1,
   "section_id":null,
   "tags":[
      
   ],
   "materials":[
      
   ],
   "can_write_inventory":false,
   "templates":null,
   "images_count":1,
   "should_auto_renew":"false",
   "who_made":"collective",
   "is_supply":"false",
   "when_made":"2020_2021",
   "original_creation_tsz":null,
   "sales_profile_id":null,
   "is_complete":true,
   "is_copied":true,
   "is_digital":false,
   "item_weight":null,
   "item_length":null,
   "item_width":null,
   "item_height":null,
   "shipping_profile_id":156156763440
}'
```

**Expected behavior**
The **create and update endpoints** mustn't return an error when weight and dimensions are `null` and the shipping profile is **fixed**

**successful request**
```
curl --location --request POST 'https://openapi.etsy.com/v3/application/shops/xxxxxxxxx/listings' \
--header 'x-api-key: xxxxxxxx' \
--header 'Authorization: Bearer xxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxx.; user_prefs=xxxxxxx.' \
--data-raw '{
   "id":"15915948",
   "shop_id":27795,
   "listing_id":1099845780,
   "state":"draft",
   "last_modified_tsz":null,
   "title":"Tset",
   "description":"Test",
   "creation_tsz":null,
   "ending_tsz":null,
   "price":20,
   "quantity":1,
   "state_tsz":null,
   "taxonomy_id":1,
   "section_id":null,
   "tags":[
      
   ],
   "materials":[
      
   ],
   "can_write_inventory":false,
   "templates":null,
   "images_count":1,
   "should_auto_renew":"false",
   "who_made":"collective",
   "is_supply":"false",
   "when_made":"2020_2021",
   "original_creation_tsz":null,
   "sales_profile_id":null,
   "is_complete":true,
   "is_copied":true,
   "is_digital":false,
   "shipping_profile_id":156156763440
}'
```

**Comment by etsyachristensen** [comment]
@yovasx2 When you don't have the need to set the item dimensions and weight, simply leave those fields out. In the documentation, when we say it's nullable, this means you can leave it out completely. This does not mean send it in with a null value. Sorry for the confusion.

**Comment by yovasx2** [comment]
@etsyachristensen I think this is not the correct behavior, in Etsy UI you can select a fixed shipping profile and make weight and dimensions fields empty, then click save as draft with no errors, this will produce null values in weight and dimensions in the GET endpoint:
```
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
```
If I try to nullify these fields via API there is no way to do that with fixed or calculated profile we are always required to send positive values, and of course, if we omit these values the fields  are not overwritten in Etsy side, said that API is not capable to nullify values as UI can do it

**Comment by etsyachristensen** [comment]
You are correct. There's no current way to null out values that have already been set. I will add it to our list of things to work on but it likely won't be done for some time.

**Comment by yovasx2** [comment]
> You are correct. There's no current way to null out values that have already been set. I will add it to our list of things to work on but it likely won't be done for some time.

Thanks a lot, could you please reopen the issue to keep track?

**Comment by yovasx2** [comment]
any update?

**Comment by etsyachristensen** [comment]
we have a ticket in our tracking system already for this but I will re-open it for future commenting.

**Comment by yovasx2** [comment]
thx

**Comment by yovasx2** [comment]
Any update on this?

**Comment by yovasx2** [comment]
news?

**Comment by etsyachristensen** [comment]
This too should be done early next week.

**Comment by yovasx2** [comment]
was it done?

**Comment by etsyachristensen** [comment]
Yes sorry @yovasx2 this was pushed last week. Sorry about forgetting to notify you.

**Comment by yovasx2** [comment]
Hi, I can see that values as still not nullable according to docs (I am using a fixed shipping profile, which doesn't require units or values fro weight and dimensions)

<img width="921" alt="Screen Shot 2022-03-18 at 15 12 28" src="https://user-images.githubusercontent.com/3578401/159083817-432d14ba-ccaf-4f9c-8812-5d7ab4c831b4.png">
