### ISSUE TITLE
[FEATURE]: UploadListingVideo

### ISSUE THREAD

**Issue by pironmj-vidi** [etsy/open-api#279]
**Is your feature request related to a problem? Please describe.**
If a seller wants video on their store, it's a tedious process where they realistically need to use 2-3 apps to create the video, and then transfer the video file to their desktop and upload it to their Etsy account. Integrations for video apps that connect seamlessly with Etsy are non-existent.

**Describe the solution you'd like**
To enable users of our video creation app to upload videos directly to their Etsy listings.

**Describe alternatives you've considered**
The current alternative used by our users, is downloading the video file from our app onto their phone. They then send the video file to their desktop via Airdrop, and then upload via their Etsy account. 

**Additional context**
The current way is tedious and has been cited as frustrating, as the vast majority of Etsy users capture video with their phone. If the above was implemented, we could provide a very seamless solution that seems very aligned with Etsy's promotion of having video as a means to increase sales on listings.

We have also created guides on our app that are in-line with Etsy's guidelines for video content, and ensure users adhere strictly to this (dimensions, ratio etc).

An example of an uploaded video (by one of our users) can be found [here](https://www.etsy.com/au/listing/615309950/velvet-duster-silk-velvet-kimono?ref=shop_home_feat_1&pro=1).

**Comment by etsyachristensen** [comment]
This is on our list of things to discuss after the beginning of the year. However, I have no idea if/when it will be greenlit. I assume it will be simply because listing videos are very effective.

**Comment by Chriscodinglife** [comment]
Would there be also the possibility of extending the allowed length of the videos? or at the least allowing sound? definitely 1+ this api endpoint though would be very useful

**Comment by pironmj-vidi** [comment]
Our videos tend to be between 15s and 1min, max. At the shorter duration, we’ve found that a looping effect occurs, where a buyer will likely watch the video between 2-3 times (if it’s autoplay). It’s a similar effect to TikTok content, if you’ve ever spent time in that app.

Sound is typically preferred by sellers for social, but for listings and product pages they typically export versions with no sound.

I could see a use case with sound if the seller themselves actually featured in the video (their voice even, if not their face). A buyer could be attracted to their story, attitude or tonality, which would likely add to their perception of value increase when deciding whether to buy the product.

From a development perspective, it wouldn’t actually be that different from the image endpoint that’s already in the documentation. Limits on size and format are super easy to dev.

@Etsy, any update on this? I am assuming you must have video listings in the hundreds of thousands, if not approaching millions in volume?

Best,

Michael Pirone
Vidico / Account Director
Vidico.com // Book a time to chat

🎬 Watch our company video to see how it all works!

**Comment by etsyachristensen** [comment]
The listing video management has just been added: https://developers.etsy.com/documentation/reference#tag/ShopListing-Video
