### ISSUE TITLE
[BUG] who_made, is_suply, when_made are requested as a bundle

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#280]
**Describe the bug**
who_made, is_suply, when_made are requested as a bundle, while in v2 they were not

**To Reproduce**
send only one of the above parameters and u receive and error in update listing endpoint:
`"error": "Cannot update 'when_made' without 'who_made' and  without 'is_supply' and vice versa"`

```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/xxxxxx/listings/xxxxxx' \
--header 'x-api-key: xxxxxx' \
--header 'Authorization: Bearer xxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxx.; user_prefs=xxxxxx.' \
--data-raw '{
    "who_made": "someone_else"
}'
```

**Expected behavior**
SAme behavior as V2, allowing me to edit one of these fields at once

**Screenshots**

**Additional context**

**Comment by etsyachristensen** [comment]
@yovasx2 Unfortunately this isn't something we can change at the moment. I don't think it's likely to change. This was added very deliberately in the V3 OpenAPI. You can pull the current values from the listing and passing in the same values for those items you don't want to change.
