### ISSUE TITLE
[BUG] production partner reset via updateListing endpoint when title is modified

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#285]
**Describe the bug**
if u omit the production_partner_ids parameter the value is reset

**To Reproduce**
Create a draft listing with production partners selected and who: "I did"
Hit API updating title:
```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/xxxx/listings/xxxx' \
--header 'x-api-key: xxxxx' \
--header 'Authorization: Bearer xxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxx.; user_prefs=xxxxxx.' \
--data-raw '{
        "title": "nopp3"
}
'
```
reload the page in etsy, the title is modified but production_partner_ids is empty

**Expected behavior**
Do not modify production partners unless u explicitly do it via API

**Comment by etsyachristensen** [comment]
@yovasx2 I have confirmed this is a bug and I've put it into the queue to be fixed right away.

**Comment by yovasx2** [comment]
thx

**Comment by etsyachristensen** [comment]
I believe this was fixed already. @yovasx2 can you confirm?

**Comment by yovasx2** [comment]
working like a charm
