### ISSUE TITLE
[BUG] application_id type interger but format int64 required

### ISSUE THREAD

**Issue by ragipunal** [etsy/open-api#287]
https://www.etsy.com/openapi/generated/oas/3.0.0.json

Since the format is not defined, the visual studio editor treats it as an integer.
Error: message: "JSON integer 1058546323577 is too large or small for an Int32. Path 'application_id' ....

Add this string: "format": "int64",
After build project then request converting successfully.
```
 "Pong": {
        "type": "object",
        "description": "A confirmation that the current application has access to the Open API",
        "required": [ "application_id" ],
        "properties": {
          "application_id": {
            "type": "integer",
            "description": "The authenticated application's ID",
            "minimum": 1
          }
        }
      },
```

to 

```
 "Pong": {
        "type": "object",
        "description": "A confirmation that the current application has access to the Open API",
        "required": [ "application_id" ],
        "properties": {
          "application_id": {
            "type": "integer",
            "format": "int64",
            "description": "The authenticated application's ID",
            "minimum": 1
          }
        }
      },
```

**Comment by adelobosko** [comment]
i am using string type for ids, i do not see any reason to use int...

**Comment by etsyachristensen** [comment]
Thanks for writing in, but our specification is actually correct according to the OpenAPI specification. OAS only has "integer" which covers standard "int" and "long" integer.

The integer type we use is only limited by JSON's number limits.
