### ISSUE TITLE
[BUG] "getListingsByShop" API end point- Response is return only 25(default) listing details even give limit query parameters is 100. kindly help.

### ISSUE THREAD

**Issue by boojan** [etsy/open-api#290]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by etsyachristensen** [comment]
@boojan Unfortunately I'm not able to understand the problem. Can you edit your post and fill in at least the sections "Describe the bug" and "To Reproduce"? The issue name should be short and concise.

Thanks!
