### ISSUE TITLE
[BUG] personalization_instructions not updated in create/update listing endpoints

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#296]
**Describe the bug**
personalization_instructions not updated in create/update listing endpoints

**To Reproduce**
#### update endpoint
request
```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/xxxxx/listings/xxxxxx' \
--header 'x-api-key: xxxxx' \
--header 'Authorization: Bearer xxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxx.; user_prefs=xxxxxxxx.' \
--data-raw '{
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 9999,
    "personalization_instructions": "dummy"
}
'
```

response:
```
{
    ...,
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 9999,
    "personalization_instructions": "1111111",
    ...
}
```

#### create endpoint
request:
```
curl --location --request POST 'https://openapi.etsy.com/v3/application/shops/xxxxxxxx/listings' \
--header 'x-api-key: xxxxxxxx' \
--header 'Authorization: Bearer xxxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxxx.; user_prefs=xxxxxxxx.' \
--data-raw '{
    "title":"no PP ",
    "description":"no PP",
    "quantity":1,
    "price":1,
    "who_made":"i_did",
    "when_made":"2020_2021",
    "is_supply":"false",
    "shipping_profile_id":159135584160,
    "taxonomy_id":66,
    "production_partner_ids":[],
    "item_weight_unit":"oz",
    "item_dimensions_unit":"in",
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 9999,
    "personalization_instructions": "dummydummydummydummydummy"
}'
```
response:
```
{
    ...,
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 9999,
    "personalization_instructions": "1111111",
    ...
}
```

**Expected behavior**
`"personalization_instructions": "1111111", `    
must be
`"personalization_instructions": "dummydummydummydummydummy",`

**Screenshots**
<img width="939" alt="create" src="https://user-images.githubusercontent.com/3578401/143659365-68a7a82f-015b-4fc2-876a-e747789fc61e.png">
<img width="972" alt="update" src="https://user-images.githubusercontent.com/3578401/143659363-10e05378-95e2-474a-810f-eaf7d71a418a.png">

**Additional context**
https://developers.etsy.com/documentation/reference/#operation/createDraftListing

**Comment by dirk-ns** [comment]
Currently the request value of personalization_instructions is always NULL

**Comment by yovasx2** [comment]
any update for this?

**Comment by yovasx2** [comment]
any update?

**Comment by etsyachristensen** [comment]
Sorry for the delay on this @yovasx2. We were pushed back with holiday stuff when this was first posted. We began investigating but had to put it on the back burner. I'll get it back on the map but I'm not sure what priority it will get.

**Comment by etsyachristensen** [comment]
@yovasx2 I put a change into the system yesterday to correct this issue. It came down to a very elusive caching issue. You should now get back the correct instructions when you update personalization instructions.

**Comment by yovasx2** [comment]
still failing, it worked in the first hit but when u played with values they re not reflected
<img width="675" alt="Screen Shot 2022-03-16 at 11 45 24" src="https://user-images.githubusercontent.com/3578401/158654286-59b4f5a2-bcb1-4bc1-ab31-44476ee841c6.png">

cc @etsyachristensen

**Comment by etsyachristensen** [comment]
ok working on this.

**Comment by yovasx2** [comment]
could u please reopen this?

**Comment by etsyachristensen** [comment]
This has now been fixed.

**Comment by yovasx2** [comment]
it's still not reflecting the payload in the response (both are different):
<img width="947" alt="Screen Shot 2022-03-28 at 10 20 41" src="https://user-images.githubusercontent.com/3578401/160443063-8fd9f840-9d59-468a-acd9-a4f11e2bbd82.png">

**Comment by etsyachristensen** [comment]
I noticed you put in “is_personalizable” as false. But required is true. Can you try setting it as true and see if works?

**Comment by yovasx2** [comment]
so if that's false all the rest is ignored? That's what I thought but seems to be a little bit weird. Yeah I noticed since the original post it was ignored when it was false

**Comment by etsyachristensen** [comment]
Correct. If it's false the fields don't get processed. I'll add that to the documentation.

**Comment by yovasx2** [comment]
@etsyachristensen now the API is not updating even when the is_personalizable value is true, could u please check it, I attach a SS for the 3 individual fields s
<img width="949" alt="Screen Shot 2022-04-08 at 17 10 41" src="https://user-images.githubusercontent.com/3578401/162540433-27104534-c692-4d99-baac-e888058e6273.png">
ent with is_personalizable

<img width="945" alt="Screen Shot 2022-04-08 at 17 10 17" src="https://user-images.githubusercontent.com/3578401/162540440-167ebce4-f1cb-48ba-87b2-72d1a751fea3.png">
<img width="951" alt="Screen Shot 2022-04-08 at 17 11 02" src="https://user-images.githubusercontent.com/3578401/162540421-140b1246-552d-49b7-91f5-e1ed52ee35e1.png">

**Comment by akowi-sknobloch** [comment]
We experience the same Bug as @yovasx2.
Please revisit this issue.

We set `is_personalizable` to true
Add a `personalization_instructions`
And set `personalization_is_required` to false

In the Response 
`is_personalizable` is true
`personalization_instructions` is null
`personalization_is_required` is false

In the Webinterface Personalization is still required even we are setting it to false.

**Comment by yovasx2** [comment]
@akowi-sknobloch as a workarrounf I send the 4 values as a bundle and API works

**Comment by akowi-sknobloch** [comment]
@yovasx2 OK i tried setting all 4 values and now it works! Thanks!
If this is the intended behaviour, this should be better documented.
