### ISSUE TITLE
[BUG] The create listing images endpoint is not honoring the rank (and execution order)

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#298]
**Describe the bug**
i removed all the images of a listing (delete endpoint, until listing is not having images)
then sent images (post) one by one in the desired order with correct rank (1-10) the responses are giving me the correct rank (1-10):
desired order:
`["3556623937","3556624095","3508989522","3508989812","3556624153","3556659489","3508989482","3509025360","3508989976","3556659423"]`
Endpoint hits obtained after the promise is resolved and executed in the order above with correct rank:
```
2021-12-01T19:35:46.011-06:00	2021-12-02T01:35:46.011Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3556623937,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/c70443/3556623937/il_75x75.3556623937_lmy6.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/c70443/3556623937/il_fullxfull.3556623937_lmy6.jpg","responseRank":1,"rank":1}

2021-12-01T19:35:46.378-06:00	2021-12-02T01:35:46.378Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3556624095,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/d8fafc/3556624095/il_75x75.3556624095_cjk6.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/d8fafc/3556624095/il_fullxfull.3556624095_cjk6.jpg","responseRank":2,"rank":2}

2021-12-01T19:35:46.647-06:00	2021-12-02T01:35:46.647Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3508989522,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/f63cf0/3508989522/il_75x75.3508989522_paxp.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/f63cf0/3508989522/il_fullxfull.3508989522_paxp.jpg","responseRank":3,"rank":3}

2021-12-01T19:35:46.951-06:00	2021-12-02T01:35:46.951Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3508989812,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/76d13c/3508989812/il_75x75.3508989812_6t8c.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/76d13c/3508989812/il_fullxfull.3508989812_6t8c.jpg","responseRank":4,"rank":4}

2021-12-01T19:35:47.239-06:00	2021-12-02T01:35:47.239Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3556624153,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/f572f1/3556624153/il_75x75.3556624153_2eht.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/f572f1/3556624153/il_fullxfull.3556624153_2eht.jpg","responseRank":5,"rank":5}

2021-12-01T19:35:47.576-06:00	2021-12-02T01:35:47.575Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3556659489,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/1ebf99/3556659489/il_75x75.3556659489_jj8j.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/1ebf99/3556659489/il_fullxfull.3556659489_jj8j.jpg","responseRank":6,"rank":6}

2021-12-01T19:35:47.844-06:00	2021-12-02T01:35:47.844Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3508989482,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/8fd75a/3508989482/il_75x75.3508989482_6s4i.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/8fd75a/3508989482/il_fullxfull.3508989482_6s4i.jpg","responseRank":7,"rank":7}

2021-12-01T19:35:48.132-06:00	2021-12-02T01:35:48.132Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3509025360,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/202b0a/3509025360/il_75x75.3509025360_f7vr.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/202b0a/3509025360/il_fullxfull.3509025360_f7vr.jpg","responseRank":8,"rank":8}

2021-12-01T19:35:48.396-06:00	2021-12-02T01:35:48.396Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3508989976,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/5db56c/3508989976/il_75x75.3508989976_juwz.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/5db56c/3508989976/il_fullxfull.3508989976_juwz.jpg","responseRank":9,"rank":9}

2021-12-01T19:35:48.705-06:00	2021-12-02T01:35:48.705Z ddfd78cf-99ec-47cf-a269-141d3eade6ce INFO Gio: addExistingListingImage {"id":3556659423,"thumbnailUrl":"https://i.etsystatic.com/18976342/r/il/0efbf6/3556659423/il_75x75.3556659423_pdah.jpg","fullsizeUrl":"https://i.etsystatic.com/18976342/r/il/0efbf6/3556659423/il_fullxfull.3556659423_pdah.jpg","responseRank":10,"rank":10}
```
As u can notice, **the first image** sent with **rank 1** is **3556623937**, but when i retrieve the images after all the posts are executed above, that image is not at place 1, it is at 2:
`[3508989522,3556623937,3556624095,3508989812,3556624153,3556659489,3508989482,3509025360,3508989976,3556659423]
`
v2 is working well because v2 is having a parameter in listing (update endpoint) called **image_ids** where you can enter the desired order  to fix any possible error happened in v2, v3 is not having that parameter

**To Reproduce**
See above

**Expected behavior**
The order of getAllImages must be the order of rank and execution

**Additional context**
This happens randomly like 1 of 3-5 tries, not happening manually (postman), my guess is the code is faster, possibly a race condition

**Comment by etsyachristensen** [comment]
@yovasx2 I have added `image_ids` to the `updateListing` endpoint. You can now submit the images ids for the listing in the order you want them to appear.

**Comment by amitshuklaCedcoss** [comment]
> @yovasx2 I have added `image_ids` to the `updateListing` endpoint. You can now submit the images ids for the listing in the order you want them to appear.

@etsyachristensen after this recent update, I'm getting issues in [createDraftListing](https://developers.etsy.com/documentation/reference/#operation/createDraftListing) .
on etsy incomplete stores (onboarding steps not completed on store). 
error is as 

> Array (
    [last_response] => Client error: `POST https://openapi.etsy.com/v3/application/shops/19453804/listings?language=en` resulted in a `400 Bad Request` response:
[{"path":"\/images","type":"array_too_short","message":"cannot be less than 1 items"}]
    [message] => Array
        (
            [0] => Array
                (
                    [path] => /images
                    [type] => array_too_short
                    [message] => cannot be less than 1 items
                )
        )
    [http_code] => 400
)

+ one more point, in *createDraftListing* API call there is one index as 

> <html>
<body>


image_ids | Array of integersAn array of numeric image IDs of the images in a listing, which can include up to 10 images.
-- | --



</body>
</html>

but here problem is, to get image_ids, we need listing_id ([uploadListingImage](https://developers.etsy.com/documentation/reference/#operation/uploadListingImage)) 

plz help me to get this resolved. 
thanks

**Comment by amitshuklaCedcoss** [comment]
> @amitshuklaCedcoss Are you passing in an empty `image_ids` field? If the field is included in the post, but there are no values you'll get that error. I'm not able to duplicate this issue on my end. Can you provide the full POST data that is being sent to the endpoint? You can of course blank out the private info like tokens and api keys etc.


> POST /v3/application/shops/19045598/listings?language=en HTTP/1.1
Host: openapi.etsy.com
Content-Type: application/json
x-api-key: {key}
Authorization: Bearer {access_token}
Cache-Control: no-cache
Postman-Token: 8294bf73-7c51-daaf-59e4-66476b4bcaef

#### Body params

> `{"quantity":4,"title":"14k Wire Bloom Earrings","description":"Sed in metus nec dui consequat vestibulum. In varius pretium nunc, sed bibendum mauris lacinia non. Praesent vel neque ut ligula porttitor vestibulum ac eu erat. Pellentesque quis turpis odio. Etiam auctor laoreet ligula, vel aliquam urna ornare sed. Praesent laoreet diam vitae lectus molestie pulvinar.\n\n\nNullam blandit\nVestibulum euismod\nNullam venenatis\u00a0\nAenean a magna eros\n\n","tags":["Rose Gold","tags-count-get"],"price":4.73,"shipping_profile_id":131166069780,"is_taxable":false,"state":"draft","processing_min":4,"processing_max":5,"taxonomy_id":6243,"who_made":"i_did","is_supply":true,"when_made":"made_to_order","item_dimensions_unit":"in"}`


#### Etsy response
> [{"path":"\/images","type":"array_too_short","message":"cannot be less than 1 items"}]


@etsyachristensen hopes this data will help you to re-generate the case. 
Thanks

**Comment by etsyachristensen** [comment]
@amitshuklaCedcoss I just processed the exact same data using a test store on our system and this is the response:
```
{
    "listing_id": zzzzzzzzz,
    "user_id": xxxxx,
    "shop_id": yyyyy,
    "title": "14k Wire Bloom Earrings",
    "description":"Sed in metus nec dui consequat vestibulum. In varius pretium nunc, sed bibendum mauris lacinia non. Praesent vel neque ut ligula porttitor vestibulum ac eu erat. Pellentesque quis turpis odio. Etiam auctor laoreet ligula, vel aliquam urna ornare sed. Praesent laoreet diam vitae lectus molestie pulvinar.\n\nNullam blandit\nVestibulum euismod\nNullam venenatis\ \nAenean a magna eros",
    "state": "draft",
    "creation_timestamp": 1642518026,
    "ending_timestamp": 1652882426,
    "original_creation_timestamp": 1642518026,
    "last_modified_timestamp": 1642518027,
    "state_timestamp": 1642518026,
    "quantity": 4,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/zzzzzzzzz/14k-wire-bloom-earrings",
    "num_favorers": 0,
    "non_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": 0,
    "tags": [
        "Rose Gold",
        "tags-count-get"
    ],
    "materials": [],
    "shipping_profile_id": 74626525897,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": true,
    "item_weight": 0,
    "item_weight_unit": null,
    "item_length": 0,
    "item_width": 0,
    "item_height": 0,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
        "amount": 473,
        "divisor": 100,
        "currency_code": "USD"
    },
    "taxonomy_id": 6243,
    "production_partners": [],
    "skus": []
}
```

I'm not entirely sure what's happening on your end. You aren't also posting files at the same time right? Not passing the image for the listing as part of the post?

One thing I noticed is that your URL is https://openapi.etsy.com but you should be using https://api.etsy.com. It shouldn't matter, but just in case please update the url on your end.

What is the shop ID you're getting this on?

**Comment by amitshuklaCedcoss** [comment]
##### What is the shop ID you're getting this on?
>  shop_id: 19453804

##### API url
> https://api.etsy.com/v3/application/shops/19453804/listings?language=en

##### One thing I noticed is that your URL is https://openapi.etsy.com but you should be using https://api.etsy.com. It shouldn't matter, but just in case please update the url on your end.
> updated this base url in sdk for now, after updating url , 2 items (listing_id: 865266234 & 700664348) successfully updated. But again tried for few more items and then again same error getting as previous. 

##### I'm not entirely sure what's happening on your end. You aren't also posting files at the same time right? Not passing the image for the listing as part of the post?
>  yes not posting image for the listing as part of the post, due to api restriction. on first upload *[createDraftListing](https://developers.etsy.com/documentation/reference/#operation/createDraftListing)* I don't having image_ids.

image_ids | Array of integers An array of numeric image IDs of the images in a listing, which can include up to 10 images.
-- | --

![image](https://user-images.githubusercontent.com/25526103/150140926-ada68f95-691d-4857-963c-7498ec3828b5.png)

@etsyachristensen plz see these details, hope this will clear my issue.
thanks.

**Comment by amitshuklaCedcoss** [comment]
string(71) "https://api.etsy.com/v3/application/shops/19453804/listings?language=en"
Array
(
    [form_params] => Array
        (
            [quantity] => 999
            [title] => test product
            [description] => test item

            [price] => 99.99
            [shipping_profile_id] => 164760033196
            [image_ids] => Array
                (
                )

            [is_taxable] => 0
            [state] => active
            [processing_min] => 1
            [processing_max] => 2
            [taxonomy_id] => 179
            [who_made] => i_did
            [is_supply] => 1
            [when_made] => made_to_order
            [item_dimensions_unit] => in
        )

    [headers] => Array
        (
            [Content-Type] => application/x-www-form-urlencoded
            [x-api-key] => {api_key}
            [Authorization] => Bearer {access_token}
        )

)

Array
(
    [exception] => Array
        (
            [last_response] => Client error: `POST https://api.etsy.com/v3/application/shops/19453804/listings?language=en` resulted in a `400 Bad Request` response:
[{"path":"\/images","type":"array_too_short","message":"cannot be less than 1 items"}]


            [message] => Array
                (
                    [0] => Array
                        (
                            [path] => /images
                            [type] => array_too_short
                            [message] => cannot be less than 1 items
                        )

                )

            [http_code] => 400
            
        )

)


@etsyachristensen we have checked again with few more items and getting same error. Though I mentioned some ids with that I get success after your response. but for some more try getting image error on same store. 

###### It seems this case was random, let me know if any other details are needed. 
thanks for your prompt response.

**Comment by amitshuklaCedcoss** [comment]
hi @etsyachristensen 
any luck?

**Comment by ramwebkul** [comment]
I have the same issue in creating Draft Listing on Etsy:
I have tried with both endpoints:
https://api.etsy.com/v3/application/shops/19453804/listings?language=en
https://openapi.etsy.com/v3/application/shops/19453804/listings?language=en

I have also passed "state"="draft" parameter to make sure. Our request data is:

    "title" => "Mug The best is yet to come"
    "quantity" => 300
    "description" => "The best is yet to come! Start the day off right with a positive thought. 8,2cm diameter / 9,5cm height / 0.43kg. Dishwasher-proof."
    "taxonomy_id" => "1"
    "price" => 11.9
    "who_made" => "i_did"
    "is_supply" => 0
    "when_made" => "made_to_order"
    "shipping_profile_id" => "169711000725"
    "state" => "draft"
    "has_variations" => false

I am getting the same error:
    
    [{"path":"/images","type":"array_too_short","message":"cannot be less than 1 items"}]

I think the image_ids should be required only for "active" listing. Because while uploading listing images, the listing ID is required. So while creating draft listing, image_ids should not be required.

I have also noticed documentation issue:
The createDraftListing endpoint in API v3 should create listing in draft state, but the response data in the documentation is showing `"state"="active"`:

![image](https://user-images.githubusercontent.com/53465735/161275864-f2c09d96-b643-4866-8492-3c4007c18ea6.png)

Also, there is no request parameter as "state" in createDraftListing endpoint. How can I make sure the listing is "draft" and image_ids are not required at first time?

Please help and guide me how to implement this API endpoint?

Thanks in advance.

**Comment by etsyachristensen** [comment]
Apologies all. I haven't run into this issue on the API previously except when "image_ids" is provided as part of the payload into the createDraftListing endpoint.

You do NOT include a state when creating a listing as the system will automatically set it to default. You can't create a listing in any other state.

@ramwebkul Are the parameters you provided your full payload? Can you provide the full payload as a curl command or something so I can attempt to reproduce the issue?

@amitshuklaCedcoss I see in your payload that you include this:
 ```
        [image_ids] => Array
            (
            )
 ```
 This will result in that error. If you have no images to link, do not pass the image_ids parameter.

**Comment by ramwebkul** [comment]
Hi @etsyachristensen ,
As requested, please find below the full payload as a curl request:

    curl --location --request POST 'https://openapi.etsy.com/v3/application/shops/20816651/listings?language=en' \
    --header 'x-api-key: bmlftw8cspgswbh1tyq8m3vu' \
    --header 'Authorization: Bearer 225902729.4GnBrWuCv4iyh9z6ZvqhR8sX6H6oTzs3il7WJI-SA1s9WCAaGjEmHMxRx6Kekx9a7AmOhYFmKql8LjcwdoRoD7V1Ye' \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --header 'Cookie: exp_hangover=FLsLgSjQzjW8q1pe26KYpFO8WKljZACCJLdlfRB667RqpYLUorQY_fLUpPjEopLMtMzkzMSc-JzEktS85Mr4QsN4IwMjIyWrtMSc4tRaBgA.; fve=1648797326.0; uaid=TWT6k8rz_z62tU_qPU4ww2ZRNEpjZACCJLdlfTC6Wqk0MTNFyUqpPNS5XNckyCDUP6wqzyMyr7LStSoo2yUyL9PcXamWAQA.; user_prefs=78ugHu4VqY8AE5hJ4tXAn8MfNRJjZACCJLdlfTA6WsnTL0hJJ680J0dHKTVP191JSQcoBBUxglC4iFgGAA..' \
    --data-urlencode 'title=new product' \
    --data-urlencode 'description=desc' \
    --data-urlencode 'price=1.99' \
    --data-urlencode 'who_made=i_did' \
    --data-urlencode 'when_made=made_to_order' \
    --data-urlencode 'taxonomy_id=1' \
    --data-urlencode 'shipping_profile_id=168891774244' \
    --data-urlencode 'quantity=1'

Awaiting your guidance.

**Comment by ramwebkul** [comment]
Hi @etsyachristensen,
Any update on this issue?

**Comment by ramwebkul** [comment]
Hi @etsyachristensen, 
I already sent the complete request data as you asked in following thread:
https://github.com/etsy/open-api/issues/298#issuecomment-1087115449

Please check and guide me through the correct process to create Etsy listing.
I am stuck in process and waiting for your response.

**Comment by etsyachristensen** [comment]
@ramwebkul Sorry I haven't been able to get back to this thread. 

I tested your payload and on my test accounts both in-house and in production I'm able to create listings with that same payload (and my own token/api key). So I used your token and api key and sure enough I got the same error as you are getting.

It seems to be something with the account that's getting in the way and we are looking into it. Odd that it would be throwing the images error though. Will let you know what we find.

**Comment by etsyachristensen** [comment]
@ramwebkul It appears that your shop isn't fully complete. I don't know for sure that this is the issue, but if you could please go into your shop manager in the Etsy website and complete the setup of the shop. The API doesn't allow creating listings without the shop being setup all the way. Odd that you are getting an array too short error. If completing the shop setup fixes the issue, please let me know so that we can investigate how that error is coming up for this situation.

**Comment by etsyachristensen** [comment]
Sorry for the confusion @amitshuklaCedcoss. I believe this was a recent requirement put in place around the time we put OpenAPI V3 out.
