### ISSUE TITLE
[BUG] Products in Etsy Pattern are unselected when they are updated via API V3

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#299]
**Describe the bug**
Our clients reported the listings selected for Etsy Pattern are becoming unselected after editing their product via our app, which is updating the listings via updateListing endpoint v3 (we haven't tested this in v2, but probably is behaving in the same way)

**To Reproduce**
1. Set up your Etsy listing to push the listing to Etsy Pattern (see screenshot at the bellow)
2. Then hit the updateListing endpoint in v3 (try v2 to discard it) 
3. The checkbox for Pattern becomes unselected

**Expected behavior**
The usage of API must only impact the listing properties and not the PAttern configuration for the listing

**Screenshots**
![image-2021-12-02-11-40-38-316](https://user-images.githubusercontent.com/3578401/144495130-004e0291-13d2-4e7f-9cda-c6d7b3cd7e1f.png)

**Additional context**
Our customers' complaints started when we migrated to V3, but could you please confirm V2 has not the same behavior?

**Comment by etsyachristensen** [comment]
@yovasx2 This has been fixed. Please give it a shot when you get a chance.

**Comment by yovasx2** [comment]
was this fixed for v3 or v2?

**Comment by etsyachristensen** [comment]
V3. I didn't check to see if the issue exists in V2 as that's not under active development. In V2 I believe you could pass "channels" as an input with a comma delimited list of channels.

**Comment by yovasx2** [comment]
@etsyachristensen it's fixed, our customers confirmed it worked, thanks a lot

**Comment by yovasx2** [comment]
@etsyachristensen  one of a customer is saying this is happening again, could u please take a look and reopen this, please?

**Comment by yovasx2** [comment]
news?

**Comment by etsyachristensen** [comment]
@yovasx2 The fix for this in already in production. It should not be happening any longer.

**Comment by yovasx2** [comment]
thx, you are the best
