### ISSUE TITLE
[DOCS] Rate Limits not specified

### ISSUE THREAD

**Issue by lw-andrewsmith** [etsy/open-api#30]
Couldn't find any information on if rate limits have changed. We often have clients that go over the previous rate limits.

**What would you like to change?**
Define rate limits for new API version.

**Why are you proposing this change?**
To better safeguard against hitting rate limits.

**Comment by capndesign** [comment]
Hello! Rate limits are the same for API v2 and v3 requests. We will update the migration guide to reflect this in case others are curious. Thanks for the feedback!
