### ISSUE TITLE
https://developers.etsy.com/documentation/reference/ is not working

### ISSUE THREAD

**Issue by MrBaz** [etsy/open-api#303]
**Your API Ref. Page is not working **

Your reference page is not working

Something went wrong...
Error downloading https://www.etsy.com/openapi/generated/oas/3.0.0.json Failed to fetch
Stack trace

ReDoc Version: 2.0.0-rc.48
Commit: 7b78e75

**To Reproduce**
Navigate to https://developers.etsy.com/documentation/reference/

**Expected behavior**
The page should display API specs

**Comment by etsyachristensen** [comment]
This happens occasionally. The fix is simply to do a hard refresh in your browser. We aren't sure what causes this but it's some issue that causes the system to cache some path to the OAS file that feeds the format of the developer guide.
