### ISSUE TITLE
Country association in receipt object

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#305]
**Current Endpoint Design**
In V2, there was the [Country association](https://www.etsy.com/developers/documentation/reference/receipt#section_associations) at the receipt object
 
**Proposed Endpoint Design Change**
Add the association back to the API upon request

**Why are you proposing this change?**
In V3 this association, along with others, is missing (I need it for the formatted country name).
I noticed that the new API returns a _formatted_address_ field which contains a country name which can be extracted.
Can this indeed be used for getting country name?

**Comment by etsyachristensen** [comment]
The shop receipt object contains an `country_iso` field that you can use. Here's the documentation: https://developer.etsy.com/documentation/reference/#operation/getShopReceipt
