### ISSUE TITLE
[BUG] API is claiming for lower limit of 0.20 but that is not applicable for all the currencies

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#309]
**Describe the bug**

1. I set my shop with euros currency, Etsy UI handles the lower limit as 0.18 euros but API is requiring more than 0.20
2. The v3 docs says the price is in the range with lower limit as 0.2 Why API is not honoring that doc?
3. Inconsistencies in the errors for lower limit among different currencies

**To Reproduce**
Set your shop to a currency more valuable than USD (e.g. euros), then hit the API, create/update endpoints are affected as well as inventory

**Expected behavior**
API to respect same range as the UI

**Screenshots**
<img width="947" alt="Screen Shot 2021-12-17 at 16 15 52" src="https://user-images.githubusercontent.com/3578401/146614316-a4dfbe4d-2e38-42b9-aa95-98e7ffb965af.png">
<img width="961" alt="Screen Shot 2021-12-17 at 15 58 58" src="https://user-images.githubusercontent.com/3578401/146614319-c996c4e1-b735-4724-9ee7-f5e158e44b4c.png">
<img width="1357" alt="Screen Shot 2021-12-17 at 15 56 25" src="https://user-images.githubusercontent.com/3578401/146614322-467e2ac4-4a7d-46c0-9112-0720217074eb.png">

**Additional context**
I would like to have a price for all the endpoints in the range mentioned in the docs for v3 from 0.2 to the upper limit

**Comment by etsyachristensen** [comment]
@yovasx2 This has been fixed on the updateListing endpoint. I'm working on the createDraftListing endpoint now.

**Comment by yovasx2** [comment]
What is the current behavior?

**Comment by etsyachristensen** [comment]
The API (internal to our system) calculates the current rate between currencies and allows you to set the price in a different currency to whatever the exchange rate is for $0.20 USD. I don't know how often the rates are updated, but I would presume it's pretty regularly updated.
