### ISSUE TITLE
[BUG] Item weight and dimensions fields are not nullable

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#311]
**Describe the bug**
when u try to use update listing endpoint to set to null item_weight_unit or item_dimensions_unit those fields are preserving their non null value

**To Reproduce**
set item_weight_unit and item_dimensions_unit to non null (eg oz and in), then use the update listing endpoint to send null values

**Expected behavior**
Nullify those fields when u send null values, according to docs

**Screenshots**
<img width="930" alt="Screen Shot 2021-12-20 at 17 39 19" src="https://user-images.githubusercontent.com/3578401/146847044-45cd473c-ece8-46c3-a0d9-1b42bb8bd723.png">

<img width="578" alt="Screen Shot 2021-12-20 at 17 39 07" src="https://user-images.githubusercontent.com/3578401/146847049-813fd29f-260e-4808-b924-a900c0767e09.png">

**Additional context**
https://openapi.etsy.com/v3/application/shops/{{shop_id}}/listings/1127318636

**Comment by etsyachristensen** [comment]
@yovasx2  We've added this to our list of items to work on in the near future.

**Comment by yovasx2** [comment]
probs involves #278

**Comment by yovasx2** [comment]
is there an update on this?

**Comment by mfarooq925** [comment]
@etsyachristensen is there an update on this? 

I tried: curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/24055913/listings/1078113827?item_weight=40&item_weight_unit=oz'

and the response shows that the weight remains unchanged
{
   ...
    "item_weight": 22,
    "item_weight_unit": "oz",
    "item_length": 10,
    "item_width": 10,
    "item_height": 1,
    "item_dimensions_unit": "in",
  ...
}

**Comment by etsyachristensen** [comment]
@mfarooq925 I can't duplicate the experience you are having. I tested the same inputs you are sending on a listing and it goes through just fine. Can you test it again?

@yovasx2 I was just going through this and realized you are sending JSON data to the endpoint in postman. That won't result in any change. Also, if the shipping_profile_id points to a calculated shipping profile it won't allow the values to be null but it should throw the error.

**Comment by mfarooq925** [comment]
@etsyachristensen that is odd. I just ran the same curl call and it remains unchanged. I'm using Postman. Are you sending anything else along with the request?

**Comment by etsyachristensen** [comment]
no I was only sending through those same fields "item_weight" and "item_weight_unit" and using the same values.

what encoding are you using?

**Comment by mfarooq925** [comment]
@etsyachristensen 
I left Postman's headers unchanged: Accept-Encoding : gzip, deflate, br

**Comment by mfarooq925** [comment]
Apologies for the back and forth. But I tried this curl from terminal and am still getting 22oz back in the response.

curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/24055913/listings/1078113827?item_weight_unit=oz&item_weight=40' \
--header 'x-api-key: KEY' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Bearer TOKEN' \

**Comment by etsyachristensen** [comment]
Ok I'm looking at that listing in our logs and I don't see any updates with 40 as the item_weight. These are the most recent api logs we have.

| __Timestamp__ | __UUID__ | __Content__                                                                                 |
|---------------------------|------------------------------|--------------------------------------------------------------------------------------------------------|
| 2022-07-07 16:52:36 -0400 | EuQCpojJ-Qp05rEaiGYeLC-D3ieb | Has only description                                                                                   |
| 2022-07-07 16:43:05 -0400 | Eu9k4DCnvmOQi-OuSIzP0DuuTv21 | Has only title and description                                                                         |
| 2022-07-07 16:40:49 -0400 | EuxrAQ9hjDkVK3k1CbqB7NyKQB9c | Has the item\_weight = 22 along with description, other item dimensions and units, taxonomy, tags etc  |

**Comment by etsyachristensen** [comment]
Can you give me the full exact response along with headers? (minus your private data of course)

**Comment by etsyachristensen** [comment]
I see a new update just came through but again it only has the description, no item_weight or item_weight_unit.

**Comment by mfarooq925** [comment]
[etsy.txt](https://github.com/etsy/open-api/files/9068046/etsy.txt)

Please see attached.  My curl does not have any data-urlencoded params

**Comment by etsyachristensen** [comment]
Thanks @mfarooq925. I don't believe that will work. If you are in Postman, are you putting the inputs in the Params section or in the Body section? If you are putting them in the params, that's why it's generating the `?item_weight=40&item_weight_unit=oz` in the URL. That's not proper form data. You have to put the in the Body tab:
![image](https://user-images.githubusercontent.com/83842847/177998866-03a1cf97-dc30-4c34-b4e0-f9718824237f.png)

**Comment by etsyachristensen** [comment]
@yovasx2 Are you still experiencing this issue? The only way you should be able to null out those values is by having a listing that is using fixed shipping profile (thus not needing the item weight and dimensions). Since Postman doesn't allow sending null values (it translates into a '' string) I can't really duplicate the issue reliably.

**Comment by mfarooq925** [comment]
Thank you @etsyachristensen ! I think I'm good now

**Comment by etsyachristensen** [comment]
@yovasx2 First, in postman, you can't send `raw` to the endpoint as it requires `x-www-form-urlencoded`. That said, I don't think your application is using `raw`. That said, it turns out that `x-www-form-encoded` will send empty values as strings `''`. We need to make some changes on our end to convert the empty string to null before saving. That may take some time though.

**Comment by etsyachristensen** [comment]
@yovasx2 With the change just pushed out, if you change your call to the `updateListing` endpoint to PATCH method from PUT, you should be able to pass in null or empty values for those item_xxx fields to null them out, but only if the listing is digital or uses a fixed shipping profile.

**Comment by yovasx2** [comment]
thx I will test it
