### ISSUE TITLE
[DOCS] Oauth conversion is now supported.

### ISSUE THREAD

**Issue by dbeleznay** [etsy/open-api#317]
**Link to Documentation Issue**
Please add a link here for which part of the documentation you're reporting an issue.
https://developers.etsy.com/documentation/essentials/authentication#apiv2-endpoints-and-oauth2-tokens

**What would you like to change?**
Please describe your proposed change here.
You mention:
We currently do not support converting an OAuth 1.0 token into an OAuth 2.0 token.

I think this should be removed.

**Why are you proposing this change?**
Please provide a reason for the change you're proposing.

later on you have the section:
https://developers.etsy.com/documentation/essentials/authentication#exchange-oauth-10-token-for-oauth-20-token
where it's clearly supported

**Comment by etsyachristensen** [comment]
Thanks for pointing this out. Fix coming shortly.
