### ISSUE TITLE
[DOCS] All post request examples are not in valid JSON

### ISSUE THREAD

**Issue by dbeleznay** [etsy/open-api#318]
**Link to Documentation Issue**
Please add a link here for which part of the documentation you're reporting an issue.
https://developers.etsy.com/documentation/essentials/authentication#step-3-request-an-access-token

**What would you like to change?**
Please describe your proposed change here.

All of the post reuquests are not in valid JSON

 {
      "grant_type"="authorization_code",
      "client_id"="1aa2bb33c44d55eeeeee6fff",
      "redirect_uri"="https://www.example.com/some/location",
      "code"="bftcubu-wownsvftz5kowdmxnqtsuoikwqkha7_4na3igu1uy-ztu1bsken68xnw4spzum8larqbry6zsxnea4or9etuicpra5zi",
      "code_verifier"="vvkdljkejllufrvbhgeiegrnvufrhvrffnkvcknjvfid"
    }

should have all of the ='s replaced with :'s

**Why are you proposing this change?**
Please provide a reason for the change you're proposing.

it's confusing to not have valid JSON here.

**Comment by etsyachristensen** [comment]
@dbeleznay Sorry for the confusion and thanks for the feedback. Fix coming soon.
