### ISSUE TITLE
[BUG] Getting issue in updateVariationImages

### ISSUE THREAD

**Issue by amitshuklaCedcoss** [etsy/open-api#32]
**Getting issue in updateVariationImages .**
Case 1: When any client adds/updates images sequence on variation level from Etsy seller panel then after updateVariationImages call those sequences are reverted back to original.
Case 2: Whenever Any client changes **Link photo** option directly from the Etsy seller panel and disable the images linking option from our app, then after **updateInventory** call all variation level images got vanished.

**Describe the solution you'd like**
[updateVariationImages](https://www.etsy.com/developers/documentation/reference/listingvariationimage#method_updatevariationimages)

> Parameters.**discardOld** | boolean | Optional | If false, Existing varition images will persist, new request data will be ignored.

**Describe alternatives you've considered**
[http://api.bonanza.com/docs/reference/add_fixed_price_item](http://api.bonanza.com/docs/reference/add_fixed_price_item)
Not sure if this doc helps u, but if you search for **discardOld** you will get clearly my point

**Comment by etsyachristensen** [comment]
@amitshuklaCedcoss Many changes have happened with the OpenAPI V3 since this was opened. I believe this has all been addressed, but I'm not 100% certain. Can you please re-open this issue if you are still experiencing issues with this endpoint?
