### ISSUE TITLE
[BUG]: Listing_Type on GET's returns 0 or 1 instead of Enumerated String or Boolean

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When getting a listing using getListing, findAllListingsActive, findAllActiveListingsByShop, etc etc... anything that returns the ShopListing schema, the property called listing_type has a value of either 0 or 1.

0 = Physical, 1 = Download.

Documentation, plus the AOS file says the following
![image](https://user-images.githubusercontent.com/22307223/147994737-6b1b1679-6459-4030-9b7c-2af82e9f0345.png)
![image](https://user-images.githubusercontent.com/22307223/147994774-6f22a687-6810-41b7-b9c6-4adc6041a875.png)

The values returned, 0 or 1, doesn't match what is being said, they are neither a Boolean or a Enumerated string.

### Steps to reproduce

An example would be to call **findAllListingsActive**

Here is an example response payload of listing for a physical type.
![image](https://user-images.githubusercontent.com/22307223/147994957-f35b9350-bdde-4eed-9aca-affb8ff36ffd.png)

Here is an example response payload of a listing for a download type.
![image](https://user-images.githubusercontent.com/22307223/147995340-55e17cef-e348-458b-8049-685f6f679b16.png)

### Expected behavior

When Creating a listing, the corresponding property for **listing_type** is **type**. And you can see from your documentation that it is indeed an enumerated string. (Although it does have a value for "both" which I don't have an example for to show in the reproduce section)

![image](https://user-images.githubusercontent.com/22307223/147995046-e6da55cd-6cec-43b7-aa6c-75e47fc40cc7.png)

**Expected behaviour option 1**
Because these are the values we have to provide when creating a listing, I would expected to get those string values back when getting a listing from the API

**Expected behaviour option 2**
Update the documentation (and OAS) to show that the return value isn't a Boolean and instead its an enumerated integer and include a description of what the integer values are equal to. 0 = Physical, 1 = Digital, 2 = Both (?)

**Comment by Gareth064** [comment]
I've just noticed that on the Example Response for getListing it shows the listing_type value as a Boolean

![image](https://user-images.githubusercontent.com/22307223/147995971-9c264895-6e01-41d8-ac8b-228ff4ae3a78.png)

**Comment by Gareth064** [comment]
@etsyachristensen Can you confirm that this is being looked at?

**Comment by etsyachristensen** [comment]
Yes it's being looked at. No estimate on time at this point.

**Comment by etsyachristensen** [comment]
This is now fixed. Please see the announcement here: https://github.com/etsy/open-api/issues/341
