### ISSUE TITLE
[DOCS]: Get Listing When Made Enum Invalid

### ISSUE THREAD

**Issue by lw-andrewsmith** [etsy/open-api#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/getListing

### What would you like to change?

WhenMade is not really a good candidate as an ENUM field if its going to auto update every year...

![image](https://user-images.githubusercontent.com/48061638/148032153-fd269bd4-3d0a-4ae5-9d50-1e9200d8c807.png)

This makes the documentation, scheme and everything out of date on the 1st of each year requiring app updates reminders and its pretty annoying with auto generation tools. 

### Why are you proposing this change?

Enum value appears to auto update every year.

**Comment by Gareth064** [comment]
What your saying is that this particular value from the enum list is going to change with each year passing until 2029 then it will stop and another new enum will be add for 2030-2030+1 every year.

![image](https://user-images.githubusercontent.com/22307223/148121976-f2263b2e-05f5-45f4-b479-98b1ec501e3a.png)

Sounds crazy. I think on my ApiWrapper I will have to add in enum values for future years then tell people that they need to make sure to NOT choose an enum value in the future.

**Comment by Gareth064** [comment]
This has just changed again since the new release on the 14th Jan

![image](https://user-images.githubusercontent.com/22307223/149617221-65a54fdd-4871-4f59-b4a2-0be6194f8629.png)

**Comment by etsyachristensen** [comment]
Correct. At this point the OpenAPI will continue to use the year ranges. This particular aspect of the OpenAPI system is controlled by a pretty old architecture. Changing it to a new structure will be a larger undertaking that we probably won't have resources to address for a while. Next year, we'll try to do better about updating the year range closer to the change of the year.
