### ISSUE TITLE
[BUG]: Profile_Type for ShopShippingProfile schema on GET's returns 0 or 1 instead of Enumerated String

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is the same type of issue as #321

The enum integer index value is being returned for the **profile_type** property, of the **ShopShippingProfile** schema, instead of the enum string value as it is documented.

### Steps to reproduce

Call **getListing** and include Shipping

Under **shipping_Profile**, the **profile_type** property is returning an integer which I assume is the integer index of the enum value.

![image](https://user-images.githubusercontent.com/22307223/148138649-7f249f2c-2f86-410f-bac1-3301547133b3.png)

Your documentation states it should return a string value of the enum

![image](https://user-images.githubusercontent.com/22307223/148138713-55702f18-b046-49e9-bfdf-0d694107394f.png)

### Expected behavior

The string value of the enum should be returned

**Comment by Gareth064** [comment]
@etsyachristensen Can you confirm that this is being looked at?

**Comment by etsyachristensen** [comment]
Yes it's being looked at. No estimate on time at this point.

**Comment by etsyachristensen** [comment]
This is now fixed. Please see the announcement here: https://github.com/etsy/open-api/issues/341
