### ISSUE TITLE
[BUG]: item_weight on ShopListing response is string instead of number <float>

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you call and endpoint which returns a **ShopListing**, the property **item_weight** returns as a **string** and not a **number<float>** as per your documentation.

Documentation shows
![image](https://user-images.githubusercontent.com/22307223/148464530-2841c678-4391-4715-bde1-5d058099d11d.png)

What is returned
![image](https://user-images.githubusercontent.com/22307223/148464568-ba3d5ac3-6a77-408e-9654-f669da784117.png)

### Steps to reproduce

I got this when calling the **findAllListingsActive** endpoint. The above screenshot comes from listing **563481605**

### Expected behavior

The **item_weight** property to be returned as a **number<float>** as per the documentation.

Probably to at least 1 decimal place but depends how it's stored in your database.
![image](https://user-images.githubusercontent.com/22307223/148464810-82cf0587-260d-49aa-a1a1-6360f19c43c8.png)

**Comment by etsyachristensen** [comment]
@Gareth064 This is been corrected.

**Comment by Gareth064** [comment]
Just confirming that it is now returning as a float
![image](https://user-images.githubusercontent.com/22307223/149617601-db7f6491-fead-4e84-94f2-0f335103c9dd.png)
