### ISSUE TITLE
[FEATURE] Why no webhooks

### ISSUE THREAD

**Issue by cybergrunge-ops** [etsy/open-api#327]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

why do you not have webhooks it would be really awesome if there were webhooks

### Describe the solution you'd like

webhooks would be cool

**Comment by Gareth064** [comment]
This has been raised here numerous times.... It's being tracked under issue #28

**Comment by etsyachristensen** [comment]
As this is indeed a duplicate ticket, I'll close it out. But webhooks have definitely been on our radar. We haven't had a chance yet to scope and discuss this, but I'm personally a big fan of the idea.
