### ISSUE TITLE
[BUG]: taxonomy_id parameter does not work as expected for active listings

### ISSUE THREAD

**Issue by erenturunc** [etsy/open-api#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`findAllListingsActive` operation returns listings from various taxonomies even though a taxonomy_id is given as a parameter.
https://developers.etsy.com/documentation/reference/#operation/findAllListingsActive

### Steps to reproduce

1. Call the URL below. Note that taxonomy `6243` is requested.
```
curl --location --request GET 'https://openapi.etsy.com/v3/application/listings/active?taxonomy_id=6243&sort_on=created&sort_order=desc&limit=100' \
--header 'x-api-key: xxxxxxxxx' 
```
2. You will receive various listings from various taxonomies. 

### Expected behavior

I would expect all returned listings to have the given taxonomy which is 6243 in this case.

**Comment by kbasali** [comment]
Any suggestion about this problem? @etsyachristensen 
Also, I sent a ticket 9 days ago still no answer, would be great if someone can answer.

**Comment by etsyachristensen** [comment]
@kbasali I've got an answer for you, though it's not a great one. The taxonomy_id you're using is a seller taxonomy_id. Unfortunately the search system doesn't search by seller taxonomy ids, but only by buyer taxonomy ids. If you look at the taxonomy tree you get from the [getSellerTaxonomyNodes](https://developer.etsy.com/documentation/reference/#operation/getSellerTaxonomyNodes) endpoint you'll see that the 6243 taxonomy id is nested in the 'Craft Supplies & Tools' main category. That main category is a buyer id and searchable, but the child category 'Yarn & Fiber' (9322) and the child of that category (6243) 'Yarn' are both seller taxonomy ids.

I'm working to try to find out how we can make it clear what taxonomy nodes are seller versus buyer.
