### ISSUE TITLE
[ENDPOINT]: Proposed design change for `updateListing`

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#330]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

The `updateListings` endpoint has no way of specifying the order of images.

### Proposed Endpoint Design Change

The `updateListings` endpoint needs an `image_ids` parameter, just like `createDraftListing`.

### Why are you proposing this change?

It's incredibly painful to change the order of images in a listing right now. Changing rank in `uploadListingImage` sometimes works, sometimes gives the error "This ListingImage already exists and is associated with the requested Listing."

This was painful in v2 (required deleting then reuploading, and even then it was erratic) but in v3 it just doesn't seem to work (or at least, the documentation is unhelpful and I can't figure it out via trial and error). The best solution is simply to let us set the list of ids (in correct order) in one fell swoop.

Likely related issues:  #298 #228 #293

**Comment by etsyachristensen** [comment]
@stickfigure This has been added as of yesterday. You can now include `image_ids` as a comma delimited string of image ides.

**Comment by stickfigure** [comment]
@etsyachristensen are you sure this works?

I've tried a simple test with a listing that has a single image. I call updateListing with that one id as the image_ids (basically a no-op, setting the existing image). The PUT body I'm posting is `image_ids=1148989022`.

I get 400 `{"error":"There was a problem with \/images : That ListingImage does not exist."}`

I've verified that the image id is correct for the listing and shop - I can get the images on the listing and see that this image id exists. I've tried other images that seem like they should work and I get that same error message. Not sure what I could be doing wrong.

**Comment by etsyachristensen** [comment]
I will look into this further @stickfigure . Can you tell me the shop id and listing id?

**Comment by cal-tec** [comment]
Please also see https://github.com/etsy/open-api/issues/120 as this is directly related to updateListing and SKU issues

**Comment by stickfigure** [comment]
After some more poking around, I found this was an error on my end (accidentally submitting the listing id instead of the image id). Terribly sorry for the false alarm! Closing this.
