### ISSUE TITLE
[BUG]: v3 getShopReceipts requires different permission scopes from v2 findAllShopReceipts

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not quite sure how to categorize this - bug, oversight? It makes the API transition *very* difficult.

The v2 findAllShopReceipts method requires `transactions_r`
The v3 getShopReceipts method requires `transactions_r` and `email_r`

Like good citizens, we don't ask for permissions we don't need, so our (v2) app never asked for `email_r`. Our application critically depends on findAllShopReceipts to process orders. If we switch to the v3 API, order processing will halt for all of our customers because we can't call getShopReceipts.

As it stands right now, the only solution to this is to contact *all* of our customers and get them to reconnect with the new permission _before_ we transition to v3. This is challenging, to say the least. And anyone who fails to update by the cutoff will have ordering problems... so we would have to chase them down individually. Yikes.

### Steps to reproduce

Try to access v3 getShopReceipts with a token that does not have `email_r` scope.

### Expected behavior

I expect that the same token that can access v2 findAllShopReceipts should be able to access v3 getShopReceipts.

### Additional context

We've updated our app to request `email_r` and started contacting customers... but honestly, there's no way we're going to reach everyone. I fear this transition is going to be a disaster. Why is `email_r` required for getShopReceipts? Why wasn't it necessary in v2? Can we eliminate the requirement for v3?

**Comment by Gareth064** [comment]
Isn't everyone going to have to re-authenticate your app anyway once V2 API is gone since anyone still using tokens generated from OAuth 1 will find it stops working?

Is that what this is suggesting?

![Screenshot_20220113-181115.png](https://user-images.githubusercontent.com/22307223/149385959-4a75707c-88b5-488d-a94f-41aabcb7f034.png)

**Comment by stickfigure** [comment]
@Gareth064 no, because we can exchange v2 tokens for v3 tokens with the grant_type=token_exchange call.

See https://developer.etsy.com/documentation/essentials/authentication#exchange-oauth-10-token-for-oauth-20-token

But even if this didn't exist and I had to force people to re-auth a second time, I *still* can't migrate to the v3 API until users have granted me the new permission. I can't just say "Oh hey, we made some meaningless-to-you backend change and all your orders will stop getting processed until you click some buttons. Hope you got this email, and hope you aren't on vacation!"

**Comment by Gareth064** [comment]
Ah good stuff. I missed that part of the docs.

**Comment by etsyachristensen** [comment]
@Gareth064 & @stickfigure We've removed the `email_r` requirement from the receipt endpoints to stay in line with V2 behavior. Hopefully this will help.

**Comment by stickfigure** [comment]
@etsyachristensen wow that's fantastic, thanks for the quick fix!
