### ISSUE TITLE
[BUG]: updateListing for title, description

### ISSUE THREAD

**Issue by mfarooq925** [etsy/open-api#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I came across this
https://issueexplorer.com/issue/etsy/open-api/156

But I'm still not able to update the title and description with v3. 

v2 updates are successful 

### Steps to reproduce

- PUT updateListing with a different title. 
- title remains unchanged

### Expected behavior

- title should be updated as long as its within the defined guidelines

**Comment by etsyachristensen** [comment]
@mfarooq925 I am unable to duplicate this issue. Can you email developers@etsy.com and include your shop id and the listing id you're attempting to update? If you can include the entire curl command you're making that would be helpful as well.

**Comment by mfarooq925** [comment]
pls disregard. I was nesting my post fields under a "body" key
