### ISSUE TITLE
[FEATURE]: Add Shipping Method fields to getShopReceipt data

### ISSUE THREAD

**Issue by mhurkman** [etsy/open-api#335]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

IMHO The single biggest omission in order processing in V2 has been the lack of fields describing the customer's selected Shipping Method. The only piece of information passed from the API is the paid shipping amount. This forces us to essentially reverse engineer the matching shipping method from other data like locally stored listing or shipping profile data that may potentially be out of date. 

The shipping method is an essential part of a fulfillment process that needs to be efficient and flawless. Etsy shows this information to those sellers who fulfill through Etsy's marketplace website. I hope that Etsy can offer functional parity to those sellers who use the API to drive their fulfillment process.

### Describe the solution you'd like

I would like to see 2 pieces of information added that unambiguously define the required shipping method:
1) Carrier
2) Mailclass

The values of these fields should match their defined values/names in the relevant ShippingProfile.

### Additional context

Clearly, it is important to have clarity on the required shipping method and I note that Etsy is to my knowledge the *only* order API that does NOT offer this information. Buy comparison, Ebay, Amazon, Walmart, and shopping carts like BigCommerce etc. all do provide this important information to the seller in their respective API's.

For example, Amazon provides the call 'getShipmentServiceLevelCategory()' to retrieve this information from order data. Walmart defines the call 'getShippingServiceSelected()', etc.

**Comment by etsyachristensen** [comment]
@mhurkman He is correct. The endpoint [here](https://developers.etsy.com/documentation/reference#operation/getShopReceipt) will provide that information.
