### ISSUE TITLE
[DOCS]: Issue about canceled order

### ISSUE THREAD

**Issue by Xiaoyi-ji-11** [etsy/open-api#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/getShopReceipt

### What would you like to change?

Hi Etsy API Support,

When I request https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id} for a canceled order, it returns 404 not found and error is "error": "Could not find a Shop Receipt with receipt_id = 2344314448 associated with shop_id = 33264519." How can I know if an order is canceled through api? Please advise.

**Comment by etsyachristensen** [comment]
The OpenAPI at this point will not return canceled orders. This is on our list of requests to address.

**Comment by nh43de** [comment]
@etsyachristensen - Thanks this is a big issue for us as well

**Comment by etsyachristensen** [comment]
FYI This is being fixed in ticket #160 and should be in production by early next week. Canceled receipts will be available via the `getReceipt` endpoint for the moment.
