### ISSUE TITLE
[BUG]: Order update_timestamp doesn't change after refund

### ISSUE THREAD

**Issue by Xiaoyi-ji-11** [etsy/open-api#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After I do partial refund to order, the information from endpoint https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}
doesn't change anything, the total amout still the original amount and the update_timestamp stays same before the refund issued.

### Steps to reproduce

1. Download the order data from _https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}_
2. Issue refund for the order
3. Download the order data from _https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}_
4. nothing changed

### Expected behavior

We might need a new property for refund in the shopReceipt, and when the refund is issued, the update time should change, also the total amout.

**Comment by etsyachristensen** [comment]
Thank you for the feedback. This is on the list of areas to address in the receipts endpoints.

**Comment by etsyachristensen** [comment]
@Xiaoyi-ji-11 We have a fix pending review and testing for showing canceled orders (which have to be refunded). This fix also shows an updated timestamp. Hopefully this will resolve the timestamp problem for you adequately. For the refund lookup, we're still investigating how best to return that information. It may come in the form of another endpoint or something.

**Comment by etsyachristensen** [comment]
@Xiaoyi-ji-11 We've deployed the change to allow for canceled/refunded receipts in the getShopReceipt endpoint. This appears to have fixed the updated timestamp. However it does not update the total as the receipt data is supposed to be static. We will add an issue to our discussion internally about building a `getShopReceiptRefund` endpoint to allow you to query that info.

**Comment by Xiaoyi-ji-11** [comment]
@etsyachristensen Thanks for your update! I will query the endpoint to see if this works. : )

**Comment by Xiaoyi-ji-11** [comment]
The cancelled order can find by id now, but when I query shopReceipts by last_modified time range, the cancelled order and refunded order in that time range didn't return in the response. Can you please check on the endpoint [](https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts)? If the update timestamp is updated, then it should be in the response when quering by last_modified time.

**Comment by etsyachristensen** [comment]
@Xiaoyi-ji-11 We have made the change to the receipt endpoints to ensure that the updated_timestamp is returned with the latest activity on the receipt (refund/transaction etc). See https://github.com/etsy/open-api/releases/tag/3.0.0-general-release-2022-07-19

**Comment by Gareth064** [comment]
As per the conversation on #513  This change won't help us pick up a receipt again if the it has been cancelled or a refund has happened.
