### ISSUE TITLE
[FEATURE]: Allow more than 10 images per listing to support variation images

### ISSUE THREAD

**Issue by neekfenwick** [etsy/open-api#340]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Etsy seems to have a hard limit of 10 images per listing (see https://www.etsy.com/seller-handbook/article/add-photos-to-show-off-your-variations/541206486344#:~:text=If%20you%20want%20to%20upload,you%20can%20add%20is%2010.)  This is insufficient when a variation property has more than 10 possible values and each variation needs a unique image.

Can the limit of 10 be raised?  I don't know what to, exactly, but 10 is very limiting.

For example, when creating a listing with variations, we can specify a property like Primary Colour as the variation, with 19 values suggested and the ability to add more custom ones.  Then in the Variations section we can use the Link Photos button to associate listing images with variations.  It's not possible to provide an image for all the available colour options.

In our case we're using the API to create a listing with 21 different colour options, so we try to upload 21 different images to the listing (POST application/shops/$shop_id/listings/$listing_id/images) and then associate the images with the variations (POST application/shops/{$shop_id}/listings/{$listing_id}/variation-images).  The attempt to upload all 21 images fails with:

400 Bad Request
{\"error\":\"Listings are only allowed 10 images. Please delete a ListingImage before trying to upload another.\"}

### Describe the solution you'd like

Raise the limit of images per listing from 10 to something like 30 or 50.

### Describe any alternatives you've considered

Our workaround would be to list each colour variation of our product as a separate Listing.  We'd much rather use a variation listing because it's a cleaner user experience.

**Comment by etsyachristensen** [comment]
@neekfenwick This is a core Etsy area and not related specifically to the OpenAPI. I will forward your request to the core team, but I'll close this issue here as it's not something we can do on our end until a change is made in the core (if it's to be made). Thank you for your feedback!

**Comment by neekfenwick** [comment]
Thank you @etsyachristensen I understand your position.  Is there a way to track this to know if it has been ignored, rejected, or considered favourably?

I would think that if a relaxation of the number of images is allowed then it would impact the API eventually, since at present there's only one endpoint that allows adding images to a listing and is limited to 10 with no way of indicating that the images are for use on a variation or not.  I expect that if we are allowed to add more images for the purpose of variations, then that information will need expressing via the API, either by a change to `uploadListingImage` or by adding a new endpoint such as a new `uploadVariationImages`.

If the whole suggestion is rejected by the core dev team, this would be valuable info for devs watching this github repo so they can plan their solutions accordingly.
