### ISSUE TITLE
[DOCS]: Clarify how to create and use custom properties for listing variations e.g. colours

### ISSUE THREAD

**Issue by neekfenwick** [etsy/open-api#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/tutorials/listings#how-to-fetch-property-values-for-the-products-array

### What would you like to change?

I really appreciate the extension to the docs that was made in response to another github Issue that explains how to add variation details to a listing.  Can this be extended to explain how to specify new property values, or how to re-use those definitions between multiple listings.

I've managed to follow the Listing tutorial to associate pre-existing Color variations on one of our listings and upload images associated with those Color variations, using just the stock Etsy "Primary Colour" properties.

e.g. I can GET application/seller-taxonomy/nodes/989/properties (for "Living Room Furniture") and see it has a Primary Colour property with property_id 200, and a list of about 19 possible colours, each with a value_id.  Via the Etsy Web UI we can select those colours, and also type in new custom ones such as a made up example "Custom Black".  If I then fetch the listing's properties, I can see the new colour property:

```
        {
            "product_id": 8893213140,
            "sku": "RADCUSTBLACK620X640",
            "is_deleted": false,
            "offerings": [
                {
                    "offering_id": 8891745858,
                    "quantity": 1,
                    "is_enabled": true,
                    "is_deleted": false,
                    "price": {
                        "amount": 5000,
                        "divisor": 100,
                        "currency_code": "GBP"
                    }
                }
            ],
            "property_values": [
                {
                    "property_id": 100,
                    "property_name": "Size",
                    "scale_id": 328,
                    "scale_name": " cm",
                    "value_ids": [
                        1047771588336
                    ],
                    "values": [
                        "620mm Wide x 640mm High"
                    ]
                },
                {
                    "property_id": 200,
                    "property_name": "Primary color",
                    "scale_id": null,
                    "scale_name": null,
                    "value_ids": [
                        578660492922
                    ],
                    "values": [
                        "Custom Black"
                    ]
                }
            ]
        },
```

It has been assigned a value_ids value of 578660492922.

Note: my 'Size' property in that example has value_ids 1069321475541 .. this is a bogus value I borrowed from another listing, and doesn't seem to cause any trouble.  However if I make up a bogus Primary Colour value_id value, I then get errors trying to call `updateVariationImages` because the value_id isn't associated with the property_id 200, so I clearly need to follow some procedure to create a valid value_id that _is_ associated with property_id 200.

When we perform the same task via the API, immediately after creating a draft listing we are expected to call PUT `application/listings/$listing_id/inventory` with the `value_ids` in the payload to create variations on that listing, but if the custom property doesn't exist yet where do you get the value_ids value from?

Once we have created a value_id for our custom colours, we would also like to use that same colour value across several of our listing's variations, e.g. we might have 5 or 6 variation products in "Custom black", each on separate listings.  Is there anything else we need to know to re-use the custom value_id value for property_id 200 across other listings, or would it 'just work'?

Apologies if this is already covered in the docs but I don't see it.

### Why are you proposing this change?

The docs show how to use the stock property_id and values_id values, but not how to create new ones.

**Comment by neekfenwick** [comment]
Just to point out, Issue #248 looks very similar (but isn't a request for enhanced Documentation), and links to https://groups.google.com/g/etsy-api-v2/c/cJg3TlOB0Y8 where people seem to be having similar trouble understanding what they are supposed to do :)

**Comment by neekfenwick** [comment]
I've tried to create a listing with two variations, one a simple "Green" and one with a "Made Up Colour", but the value_ids returned are confusing.  I would think I should post the Green colour using property_id 200 ("Primary color") and value_ids [ 4 ], where 4 is the value_id returned from the taxonomy data.  For the Made Up Colour, I pass a value_ids of [ 1 ] as a complete guess, hoping that a new custom value_id will be assigned by Etsy.  The response from application/listings/{listing_id}/inventory contains completely different value_ids values, and Made Up Colour has been changed to Black.

Request:
PUT {{baseURL}}application/listings/{{listing_id}}/inventory
```
{
    "products": [
        {
            "sku": "TESTGREEN1",
            "offerings": [
                {
                    "quantity": 1,
                    "is_enabled": true,
                    "price": 123
                }
            ],
            "property_values": [
                {
                    "property_id": 200,
                    "property_name": "Primary color",
                    "scale_id": null,
                    "value_ids": [ 4 ],
                    "values": [ "Green" ]
                }
            ]
        },
        {
            "sku": "TESTMADEUP1",
            "offerings": [
                {
                    "quantity": 1,
                    "is_enabled": true,
                    "price": 123
                }
            ],
            "property_values": [
                {
                    "property_id": 200,
                    "property_name": "Primary color",
                    "scale_id": null,
                    "value_ids": [ 1 ],
                    "values": [ "Made Up Colour" ]
                }
            ]
        }
    ],
    "price_on_property": [ 200 ],
    "quantity_on_property": [ 200 ],
    "sku_on_property": [ 200 ]
}
```

Response:
```
{
    "products": [
        {
            "product_id": 8900054300,
            "sku": "TESTGREEN1",
            "is_deleted": false,
            "offerings": [
                {
                    "offering_id": 8898592654,
                    "quantity": 1,
                    "is_enabled": true,
                    "is_deleted": false,
                    "price": {
                        "amount": 12300,
                        "divisor": 100,
                        "currency_code": "GBP"
                    }
                }
            ],
            "property_values": [
                {
                    "property_id": 200,
                    "property_name": "Primary color",
                    "scale_id": null,
                    "scale_name": null,
                    "value_ids": [
                        49974750678
                    ],
                    "values": [
                        "Green"
                    ]
                }
            ]
        },
        {
            "product_id": 8900054302,
            "sku": "TESTMADEUP1",
            "is_deleted": false,
            "offerings": [
                {
                    "offering_id": 8727530709,
                    "quantity": 1,
                    "is_enabled": true,
                    "is_deleted": false,
                    "price": {
                        "amount": 12300,
                        "divisor": 100,
                        "currency_code": "GBP"
                    }
                }
            ],
            "property_values": [
                {
                    "property_id": 200,
                    "property_name": "Primary color",
                    "scale_id": null,
                    "scale_name": null,
                    "value_ids": [
                        49928889190
                    ],
                    "values": [
                        "Black"
                    ]
                }
            ]
        }
    ],
    "price_on_property": [
        200
    ],
    "quantity_on_property": [
        200
    ],
    "sku_on_property": [
        200
    ]
}
```

So I seem to get back value_ids 49974750678 for Green, and my Made Up Colour has been changed to "Black" with a value_ids of 49928889190.  Where are these values coming from?

**Comment by etsyachristensen** [comment]
@neekfenwick I have just been working on another issue in the inventory system that will actually address this issue. In your case, when you don't already have a value_id for your value, leave the `value_ids` array empty (`[]`) and our system will create the value id for anything it doesn't have a value id for and will return that to you. If one already exists it will return that. You will always get back a value_id for the value you pass. Both arrays are required to be included, but `value_ids` may be blank. Conversely, `values` may be blank if `value_ids` is filled in.

**Comment by neekfenwick** [comment]
Thanks @etsyachristensen that makes sense, this seems valid for custom values, but I'm still a little confused by my experience with the stock colour Green.  I got a value_id of 49974750678 back for Green instead of the valid value_id 4.  I just repeated my request, this time leaving value_ids blank `[]` for "Made Up Colour" as you suggested, and got the same value_id 49974750678 for Green, and a new value_id of 1071142040881 returned, so I guess this is a new one Etsy has cooked up.

If I then call GET application/listings/{{listing_id}}/inventory, I see the same value_id 49974750678 for Green and 1071142040881 for Made Up Colour.  Consistent so far.

To experiment, I created a second listing with createDraftListing and uploaded exactly the same inventory payload to it, with colour Green value_id 4 and colour Made Up Colour value_id blank.  I got back exactly the same value_ids as for the first test listing, 49974750678 for Green and 1071142040881 for Made Up Colour.  This implies the value_ids for custom properties will be maintained across different listings, e.g. I could apply Made Up Colour to a hundred listings and they would all maintain the same value_id for that property value.  This would be useful to mention in any docs update you're writing, for people writing support for the Etsy API into their systems.

So both value_ids are consistent, they aren't changing, but I would expect a value_id of 4 to be returned for Green.  What am I doing wrong?

**Comment by etsyachristensen** [comment]
I know that this is a bit confusing. The id 4 being passed in is in fact the id for green, but we have essentially 2 ids:
1. Our known color value id (which we use in the UI on the Etsy website).
2. ID specific to the that same color value but the ID belongs to your shop.

When you pass in `4`, we convert that to your shop's ID for that color. If it's not already in the system for your shop, it will create one. And then you'll use it over and over again any time you provide 'Green' for the color in the `values` field OR if you pass in 4 or your custom ID in the `value_ids` field and subsequent queries to get inventory should return that custom ID and not our known common ID.

There's a number of reasons why we do this but essentially it ensures that you will always have your ID number regardless of what may happen with our interface.

Hope that helps. I'll try to update our docs with something to this effect for other developers.

**Comment by neekfenwick** [comment]
Thanks @etsyachristensen, all this is pretty weird and not documented, so an update for newbies would be greatly appreciated.  I assume you'll associate the changeset with this Issue ticket.

We've got our system publishing variations OK now, so apart from the images limit of 10 raised on another ticket we're pretty much good to go, thanks :)
