### ISSUE TITLE
[BUG]: findAllListingsActive with an offset of 12,001 or more comes back with a 400 HTTP error  

### ISSUE THREAD

**Issue by azs0000** [etsy/open-api#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

findAllListingsActive with an offset of 12,001 or more comes back with a HTTP 400 error, with the message of: Offset provided is greater than the maximum offset allowed.

### Steps to reproduce

curl -H 'x-api-key: F00B@R' "https://openapi.etsy.com/v3/application/listings/active?keywords=toaster&limit=100&so
rt_on=updated&offset=12001" 
{"error":"Offset provided is greater than the maximum offset allowed."}

### Expected behavior

curl -H 'x-api-key: F00B@R'' "https://openapi.etsy.com/v3/application/listings/active?keywords=toaster&limit=100&so
rt_on=updated&offset=12000"  

{"count":310579,"results":[{"listing_id"
<snip>

### Additional context

The documentation at the below link doesn't mention a 400 HTTP method error or any restrictions on a max number for the offset parameter.

https://developers.etsy.com/documentation/reference/#operation/findAllListingsActive

**Comment by azs0000** [comment]
Apologies. Please use "stamp" as an example in the keywords parameter and not "toaster".

**Comment by Gareth064** [comment]
Hi @azs0000 
The 12000 limitation is mentioned here
https://developers.etsy.com/documentation/essentials/urlsyntax#pagination
![image](https://user-images.githubusercontent.com/22307223/150875568-e64b51b8-9a16-432f-874e-725cf731fc32.png)

**Comment by Gareth064** [comment]
I'm also curious about the `"count":310579,"` you mentioned when searching with keyword `toaster`. When I do a search on the website for `toaster` and inspect the api queries using dev tools, I get roughly 3,392 results over 53 pages. I wonder why our public API returns so many more results using the "same" keyword.

**Comment by azs0000** [comment]
Sounds good.

The API has been accurate in returning counts for me. I should have proved you a better example than 'toaster'.
