### ISSUE TITLE
[BUG]: Not getting title of shipping profile back when querying by profile Id

### ISSUE THREAD

**Issue by mmowchan** [etsy/open-api#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When making the getShopShippingProfiles API call in Postman with my shop Id I am getting back a full list of all my defined shipping profiles with their titles. 

However, when making the getShopShippingProfile for a specific profile Id I am seeing that the returned title field is always "null". Is this expected behavior? What needs to be done in order to return the title for a specific shipping profile from a receipt?

### Steps to reproduce

1. Make the getShopShippingProfile API call using a specific shipping profile Id
2. See that it does not return the title

### Expected behavior

A shipping profile is returned but the title field is showing as null

**Comment by etsyachristensen** [comment]
@mmowchan Can you give me an example shipping profile id that I can look into?

**Comment by mmowchan** [comment]
@etsyachristensen To clarify my original post, it looks like the shipping profile Ids being returned on orders are different Ids than those being returned when making the getShopShippingProfiles API call. Is this expected behavior?

For example, I placed test order 2357994268 and selected the shipping profile named "Test Express Profile (Multiple options)". When I make the getShopShippingProfiles API call I am clearly seeing a shipping profile with this title and a shipping profile id of 168047589277. 

However, when I make the Get Receipt API call for my test order, I am seeing a shipping profile id of 167504995790 tied to my order. When I  use the getShopShippingProfile API call to query the shipping profile Id from the order (167504995790) I get a response back saying the title of the profile is "null".

Is there a specific reason the profile Id seems to change on an order by order basis? As well as a reason why the profile Id given for the order does not return a title?

**Comment by etsyachristensen** [comment]
@mmowchan Could you give me the name of your app? I DO NOT need the api key. Alternatively the shop id you are testing with would help. We are looking into this and want to make sure we are looking at the same things. Thanks!

**Comment by mmowchan** [comment]
@etsyachristensen our app name is VeraCore Integration Hub and our shop Id is 28880805
