### ISSUE TITLE
[BUG]: findAllListingsActive doesn't return all results

### ISSUE THREAD

**Issue by ddervosj** [etsy/open-api#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey,

It seems that neither v2 or v3 API "findAllListingsActive" endpoint returns documented number of results.

Max offset for v2 API as per documentation is 50000, but in reality, once offset reaches 12000+  0 results are being returned.

Here are the screenshots for v2 version, but the exact same behavior can be observed using v3 API.

![image](https://user-images.githubusercontent.com/49906438/151709712-7a5fa328-82ac-4066-902b-195d0c41f831.png)
![image](https://user-images.githubusercontent.com/49906438/151709737-ad7735be-cfd6-4957-96a4-2a94449a7bae.png)

Endpoints

- V3 --> https://openapi.etsy.com/v3/application/listings/active
- V2 --> https://openapi.etsy.com/v2/listings/active

### Steps to reproduce

Here's V2 API Python script which results in 0 results even though result count is > 50k (change offset to 12000 to see that)

import requests
import json

api_key = "xxx"

Connection String

payload = {'api_key': api_key, 'keywords': "linen", 'taxonomy': 505, 'offset': 12500}

response = requests.get("https://openapi.etsy.com/v2/listings/active", params=payload, timeout=5)

data = response.json()
data_str = json.dumps(data, indent=2)
print(data_str)

### Expected behavior

Offset limit to be at least 50k (as documented in V2).

**Comment by Gareth064** [comment]
Read here.

https://github.com/etsy/open-api/issues/344
