### ISSUE TITLE
[BUG]: `updateListing` passing image_ids (only) resets title and description too

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When updating a listing passing `image_ids` only, the default language translation title and description are getting nulled out.  I expect the translation values to remain unchanged unless I explicitly specify title= or description=.

### Steps to reproduce

In Etsy production I have a store with default language 'de'.

* Create a listing
* Create two translations, one 'en' one 'de' each with title, description, and tags.
* Update the listing, PUTing `image_ids=3684529251%2C3636920996` (no mention of title or description)
* Notice that the 'de' translation title and description have been reset to null. The tags remain. The english translation remains intact.

### Expected behavior

If I don't PUT title or description to the `updateListing` endpoint, the translation title should remain unmodified.

### Additional context

Possibly related to #222 ?

**Comment by etsyachristensen** [comment]
This is now fixed with the update pushed out today.
