### ISSUE TITLE
[BUG]: Refresh Token constantly changes

### ISSUE THREAD

**Issue by Err1** [etsy/open-api#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not sure if this is a bug or not but having gone through the authorisation / grant process and got back a short-lived access token (AT) and long-lived refresh token (RT)... my understanding is that 

the AT is valid for an hour (from date of issue).
the RT is valid for 90 days (from date of issue).

Thus, when the AT has expired, to refresh it, (without having to go through the entire grant process again), simply following process outlined in their docs: https://developers.etsy.com/documentation/essentials/authentication/#requesting-a-refresh-oauth-token

ie send a POST to https://api.etsy.com/v3/public/oauth/token with application/x-www-form-urlencoded encoded parameters 

	grant_type = refresh_token... 
	client_id = blah
	refresh_token = RT

The response will be:
	{
	    "access_token": "<A-New-AT-Token>",
	    "token_type": "Bearer",
	    "expires_in": 86400,
	    "refresh_token": "<The-original-RT-Token-that-was_sent-in-the-refresh-request>"
	}

That is, a new AT and the original RT that was sent in the refresh request.

However, what I am finding every time is that the refresh request (even if I use the same origin RT) is returning:
	a new AT
	a new RT

### Steps to reproduce

Production environment.

### Expected behavior

Having gone through the OAuth and user grant process, the RT should be valid for 90 days as stated in the docs.  The AT will expire in 1 hr.

However, when the refresh process is followed, a new AT is returned as expected BUT the RT has changed as well.

Why am I still able to use the original RT (for a time only) and also the new RT to request a refresh of the AT?

Why is it that the original RT has now expired when it was issued today and thus should be valid for 90 days?

	{
		"error":"invalid_grant",
		"error_description":"refresh_token is invalid"
	}

If the RT is always different in the refresh response, then when does it expire?

### Additional context

Also, when the RT expires after 90 days, my understanding is that the whole OAuth / User Grant process needs to be repeated to re-generate  another RT, which can then be used to refresh the ATs....

**Comment by etsyachristensen** [comment]
If I'm understanding this correctly, the issue you're running into is when you refresh your expired token, you are getting a new refresh token correct? If so, this is how the OAuth system works. When you request a new token from the 90 day refresh token, it will give you a new 90 day refresh token. Otherwise if you kept re-using the same refresh token, after 90 days it too would expire and you'd have to redo all the auth all over again. The idea here is to store the new refresh token every time you get a new token. That way, unless your app doesn't connect for more than 90 days, you'll never run out of refresh.

**Comment by Err1** [comment]
> 
Indeed.  But I thought the process was that when the AT expired (after 1 hr), that I request a new AT via the refresh process passing in the RT (that would expire 90 days after first issue)..  And in response I'd get a new AT and same old RT.  And, after 90 days, to renew the RT I'd have to repeat that OAuth/Grant process again.

If the RT keeps on getting refreshed, this is good but then when does it (the new RT) expire - I'm guessing 90 days later...?  That is, every RT issued is good for 90 days?

So, if what you say is correct, then I simply follow the refresh process every hour to get a new AT and new RT.

**Comment by etsyachristensen** [comment]
Yes correct. The RT is new and lasts 90 days every time you get a new AT. This ensures you never run out of refresh token.
