### ISSUE TITLE
[BUG]: Cannot activate listing in "edit" state

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to update a listing state to active I get this error message:

{"statusCode":400,"data":"{\"error\":\"Cannot activate a listing in this state: state = edit, listing_id = 1234, ending_tsz = 123\"}

Since listings belong to my customers, I dont want to share them online
Is there a limitation that should be documented? What should be the flow to re-activate a product in edit state?

### Steps to reproduce

Invoke the [updateListing](https://developer.etsy.com/documentation/reference/#operation/updateListing) API on a listing in "edit" state

### Expected behavior

Listing should be updated successfully

**Comment by assaflei** [comment]
Any comments on this?
It was an action that used to work on V2 and now starts creating problems on my systems

**Comment by etsyachristensen** [comment]
@assaflei I have not been able to find a listing in the edit state that can't be activated via the API. Can you email developers@etsy.com and reference me (Andrew Christensen) and this Github issue? Please provide the api key, shop id and listing id so I can try to duplicate your experience?

**Comment by assaflei** [comment]
I sent an email with details, thanks

**Comment by etsyachristensen** [comment]
@assaflei Please look for an email back tomorrow from the support team. In this case the issue isn't with the API but with the listing itself. They can explain in the email. I will work on making some changes to the api response to give back a more appropriate error message in a case like this.

**Comment by amitshuklaCedcoss** [comment]
> {"statusCode":400,"data":"{"error":"Cannot activate a listing in this state: state = edit, listing_id = 1234, ending_tsz = 123"}


> @assaflei Please look for an email back tomorrow from the support team. In this case the issue isn't with the API but with the listing itself. They can explain in the email. I will work on making some changes to the api response to give back a more appropriate error message in a case like this.

Hello @etsyachristensen, 
I'm still facing the same issue in many clients' shops. I had already sent a detailed mail to  [developers@etsy.com]  on *Mon, Feb 21, 8:13 PM (11 days ago)* from *amitshukla@cedcommerce.com* but didn't get any response yet. 

plz once again check same issue. 
thanks

**Comment by assaflei** [comment]
I think that I understood the reason for these messages,
The ending_tsz value is a time that has already passed so I assume the listings are expired and the seller needs to renew them

@etsyachristensen does this make sense to you?
Is there a way to get a more informative message?

**Comment by amitshuklaCedcoss** [comment]
> I think that I understood the reason for these messages,
> The ending_tsz value is a time that has already passed so I assume the listings are expired and the seller needs to renew them

@assaflei I had tried with activate renew both actions, but no luck. 
`{ state: 'active', should_auto_renew: true }`

now waiting for @etsyachristensen response.
