### ISSUE TITLE
[BUG]: "Oh dear, you cannot sell this item on Etsy" setting who_made=someone_else even with a production partner

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My understanding (correct me if wrong) is that we can set who_made=someone_else if the listing has a production partner. I'm pretty sure this worked fine in the v2 API. I'm trying it now with the v3 API and getting:

400: {"error":"There was a problem with \/marketplace : Oh dear, you cannot sell this item on Etsy."}

IIRC that was the error we'd get if we tried to set who_made=someone_else on a listing that didn't have a production partner. After setting a production partner, it worked.

### Steps to reproduce

Create a listing.
Give it a production partner.
Call `updateListing` with `who_made=someone_else&when_made=made_to_order&is_supply=false`
Get the 400 error.

Here's the shop/listing I'm attempting: /shops/17014045/listings/894143827

### Expected behavior

I expect that setting who_made to someone_else should be fine if the listing has a production partner.

**Comment by etsyachristensen** [comment]
You are correct in your analysis. You should be able to set it to someone_else if you have production partners. We are investigating.

**Comment by etsyachristensen** [comment]
@stickfigure The fix for this was pushed up a couple days ago. You should now be able to set it to someone_else on listings that have production partners

**Comment by josefanostylus** [comment]
when creating a new listing using the createDraftListing API though, it is not possible to set "who_made" to "someone_else". I get the same error. However, there's no way of specifying a "production partner" via API, correct? Is this a manual process where the user will have to select a production partner for each listing that's created by a 3rd party app ?

**Comment by josefanostylus** [comment]
Got it, thank you so much @etsyachristensen . Any plans on making creating a production partner available trough the API ?
