### ISSUE TITLE
[BUG]: createShopShippingProfile is not supposed to require origin_postal_code

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to create a new Shipping Profile, I get the error:

`'' is an invalid postal code for country: US`

[The documentation](https://developer.etsy.com/documentation/reference/#operation/createShopShippingProfile) does not list origin_postal_code as a required field.

### Steps to reproduce

1. Attempt to create a new shipping profile (ex: title=temp&origin_country_iso=US&primary_cost=10&secondary_cost=10&min_processing_time=5&max_processing_time=7&destination_region=non_eu)
2. Receive error

### Expected behavior

The shipping profile should get successfully created.

NOTE: I assume this is a bug in API v3 and not a documentation issue because in API v2 the origin_postal_code is not required.

**Comment by etsyachristensen** [comment]
Sorry for the confusion. If you include origin_country_iso=US, it will require a valid US postal code for origin_postal_code. Same goes for Canada. Other countries do not require that. We will work on updating the documentation to reflect this.
