### ISSUE TITLE
[ENDPOINT]: Proposed design change for Api types int32 to int64 

### ISSUE THREAD

**Issue by MaciejDerek** [etsy/open-api#369]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Hello, current open api json definition defines **offering_id** and **product_id** as integer. It causes the problem when it comes to code generation in Visual Studio as it's defined as int type.

### Proposed Endpoint Design Change

In the definition of json file there should be added a format: int64 for **offering_id** and **product_id** so that those are defined as long types in the code.

### Why are you proposing this change?

Because I'm using the open api definition in order not the re-write models in my code

**Comment by Gareth064** [comment]
See #326

**Comment by etsyachristensen** [comment]
Thanks @Gareth064. The OpenAPI spec does not differentiate integer types.

**Comment by lw-andrewsmith** [comment]
@etsyachristensen I'd like you/the team to reconsider and possibly reopen as the Open API allows for the format: int64 to be defined in the spec

https://swagger.io/docs/specification/data-models/data-types/


Example:
{
"name": "listing_id",
                        "in": "path",
                        "description": "The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            **"format": "int64"**
                            "description": "The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.",
                            "minimum": 1
                        }

**Comment by MaciejDerek** [comment]
Yeah,
Format: int64 is what I thought about :) Please let me know if you are going to implement this change for the applicable properties.

Regards
