### ISSUE TITLE
[FEATURE]: Allow to query multiple shops at once

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#372]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

My application often needs to query the details of multiple shops (up to a few hundred). In V2 I was able to do it with a single call, by providing a list of the shop ids in the url:
`GET https://openapi.etsy.com/v2/shops/shop_id_1,shop_id_2,shop_id_3,...`

In V3 there is no such endpoint. As a result, I have to perform a separate call for every single shop.

### Describe the solution you'd like

The solution of the equivalent problem for listings is already implemented - with the getListingsByListingIds endpoint . I would like to have an equivalent endpoint for shops - getShopsByShopIds.

### Describe any alternatives you've considered

I cannot think of an alternative.

**Comment by jasonpincin** [comment]
Thank you for the suggestion! We have no plans to offer this functionality.
