### ISSUE TITLE
[BUG]: price_on_property error during inventory update

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I followed the tutorial https://developers.etsy.com/documentation/tutorials/listings#handling-variations-in-inventory-updates  by time to time I received an error: `price_on_property: property IDs must be in the same order as in products`

I don't understand what is wrong because I am including the price_on_property 513

### Steps to reproduce

the payload used is the next one: 

Field | Value
-- | --
@ingestionTime | 1644883878156
@log | 973585226611:/aws/lambda/etsy-integration-prod-performChannelUpdates
@logStream | 2022/02/14/[$LATEST]7394bb902226464ab7650edc14c4b6e6
@message | 2022-02-15T00:11:07.894Z ==> error: Processing Etsy call resulted in error {"message":"Bad Request","status":400,"text":"{\"error\":\"price_on_property: property IDs must be in the same order as in products\"}\n","method":"PUT","path":"/v3/application/listings/1177230475/inventory","url":"https://openapi.etsy.com/v3/application/listings/1177230475/inventory","params":{"params":{"listing_id":1177230475,"products":[{"sku":"","property_values":[{"property_id":513,"property_name":"Design / Case Type","scale_id":null,"value_ids":[],"values":["Baseball / Snap Case"]},{"property_id":513,"property_name":"Device Type","scale_id":null,"value_ids":[],"values":["iPhone 13 Pro Max"]}],"offerings":[{"price":25,"quantity":25,"is_enabled":1}]},{"sku":"","property_values":[{"property_id":513,"property_name":"Design / Case Type","scale_id":null,"value_ids":[],"values":["Volleyball / Tough Case"]},{"property_id":513,"property_name":"Device Type","scale_id":null,"value_ids":[],"values":["Galaxy S8"]}],"offerings":[{"price":32,"quantity":25,"is_enabled":1}]},{"sku":"","property_values":[{"property_id":513,"property_name":"Design / Case Type","scale_id":null,"value_ids":[],"values":["Volleyball / Tough Case"]},{"property_id":513,"property_name":"Device Type","scale_id":null,"value_ids":[],"values":["Galaxy Note 10 Plus"]}],"offerings":[{"price":32,"quantity":25,"is_enabled":1}]},{"sku":"","property_values":[{"property_id":513,"property_name":"Design / Case Type","scale_id":null,"value_ids":[],"values":["Volleyball / Tough Case"]},{"property_id":513,"property_name":"Device Type","scale_id":null,"value_ids":[],"values":["Galaxy Note 10"]}],"offerings":[{"price":32,"quantity":25,"is_enabled":1}]}]
path | /v3/application/listings/1177230475/inventory
status | 400
text | {"error":"price_on_property: property IDs must be in the same order as in products"}
url | https://openapi.etsy.com/v3/application/listings/1177230475/inventory

### Expected behavior

Update inventory

### Additional context

it happens with another property ids

**Comment by etsyachristensen** [comment]
I may be late in responding to this @yovasx2 . But I just queried the inventory for that listing and I see two properties:
Finish (500) and Device Type (513).

So your inventory update for price_on_property would be [500,513] and must be in that order (the same order they show up in when you get the inventory).

**Comment by yovasx2** [comment]
checking it, thx
