### ISSUE TITLE
[BUG]: item_dimensions_unit received as null

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when I hit getListing endpoint for a us-based shop my item_dimensions_unit is null:
```
    "item_weight": 1,
    "item_weight_unit": "oz",
    "item_length": 0,
    "item_width": 0,
    "item_height": 0,
    "item_dimensions_unit": null,
```

### Steps to reproduce

1. Use update endpoint to set the unit
2. Use getListing endpoint to see the unit is null

### Expected behavior

to receive the imperial base unit oz

### Additional context

curl:
```
curl --location --request GET 'https://openapi.etsy.com/v3/application/listings/1157894078' \
--header 'x-api-key: xxxxx' \
--header 'Authorization: Bearer xxxx' \
--header 'Cookie: user_prefs=xxxxxx.'
```

list of affected listings belonging to the shop:

1167114235
1165860509
1157392432
1171147759
1167028349
1153138210
1171340709
1167033945
1156393130
1158266204
1169173213
1155217938
1180692921
1166026077
1171841971
1153137364
1153069670
1171553265
1154991454
1153153352
1154992438
1171148049
1166025849
1166028137
1156392994
1167099237
1166025923
1168954127
1157892570
1172214899
1156393180
1153155856
1155217038
1171554099
1154995022
1168948651
1156399712
1153074412
1167962133
1152070664
1153266816
1166025991
1167030175
1180695097
1154996656
1153069972
1152070834
1167962345
1180692509
1168949817
1156400150
1167100373
1156399922
1167225797
1153154188
1154995710
1158266944
1154991764
1167031315
1167098917
1157393722
1152070522
1171842867
1154994698
1172214527
1153137042
1158266762
1158266372
1152066346
1158266464
1153068202
1167098547
1152070744
1167102375
1167113411
1154993678
1169212331
1171342981
1154996992
1157605058
1153068568
1167316191
1155215036
1166029853
1154996032
1170347199
1154992746
1157604502
1166030027
1171342381
1167113705
1167114853
1169171635
1169169997
1154991158
1169172871
1153152808
1169173567
1180694641
1167101755
1153142840
1153153056
1180692589
1155215954
1152066992
1157196808
1157893716
1167097739
1154923684
1154997308
1156392936
1152069932
1153136736
1168951781
1155214818
1154996352
1172215073
1167100647
1167029441
1167100925
1180692943
1152067400
1166742596
1166737334
1166739484
1164324636
1166736342
1166738512
1164322308
1176616547
1166026681
1166736266
1166738998
1166742444
1180692595
1171369449
1176623405
1152067092
1166739770
1180691591
1166738660
1167115133
1180690195
1166737518
1166028393
1166028709
1176588933
1176616429
1180691257
1180693227
1176616191
1162669262
1152070302
1180689747
1166742552
1180692203
1178280587
1162663046
1166742250
1178280237
1166738934
1180690445
1164323840
1157420850
1166738840
1157419820
1162636664
1152069228
1166739854
1180688039
1162670974
1176614619
1166740702
1180694857
1176613973
1166027133
1164322870
1166028899
1166735214
1166740694
1180689969
1157419530
1180693459
1166746454
1166735554
1162669514
1166736324
1180691891
1169234699
1178279037
1152068948
1166029451
1180691241
1162667816
1157894078
1162662770
1162637666
1180690665
1180688267
1176809835
1164324362
1171371063
1176614747
1166740068
1162661886
1166735274
1176588659
1162660532
1166737100
1166741236
1166736064
1166740432
1176613271
1180688345
1178280839
1166739086
1162634450
1180690589
1180692593
1162635682
1162662212
1166742340
1162659986
1176590291
1176622255
1162659828
1166740152
1166029525
1166737354
1166738442
1180691699
1166026853
1152067710
1166026339
1176623541
1155236368
1166735402
1166734786
1152067860
1152067256
1164323330
1180697785
1166737580
1164323110
1157420474
1180694825
1166740984
1180699311
1166736466
1180695327
1180699111
1164325154
1162637804
1166737526
1152067568
1180692079
1180694273
1166744806
1176587995
1176625021
1180690397
1176621691
1166028817
1166740358
1180698565
1180691075
1176621387
1180691271
1180695131
1180689129
1166029159
1176622891
1157418878
1180691531
1180692023
1152069610
1176615269
1166745132
1166741624
1164325862
1176624875
1164322580
1166735992
1164325624
1180691887
1162661386
1176615137
1166738196
1157418260
1180697501
1171371329
1162661520
1180698855
1180692869
1176614253
1166735734
1162856994
1166736616
1162659556
1166736778
1166742062
1176613845
1152068858
1166739004
1176613689
1180688741
1176615621
1164323600
1166742010
1166742952
1171367873
1176616797
1180691333
1166737252
1162856714
1166735744
1180689867
1171368501
1157421524
1180689427
17930182
1166737814
1166736036
1152069672
1156399800
1167031679
1171553817
1162660994
1166737640
1162669000
1152070370
1152069130
1157391422
1167099863
1180693427
1167112329
1162637522
1166742838
1178278261
1180691415
1157604804
1169172189
1180694275
1169234587
1166026981
1178279533
1180695565
1180691057
1169170565
1169171081
1157394392
1169173377
1157390770
1172214811
1171342687
1170347045
1154923954
1155215394
1152066806
1156400030
1180691599
1167097481
1153073180
1169171957
1167033233
1153068958
1180693733
1157893014
1169172569
1167102945
1157198008
1153141428
1171341641
1168950771
1153155570
1153070638
1153072802
1154003990
1167102035
1172214301
1168950437
1170347395
1167100117
1171553497
1157196480
1166740688
1155216110
1154993054
1167099565
1167101459
1152066728
1155216440
1155217580
1167030955
1155216592
1157394054
1167241699
1167030583
1167096303
1166739842
1171840837
1152067168
1176615913
1171370443
1166737660
1180693779
1166741254
1176616057
1180690097
1166029255
1170346981
1167026897
1167205310
1157894692
1153073620
1155218288
1167114553
1169170355
1162660844
1166742746
1166029597

**Comment by yovasx2** [comment]
news?

**Comment by etsyachristensen** [comment]
We are still investigating this. Hopefully have some answers next week.

**Comment by foxfriends** [comment]
I am finding many fields are returned as null or invalid values, which may be related. This makes it hard to use `updateListing`, since updates to unrelated fields are now impossible.

All of these fields have caused problem for me so far when trying to simply update a single field of my products:
* `item_weight_unit` is null
* `item_dimensions_unit` is null
* `personalization_char_count_max` is null
* `item_weight`/dimensions are received as 0

**Comment by etsyachristensen** [comment]
@foxfriends we deployed a change on Thursday that seems to fix the problem with the weights/dimensions for the list of listings (spot checked a number of them) that @yovasx2 posted.

Can you give me a short list of ids to check where you are seeing this problem? or even if it's only personalization at this point.

**Comment by yovasx2** [comment]
@etsyachristensen is this related with https://github.com/etsy/open-api/issues/403?

**Comment by etsyachristensen** [comment]
No. The shipping_profile_id was a completely separate issue.

**Comment by yovasx2** [comment]
it's fixed for me all products for that shop have units in place

**Comment by foxfriends** [comment]
> Can you give me a short list of ids to check where you are seeing this problem? or even if it's only personalization at this point.

Ah it's some products I have that don't have dimensions set at all, they were showing 0 on the Etsy UI and could not be edited there without setting them either. Not really a problem now though, we'll just get those filled in manually... pretty weird that they can be in a 0/null state but cannot be set into that state...

**Comment by etsyachristensen** [comment]
Listing can now be set to null now with a change that recently went into production. But, they must be either a fixed shipping profile or a digital listing. Physical listings still require dimensions and weight.
