### ISSUE TITLE
[ENDPOINT]: Proposed design change for `getShopReceipts`

### ISSUE THREAD

**Issue by chanpory** [etsy/open-api#380]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

`getShopReceipts` accepts query parameters named `was_shipped` and `was_paid`, while the returned `Shop Receipt` resource shows these as `is_shipped` and `is_paid`.

### Proposed Endpoint Design Change

Query parameters should be named `is_shipped` and `is_shipped`.

### Why are you proposing this change?

This is a nomenclature inconsistency here is confusing.

Note: I'm not sure why the nomenclature for `was_shipped` and `was_paid for the Shop Receipt resource was changed from the v2 API to begin with. They read grammatically weird now, and it's caused more headaches for me during the migration to v3.

**Comment by etsyachristensen** [comment]
The "is" nomenclature is more consistent with standard data architecture as being a boolean value. This may be addressed in the future.
