### ISSUE TITLE
[DOCS]: 

### ISSUE THREAD

**Issue by HSCONickMachin** [etsy/open-api#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/

### What would you like to change?

When opening Migrating to Etsy’s Open API v3 in a new tab creates this link
https://developer.etsy.com/documentation/migration/index/
which then breaks these links
[Open API v3 launch timeline](https://developer.etsy.com/documentation/migration/index/index#launch-stages)
[Changes to API functionality](https://developer.etsy.com/documentation/migration/index/summary-changes)
[Resources not supported in V3](https://developer.etsy.com/documentation/migration/index/retired-resources)
[Frequently Asked Questions](https://developer.etsy.com/documentation/migration/index/faq)

### Why are you proposing this change?

https://developer.etsy.com/documentation/migration/index
this link create these links
[Open API v3 launch timeline](https://developer.etsy.com/documentation/migration/index#launch-stages)
[Changes to API functionality](https://developer.etsy.com/documentation/migration/summary-changes)
[Resources not supported in V3](https://developer.etsy.com/documentation/migration/retired-resources)
[Frequently Asked Questions](https://developer.etsy.com/documentation/migration/faq)
which aren't broken

**Comment by etsyachristensen** [comment]
This was fixed.
