### ISSUE TITLE
[BUG]: {"error":"Expected float value for 'price' (got NULL)."}

### ISSUE THREAD

**Issue by bandoxx** [etsy/open-api#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've got an error: {"error":"Expected float value for 'price' (got NULL)."}

### Steps to reproduce

Used endpoint: /v3/application/listings/1188547181/inventory [PUT]

Data:
{"products":[{"sku":"Hoodies_Gildan[ ]()18500 Pullover Hoodie_Gildan_Red_Front_S","property_values":[{"property_id":513,"property_name":"Color","values":["Red"]},{"property_id":514,"property_name":"Print Area","values":["Front"]}],"offerings":{"price":15.9,"quantity":100,"is_enabled":true}},{"sku":"Hoodies_Gildan 18500 Pullover Hoodie_Gildan_Red_Front_M","property_values":[{"property_id":513,"property_name":"Color","values":["Red"]},{"property_id":514,"property_name":"Print Area","values":["Front"]}],"offerings":{"price":15.9,"quantity":100,"is_enabled":true}}],"price_on_property":[513],"quantity_on_property":[513],"sku_on_property":[513]}

Response headers:
x-cloud-trace-context: 7190ca5d41f0c850c232588aada0c498/714083976593089762;o=0
x-etsy-request-uuid: EuvmjS48ls87F7gBjfaxdqwRtq71

If you can check requests by those header information, it would be cool to see what is the issue.

### Expected behavior

Expected behavior is to get valid error message if nothing more, because error message doesn't have sense with the data that I've sent.

**Comment by bandoxx** [comment]
As I realized, issue is that I had 2 products with same property_values, so it would be good to add check on that, and return more appropriate error message, because Expected float value for 'price' in this situation is a mislead.

**Comment by etsyachristensen** [comment]
@bandoxx You are correct. We should have a better response for that situation. We'll add it to our list of issues to address.

**Comment by etsyachristensen** [comment]
We've been through this ticket and determined that while the error isn't particularly useful, it does prevent erroneous inventory from being written. As this is somewhat of an edge case, we'll simply log it as a future task and close this ticket out.
