### ISSUE TITLE
[BUG]: Invalid auth/bad request (got a 500, expected HTTP/1.1 20X or a redirect)

### ISSUE THREAD

**Issue by aniruddhaad** [etsy/open-api#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

We are trying upload this product and we are getting error -
Invalid auth/bad request (got a 500, expected HTTP/1.1 20X or a redirect)

Here is request - 

{"quantity":"1","title":"Pearlsjoy lariat necklace in white gold and yellow gold plating - style,color 2 pearl lariat \/ white gold","description":"Precious and Priceless. Pearls Of Joy Lariat style Necklace is meant for rare occasions.For those happy moments when your heart is so filled with joy that your lips can't stop smiling and you get so emotional that tears roll down the eyes.Have you ever felt such moments? \u00a0May be when you see your baby daughter all grown up and graduated? May be when you see her walking down the aisle as a beautiful bride?Laugh and cry with the Pearls Of Joy gift her this beautiful necklace on the most memorable day of her life and yours too.\u00a0Details:One Tear Drop Pearl and One Round Pearl.Or Get the One Tear Drop with Multi Pearl.Select from White Gold Plated or Yellow Gold Plated Branch and chain.\u00a0Lariat style necklace.Necklace is 20 inches and can be extended 2 more inches.Extender included with every necklace.\u00a0Faux Pearls created in a Lab with High Lusture.\u00a0Select from 2 PEARL LARIAT (1 tear drop with 1 round pearl in White Gold or Yellow Gold plating ) AND MULTI-PEARL LARIAT ( 1 tear drop with 3 round pearls in\u00a0White Gold or Yellow Gold plating).It comes in a gift pouch.","price":"22","taxonomy_id":"1225","who_made":"someone_else","is_supply":"1","item_weight":"0.00","item_weight_unit":"lb","when_made":"2020_2021","state":"active","shipping_template_id":"169270038036","sku":["K290-4006993925"]}

Here is response -

ApiException

OAuthException Object
(
    [message:protected] => Invalid auth/bad request (got a 500, expected HTTP/1.1 20X or a redirect)
    [string:Exception:private] =>
    [code:protected] => 500

    [line:protected] => 2025
    [trace:Exception:private] => Array
        (
            [0] => Array
                (

                    [line] => 2025
                    [function] => fetch
                    [class] => OAuth
                    [type] => ->
                    [args] => Array
                        (
                            [0] => https://openapi.etsy.com/v2/listings
                            [1] => Array
                                (
                                    [quantity] => 1
                                    [title] => Lovependant and chain necklace
                                    [description] => It's your 1st wedding anniversary.. what to give her that you haven't given her already..?It's funny and kind of strange how it's been a year but feels just like yesterday and at the same time it seems as if you know each other for ages.. Have your beloved better half see this Love Quote around her neck as you put it on her and let her read the beautiful sentiments written all over it .. it sure will speak volumes about your love for her..Tell her this year you will marry her all over again.. tell her 'Every love story is beautiful but ours is my favorite'..  DETAILS: The Pendant is made of Silver plating over Alloy.Pendant measures 1 inch Wide with hand stamp words that say,' Every love story is beautiful but ours is my favorite'.The Chian is 11 inches Long including 2 inches Long extender chain.It comes in a gift pouch for gift giving and safe keeping.
                                    [price] => 30
                                    [taxonomy_id] => 1229
                                    [who_made] => someone_else
                                    [is_supply] => 1
                                    [item_weight] => 0.00
                                    [item_weight_unit] => lb
                                    [when_made] => 2020_2021
                                    [state] => active
                                    [shipping_template_id] => 169270038036
                                    [sku] => Array
                                        (
                                            [0] => K290-16691060293
                                        )

                                )

                            [2] => POST
                        )

                )

        )

    [previous:Exception:private] =>
    [lastResponse] => Server Error
    [debugInfo] =>
)

### Steps to reproduce

Try to upload item with this json -

{"quantity":"1","title":"Pearlsjoy lariat necklace in white gold and yellow gold plating - style,color 2 pearl lariat \/ white gold","description":"Precious and Priceless. Pearls Of Joy Lariat style Necklace is meant for rare occasions.For those happy moments when your heart is so filled with joy that your lips can't stop smiling and you get so emotional that tears roll down the eyes.Have you ever felt such moments? \u00a0May be when you see your baby daughter all grown up and graduated? May be when you see her walking down the aisle as a beautiful bride?Laugh and cry with the Pearls Of Joy gift her this beautiful necklace on the most memorable day of her life and yours too.\u00a0Details:One Tear Drop Pearl and One Round Pearl.Or Get the One Tear Drop with Multi Pearl.Select from White Gold Plated or Yellow Gold Plated Branch and chain.\u00a0Lariat style necklace.Necklace is 20 inches and can be extended 2 more inches.Extender included with every necklace.\u00a0Faux Pearls created in a Lab with High Lusture.\u00a0Select from 2 PEARL LARIAT (1 tear drop with 1 round pearl in White Gold or Yellow Gold plating ) AND MULTI-PEARL LARIAT ( 1 tear drop with 3 round pearls in\u00a0White Gold or Yellow Gold plating).It comes in a gift pouch.","price":"22","taxonomy_id":"1225","who_made":"someone_else","is_supply":"1","item_weight":"0.00","item_weight_unit":"lb","when_made":"2020_2021","state":"active","shipping_template_id":"169270038036","sku":["K290-4006993925"]}

I am able to reproduce this error everytime I try to upload the product.

### Expected behavior

Items should be uploaded fine without error.

**Comment by etsyachristensen** [comment]
@aniruddhaad I will need more information in order to troubleshoot this.
1. is this an app you've built? Or an integration you've added to a shop?
2. Are you calling the V3 API endpoint or the V2 API endpoint? (what url are you using)?
3. Does the user that's uploading this listing have listings_w scope permissions?
4. Are you doing a GET, PUT or POST to the endpoint?
5. Are you sending JSON data? Or multipart form data variables?
6. Price and item_weight are supposed to be floats, not strings.
7. Quantity, taxonomy_id, is_supply and shipping_template_id are integers, not strings.
8. sku is not an allowed variable for input on the V3 API.

**Comment by aniruddhaad** [comment]
Hi @etsyachristensen ,

Thanks for reply.

1. is this an app you've built? Or an integration you've added to a shop?
- Yes. I have built this app.
2. Are you calling the V3 API endpoint or the V2 API endpoint? (what url are you using)?
- I am using V2 endpoint & URL:  https://openapi.etsy.com/v2/listings
3. Does the user that's uploading this listing have listings_w scope permissions?
- Yes because I am able to upload few items except 2  items. One of the item i have provided here.
5. Are you sending JSON data? Or multipart form data variables?
- I am creating a php array (Just for understanding I provided json) & passing it to php oauth function as follows -
$arr=[
							'quantity'=>(int) $qty_to_push,//$qty_to_push is 1
							'title'=>$supp_prod_name],
							'description'=>$productDescription,
							'price'=>$retail_price,
							'taxonomy_id'=>$taxonomy_id,
							'who_made'=>'someone_else',
							'is_supply'=>true,
							'item_weight'=>$products['weight'],
							'item_weight_unit'=>'lb',
							'when_made'=>'2020_2021',
							'state'=>'active',
							'shipping_template_id'=>(int) ($store_currency=='USD'?$usa_shipping_template_id:$canada_shipping_template_id),
							'sku'=>array($products['supplier_id'].'-'.$products['supp_prod_id'])
						
					];
$oauth = new \OAuth($app_etsy_oauth_key, $app_etsy_oauth_shared_secret, OAUTH_SIG_METHOD_HMACSHA1, OAUTH_AUTH_TYPE_URI);
$oauth->setSSLChecks(false);
$oauth_token=$member_oauth_token;
$oauth_token_secret=$member_oauth_token_secret;

$oauth->setToken($oauth_token, $oauth_token_secret);
$etsy_base='https://openapi.etsy.com/v2';
$path='/listings';
sleep(mt_rand(1,3));
$data = $oauth->fetch($etsy_base . $path, $arr, OAUTH_HTTP_METHOD_POST);
4. Are you doing a GET, PUT or POST to the endpoint?
- POST as this is new item.
5. Are you sending JSON data? Or multipart form data variables?
- I am only passing php array to Oauth
6. Price and item_weight are supposed to be floats, not strings.
7. Quantity, taxonomy_id, is_supply and shipping_template_id are integers, not strings.
- I think it's automatic unless I need to explicit typecaseting. See I have pasted the array i create dynamically. 
- Also like I mentioned I was able to create 33 listings with same code.
3. sku is not an allowed variable for input on the V3 API.
- We are using V2 version endpoint.

**Comment by etsyachristensen** [comment]
Unfortunately this github repository is for V3. For support on V2 endpoints, you will need to go to the Google Group here: https://groups.google.com/g/etsy-api-v2

Users there are more able to help answer your questions.
