### ISSUE TITLE
[ENDPOINT]: Proposed design change for <How does app test> 

### ISSUE THREAD

**Issue by MarsLauCN** [etsy/open-api#391]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

1.Test store not found.
2.No detailed test introduction.

### Proposed Endpoint Design Change

Add test process.

### Why are you proposing this change?

I don't know how to test.

**Comment by etsyachristensen** [comment]
There isn't nearly enough information in this issue to be able to answer you. Please email support@etsy.com if you're having issues with creating a shop. If you have issues with specific endpoints, please detail what you are having problems with.
