### ISSUE TITLE
Detailed Release Notes

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#392]
@jasonpincin @nateswart @etsyachristensen 
This post is just to ask that the Etsy staff be more specific with the release notes.

I mention this because the latest "release" [here](https://github.com/etsy/open-api/releases/tag/3.0.0-general-release-2022-03-01) doesn't mention that 2 new properties were added to the ShopShippingProfile schema.

For anoyone interested, these are to 2 new properties

```
"domestic_handling_fee": {
    "type": "number",
    "description": "The domestic handling fee added to buyer's shipping total - only available for calculated shipping profiles.",
    "format": "float",
    "minimum": 0,
    "default": 0
},
"international_handling_fee": {
    "type": "number",
    "description": "The international handling fee added to buyer's shipping total - only available for calculated shipping profiles.",
    "format": "float",
    "minimum": 0,
    "default": 0
}
```
I have set a reminder each month to download the OAS file and run it through a JSON compare tool to compare it to last months and that is how I have discovered this.

I am building a .NET API Wrapper Library and maintaining it really relies on clear communications from the Etsy team about when they make changes to schemas and endpoints etc.

**Comment by etsyachristensen** [comment]
Thanks for the note @Gareth064 we are addressing this discrepancy internally. In the meantime, I'm working on updating the changelog.

**Comment by Gareth064** [comment]
@etsyachristensen I just wanted to say that it's great to see so many new "Releases" being published with their change notes. On other possible slight cherry on the top would be to include against a Change Note, the GitHub Issue or Issues that the change addressed. This would provide a quick link for anyone to go back and read the history behind the change. A lot of the time the issues contain good conversations leading up the the change/fix.
