### ISSUE TITLE
Problem on updateInventory Endpoint.

### ISSUE THREAD

**Issue by jwn25** [etsy/open-api#393]
**Scenario**: I am developing an app that syncs between other Marketplace and Etsy
I have given an option to users that they can choose if they want to sync their price or not.

If the option is off, I don't want to update the price at all on Etsy, 

But I found on updateInventory endpoint, the price field is **required** on Products json.

As a quick solution, I am first fetching the inventories and creating SKU => CURRENT PRICE association.
and assigning the price back by checking the sku to price field before calling the API. 

But when user changes any of the SKU on other market_place, There won't be the updated SKU on ETSY's inventories, Which is causing me a headache to assign the price back while updatingInvenory. 

It would be awesome if we can make the price, quantity field optional.
Or please suggest to me what solution I can implement in order to support no price sync to Etsy.

NOTE: I am using V2 API Endpoint.

THANK YOU!!!

**Comment by etsyachristensen** [comment]
Unfortunately, the `updateListingInventory` (V3) and `updateInventory` (V2) endpoints require the full inventory data to be passed back in due to the complexity of the inventory/variations system. We are not able to separate out parts of the inventory to update only pieces.
