### ISSUE TITLE
[DOCS]: 

### ISSUE THREAD

**Issue by Robeszpierre** [etsy/open-api#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/reference#operation/updateShop

### What would you like to change?

Please include in the documentation if the property is nullable.

### Why are you proposing this change?

Because it's important.

**Comment by etsyachristensen** [comment]
There is not enough information to address this ticket. We don't know what property you're referring to.
