### ISSUE TITLE
[BUG]: Dimension units set to null

### ISSUE THREAD

**Issue by Euse** [etsy/open-api#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We edited an existing listing and add some dimensions.
<img width="459" alt="Screenshot 2022-03-09 at 11 13 26" src="https://user-images.githubusercontent.com/6683575/157420899-97724549-97bf-4192-8c0f-c3f48acd57b6.png">

The problem is when we call getListing it returns all dimensions fields as null:

<img width="236" alt="Screenshot 2022-03-09 at 11 14 37" src="https://user-images.githubusercontent.com/6683575/157421128-739da765-7430-4e19-8215-e346756be502.png">

The item id is: 905518709

### Steps to reproduce

- Create a listing without dimensions.
- Edit the listing and add dimensions.
- Call getlisting endpoint using the listing id.

### Expected behavior

Dimensions being correctly fetched.

**Comment by Euse** [comment]
Sorry, but I still can't see the dimensions... Do you have access to this listing? 905518709
I'm using a legacy token to do the call and it should have all the permissions.

**Comment by mhaydenetsydev** [comment]
@Euse 
Yes I have access to the listing. You initially created the listing with dimensions set to null:
  "item_weight": null,
  "item_length": null,
  "item_width": null,
  "item_height": null,
  "item_weight_unit": null,
  "item_dimensions_unit": null,

Can you please edit the list and give the dimensions NON null values and see if that overwrites those null values.
