### ISSUE TITLE
[ENDPOINT]: Proposed design change for `getListing`/`getShopReceipt`/etc.

### ISSUE THREAD

**Issue by foxfriends** [etsy/open-api#399]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Some endpoints return [`create_timestamp`](https://developers.etsy.com/documentation/reference/#tag/Shop-Receipt), others return `creation_timestamp`. Same idea for `update_timestamp` and [`last_modified_timestamp`](https://developers.etsy.com/documentation/reference/#operation/getListing), and I would suspect some others.

### Proposed Endpoint Design Change

Pick one name and stick to it.

### Why are you proposing this change?

It makes the API easier to use when the fields are consistently named.

**Comment by etsyachristensen** [comment]
Consistency would be nice. Many of the V3 OpenAPI endpoints were written by many different developers so we end up with some different names. I'll this to our list of enhancements, but it will likely be a while before we can address it.

**Comment by assaflei** [comment]
@etsyachristensen can you share a backlog of all impacted APIs and fields?
There are references to many types of fields and I want make sure all of them are updated correctly

**Comment by etsyachristensen** [comment]
Every endpoint that had a date field name that wasn't created_timestamp or updated_timestamp now has these fields. The old fields are still there. I'll have to go through our repo to find out which endpoints were touched as I didn't do this work. It'll take some time to get that info.
