### ISSUE TITLE
[ENDPOINT]: Proposed design change for all endpoints (?)

### ISSUE THREAD

**Issue by foxfriends** [etsy/open-api#400]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Seems to me some endpoints accept the body as form (e.g. [`updateListing`](https://developers.etsy.com/documentation/reference/#operation/updateListing)) while others accept JSON (e.g. [`updateListingInventory`](https://developers.etsy.com/documentation/reference/#operation/updateListingInventory)).

### Proposed Endpoint Design Change

Use JSON for all requests, or form body for all requests, or support both on all endpoints, but not half/half.

### Why are you proposing this change?

This is annoying and confusing as now my API layer needs to have both forms of API call implemented, and I have to carefully check each request I make that it's using the right one.

**Comment by etsyachristensen** [comment]
I'm sorry for the confusion @foxfriends. In order to make things simpler for beginners we tried to minimize the use of json data being required as input and opted for form data whenever possible. Unfortunately we are not able to make such a significant change to our API.
