### ISSUE TITLE
[BUG]: getShopSections endpoint returning 500 (almost always) and 400 (by time to time)

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hitting getShopSections endpoint is returning 500 and 400 for some of our customers:
shop_id example: **30664462**

v2 API equivalent endpoint is working almost perfectly but also returning the 400 errors from time to time

### Steps to reproduce

curl --location --request GET 'https://openapi.etsy.com/v3/application/shops/30664462/sections' \
--header 'x-api-key: xxxxxxxx' \
--header 'Authorization: Bearer xxxxx' \
--header 'Cookie: user_prefs=xxxxxxx.' \

### Expected behavior

get 200 OK instead of 500 and 400

### Additional context

<img width="927" alt="Screen Shot 2022-03-11 at 14 34 27" src="https://user-images.githubusercontent.com/3578401/157959837-703138d8-7110-400e-aafb-a214ab901faa.png">
<img width="931" alt="Screen Shot 2022-03-11 at 14 34 18" src="https://user-images.githubusercontent.com/3578401/157959848-106f7ebe-dee4-4897-8e5a-3dcacd10c039.png">

**Comment by etsyachristensen** [comment]
Ok so we have determined the problem (I believe). That shop you provided has sections that have no names. This is upsetting the query system. Looking into solutions now.

**Comment by etsyachristensen** [comment]
A fix is in testing now and will hopefully be pushed into production tomorrow.

**Comment by yovasx2** [comment]
> Ok so we have determined the problem (I believe). That shop you provided has sections that have no names. This is upsetting the query system. Looking into solutions now.

That's really weird because we are using createSectionV3 which requires the title: https://developers.etsy.com/documentation/reference/#operation/createShopSection

> A fix is in testing now and will hopefully be pushed into production tomorrow.

Is this fixing the 400 and 500?

**Comment by etsyachristensen** [comment]
> That's really weird because we are using createSectionV3 which requires the title: https://developers.etsy.com/documentation/reference/#operation/createShopSection

Yeah I think the fact that they are blank was outside of the OpenAPI and something that was a bug in another app. The bug was fixed but it still left blank section names.

> Is this fixing the 400 and 500?

I couldn't find a 400 error on this one. The change may fix both but if you can provide an example of a 400 error I can look into that as well.

**Comment by yovasx2** [comment]
the query above is producing the 400, I hit it multiple times with postman like 10, and from time to time the 400 is coming

**Comment by etsyachristensen** [comment]
Oh sorry. I see it now. Hmm. I'm not able to duplicate that error exactly. I'll keep trying.

**Comment by etsyachristensen** [comment]
Ok the fix for the 500 error is now in production. Please test is out and let us know if you still have the 400 errors. If you do get them, please post the resulting headers (remove any private info of course).

**Comment by yovasx2** [comment]
all is good, thx
