### ISSUE TITLE
[BUG]: shipping_profile_id is null even when shipping profile exists

### ISSUE THREAD

**Issue by chrismccaw** [etsy/open-api#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have noticed that `shipping_profile_id` in the GET shop listing API has suddenly started showing as null. In the etsy admin the listing does have a shipping profile (calculated or fixed). Furthermore when we include `?includes=Shipping`in the API we see the correct profile in the `shipping_profile`

Here are a few affected listing IDs

1088186151
1050680749
882404575
1052989099
1036178158

### Steps to reproduce

I am unsure how the listings got into this state. We just noticed it occurring today so a recent Etsy deployment must have changed something

### Expected behavior

`shipping_profile_id` should not be null if a shipping profile exists

**Comment by chrismccaw** [comment]
Great Andrew. Let me get them together for you. Those other Ids must have corrected themselves over the weekend. Usually, if the user reapplies shipping again in Vela then shipping_id is not null. However can be random

**Comment by chrismccaw** [comment]
Hey @etsyachristensen  here are some more listing ids that have `shipping_profile_id` as null but contain `shipping_profile` when using `?includes=Shipping`

1085791299
17797767
17708837
1041528146
1041528146

**Comment by etsyachristensen** [comment]
Thanks @chrismccaw ! That helped validate that the fix I have in process does correct the problem. Will try to get this fix out as soon as possible.

**Comment by chrismccaw** [comment]
Awesome. thanks @etsyachristensen for the quick turnaround on this one

**Comment by etsyachristensen** [comment]
@chrismccaw The fix for this is now in production. Thanks for your patience!

**Comment by etsyachristensen** [comment]
I had to roll this back yesterday due to the emergence of another issue. I'll get it worked out as quickly as I can.

**Comment by etsyachristensen** [comment]
Ok the fix is back into production correctly. Please check your listings now and let me know if you run into any problems with the shipping_profile_id.

**Comment by yovasx2** [comment]
hey we are receiving shipping_template_ids (products endpoint GET) that are not in the catalogue (shipping profiles GET)
here are some shop ids:
```
"26463825"
"19905559"
"31604913"
"34947684"
"33700730"
"34788451"
"7092465"
"24838718"
"19302523"
"27158158"
"11081654"
"15259226"
"30372335"
"7936548"
"5597747"
"5722973"
"24597440"
"26172306"
"28121411"
"7687655"
"29280332"
"15705777"
"22778526"
"11606469"
"29449779"
"18832511"
"28087302"
"32544516"
"13696417"
"32552188"
"22207419"
"5283403"
"17670380"
"16797302"
"15289008"
"5602520"
"33820137"
"6203942"
"6724400"
"24425480"
"30766538"
"27782542"
"34898578"
"18298941"
"12545060"
"11749277"
"22343559"
"29910239"
"32677457"
"34644782"
"34355330"
"34036277"
"5748281"
"26956149"
"13294631"
"30095353"
"27613659"
"9755373"
"23852101"
"27757823"
"18869717"
"9518867"
"26523961"
"34874443"
"5568712"
"32782728"
"9196504"
"16014947"
"24375049"
"24215432"
"33103766"
"34939982"
"26878587"
"17293418"
"6889097"
"31953418"
"8915154"
"8928844"
"32680481"
"18086389"
"12068633"
"15331277"
"34478386"
"23297292"
"34917103"
"16692779"
"32146231"
"8217542"
"5446290"
"8945097"
"12521507"
"28315461"
"14865969"
"5442951"
"23431598"
"18895273"
"33111671"
"34262872"
"14691261"
"23363803"
"34961065"
"18207490"
"10872308"
"11909085"
"5204248"
"24894395"
"33307938"
"32696453"
"34231740"
"27991084"
"27731084"
"11149049"
"9014074"
"24115390"
"34072795"
"22287521"
"16019719"
"29397476"
"9151712"
"31648657"
"17394933"
"17116733"
"25905085"
"34254480"
"21275405"
"18045395"
"6769639"
"34144817"
"34089059"
"34365664"
"10537557"
"13666460"
"34574841"
"10939891"
"10332481"
"24542959"
"15177210"
"5919678"
"19830798"
"23752731"
"26757769"
"13007480"
"22584291"
"18259298"
"33391859"
"25587402"
"27564276"
"12848806"
"27003601"
"7495876"
"25410626"
"23719510"
"20590555"
"14386650"
"14002246"
"33786380"
"9582321"
"31461770"
"29336950"
"34966995"
"19810771"
"30664462"
"16813902"
"23743721"
"33126884"
"33841296"
"25752527"
"19690325"
"18922127"
"34512208"
"6370988"
"34329949"
"14466987"
"29859933"
"30024942"
"15035967"
"33779321"
"20375717"
"30566555"
"8799989"
"34705710"
"11993409"
"5785611"
"26143773"
"21324122"
"30263623"
"5228518"
"5478724"
"20372966"
"31809698"
"10373332"
"28439124"
"34510661"
"32332966"
"20772484"
"10332194"
"30972692"
"15461776"
"18080095"
"10633233"
"9134559"
"17673493"
"18021757"
"28163663"
"30780948"
"34701584"
"18836924"
"28211164"
"33214612"
"23014013"
"18914659"
"27826819"
"11488234"
"16412973"
"24181581"
"5230528"
"34655058"
"33954123"
"12630272"
"15226724"
"16772059"
"10177124"
"31872833"
"15559813"
"14473936"
"13051745"
"8573547"
"16491908"
"9321433"
"14757119"
"20497911"
"23279181"
"29391777"
"6734278"
"32475025"
"21835888"
"25146368"
"25053288"
"16505140"
"14110822"
"6750117"
"17279467"
"14874049"
"7122042"
"5255878"
"20748602"
"7673088"
"20684627"
"27484810"
"30737748"
"20810558"
"26839189"
"20640760"
"27470216"
"11604414"
"23744702"
"18542675"
"25512003"
"21577375"
"7696549"
"21398930"
"21513854"
"12620286"
"30802092"
"22477601"
"20917302"
"32947175"
"8901376"
"32177166"
"25157134"
"28282622"
"28555180"
"11991971"
"25173289"
"27498310"
"7792385"
"28554627"
"25406927"
"17803713"
"32530732"
"29136079"
"16130127"
"22150795"
"31006569"
"12421314"
"18455165"
"16489770"
"19073041"
"28736756"
"28693699"
"29516703"
"13754042"
"27327772"
"26503640"
"16808218"
"24001024"
"24877563"
"25647570"
"27602661"
"24275031"
"9034790"
"22808789"
"6775168"
"26571456"
"6383208"
"10124341"
"13307879"
"9411174"
"17021729"
"27679739"
"26452865"
"10554944"
"27666809"
"27690241"
"20801516"
"25197276"
"22750361"
"27937572"
"22765073"
"23699071"
"22384113"
"25332904"
"23284377"
"21366417"
"16759092"
"20829011"
"21469582"
"11433716"
"17210700"
"5511285"
"7957228"
"10727734"
"21330435"
"24944523"
"10164538"
"10277248"
"7721119"
"13630183"
"11051492"
"15018581"
"12637144"
"10118072"
"8811013"
"14551925"
"28026576"
"7369830"
"19953918"
"22407440"
"17781481"
"22802432"
"28274703"
"25293056"
"27403119"
"23339014"
"14988944"
"6078010"
"21002135"
"19753472"
```

**Comment by yovasx2** [comment]
Hi @etsyachristensen, we noticed some shops on our end having the same problem reported above, the API (getLisitng endpoint) is returning a shipping profile id that doesn't exist in the catalog of shop shipping profiles (shipping profiles endpoint).

He is one example part from the list above:
https://openapi.etsy.com/v3/application/listings/259630284?includes=Shipping
returns 
```
"shipping_profile": {
        "shipping_profile_id": 19446745833,
        "title": null,
        "user_id": 55410968,
```

The id 19446745833 is not present in the shipping profiles endpoint results, 
<img width="939" alt="Screen Shot 2022-04-25 at 17 04 02" src="https://user-images.githubusercontent.com/3578401/165190528-4caf15e6-f271-42bd-91a4-c2128794a073.png">

is the API returning corrupted data? What do u need to fix all the shops suffering the same (shop ids, listing ids, ...)?

**Comment by etsyachristensen** [comment]
@yovasx2 Your issue appears to be a bit different. The shipping profile that is being returned in the example above for listing `259630284` is `19446745833` which is a custom shipping profile. We don't return custom profiles in the getShopShippingProfiles endpoint.

**Comment by yovasx2** [comment]
how can I know the shipping profile is custom and it's not the old problem of having a corrupted nonexisting shipping profile id, on the API side there is no way to discover that. Could u take a look at the list above: https://github.com/etsy/open-api/issues/403#issuecomment-1075812622, please?

**Comment by etsyachristensen** [comment]
Sorry for the confusion @yovasx2. We don't show the custom shipping profiles because there are usually so many of them. However, any shipping profile you get back in the listing object should still be able to be fetched via the `getShopShippingProfile` endpoint. This will let you get the shipping profile information.

**Comment by yovasx2** [comment]
is the custom shipping profile unique per listing or a custom shipping profile can be associated with many listings?

**Comment by etsyachristensen** [comment]
many are custom per listing due to the V2 behavior of creating a new shipping profile when a listing is created. Ultimately down the line we hope that this will change to be largely the same profiles being used across many listings.

**Comment by yovasx2** [comment]
Hello again, I understood the technical point of custom shipping profiles, but when we look into the customer account our gut tells us there is something weird, take a look at the next screenshot, the customer is selling shirts and he has a unique shipping profile, it doesn't make sense to have products with custom shipping profiles if the product is having same characteristics:

<img width="1346" alt="Screen Shot 2022-04-27 at 18 13 45" src="https://user-images.githubusercontent.com/3578401/165646535-216c57ee-c325-4868-9eb9-c7290b0b1901.png">

Said that could u please take a look at the shipping profile 104189587646 associated with the listing 839008392
We feel like that should be associated with the same one of the rest of the listings like the table below shows:
|||||
|-|-|-|-|
|8516616	|116733819302|	"2022-04-21 03:14:36+00"|	1110764892|
|8516617	|116733819302|	"2022-04-22 03:14:10+00"|	1113520820|
|8516618	|104189587646|	"2022-03-02 09:54:45+00"|	839008392|

**Comment by etsyachristensen** [comment]
@yovasx2 Sorry it has taken so long to get through this one. I'm having trouble figuring out how this is happening. If the customer is always choosing the same shipping profile for all of their listings, then it should conceivably always return the same shipping profile id UNLESS a change has been made to the listing that would affect the shipping profile.

Oddly though, the shipping profile id `104189587646` does not appear to be a clone of another profile. So this tells me that it has to have been created directly via the API. Still trying to put my finger on what the issue could be.

How prevalent is this for your customers? Is it happening a lot or just with a select few?

**Comment by yovasx2** [comment]
>So this tells me that it has to have been created directly via the API

Vela only pulls profiles it doesn't create them

>How prevalent is this for your customers? Is it happening a lot or just with a select few?

It's wide spread 95% of support cases suddenly appeared saying the profiles were gone

**Comment by etsyachristensen** [comment]
Oh interesting. Were they showing up just fine using V3 and only just stopped working recently? Or has V3 been a problem for this issue all along?

**Comment by etsyachristensen** [comment]
Ok so I have not been able to figure out how the listing `839008392` got set to the custom shipping profile `104189587646`. I can see in our system that the profile was created via the shop manager. My only assumption is that the shop owner modified the listing to use that profile manually via the shop manager. I checked this shop owner and they have only one shipping profile that is fetchable via the API. But they have nearly 6800 shipping profiles. So you can imagine why we don't want to return those profiles via the API when most will be nearly identical. 

My only suggestion would be to have your system show "Custom Profile for Listing" when a listing has a profile id that isn't returned via the `getShopShippingProfiles` endpoint or when the title of the profile isn't shown in the `getShopShippingProfile` endpoint. We don't have a logical, simple way to return a profile title in a situation like this. Even when the profiles aren't included in the `getShopShippingProfiles` endpoint, they are still returned via the `getShopShippingProfile` endpoint.

If users wish to edit those shipping profiles they can go to their `Shop Manager -> Settings -> Shipping Settings` under the Custom shipping settings section.

**Comment by yovasx2** [comment]
but that's part of the problem, the customer and some others have only one profile, it isn't making sense to create that amount of manual profiles, The API was working and suddenly one day all the products were associated to this custom profiles by some reason and my guess is the customers didn't create them, probably we can move the investigation to another case

**Comment by etsyachristensen** [comment]
Oh I see. So the listings WERE associated to their one common shared profile but then were suddenly associated to a different profile? I hadn't realized that was what you were saying. My apologies for the misunderstanding. That is certainly very concerning. I'll connect with our shipping team to see if something was done recently that would have caused this. We didn't change the OpenAPI in any way that would have updated shipping ids.

**Comment by etsyachristensen** [comment]
> it isn't making sense to create that amount of manual profiles,

Just a quick note on this. Most, of all of those manual profiles were created via the old V2 API when listings were created. We don't do that in V3 any longer so moving forward we don't create all those manual profiles. The only way they can be created is via the Shop Manager UI on Etsy.com.

**Comment by etsyachristensen** [comment]
Can you give me a list of listing ids that are currently appearing to have the wrong shipping profile id in your system? We checked the couple listing ids we have from the examples you provided above. Both listings appear to have had the same shipping profile ids for a long time. Neither have been updated any time recently. I'm wondering if their list of shipping profiles changed rather than the listings themselves. We haven't changed the OpenAPI endpoint for the shipping profiles in 10 months or more in terms of where it goes in our system to fetch the profiles. I'm wondering if somewhere up the change, something was done that narrowed the list of returned profiles.

**Comment by yovasx2** [comment]
hey @etsyachristensen i will take your advice to mirror the current shipping_profile_id when it's custom, but I found a weird inconsistency in the API, the shipping ids are different for some listings, we are taking into consideration the one at product level:

by hitting: https://openapi.etsy.com/v3/application/listings/1036178158?includes=shipping
the response is:

```
{
    "listing_id": 1036178158,
    "user_id": 294195336,
    "shop_id": 23032671,
    "title": "Taylor Swift evermore Tshirt // what a shame t-shirt //  Taylor Swift Tshirt // evermore album tshirt // Taylor swiftie Tshirt",
    "description": "*** Welcome everyone to visit jk36creations  ***\n             Please choose your favorite item. \n                                 Let&#39;s Go\n\n *** T-Shirt***\n\n- About :\nThis heavy cotton tee has the classic cotton look and feel. Casual elegance will make it an instant favorite in everyone&#39;s wardrobe.\n- Key features :\n+ 100% Open end cotton: Environmentally-friendly manufactured cotton that gives thicker vintage feel to the shirt. Long lasting garment suitable for everyday use\n+ Without side seams: Knitted in one piece using tubular knit, it reduces fabric waste and makes garment more attractive\n+Ribbed knit collar without seam: Ribbed knit makes collar highly elastic and helps retain its shape\n+Shoulder taped: Twill tape covers the shoulder seams to stabilize the back of the shirt and to prevent stretching\n- Care instructions :\nMachine wash: warm (max 40C or 105F); Non-chlorine: bleach as needed; Tumble dry: medium; Do not iron ; Do not dryclean.\n\n *** Sweatshirt ***\n\n- About :\n+ Loose fit\n+ 50% Cotton; 50% Polyester (fibre content may vary for different colors)\n+ Medium fabric (8.0 oz/yd² (271.25 g/m²))\n+ Sewn in label\n+ Runs true to size\n- Key features :\n+ 50% Cotton: Made by specially spinned fibers that make very strong and smooth fabric\n+ 50% Polyester: Polyester fibers are extremely strong, resistant to most chemicals, stretching and shrinking. Viscose adds amazing draping and softness to the shirt\n+ Without side seams: Knitted in one piece using tubular knit, it reduces fabric waste and makes garment more attractive\n+ Ribbed knit collar with seam: Ribbed knit makes collar highly elastic and helps retain its shape\n- Care instructions :\nMachine wash: warm (max 40C or 105F); Non-chlorine: bleach as needed; Tumble dry: medium heat; Do not iron ; Do not dryclean\n\n-----------------------------------------------------\nRETURN POLICY\n\n-All sales are FINAL and I DON’T accept returns.\n-This is a customized and personalized product, and can not be resold.\n-If you have any questions please do not hesitate to contact me.\n\n-------------------------------------------------------\nCAN’T FIND THE ANSWER TO YOUR QUESTION?\n\n-If you can’t find the answer to your question, don’t hesitate to send me a quick message.\n-I will do my best to accommodate your requests.",
    "state": "edit",
    "creation_timestamp": 1647244219,
    "created_timestamp": 1647244219,
    "ending_timestamp": 1657785019,
    "original_creation_timestamp": 1626066481,
    "last_modified_timestamp": 1647920974,
    "updated_timestamp": 1647920974,
    "state_timestamp": 1647244219,
    "quantity": 35,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1036178158/taylor-swift-evermore-tshirt-what-a",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
        "Taylor Swift shirt",
        "folklore sweatshirt",
        "folklore shirts",
        "Taylor Swift t-shirt",
        "swiftie t-shirt",
        "evermore shirt",
        "champagne problems",
        "fucked in the head",
        "what a shame she's",
        "auroras and ivy co",
        "Taylor swiftie shirt",
        "aurorasandivyco"
    ],
    "materials": [
        "cotton"
    ],
    "shipping_profile_id": 150425788422,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
        "amount": 2298,
        "divisor": 100,
        "currency_code": "USD"
    },
    "taxonomy_id": 482,
    "production_partners": [],
    "skus": [],
    "shipping_profile": {
        "shipping_profile_id": 145147258560,
        "title": null,
        "user_id": 294195336,
        "min_processing_days": 3,
        "max_processing_days": 5,
        "processing_days_display_label": "3-5 business days",
        "origin_country_iso": "US",
        "origin_postal_code": "95112",
        "profile_type": "manual",
        "is_deleted": false,
        "domestic_handling_fee": 0,
        "international_handling_fee": 0,
        "shipping_profile_destinations": [
            {
                "shipping_profile_destination_id": 27177075795,
                "shipping_profile_id": 145147258560,
                "origin_country_iso": "US",
                "destination_country_iso": "",
                "destination_region": "none",
                "primary_cost": {
                    "amount": 1799,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "secondary_cost": {
                    "amount": 299,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "shipping_carrier_id": 0,
                "mail_class": null,
                "min_delivery_days": 21,
                "max_delivery_days": 40
            },
            {
                "shipping_profile_destination_id": 28048404493,
                "shipping_profile_id": 145147258560,
                "origin_country_iso": "US",
                "destination_country_iso": "CA",
                "destination_region": "none",
                "primary_cost": {
                    "amount": 1799,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "secondary_cost": {
                    "amount": 100,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "shipping_carrier_id": 0,
                "mail_class": null,
                "min_delivery_days": 12,
                "max_delivery_days": 20
            },
            {
                "shipping_profile_destination_id": 28048404501,
                "shipping_profile_id": 145147258560,
                "origin_country_iso": "US",
                "destination_country_iso": "GB",
                "destination_region": "none",
                "primary_cost": {
                    "amount": 1799,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "secondary_cost": {
                    "amount": 199,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "shipping_carrier_id": 0,
                "mail_class": null,
                "min_delivery_days": 22,
                "max_delivery_days": 30
            },
            {
                "shipping_profile_destination_id": 27177075789,
                "shipping_profile_id": 145147258560,
                "origin_country_iso": "US",
                "destination_country_iso": "US",
                "destination_region": "none",
                "primary_cost": {
                    "amount": 199,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "secondary_cost": {
                    "amount": 150,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "shipping_carrier_id": 1,
                "mail_class": "first_class",
                "min_delivery_days": null,
                "max_delivery_days": null
            }
        ],
        "shipping_profile_upgrades": [
            {
                "shipping_profile_id": 145147258560,
                "upgrade_id": 6369189901,
                "upgrade_name": "Express",
                "type": 0,
                "rank": 0,
                "language": "en-US",
                "price": {
                    "amount": 3100,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "secondary_price": {
                    "amount": 300,
                    "divisor": 100,
                    "currency_code": "USD"
                },
                "shipping_carrier_id": 1,
                "mail_class": "priority",
                "min_delivery_days": null,
                "max_delivery_days": null
            }
        ]
    },
    "shop": null,
    "images": null,
    "user": null,
    "translations": null,
    "inventory": null
}
```

Where u can see 2 different ids associated with the same listing:
"shipping_profile_id": 150425788422, (listing level)
"shipping_profile_id": 145147258560,
This is present in a bunch of listings, is there something wrong with the data, will the listing level one be accepted by the API?

**Comment by etsyachristensen** [comment]
Ok I believe this issue is now fixed @yovasx2 . Please check it out. I think the issue came up from a different supposed fix that didn't end up fixing the problem. Well masked though. Anyway, just check it out and let me know if this clears up the issues.

**Comment by thisisjake** [comment]
@etsyachristensen I believe the changes made here might have caused what I've described in https://github.com/etsy/open-api/issues/508 (I created a new issue as its a different issue to what is described in the title of this issue).

These changes have broken our inventory updating process.

**Comment by etsyachristensen** [comment]
@thisisjake You are correct. @yovasx2 The fix that *should* have been done last week (that I messed up on) should be in production tomorrow (June 21).
