### ISSUE TITLE
The requested redirect URL is not permitted

### ISSUE THREAD

**Issue by lalitarya128** [etsy/open-api#404]
hello
I have create an app few days ago but until this is not approve. when I am going to edit my previous app to add the redirect urI but I am getting this please help me https://qsnapnet.com/snaps/y90r64pclls
from api https://qsnapnet.com/snaps/ydec99wbfji

**Comment by Gareth064** [comment]
@lalitarya128 as per your other ticket #407 please see my comment on  #410 for the workaround to this issue
