### ISSUE TITLE
[BUG]: The redirect url is not permitted 

### ISSUE THREAD

**Issue by lalitarya128** [etsy/open-api#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

etsy error I have create an app few days ago but until this is not approve. when I am going to edit my previous app to add the redirect urI but I am getting this please help me https://qsnapnet.com/snaps/y90r64pclls from api https://qsnapnet.com/snaps/ydec99wbfji

### Steps to reproduce

1. Create an app on etsy
2. Try to edit my created app.
3. Click on name of app title 
4. Redirect error page is not found 

### Expected behavior

Please help what should I have to do

**Comment by Gareth064** [comment]
@lalitarya128  see my comment on  #410 for the workaround to this issue
