### ISSUE TITLE
[BUG]: Missing SKUs and production_partners in Additional_Parameters for ShopListing (findAllActiveListingsByShop endpoint)

### ISSUE THREAD

**Issue by MaciejDerek** [etsy/open-api#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I'm creating an integration with etsy API V3 (transitioning from V2). I would like to get active listings with SKUs values.

I added a listing with SKU (together with a variation). When calling the endpoint findAllListingsActive I see that in the Additional_parameters property there is 'skus' key but the value is the empty array. I also see that the 'production_partners' key is also empty even though I added a value via platform.

endpoint called: shops/34159050/listings/active

Please let me know if this is an issue on your side or I'm doing something wrong. Perhaps there is an option to get bulk results for listings together with the skus without calling endpoint for getting listings by id (due to many listings on production it will produce a lot of calls to your API).

Hope to hear from you soon,

Maciej D.

### Steps to reproduce

Call findAllListingsActive for the given shopId which has sku and production_partner added

### Expected behavior

Those values should be visible in Additional_parameters property

**Comment by etsyachristensen** [comment]
The findAllListingsActive endpoint is a public endpoint. The "sku" array element is included but only because all the endpoints that return listings use the same common resource in our system. However, the values of sku and production_partner_ids are private information and thus only exposed in listings that are owned by the user that is authenticated. So if you are querying your own listings (as a shop owner) you should see those values. But if you are getting listings from other shops, you won't see that information.

**Comment by MaciejDerek** [comment]
Sorry for not precise description. Of course I use **findAllActiveListingsByShop** - and I add authentication token and still there are no values for skus and production_partner. I updated the title

**Comment by etsyachristensen** [comment]
Apologies @MaciejDerek I should have been a bit more clear. The "find" endpoints are public and aren't setup to fetch that information. The "getListing" and "getListingsByShop" are the endpoints you'll need to use to get that information.

**Comment by MaciejDerek** [comment]
Hi @etsyachristensen. I understand your point. But as described above I use getListingsByShop and Additional_parameters keys have empty values.

**Comment by etsyachristensen** [comment]
I don't know what you mean by "additional_parameters". This is not a field we provide in our API or accept in our API. The `getListingsByShop` and `getListing` endpoints will include "production_partner_ids" and "skus" if the owner of the access token requesting the information is the owner of the listings. The two endpoints for "find" are public search endpoints that are designed to fetch publicly available information and allow you to use keywords etc. But the "get" endpoints are for the shop owners and require the oauth scope. If you are still not getting skus or production partner ids, please provide a list of listing ids that we can look into and the shop id that belongs to the requesting user.

**Comment by MaciejDerek** [comment]
Hi @etsyachristensen. Thanks for explanation! I found out the source of confusion :)
In the summary of changes https://developers.etsy.com/documentation/migration/summary-changes 
you specified that:
Endpoint **findAllShopListingsActive in V2** is mapped to **findAllActiveListingsByShop in V3** which in my case would be as you wrote above **getListingsByShop with query param state=active** I totally missed this endpoint focused on 'active' part of the name of endpoint :)

However, when it comes to SKUs and production_partners - you can check that on the website https://developers.etsy.com/documentation/reference/#operation/getListingsByShop that those fields are not specified in the response provided. Model from openApi ShopListing also doesn't have it implictly specified and I see that during deserialization those properties are placed in AdditionalProperties property.

```
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
```

you were right that those values are populated for getListingsByShop but are empty for findAllActiveListingsByShop.

**Seems like issue is solved with conclusion:**
In order to get skus for all active listings of the given account one should call getListingsByShop and look for this in the dictionary AdditionaProperties of the ShopListing model. (I think website should contain this info).
