### ISSUE TITLE
[BUG]: findAllActiveListingsByShop retrieving 0 records

### ISSUE THREAD

**Issue by tythomas** [etsy/open-api#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling the findAllActiveListingsByShop with the state of `expired`, it retrieves the number of records I expect, but when calling it with state of `active`, no records are returned.

Expired State
URL: https://openapi.etsy.com/v3/application/shops/7345095/listings
http method: GET
payload: {'state': 'expired', 'offset': 0, 'limit': 100}
http headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'VALID BEARER TOKEN', 'x-api-key': 'MYAPIKEY'}
Retrieved 100 records.

Active state
URL: https://openapi.etsy.com/v3/application/shops/7345095/listings
http method: GET
payload: {'state': 'active', 'offset': 0, 'limit': 100}
http headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'VALID BEARER TOKEN', 'x-api-key': 'MYAPIKEY'}
Retrieved 0 records.

The only difference between the 2 calls is the state attribute being `active` vs. `expired`.

In fact, most other valid values in the enum work, except active, which I assume is also '0', that doesn't retrieve any records either:
{"error":"Invalid value (asd) for enum(0, 1, 2, 3, 4, 5, active, inactive, sold_out, draft, removed, expired, edit)"}

This used to work, although it has been a few months since I was actively doing development.

Not sure if something has changed with trying to retrieve my shops active listings, but I didn't see anything in the docs.

I reviewed the active bugs and there is a similar issue, although theirs says this endpoint is work for them and a different endpoint is not.

There are no errors returned, the http status code is 200 for every query, ones that return data or ones that don't.

When state is `active`:
http status: `200`
http result text: `{"count":0,"results":[]}`

### Steps to reproduce

Run a valid query against our shop, that has over 500 active listings currently.

### Expected behavior

I expect to retrieve the active listings for the shop.

**Comment by etsyachristensen** [comment]
@tythomas The shop you provided (7345095) has no active listings.

**Comment by tythomas** [comment]
@etsyachristensen - Thanks for the quick comment....I just realized the shop is in vacation mode, which is probably why the "active" aren't showing up.  In this case, how do I retrieve those listings that are marked as "active" in the UI.  I can retrieve every other state fine through the api.

<img width="1628" alt="Screen Shot 2022-03-15 at 4 49 14 PM" src="https://user-images.githubusercontent.com/42620003/158490727-34ae63d2-9f09-4fdc-b21d-388e4fe581b2.png">

**Comment by tythomas** [comment]
Turns out, that is the API I'm using....with the state attribute and it's not working.

Here's my URL:  URL: https://openapi.etsy.com/v3/application/shops/7345095/listings

findAllActiveListingsByShop:
https://openapi.etsy.com/v3/application/shops/{shop_id}/listings

Seems vacation mode might be causing them to not be returned?  Just speculating

**Comment by etsyachristensen** [comment]
That likely is the issue yes. I think when vacation mode is on, the "active" state listings won't be returned to avoid any possibility of those listings being displayed by mistake when the shop is in vacation mode.

**Comment by etsyachristensen** [comment]
At the moment there is no way unless you already know the listing ids. If you know any given listing id you can do an update and only post the fields you know you want to change.

**Comment by etsyachristensen** [comment]
Given that the V2 OpenAPI behaves the same way, we are not going to work on making any changes to this endpoint at this time.
