### ISSUE TITLE
[BUG]: Cannot create a new app

### ISSUE THREAD

**Issue by vladimirus** [etsy/open-api#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had a working app which I asked to delete because I accidentally pressed "Full Access" which I do not need and I thought the app was "stuck" because I couldn't update my redirect url. The app was deleted.

Now, I try to create a new app in https://www.etsy.com/developers/your-apps but it doesn't seem to be working. First my apps weren't appearing there. Then eventually appeared but when I click on any app I get "Oh-Uh" page and I cannot do anything with it... (cannot create redirect_url or see my description)

I've noticed that the apps I create is in "Pending Approval" state for few days, after that they are simply removed.

Please, help!

My shop name is: BestRated

### Steps to reproduce

1. go to https://www.etsy.com/developers/your-apps
2. create new app
3. fil in details
4. submit
5. where the app appears click on it and see Uh-Oh page

### Expected behavior

Should be able to create an app and change redirect_url so I can perform oath and createListings for my own shop.

**Comment by nateswart** [comment]
There's a good chance that your request is either missing information or demonstrates a violation of the Terms of Service. Be sure when filling out the form to complete everything with as much detail as possible, ensure it's accurate, and abides by the API policies.

**Comment by Gareth064** [comment]
@vladimirus number 5 from your list is an issue I just ran into, and found the BUG and the Workaround for it.

Here is what I just emailed to the Etsy Developers email address to inform them of the BUG

When you go to [Apps You've Made - Etsy Developers](https://www.etsy.com/developers/your-apps)

Click on any App name

![image](https://user-images.githubusercontent.com/22307223/158706950-fdfa4837-ed15-4067-b9be-4641451364f2.png)


You end up with a with a 404 Page not found response

![image](https://user-images.githubusercontent.com/22307223/158706979-48b10dc8-c574-457f-a04a-b7e623b9e8cd.png)


But look at the URL

![image](https://user-images.githubusercontent.com/22307223/158707024-aa3bcfbe-c1d8-4ff9-840c-eaab35782736.png)


And hovering over the App Names you can see this

![image](https://user-images.githubusercontent.com/22307223/158707072-6cd4b05a-fcde-47d6-9a9c-b4baaba12bfc.png)


Once I am on the 404 page, and I remove the extra slash and space from the URL, it all comes back to live again.

![image](https://user-images.githubusercontent.com/22307223/158707238-69dbab02-9931-4393-acf4-fb761fb51b00.png)

@nateswart @etsyachristensen - Could either of you inform the Developers to look for my email sent about 15 mins before I posted this here
