### ISSUE TITLE
Why my app still "Awaiting Approval"?

### ISSUE THREAD

**Issue by MarsLauCN** [etsy/open-api#411]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

I have revised the content as required, but still "Awaiting Approval", Please check it, my APP name is "Shipreadygo", thanks a lot.

### Proposed Endpoint Design Change

I suggest to add status for "request full access".

### Why are you proposing this change?

In this way, I can know the process.

**Comment by nateswart** [comment]
Approvals are not instantaneous and need to be reviewed for compliance and acceptability, so it may be in "Awaiting Approval" for a few days. 

A couple key points though, from reading your ticket here, that may be key to know (and anyone else who finds this thread):
- It is against Etsy's Terms of Service for companies to instruct users to register their own API key, so there's a good chance your request will be rejected. I'm making the assumption you are not the creator of Shipreadygo, meaning you may want to ask them why they are asking you to register your own key. If you are the developer for Shipreadygo, be sure to include all relevant information in the request submission to accurately represent it as a commercial software offering.
- "Request Full Access" is only necessary if you plan on supporting your application outside of your personal use, meaning hundreds or thousands of users accessing your application.
