### ISSUE TITLE
[BUG]: A missing label on the UI when creating shipping profile/destination for some countries via API

### ISSUE THREAD

**Issue by NSaikevych** [etsy/open-api#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is possible to create a shipping profile or shipping profile destinations with `destination_country_iso: GG`, for example. The shipping profile/destination will be created but the label of this country is missing:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/12773692/158835666-14a8d1e7-f9cb-4276-9a55-6560307e8d48.png">

### Steps to reproduce

1. Create a shipping profile with `destination_country_iso: GG` via API

### Expected behavior

The destination label is displayed on the UI.

### Additional context

There are more countries related to that, additional example that was found: `JE`

**Comment by etsyachristensen** [comment]
@NSaikevych When you query the API after creating the destinations via the API are the labels correct? Is it only an issue in the Etsy web UI?

**Comment by NSaikevych** [comment]
@etsyachristensen According to the Etsy v3 API docs there are no country labels. But the `destination_country_iso` is correct.
I think it is the Etsy web UI issue only

**Comment by etsyachristensen** [comment]
@NSaikevych We have a solution we are working on. We hope to have this fixed next week. This is not actually an issue with the OpenAPI, but with another area of the the Etsyverse. I'll leave this ticket open but our team won't be the ones working on the fix. If/when I get an update I'll let you know.

**Comment by NSaikevych** [comment]
@etsyachristensen I understand that it is not related to the API. 
Please share where to log such unrelated to the API bugs, just in case for the future.
Thank you for your feedback!

**Comment by NSaikevych** [comment]
@etsyachristensen 
I have found an API issue regarding the creation of the Shipping Profile Destination.
`destination_country_iso: BY` and `destination_country_iso: RU` leads to the 500 Server Error.

Would be great to get another HTTPS error code for it.

**Comment by etsyachristensen** [comment]
@NSaikevych The API will now return a 400 Bad Request response when using RU or BY for the time being.

Also, the GG and JE should start showing up in the UI soon, if not already.
