### ISSUE TITLE
Getting Error when trying to add new variations with Etsy API V3

### ISSUE THREAD

**Issue by onestcom** [etsy/open-api#413]
Hi,
I'm getting the error: "Expected int value for 'property_id' (got NULL)" when trying to add new variations to my Listing, using the EndPoint updateListingInventory.
here is an example of data i send:
array:2 [
  "products" => array:21 [
    0 => array:3 [
      "sku" => "2020"
      "property_values" => array:4 [
        "property_id" => 513
        "value_ids" => array:1 [
          0 => 1
        ]
        "property_name" => "Size"
        "values" => array:1 [
          0 => "4x6ft/120x180cm"
        ]
      ]
      "offerings" => array:3 [
        "price" => 858.0
        "quantity" => 100
        "is_enabled" => true
      ]
    ]
  ]
  "price_on_property" => array:1 [] 

Although I send the property_id as you notice (513), i get the error  "Expected int value for 'property_id' (got NULL)".
Can you please tell me what's wrong?
If you need any further pieces of information I'll be happy to share them with you.
Best Regards.

**Comment by etsyachristensen** [comment]
@onestcom The array you provided appears to be somewhat of a php array. It's tough to read. Can you provide your post data as a JSON array? The data has to posted as JSON data.

**Comment by onestcom** [comment]
Thank you @etsyachristensen for your quick reply,
here is my post data as json array:
"products" => [ 
				"sku" => 2167
				"property_values" => {"property_id":513,
										"value_ids":[1],
										"property_name":"Size",
										"values":["4x6ft\/120x180cm"]
										} 
				"offerings" => {"price":858,
					"quantity":100,
					"is_enabled":true
					} 
			]
An important notes that when i'm editing existion variation the endpoint updateListingInventory works without any problèm, i got the message eror only when traying to add new variation to listing.
Best Regards.

**Comment by etsyachristensen** [comment]
I'm not sure if this is related but if you are adding a new property to a listing you won't include any values in the `value_ids` array. Leave that array empty. The system will create a new value id for the new property value. Try submitting with an empty array for `value_ids`.

**Comment by onestcom** [comment]
Hi @etsyachristensen,
Thank you for your reply, I did send the post data with an empty array for value_ids, but still get the same error:  "error" => "Expected int value for 'property_id' (got NULL)".
what I want to do is to add new variations (Sizes) to my listing,  and as I mentioned before when I'm updating existing variations prices using the endpoint updateListingInventory it works perfectly, but when trying to add new ones the mentioned error appears.
Best Regards.

**Comment by onestcom** [comment]
Thank you @etsyachristensen  for your reply and your patience.
I did find the issue.
My bad,
offrenigs and property_values should be an array of OBJECTS.
for example
    "offerings" => array:1 [
            0 => array:3 [
              "price" => 858.0
              "quantity" => 100
              "is_enabled" => true
            ]
          ]

Best Regards
