### ISSUE TITLE
[BUG]: createShopShippingProfile returns new error about origin_postal_code that contradicts the documentation

### ISSUE THREAD

**Issue by Y0lk** [etsy/open-api#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since last week, it seems the createShopShippingProfile endpoint returns this new error: `We currently do not support submitting postal codes for this country: CA` when creating a shipping profile with an origin_postal_code in Canada. I have never seen this error before. In the documentation https://developers.etsy.com/documentation/reference#operation/createShopShippingProfile, under origin_postal_code, it clearly says: "Required if the origin_country_iso is US or CA", which contradicts the new error.

### Steps to reproduce

1. Send a request to the createShopShippingProfile endpoint with a origin_country_iso=CA and original_postal_code set to a canadian postal code

### Expected behavior

If the documentation is correct, this should not return an error. This was working normally before before last week.

**Comment by etsyachristensen** [comment]
@Y0lk I am not able to duplicate your experience. I was just able to create a new shipping profile destination using `origin_postal_code` of "A1A1A1" and the `destination_country_iso` of "CA".

Can you post the full payload (with your credentials redacted) you are sending?

**Comment by Y0lk** [comment]
As mentioned, the `origin_country_iso` should be CA. Here's an example of a payload that triggers the error

`{
    "title": "Test title",
    "origin_country_iso": "CA",
    "destination_country_iso": "CA",
    "primary_cost": 18.51,
    "secondary_cost": 3.70,
    "min_processing_time": 5,
    "max_processing_time": 10,
    "min_delivery_days": 1,
    "max_delivery_days": 7,
    "processing_time_unit": "business_days",
    "origin_postal_code": "H3C6M0",
    "language": "en"
}`

**Comment by etsyachristensen** [comment]
Ah ok thanks for the clarification @Y0lk. At the moment, the documentation is a little bit incorrect. Currently the postal code for Canada is only required/allowed when the shipping profile is a calculated profile. The calculated profiles can only be created via the Esty UI. We are currently working on opening up the fixed/manual profiles to allow for use of postal codes in other countries. We will likely update the documentation to reflect this.

**Comment by amitshuklaCedcoss** [comment]
Hi @etsyachristensen i'm also getting issues for few clients when creating shipping profiling 
**case 1: "error": "You can't provide a carrier or mail class and min/max delivery days at the same time."**
post data : 
{"title":"shipping-united states","primary_cost":5,"secondary_cost":2,"destination_region":"","origin_postal_code":"94619","origin_country_iso":"US","destination_country_iso":"US","processing_time_unit":"business_days","shipping_carrier_id":1,"mail_class":"first_class","min_processing_time":7,"max_processing_time":10,"min_delivery_days":1,"max_delivery_days":5}


**case 2 : "error": "There are no supported shipping carriers for the origin country. You can only pass custom min and max delivery days."**
post data : 

{"title":"shipping-united states","primary_cost":5,"secondary_cost":2,"destination_region":"","origin_postal_code":"94619","origin_country_iso":"US","destination_country_iso":"US","processing_time_unit":"business_days","shipping_carrier_id":1,"mail_class":"first_class","min_processing_time":7,"max_processing_time":10}

[https://developers.etsy.com/documentation/reference#operation/getShippingCarriers](https://developers.etsy.com/documentation/reference#operation/getShippingCarriers)

![image](https://user-images.githubusercontent.com/25526103/160661936-be11a44b-ea5a-4496-8e9a-56be7523734f.png)


I'm getting this error for 5 to 6 clients daily from last 1 week, it was working fine previously.
Any help would be greatly appreeciated.

**Comment by etsyachristensen** [comment]
There is an upcoming change that will affect OpenAPI V2 regarding the delivery estimates, which you can read about here (https://www.etsy.com/developers/documentation/getting_started/edd). That said, I am not sure if this is related to that change as none of that was meant to be in place just yet.

I am updating the documentation today as well to make the following more clear:

When adding or updating a shipping profile, you have to have EITHER `shipping_carrier_id` and `mail_class` OR `min_delivery_days` and `max_delivery_days`, but not both and not some combination of those fields.

The `shipping_carrier_id` will default to 0 on it's own so don't pass that if you want to set the min/max delivery days. If you do not want to set the days, then only pass in a value (>= 0) for `shipping_carrier_id` and the `mail_class` string.

I'm looking into your individual cases above. I just wanted to make sure you all understood this setup.

Given the influx of new issues being reported I am assuming that something else has cropped up and we will need to find/fix it.

**Comment by amitshuklaCedcoss** [comment]
> case 2 : "error": "There are no supported shipping carriers for the origin country. You can only pass custom min and max delivery days."

@etsyachristensen seems this issue is rectified now, tested for same client now shipping template create without any issue. Can you plz confirm same from your end?
Thanks

**Comment by rkistaps** [comment]
Hello, @etsyachristensen. We recently launched a feature on our end that allows customers to select one of our fulfillment centers as a default country of origin for their listings. We use this information when creating and updating shipping templates we create in their Etsy accounts(fields `origin_country_iso` and `origin_postal_code`). But we are facing validation issues for three countries - "CA", "MX", and "LV". 

```
{
    "title": "Printful: Bags, Sherpa jackets, Other non-standard size items (#PF-FRG15)",
    "primary_cost": 12.49,
    "secondary_cost": 5,
    "min_processing_time": 2,
    "max_processing_time": 5,
    "min_delivery_days": 7,
    "max_delivery_days": 18,
    "origin_country_iso": "CA",
    "origin_postal_code": null,
    "destination_country_iso": "US"
}
```

And the response is 
```
{
    "headers": {
        "X-Etsy-Request-Uuid": "EuzapU6EPmsQKZiIa4ClJD7VIec6",
        "X-Limit-Per-Second": "20",
        "X-Remaining-This-Second": "19",
        "X-Limit-Per-Day": "50000",
        "X-Remaining-Today": "49952"
    },
    "data": {
        "error": "'' is an invalid postal code for country: CA"
    }
}
```

We also tried various different combinations like `null`, and real postal code, tried omitting this parameter at all, but could not get this working.

The errors we received:
`'' is an invalid postal code for country: CA`
`We currently do not support submitting postal codes for this country: CA`


This issue appears to be only for certain countries because we were able to set postal codes for "UK" and "ES". We tested setting this function in the Etsy dashboard and it works for all countries, so it seems like a V3 API issue.

Probably worth mentioning that it was not possible to add postal codes for these countries in UI a few weeks back, so it seems like after adding this feature in UI, the API validation part "broke".

Currently, we have disabled postal code updating for "CA", "MX" and "LV" for our profiles, but would like to hear some advice from you. Is there something you can advise us on this matter?

**Comment by etsyachristensen** [comment]
@rkistaps and @Y0lk We are aware of this issue. We are working on a fix that should be in place early next week. Sorry for the issues with this. Dealing with postal codes around the world is rather challenging. Some countries use them 100% of the time. Some use them only sometimes and some don't use them at all.

**Comment by rkistaps** [comment]
Thanks for heads up. We will be waiting for updates on this one.

**Comment by etsyachristensen** [comment]
This issue should be fixed now. Please give it a try and let us know if you run into issues still.
