### ISSUE TITLE
[BUG]: Clicking App name in developer account results in a 404 page

### ISSUE THREAD

**Issue by probc** [etsy/open-api#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The documentation is telling me to click on my App name in my developer account for additional settings, however when I do this I am presented with a "Uh oh! Page Not found" error.  I suspect this is because my new App is still set as "Pending Approval". 

I have sent in about a dozen emails to developers@etsy.com over the last 4 weeks with no response and suspect there must not actually be anyone in that department anymore.

Does anyone here have suggestions on how to proceed with using the Etsy API when there is no support?

### Steps to reproduce

1) Login to developer account
2) click on the App name in the "Manage your Apps" page
3) 404 page is presented

### Expected behavior

I would expect there is another settings page with more detail and options available after clicking on the App name

**Comment by Gareth064** [comment]
Hey @probc, please see #410 for a description of this issue and the work around.

**Comment by probc** [comment]
Thanks for the info.  As it turned out my app still hadn't been approved (almost 4 weeks later), and coincidently yesterday it was approved.  Now I do see the same issue here when trying to click the App name with the extra / / in the url.  Simply removing this does load the page as expected.

Our next challenge is to finally start programming our functions with the API.  Slowest approval process I've ever seen here just to get started, but at least it looks like we can move forward now.
