### ISSUE TITLE
[BUG]: Edit app URL on your apps page has a space

### ISSUE THREAD

**Issue by vethan** [etsy/open-api#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the page https://www.etsy.com/developers/your-apps clicking on the name of an app generates a URL with an extra space inserted

e.g.: https://www.etsy.com/uk/%20/developers/edit/{APPID}

instead of: https://www.etsy.com/uk/developers/edit/{APPID}

### Steps to reproduce

1. Have a app created
2. Visit https://www.etsy.com/developers/your-apps
3. Click on the name of you app
4. View a 404

### Expected behavior

The link should be formed correctly and take you to the edit app page.

**Comment by etsyachristensen** [comment]
This has been fixed @vethan . Thanks for the help!
