### ISSUE TITLE
[BUG]: UpdateListing - "There was a problem with price : must be above min price"

### ISSUE THREAD

**Issue by neilnguyendev** [etsy/open-api#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to update the listing by using this API: [updateListing](https://developer.etsy.com/documentation/reference#operation/updateListing).

But the response always has status 400 code and message:
`{"error":"There was a problem with \/price : must be above min price \u20ab4,420 VND"}`

### Steps to reproduce

1. My listing id is: 1202278067. Its current price is 168,241VND.
2. Params for PUT request body: 
`{:listing_id=>1202278067, :title=>"Teacher or teaching assistant personalised pen pot gift birthday end of year", :description=>"Cute personalised pen pot. Perfect gift for a teacher or TA  on any occasion.", :shipping_template_id=>170459002586, :taxonomy_id=>1101, :who_made=>"i_did", :is_supply=>false, :when_made=>"made_to_order", :state=>"draft", :should_auto_renew=>false, :price=>172670.0, :materials=>"", :tags=>"personalised gift,teacher,personalised,stocking filler,for her,teaching assistant,name gift,birthday gift,end of year gift,school gift"}`

I also tried with other values for the price as 200000, 20000000, 200000.0, 20000000.0, 100000,...
I'm using RestClient of Ruby.

3. The response in those cases always is:
`{"error":"There was a problem with \/price : must be above min price \u20ab4,420 VND"}`

### Expected behavior

The listing should be updated and return the listing object.

**Comment by neilnguyendev** [comment]
I tried to remove the price from the request's payload. But I still get the same error.

**Comment by etsyachristensen** [comment]
@neilnguyendev Can you please try to use the [updateListingInventory](https://developers.etsy.com/documentation/reference#operation/updateListingInventory) endpoint instead? It will be helpful to call [getListingInventory](https://developers.etsy.com/documentation/reference#operation/getListingInventory) first to get all of the inventory structure that you will need to return in the `updateListingInventory` call. See the tutorial for updating inventory here: https://developers.etsy.com/documentation/tutorials/listings#updating-inventory

Your listing is already converted to an inventory based listing so updating the price or quantity via the updateListing endpoint would likely fail anyway.

Let me know if it fails with the same error when attempting to update via the `updateListingInventory` endpoint.

**Comment by neilnguyendev** [comment]
@etsyachristensen Thanks for your comment. I tried to use the `updateListingInventory` endpoint to update prices and it works. But when I use the `updateListing` endpoint to update the listing state, the same error happens.

```
{:listing_id=>1212188735, :title=>"Embroidered Sunflower Knitted Tops For Women Colorblock Sexy Crop Tops Off Shoulder Camis Sleeveless Patchwork Tanke Top Omighty/Camisole", :description=>"One Size        Length:35cm       Bust:90cm \n\n1.Due to the lighting and display reasons, little color difference is normal ,please forgive\n\n2.Due to different measurement methods, there will be 1-3 cm error is a normal phenomenon\n\n3. Our size is Asia size normally smaller than US size\n\n4.Please take a minute to check size chart,if you are not sure about size details\n\n5.1cm = 0.39 inches 1inch=2.54cm\n\n6.Unit: cm", :shipping_template_id=>170459002586, :taxonomy_id=>517, :who_made=>"i_did", :is_supply=>false, :when_made=>"made_to_order", :state=>"active", :should_auto_renew=>false, :materials=>"", :tags=>"Renaissance Corset,Floral Vest Corset,Lace Bow Corset,Fishbone Lace Corset,Jacquard Corset,Fairycore Clothing,Renaissance Bodice,Crop Top,Y2K Top,Cottagecore Corset,Corset Crop Top,Under Bust Lace,spring clothing"}
RestClient.put "https://openapi.etsy.com/v3/application/shops/32055095/listings/1212188735", 1031 byte(s) length, "Accept"=>"*/*", "Authorization"=>"Bearer _XXXX_", "Content-Length"=>"1031", "Content-Type"=>"application/x-www-form-urlencoded", "User-Agent"=>"rest-client/2.1.0 (darwin20.6.0 x86_64) ruby/2.6.5p114", "X-Api-Key"=>"_XXXXX_"
# => 400 BadRequest | application/json 87 bytes, 0.55s
RuntimeError: {"error":"There was a problem with \/price : must be above min price \u20ab4,418 VND"}
```

I tried to remove the price field in the body param.

**Comment by etsyachristensen** [comment]
are you using the V3 OpenAPI? Or V2 OpenAPI? In V3, we don't use "shipping_template_id" but rather "shipping_profile_id" so I'm concerned you're asking for help on V2 which isn't done here. I'm still looking into the issue though because it may not be related to the version of the API.

**Comment by neilnguyendev** [comment]
@etsyachristensen I'm asking for help on V3. I changed the field to "shipping_profile_id" but the error still happens.

**Comment by etsyachristensen** [comment]
We have a theory @neilnguyendev that will be easiest for you to test. Can you try removing the taxonomy_id value from your update post data? Let me know if you're able to update with that out of there. Hard to explain why this may be the case. But if this does allow you to update, we have a clearer picture of what is going on and we can work on fixing it.

**Comment by neilnguyendev** [comment]
@etsyachristensen Oh yeah. I have already tried to remove the taxonomy_id value and it works!

**Comment by etsyachristensen** [comment]
That's great news! I believe I have the start of a plan to correct the problem. Will let you know when we have addressed the problem.

**Comment by etsyachristensen** [comment]
Ok this issue has been fixed. You should be able to include taxonomy_id without triggering that error.
