### ISSUE TITLE
[FEATURE]: pagination errors

### ISSUE THREAD

**Issue by jon-chambers** [etsy/open-api#422]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

The documentation reads "the Open API v3 a maximum limit of 100 for performance reasons, and passing a higher value resolves to the limit of 100 instead of throwing an error."

This means that if I mistakenly set the limit to 101, my error will never be corrected and I will always be missing one item.

### Describe the solution you'd like

Throw an error. That's what errors were designed for. This is the exact use case people had in mind when they invented errors.

### Additional context

This is not a trap I have fallen into, nor is it a trap I expect I'd fall into. I don't even think it's a trap many people will fall into. But that one poor developer who sets a limit to 101 because they started the loop on "i = 0" instead of "i = 1" is going to have one hell of a time figuring out what's going wrong. Throw an error, and you may save them several hours of troubleshooting.

**Comment by etsyachristensen** [comment]
We appreciate the feedback on this. However, this the way our various versions of the OpenAPI have always behaved. We felt it didn't warrant returning an error given the documentation is fairly clear.
