### ISSUE TITLE
[BUG]: Cannot update the listing with calculated shipping template id.

### ISSUE THREAD

**Issue by jeevan-dpl** [etsy/open-api#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Etsy API Version: V2

While creating the product using createListing endpoint I was able to create the product without any issue or error messages. 
I used calculated shipping template id and also my product had no data on height, weight, length and width. So they were set to 0 by my system.

But while updating the very same product using updateListing endpoint, I ended up with the error message saying
: The weight/dimensions field are required for calculated shipping profile id. 

Is this a bug or It's just me getting confused about the working mechanism of APIs?

### Steps to reproduce

1. API version V2
2. Created listing using createListing Endpoint
3. Used calculated shipping template id and all dimensions and weight fields were set to 0
4. The product was Uploaded sucessfully
5. Tried to update the product usingg updateListing endpoint with very same data. 
6. Ended up with error saying weight/dimension is required for calculated shippingg template ID.

Error Message: 
[calculated_shipping_error:missing_weight] This shipping profile cannot be applied to a listing with no weight

### Expected behavior

If I can create the product with the data I provided, I expect that it can be used to update the product as well.

**Comment by etsyachristensen** [comment]
This github repo is for V3 version of the OpenAPI. For support with V2, you can use the Google Group here: https://groups.google.com/g/etsy-api-v2
