### ISSUE TITLE
[BUG]: API v2. Zip code is invalid for not the USA countries

### ISSUE THREAD

**Issue by NSaikevych** [etsy/open-api#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
{
  "title": "Random title",
  "origin_country_id": 90,
  "destination_country_id": null,
  "primary_cost": "11",
  "secondary_cost": "3",
  "min_processing_days": 1,
  "max_processing_days": 7,
  "min_delivery_time": 10,
  "max_delivery_time": 30
}
```

The creation of such a template sometimes fails with the `ZIP Code  is invalid` error. 

### Steps to reproduce

1. Create a shipping template without a postal code for other than the USA country.
2. Sometimes it fails with the `ZIP code is invalid` error.

### Expected behavior

It is allowed to create a shipping template without a postal code for other countries than the USA.

**Comment by etsyachristensen** [comment]
@NSaikevych I need to know what shipping profile you are using. Can you give me the shipping profile id?

**Comment by etsyachristensen** [comment]
Oh gotcha. You are working with the V2 OpenAPI. For help with that, you will need to post in the Google Group. https://groups.google.com/g/etsy-api-v2. This repo is for V3 OpenAPI.
