### ISSUE TITLE
[BUG]: bad <a> tag on migrating from v2 page

### ISSUE THREAD

**Issue by luiderek** [etsy/open-api#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

broken link on https://developers.etsy.com/documentation/migration/index/ that points to https://developers.etsy.com/documentation/migration/ which is a 404

![image](https://user-images.githubusercontent.com/12964172/162093215-7c48d0c8-ccfa-4bd3-904b-be18f3cf1830.png)

### Steps to reproduce

1. go to https://developers.etsy.com/documentation/migration/index/
2. click on [API development guides](https://developers.etsy.com/documentation/migration/) (this site)

### Expected behavior

not going to a 404

**Comment by etsyachristensen** [comment]
Thank you for bringing this to our attention. We will get it fixed ASAP.

**Comment by etsyachristensen** [comment]
This is fixed.
