### ISSUE TITLE
Unique "product_id" value is always changing

### ISSUE THREAD

**Issue by multiorders** [etsy/open-api#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`I was not sure if this is the way it works, if yes, then this should have been a feature request, apologies`

We are attempting to use the "product_id" value as a unique identifier to map Etsy products to our inventory so that the system could communicate and update stock and price correctly.

### Steps to reproduce

1. Create a product with variations on Etsy
2. Run - GET https://openapi.etsy.com/v3/application/listings/1211711901/inventory - to get product info
3. Make stock and price adjustments 
4. Run - PUT https://openapi.etsy.com/v3/application/listings/1211711901/inventory - to update product info

The PUT code for reference:
{
    "products": [
        {
            "sku": "SKU1",
            "property_values": [
                {
                    "property_id": 200,
                    "value_ids": [
                        54711166638
                    ],
                    "scale_id": null,
                    "property_name": "Primary color",
                    "values": [
                        "Beige"
                    ]
                },
                {
                    "property_id": 52047899002,
                    "value_ids": [
                        56848080817
                    ],
                    "scale_id": null,
                    "property_name": "Secondary color",
                    "values": [
                        "Black"
                    ]
                }
            ],
            "offerings": [
                {
                    "quantity": 22,
                    "is_enabled": true,
                    "price": 22
                }
            ]
        }
    ],
    "price_on_property": [
        200,
        52047899002
    ],
    "quantity_on_property": [
        200,
        52047899002
    ],
    "sku_on_property": [
        200,
        52047899002
    ]
}

### Expected behavior

We expected the "product_id" to remain the same in the same manner as the "listing_id", but every time a products qty or price is updated the ID "product_id" changes. Sometimes the ID reverts back to original form when updated via Etsy again and sometimes a new third variant is generated.

### Additional context

We are an Inventory and Order management tool. The users imports Etsy products and then manages stock and pricing through us. When a user imports their inventory we save various products id's and other critical info so that we would know which variation to update and with what data.

We need a way to map the configurable product variations, but we cannot find a single Unique piece of info that would allow us to map Etsy variations to the data stored on our app.
(from this data https://openapi.etsy.com/v3/application/listings/1211711901/inventory).

We have considered the "product_id" value, but as described it keeps changing. We expected it to work in the same way a "listing_id" does.

Alternatively we considered mapping based  "property_values": [ "values": [ string ], but the users tend to adjust or change the names completely in which case the mapping breaks again.
We also considered using SKU's, but as those are not mandatory and duplicates can created, they are also useless.

Perhaps we are missing something in the API that could help us, or is there no other unique identifier?

**Comment by etsyachristensen** [comment]
The inventory system does work as intended. We are aware that this can be challenging because the product ids and offering ids are changed each time you save the inventory.

However, this is by design. Every time the inventory is updated, a new set of inventory data is created and the previous set of data is archived for posterity and tracking purposes. There is no single key id for any given product in an inventory. We recommend using SKUs for each product/variation. You can set the variations to affect the SKU so that every single variation can have a unique SKU. The SKU would be sent into the `updateListingInventory` endpoint from your system so you can use your own unique values or keys for the SKU.

The only other alternative is to track the property_id and value_id for each product and use that as your key, but that can get very complicated when you have multiple variations/properties.

**Comment by multiorders** [comment]
I see, thank you for confirming the situation.
