### ISSUE TITLE
[BUG]: updateVariationImages doesn't seem to work?

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Here's an example of a request

```
POST https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/variation-image

Body:
{"variation_images":[{"property_id":513,"value_id":129471853302,"value":"NO 1","image_id":3833816919},{"property_id":513,"value_id":111782746046,"value":"NO 2","image_id":3833816945}]}
```

When I make that request, I'm getting this error:

`{"error":"Missing input parameter: [variation_images]"}`

Not only does this error not make any sense, but the error is incredibly unhelpful.

### Steps to reproduce

POST https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id}/variation-image

Body:
{"variation_images":[{"property_id":513,"value_id":129471853302,"value":"NO 1","image_id":3833816919},{"property_id":513,"value_id":111782746046,"value":"NO 2","image_id":3833816945}]}

### Expected behavior

Either the request should work... or better explain why my request is invalid and what I need to do to fix it.

**Comment by etsyachristensen** [comment]
Try removing the "value" node from your arrays. The API only expects to receive `property_id`, `value_id`, `image_id`.

**Comment by etsyachristensen** [comment]
were you able to get his working @DemiImp ?

**Comment by DemiImp** [comment]
After removing the value field, it looks like it's working now.  I'll keep an eye out for further errors and if I see any I'll mention it here.

**Comment by DemiImp** [comment]
Looks like I closed it too soon.

```
X-Etsy-Request-Uuid: Euijzr6fjNpfSjOJG_raYc1732cf

{"error":"Missing input parameter: [variation_images]"}
```


API call:

```
POST https://openapi.etsy.com/v3/application/shops/13417053/listings/1200622252/variation-images
Authorization: Bearer [hidden]
User-Agent: libwww-perl/6.31
Content-Length: 153
Content-Type: application/x-www-form-urlencoded
X-Api-Key: [hidden]

{"variation_images":[{"property_id":502,"value_id":62847206740,"image_id":3809658014},{"property_id":502,"value_id":210747741190,"image_id":3809657960}]}
```

**Comment by DemiImp** [comment]
Here's another simpler example that I did on my own account:

```
POST https://openapi.etsy.com/v3/application/shops/636319
7/listings/1215509113/variation-images
Authorization: Bearer [hidden]
User-Agent: libwww-perl/6.31
Content-Length: 87
Content-Type: application/x-www-form-urlencoded
X-Api-Key: [hidden]

{"variation_images":[{"property_id":200,"value_id":49928889192,"image_id":3810288812}]}
```

```
X-Etsy-Request-Uuid: Eu4anxDnc6aRNO-lt4Q0UVhZEO98

{"error":"Missing input parameter: [variation_images]"}
```

Can you show me a valid example of the POST data I am supposed to be sending?

**Comment by DemiImp** [comment]
Hold on, I just noticed I'm sending application/x-www-form-urlencoded instead of application/json.  Will be testing that fix soon.

**Comment by etsyachristensen** [comment]
Ah yeah that would likely do it.

**Comment by DemiImp** [comment]
Okay, that error has been fixed.  Now I'm getting a new one:

`{"error":"Could not update variation images because of the following error: variation with property_id 200 and value_id 49928889192 is invalid"}`

What I'm doing is I'm querying the current variation images, store the property_id's and value_ids, delete the listing's current images and replace them with new images, and then I generate a new json string using the old property_id and value_ids.  Is that not the correct thing to do?

Here's the json string I'm using to update the listing with:

`{"variation_images":[{"property_id":200,"value_id":49928889192,"image_id":3859213639}]}`

**Comment by DemiImp** [comment]
I did more testing and this is what I've got.

This is the current inventory:

`{"products":[{"product_id":9505508752,"sku":"","is_deleted":false,"offerings":[{"offering_id":9326405641,"quantity":1,"is_enabled":true,"is_deleted":false,"price":{"amount":1000,"divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":200,"property_name":"Primary color","scale_id":null,"scale_name":null,"value_ids":[49928889192],"values":["Blue"]},{"property_id":52047899002,"property_name":"Secondary color","scale_id":null,"scale_name":null,"value_ids":[52114844802],"values":["White"]}]}],"price_on_property":[],"quantity_on_property":[],"sku_on_property":[],"listing":null}`

This is my latest variation images update request:

`{"variation_images":[{"property_id":200,"value_id":49928889192,"image_id":3859458233}]}`

I got the same error as before:

`{"error":"Could not update variation images because of the following error: variation with property_id 200 and value_id 49928889192 is invalid"}`

**Comment by etsyachristensen** [comment]
What colors do those two value ids represent? I'm curious if you tried saving using our default common ids for those colors if it would then save correctly. I'll do some digging on my end.

**Comment by etsyachristensen** [comment]
Disregard my last. I just realized we have the colors in the data. So try using just `2` for the value id on the Blue property. Let me know if that works.

**Comment by DemiImp** [comment]
I will try to override the value to be 2 and get right back to you.  That isn't going to help me long-term though... We need to support any and every value.  If Etsy accepts the value of 2, why does Etsy return to me 49928889192 instead of 2?

**Comment by etsyachristensen** [comment]
Absolutely agree. I just want to know if it works. I'll be digging in for the moment to figure it out.

**Comment by DemiImp** [comment]
Yes, changing the value_id to be 2 makes it work.

**Comment by etsyachristensen** [comment]
Ok thanks. I'll work on a fix. Likely won't be out until early next week.

**Comment by DemiImp** [comment]
Thank you!

**Comment by etsyachristensen** [comment]
@DemiImp When you get a chance can you test it again passing the correct id numbers? I put up a change that I'm hopeful will fix it.

**Comment by DemiImp** [comment]
I just tested it and it looks like it's working.

I don't see any errors in my log from other users, so I think it's fixed.  Thank you so much for jumping on this and helping me out.
