### ISSUE TITLE
[BUG]: Getting error "User does not own shop", but the user DOES own the shop

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

One of my customers is suddenly getting the error "User does not own Shop 7360467".  However, when I check what shops are owned by that account with the API, I get "{"count":1,"results":[{"shop_id":7360467"

This error only appears to happen when I'm adding an image to a listing.

`POST https://openapi.etsy.com/v3/application/shops/7360467/listings/1215498087/images`

`X-Etsy-Request-Uuid: EuoHUCECe_xlCjPs2iAdkGgyZQ35`

### Steps to reproduce

This bug appears to be user-specific.  I cannot reproduce the error on my own account/shop.

### Expected behavior

I expect the image to get added to the listing without any errors

**Comment by etsyachristensen** [comment]
@DemiImp I will need more information to debug this. Can you email developers@etsy.com and reference this ticket and ask that the email be forwarded to me "Andrew Christensen". I can then look into the issue further.

In that email be sure to include the auth token being passed into the endpoint for that user as well as the payload you are sending.

**Comment by DemiImp** [comment]
@etsyachristensen - I can try that.  I have made several emails to developers@etsy.com and I haven't gotten a response from them in about 2 months for any of my tickets.

**Comment by etsyachristensen** [comment]
Understood. I'll make sure they are aware that you are sending this and have them look for it.

**Comment by DemiImp** [comment]
Sent.

**Comment by etsyachristensen** [comment]
@DemiImp I got the email. The person requesting this change on that listing is not the owner of the listing.

The first part of the OAuth2 token is the user id, which in your payload says "21037442". But listing id 1215498087 is owned by a different user id. That said, it appears to be the same person that has two different shops:

https://www.etsy.com/shop/SilkDivine (21037442)
https://www.etsy.com/shop/DivinityFibers (25479246)

Somehow your user is trying to use your app to update a listing in the wrong shop.

**Comment by DemiImp** [comment]
Thank you, that would make a lot of sense.  They must have unlinked their
account with their one Etsy shop and went ahead to link it to a completely
different shop that they also own.  When they switch shops like that, we
don't automatically delete all their old work.

I'm very glad this was a simple problem.  I'll put in protections to
prevent this from happening again.

Thank you so much for your help.

--
David Olick
