### ISSUE TITLE
[DOCS]: Small Doc Errors

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/reference#operation/updateVariationImages

### What would you like to change?

https://developer.etsy.com/documentation/reference#operation/updateVariationImages

`Creates variation images on a listing.\n\nvariation_images is an array `

Looks like the new lines accidentally are \n's

https://developer.etsy.com/documentation/reference#operation/createDraftListing
https://developer.etsy.com/documentation/reference#operation/updateListing

`The getInventory method requests exact`

Under price on both of those, you reference **getInventory**, but this is the v2 name.  In v3 it is **getListingInventory**.

### Why are you proposing this change?

They're just small nitpicky mistakes.  No hate please.

- [x] No hate

**Comment by etsyachristensen** [comment]
Thanks @DemiImp . I'll get those updated ASAP.
