### ISSUE TITLE
[BUG]: Incorrect count in findShops results

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The **count** value provided by the findShops method is incorrect. Currently the **count** field in the response is equal to the number of elements in the results array. In V2, the **count** field used to provide the total number of results which match the search criteria, not only the returned ones. In the findAllListingsActive method in V3, **count** is correct and contains the total number of results overall.

`GET https://openapi.etsy.com/v3/application/shops?shop_name=craft`
`Response:`
`{`
`  "count": 25,`
`  "results": [...]`
`}`

### Steps to reproduce

1. Execute a GET request to the following endpoint: https://openapi.etsy.com/v3/application/shops?shop_name=craft
2. Note that **count** in the response is 25

### Expected behavior

The **count** field should contain the total number of shops which match the search criteria rather than the number of the returned shops only. In the example above, I expect that the **count** field in the response will be several thousands.

**Comment by mhaydenetsydev** [comment]
@VasilVelikov Can you try again. We have just pushed up what we believe should fix this issue. Please let us know how the response time is working compared to before this push.

**Comment by etsyachristensen** [comment]
This has been fixed.
