### ISSUE TITLE
[BUG]: A missing label on the UI when creating shipping profile/destination for AX via API

### ISSUE THREAD

**Issue by NSaikevych** [etsy/open-api#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Related to https://github.com/etsy/open-api/issues/412

It is possible to create a shipping profile or shipping profile destinations with destination_country_iso: `AX`. The shipping profile/destination will be created but the label of this country is missing:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/12773692/164271052-7275d201-7604-4c69-91e4-b200066b23e5.png">

### Steps to reproduce

1. Create a shipping profile or destination with destination_country_iso: `AX` via API

### Expected behavior

The destination label is displayed on the UI.

**Comment by etsyachristensen** [comment]
@NSaikevych I've pushed an update that should fix this.
![image](https://user-images.githubusercontent.com/83842847/165564754-ec39e3da-68c8-488c-808a-4d40d5454eb3.png)
