### ISSUE TITLE
[BUG]: Listings shows 2 different shipping profile IDs

### ISSUE THREAD

**Issue by nmrdxt** [etsy/open-api#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're seeing some products that contain 2 different shipping profile IDs:

```
[
  "listing_id" => 1190774501,
  "shipping_profile_id" => 39120556343,
  "shipping_profile" => [
     "shipping_profile_id" => 170670066893,
     "title" => null
    .
    .
    .
  ]
]
```

When a query the API for the shop's shipping profiles, I'm seeing '39120556343' but not '170670066893' (both manual profiles). When I specifically query the API for the profile 170670066893, Etsy can find it.

What could cause the issue?

### Steps to reproduce

Query the API for listing ID 1190774501 to view the profiles.

### Expected behavior

Shipping profile IDs should match, and 170670066893 should appear in the shop's shipping profiles.

**Comment by etsyachristensen** [comment]
Ah ok. This is due to the fact that the shipping profile used on this listing was `170670066893` BUT this profile was originally based on the shipping profile `39120556343`. This is what we call the "source shipping profile". I'm looking into trying to figure out why this is coming up.

**Comment by nmrdxt** [comment]
Hey, Thank you for checking.

The weird thing is that the merchant received an order, with the transactions' shipping profile set as 39120556343, but the shipping totals do not match the shipping profile set prices (order #2446218464) – could it be related?

**Comment by etsyachristensen** [comment]
That's good information! I'll pass this on to the shipping teams so that they can investigate. My bet is that the shipping costs are actually based on `170670066893` which is the correct shipping profile id. For some reason it's returning the source profile id that it was originally based on. Do you have any way to confirm that the shipping costs would match that profile?

**Comment by nmrdxt** [comment]
The shipping costs do not match the `170670066893` profile – both `170670066893` and `39120556343` look like the same profile with different IDs (they share the same prices as well). There is something strange going on there. Thank you for looking into this.
