### ISSUE TITLE
[BUG]: Offset parameter in findShops doesn't work

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the offset parameter in the findShops endpoint is treated as invalid by the API if its value is greater than the limit parameter. This is incorrect - the offset parameter should be allowed to get any non-negative value, possibly limited only by the total search results in findShops.

### Steps to reproduce

1. Execute GET https://openapi.etsy.com/v3/application/shops?shop_name=art&limit=50&offset=51
2. Observe that the API will return an error with text "Offset provided is greater than the total count of search results."
3. If you replace offset=51 with offset=50 the call will be executed as expected.

### Expected behavior

The offset should be allowed to acquire any non-negative value. In this case, it makes sense to be able to request an offset up to 247842, which is the total number of search results for this keyword.

**Comment by etsyachristensen** [comment]
@VasilVelikov This has been corrected. Sorry for the trouble!

**Comment by VasilVelikov** [comment]
That was fast! Thanks for fixing it :)
