### ISSUE TITLE
[BUG]:  Tracking number is required on v3 api for order fulfillment

### ISSUE THREAD

**Issue by shrestharikesh** [etsy/open-api#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Most of my Order fulfillment request went good even when tracking_code and carrier_name are blank. But some of my API calls is giving me response like this `{"error":"A tracking number is required"}`. 
I am using v3 order fulfillment API and the documentation says that the fields are not required. 
Why am I facing this issue?

### Steps to reproduce

Call this API 
https://api.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}/tracking
CURLOPT_POSTFIELDS = tracking_code=&carrier_name=&send_bcc=false

Most of them are successful but some of them returns the error

### Expected behavior

As the fields are not required it should not cause error evan if the fields are empty

**Comment by etsyachristensen** [comment]
@shrestharikesh Out of curiosity, have you tried making the call but NOT passing in the fields?
tracking_code
carrier_name
send_bcc

Let me know if that changes the response.

**Comment by shrestharikesh** [comment]
No sir, The response is still same for some of the order. @etsyachristensen

**Comment by etsyachristensen** [comment]
Ok thanks. Is there any correlation to where the shipments are going to or coming from (origin country/destination country) for the orders where this is happening? Can you provide a few receipt ids so we can look into this? If you prefer, you can email them to developers@etsy.com and mention that the email is for me (Andrew Christensen) and reference this github issue. The support team will forward to me.

**Comment by danegigi** [comment]
hey @etsyachristensen, 

I used the [createReceiptShipment](https://developers.etsy.com/documentation/reference/#operation/createReceiptShipment) to mark an order complete and at the same time send the carrier and tracking number back to Etsy.

The problem I'm having is that the tracking number is not being reflected by Etsy, it marks it completed but it keeps saying "No Tracking" which is very annoying since I had to manually add the tracking to the specific order.

Thank
<img width="1135" alt="Etsy_-_Sold_Orders" src="https://user-images.githubusercontent.com/413985/166295260-364cd28c-a860-4ef8-a3a7-7717dcca19d2.png">
s

**Comment by etsyachristensen** [comment]
@danegigi Can you give me a listing ID number to check this out? I need to see if it saved to the database.

**Comment by danegigi** [comment]
hey @etsyachristensen,

The order number is Order#2451895934.

Thanks @etsyachristensen.

**Comment by etsyachristensen** [comment]
Thanks @danegigi I don't see any tracking information in the order. Can you give me the payload you are sending for the `createReceiptShipment` endpoint (without your auth credential data)?

**Comment by etsyachristensen** [comment]
@danegigi Are you using Shiprocket? I'm looking at that transaction and our database has recorded the carrier id under the Shiprocket id. I'm just wanting to make sure.

Also when you FIRST tried to submit the tracking you had both the tracking code AND carrier name right?

**Comment by danegigi** [comment]
hey @etsyachristensen

No, we're not using shiprocke. We use axios and PHP client to send the request to etsy. 

Yes, we both send the tracking number and the carrier which is usps.

**Comment by danegigi** [comment]
hey @etsyachristensen,

Just want to follow up on this and also want to ask why our record shows that we're using shiprocket, we don't use shiprocket instead we have our own account under grandshipper.

Thanks

**Comment by etsyachristensen** [comment]
We are still investigating this. Every transaction that has a shipment has a "carrier id" in the record. For some reason that one shipment is marked with that id. We are trying to figure out why or how that could have happened. Our shipping system team will get back to me and I'll relay to you.

**Comment by etsyachristensen** [comment]
@danegigi Is this happening on ALL shipments for you?

**Comment by danegigi** [comment]
hi @etsyachristensen,

I only tried 2 orders for testing but both don't show tracking numbers only marking the order as complete.
Is there a way to see the record being passed to Etsy to confirm that the records are being saved and under our account since it's weird that it shows shiprocket. 

Thanks @etsyachristensen

**Comment by etsyachristensen** [comment]
@danegigi In the response headers, you should see a "X-Etsy-Request-Uuid". If you can send at least that we can hopefully look it up. If you could send us the full post with all the headers (minus your credentials) and the full response with headers that may help us figure this out.

I just did a test on that same shop for receipt id `2455750484`. It went through and stored properly. Here's the Axios code (generated by postman - I'm not a node js developer):
```
var axios = require('axios');
var qs = require('qs');
var data = qs.stringify({
  'tracking_code': '9400109898642197393310',
  'carrier_name': 'usps' 
});
var config = {
  method: 'post',
  url: 'https://api.etsy.com/v3/application/shops/34632576/receipts/2455750484/tracking',
  headers: { 
    'Content-Type': 'application/x-www-form-urlencoded', 
    'x-api-key': 'xxxx', 
    'Authorization': 'Bearer xxxx', 
    'Cookie': '...'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```
I am not sure why yours isn't writing.
