### ISSUE TITLE
[BUG]: digital listings with when_made as "made_to_order" are converted into physical when all their files are removed

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Removing all the files associated with a digital listing with when_made as "made_to_order"  will convert it into a physical listing

### Steps to reproduce

1. Create a digital listing with when_made as 2022...
1. Attach a file to it
1. Then hit edit listing endpoint sending when_made (made_to_order, this option does not require a file attached), who_made, is_supply (u need to send the 3 values to have a 200)
1. Hit get listing endpoint, listing_type is "download"
1. Then hit remove digital file attached to the listing
1. Hit get listing endpoint, listing_type is "physical"

### Expected behavior

the digital listing must remain digital since the when_made "made_to_order" does not require files attached

**Comment by etsyachristensen** [comment]
@yovasx2 We did some testing to confirm this. You are correct that it's converting the listing to physical when removing the attachment. However, this isn't something we can fix at the moment as applying a change here may affect how other areas of the system. For now, I suggest that after removing the attachment on a digital listing, you fire off a call to updateListing to change the type back to "download". I'll add this to our list of things to deal with but unfortunately it won't be right away.

**Comment by yovasx2** [comment]
any eta to deliver this?

**Comment by etsyachristensen** [comment]
I have no ETA unfortunately. The fix for this will be up to our fulfillment team and they are currently busy with other projects.

**Comment by yovasx2** [comment]
any update on this?

**Comment by etsyachristensen** [comment]
We should have a fix out for this very soon.

**Comment by etsyachristensen** [comment]
@yovasx2 This has been fixed. Please let me know if you run into any more problems with it.
