### ISSUE TITLE
[FEATURE]: Add a Route to get all aktive SKU's

### ISSUE THREAD

**Issue by akowi-sknobloch** [etsy/open-api#456]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

We want to be able to synchronize our product catalogue in both directions.
When we remove an Article in the Etsy Webinterface our local Database should synchronize to that.

For that we currently fetch all active Listings and then **for each** Listing it's inventory.
Then we compare the SKU's with the local Database.

For our current product catalogue on Etsy this needs over **400 individual Requests**.
We plan to expand our catalogue by a lot in the near future so this number will increase ;)

### Describe the solution you'd like

I would like a Route that returns all SKU's with the minimal amount of Requests (paging would be ok).
Or include the SKU's with the `findAllActiveListingsByShop` Endpoint.

This would also decrease the amount of Requests the API would have to handle.

**Comment by etsyachristensen** [comment]
@akowi-sknobloch We have added the SKUs and production partner arrays to the `findAllActiveListingsByShop` endpoint.
