### ISSUE TITLE
[BUG]: must be below max price $50,000.00 USD returned even when we don't update price

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

PUT /v3/application/shops/13057046/listings/976687714 is getting 400 error

with next params:
```
params.is_digital | 0
params.is_personalizable | 0
params.item_dimensions_unit | in
params.item_height | 3
params.item_length | 10
params.item_weight | 5
params.item_weight_unit | oz
params.item_width | 7
params.listing_id | 976687714
params.state | active
params.taxonomy_id | 1261
params.type | physical
```

### Steps to reproduce

hit the endpoint with the parameters above

### Expected behavior

to get the update pass

### Additional context

the price is set into the variations so Idk why the update listing endpoint is complaining

**Comment by etsyachristensen** [comment]
@yovasx2 I've deployed a change that I'm hoping will fix this issue. Can you try it again and let me know?

**Comment by yovasx2** [comment]
it's still happening, this is my curl:

```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/13057046/listings/1092950784' \
--header 'x-api-key: xxxxxx' \
--header 'Authorization: Bearer xxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxx.; user_prefs=xxxxxx.' \
--data-raw '{
    "state": "active",
    "taxonomy_id": 1261,
    "item_weight": 5,
    "item_weight_unit": "oz",
    "item_width": 7,
    "item_length": 10,
    "item_height": 3,
    "item_dimensions_unit": "in",
    "production_partner_ids": [],
    "is_digital": false,
    "is_personalizable": false,
    "type": "physical"
}'
```

response:
```
{
    "error": "There was a problem with /price : must be below max price $50,000.00 USD"
}
```

**Comment by etsyachristensen** [comment]
@yovasx2 It seems this is due to the taxonomy id being in there. I'm working on figuring out why, but in the meantime, you can leave that out and it will update properly. We had this problem before and we had fixed it. Not sure why it's cropping up again.

**Comment by yovasx2** [comment]
hey guys, was this fixed?

**Comment by etsyachristensen** [comment]
@yovasx2 We've been trying to find the problem here. I'm curious if this is happening with other listings or if this is an outlier. There's a complication to this in that we can't duplicate the issue in our development area and production edit-ability is heavily restricted so I can't debug the actual listing. We recreated the listing in dev but like I said it's not throwing the error. Our suspicion is that there's something odd about this one listing or the shop itself. This is a really challenging one.

**Comment by yovasx2** [comment]
understood i have seen this in at least 5 different shops

**Comment by yovasx2** [comment]
here is the shop ids identified:

```
--------------------------------------------
| shop_id  | count | @timestamp | @message |
|----------|-------|------------|----------|
| 11096131 | 2175  |            |          |
| 13861920 | 879   |            |          |
| 15654985 | 504   |            |          |
| 18810414 | 18    |            |          |
| 21622583 | 15    |            |          |
| 6133469  | 9     |            |          |
| 12068633 | 3     |            |          |
--------------------------------------------

**Comment by etsyachristensen** [comment]
@yovasx2 Is the count column a count of listings that are having this same problem or just the number of listings in the corresponding shop?

**Comment by yovasx2** [comment]
count is the number of errors seen in that shop (I updated the table)

**Comment by etsyachristensen** [comment]
Ok great thank you! That helps for sure.

**Comment by yovasx2** [comment]
Here are the listing examples belonging to the shops above:
--------------------------------------------
|etsy_shop_id  | etsy_listing_id |
|----------|-------|
| 16237718 | 858140479  |
| 16237718 | 844234052   |
| 16237718 | 754718242   |
| 16237718 | 754725208    | 
| 11096131 | 694856495    |
| 11096131  | 399496361     | 
| 11096131 | 520251782     |
| 11096131 | 281226002     |
| 13861920 | 717030979     |
| 13861920 | 717031373     |
| 13861920 | 1032264691     |
| 13861920 | 1029561759     |
------------------

**Comment by yovasx2** [comment]
I used v3 to update taxonomy to and the error comes, with v2 it passes:
```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/15654985/listings/1232444212' \
--header 'x-api-key: xxxxxxx' \
--header 'Authorization: Bearer xxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxx.; user_prefs=xxxxxxx.' \
--data-raw '{
    "taxonomy_id": 891
}'
```
response:
```
{
    "error": "There was a problem with /price : must be below max price $50,000.00 USD"
}
```


with v2 I got 200

```
curl --location --request PUT 'https://openapi.etsy.com/v2/listings/1232444212?taxonomy_id=891&oauth_consumer_key=xxxxxxx&oauth_token=xxxxxxx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=xxxxxxx&oauth_nonce=xxxxxxx&oauth_version=1.0&oauth_signature=%xxxxxxx%3D' \
--header 'Cookie: uaid=xxxxxxx.; user_prefs=xxxxxxx.'
```

**Comment by etsyachristensen** [comment]
We finally found the problem! Pesky typing issue in the inventory system. We've made a correction and it is now live. Please let me know if it still gives you errors.

**Comment by yovasx2** [comment]
seems to be working for a couple of the mentioned products, thanks a lot
