### ISSUE TITLE
[BUG]: Incorrect count of result when using limit parameter

### ISSUE THREAD

**Issue by fsheedy** [etsy/open-api#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using limit parameter, the count return in the response is invalid

This is maybe related to the fix on #440

### Steps to reproduce

**Incorrect result using limit=1**
https://openapi.etsy.com/v3/application/shops?offset=0&limit=1&shop_name=WithCindyMarie

Result returned:
```
{
  "count": 0, **<-- incorrect count, there is some results**
  "results": [
    {
      "shop_id": 35075647,
      "shop_name": "WithCindyMarie",
...
}
```

**Correct result when not using limit or offset**
https://openapi.etsy.com/v3/application/shops?shop_name=WithCindyMarie

Result returned:
```
{
  "count": 2, **<-- correct, 2 results**
  "results": [
    {
      "shop_id": 35075647,
      "shop_name": "WithCindyMarie",
...
    {
      "shop_id": 35149436,
      "shop_name": "WithCindyMarieStore",
...
}
```

### Expected behavior

Count should equal to the total number of shops ad documented: [findShops](https://developer.etsy.com/documentation/reference#operation/findShops)

**Comment by etsyachristensen** [comment]
@fsheedy A fix has been put into production for this.
