### ISSUE TITLE
[ENDPOINT]: Proposed design change for updateListing

### ISSUE THREAD

**Issue by nmrdxt** [etsy/open-api#461]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Currently, the body schema includes the property 'type'.

### Proposed Endpoint Design Change

Body schema should include 'listing_type' instead of 'type'.

### Why are you proposing this change?

For consistency. Thanks!

**Comment by etsyachristensen** [comment]
This has already been suggested and is on our list of changes to get to. https://github.com/etsy/open-api/issues/398
