### ISSUE TITLE
[BUG]: Updating digital listings results in Server Error if body does not include type => 'download'

### ISSUE THREAD

**Issue by nmrdxt** [etsy/open-api#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It looks like specifying the listing type during updateListing is required for digital listings, but not for physical. Moreover, the error returned appear to be a 500 error and not 400 error.

### Steps to reproduce

updateListing a digital listing with a body that does not include the type of the product.

### Expected behavior

I believe the updateListing body should inherit the current type of the listing, if the 'type' property is missing.

**Comment by etsyachristensen** [comment]
@nmrdxt Can you provide some example listing ids? I'm not able to duplicate this behavior.

**Comment by etsyachristensen** [comment]
@Allen209 I will see if I can duplicate this, but I can tell you that you should NOT use `updateListing` to change the quantity or price. You need to use the `updateListingInventory` endpoint. This will be enforced starting June 6th anyway.
