### ISSUE TITLE
[BUG]: Listing SKU return as numberic

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When getting shop's listings (https://developer.etsy.com/documentation/reference#operation/getListingsByShop) the returned skus property is sometimes numeric instead of string

I will send the details offline in email if required

### Steps to reproduce

1. Invoke getListingsByShop api
2. For some listings, the skus array will contain numeric values

### Expected behavior

All values in result skus array should be of string type

**Comment by etsyachristensen** [comment]
@assaflei We have deployed a correction for this. The listing resource skus should now come out a strings, even if only numbers.
