### ISSUE TITLE
[BUG]: Tracking number is not showing or is not accurate.

### ISSUE THREAD

**Issue by danegigi** [etsy/open-api#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried posting back to Etsy the tracking number using the [createReceiptShipment](https://developers.etsy.com/documentation/reference/#operation/createReceiptShipment). Back to Etsy, it showed that the order was completed but no tracking number is showing. After several tries, I was able to see a tracking number but a new problem arises, the tracking number is showing under a different order.

### Steps to reproduce

Environment Live Test since No Sandbox Available

Sample Request using GuzzleHttp\Client (PHP)
1st Request
$url =  https://api.etsy.com/v3/application/shops/34632576/receipts/2455200512/tracking;
$response = $client->request('post',
$url,
[
  'headers' => [
     'Content-Type' => 'application/x-www-form-urlencoded',
      'x-api-key' => env('ETS_KEY'),
      'Authorization' => 'Bearer ' . some_token_from_etsy,
   ],
   RequestOptions::JSON => [
      "tracking_code" => 9449009898642937571475,
      "carrier_name" => "USPS",
   ]
]);

2nd Request, same just changed the tracking and receipt id
$url = https://api.etsy.com/v3/application/shops/34632576/receipts/2455750484/tracking;
// Note: $client is GuzzleHttp\Client;
$response = $client->request('post',
$url,
[
  'headers' => [
     'Content-Type' => 'application/x-www-form-urlencoded',
      'x-api-key' => env('ETS_KEY'),
      'Authorization' => 'Bearer ' . some_token_from_etsy,
   ],
   RequestOptions::JSON => [
      "tracking_code" => 9449009898642937582624,
      "carrier_name" => "usps",
   ]
]);

### Expected behavior

The tracking number should be posted back to Etsy. Please refer to the image below:

![GrandShipper-2](https://user-images.githubusercontent.com/413985/166916298-fe3c6fbe-ae4c-473d-9535-6abd0b852133.png)

But the tracking is not accurate and the majority of the orders that were marked completed don't have a tracking number even though they should have one as shown below.
![Etsy_-_Sold_Orders](https://user-images.githubusercontent.com/413985/166915936-4bcb6d37-ca42-410b-8ddd-1329f3a9d109.png)

### Additional context

Response Got From Etsy:
array (
  'receipt_id' => 2455200512,
  'receipt_type' => 0,
  'seller_user_id' => ,
  'seller_email' => 'seller@email.com',
  'buyer_user_id' => number_of_number,
  'buyer_email' => 'buyer@email.com',
  'name' => 'name',
  'first_line' => 'Some_address',
  'second_line' => '',
  'city' => 'City',
  'state' => 'STATE',
  'zip' => 'ZIP',
  'status' => 'Completed',
  'formatted_address' => 'name
Address line 1
City, State ZIP 
United States',
  'country_iso' => 'US',
  'payment_method' => 'cc',
  'payment_email' => '',
  'message_from_payment' => NULL,
  'message_from_seller' => NULL,
  'message_from_buyer' => '',
  'is_shipped' => true,
  'is_paid' => true,
  'create_timestamp' => 1651079341,
  'update_timestamp' => 1651742878,
  'is_gift' => false,
  'gift_message' => '',
  'grandtotal' =>
  array (
    'amount' => 65,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'subtotal' =>
  array (
    'amount' => 60,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'total_price' =>
  array (
    'amount' => 60,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'total_shipping_cost' =>
  array (
    'amount' => 0,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'total_tax_cost' =>
  array (
    'amount' => 5,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'total_vat_cost' =>
  array (
    'amount' => 0,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'discount_amt' =>
  array (
    'amount' => 0,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'gift_wrap_price' =>
  array (
    'amount' => 0,
    'divisor' => 100,
    'currency_code' => 'USD',
  ),
  'shipments' =>
  array (
    0 =>
    array (
      'receipt_shipping_id' => NULL,
      'shipment_notification_timestamp' => 1651742878,
      'carrier_name' => '',
      'tracking_code' => '',
    ),
  ),
  'transactions' =>
  array (
    0 =>
    array (
      'transaction_id' => 2990374249,
      'title' => 'GrandShipper Test Product *Please do not buy*',
      'description' => 'This is a test product.

Please DO NOT BUY!  The transaction will be canceled.

Thank you!',
      'seller_user_id' => user_id,
      'buyer_user_id' => number_of_number,
      'create_timestamp' => 1651079341,
      'paid_timestamp' => 1651079358,
      'shipped_timestamp' => 1651742878,
      'quantity' => 3,
      'listing_image_id' => 3749301425,
      'receipt_id' => 2455200512,
      'is_digital' => false,
      'file_data' => '',
      'listing_id' => 1173572782,
      'sku' => 'SKU888',
      'product_id' => 9141496930,
      'transaction_type' => 'listing',
      'price' =>
      array (
        'amount' => 20,
        'divisor' => 100,
        'currency_code' => 'USD',
      ),
      'shipping_cost' =>
      array (
        'amount' => 0,
        'divisor' => 100,
        'currency_code' => 'USD',
      ),
      'variations' =>
      array (
      ),
      'product_data' => NULL,
      'shipping_profile_id' => 172307102898,
      'min_processing_days' => 1,
      'max_processing_days' => 3,
      'shipping_method' => NULL,
      'shipping_upgrade' => 'Free shipping (USPS Media Mail)',
      'expected_ship_date' => 1651742878,
    ),
  ),
)

**Comment by etsyachristensen** [comment]
@danegigi To answer your concern about the tracking code being on the wrong receipt, that was from me testing your inputs the other day.

I think the format of the data coming into our system isn't formatted properly. I think it may be the RequestOptions::JSON that's doing it. The two parameters need to be passed in as post variables.

**Comment by danegigi** [comment]
hey @etsyachristensen, thank you so much for your big help. It works. Update the code and use form_params and it works.
