### ISSUE TITLE
[BUG]: Server Error on listing update

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Executing partial listing update for certain listings fails with status code 500 and message 'Server Error'. The issue occurs only for some listings from some shops. The issue is consistent - a listing cannot be updated no matter how many times I execute the request.

### Steps to reproduce

Execute a PUT request to this endpoint:
https://openapi.etsy.com/v3/application/shops/22006962/listings/1212362248

The body of the request contains only the following fields with correct non-empty values:
- title
- tags
- description

### Expected behavior

I expect the request to succeed. If there is an actual problem, I expect to receive a Bad Request error with some error message.

**Comment by chucuoinb** [comment]
Did you get any updates? Until now I still get this error

**Comment by VasilVelikov** [comment]
@chucuoinb Unfortunately I haven't heard anything yet.
The interesting thing in my case is that it happens only for some listings. For the majority of listings the update works as expected.

**Comment by etsyachristensen** [comment]
@VasilVelikov and @chucuoinb I will need to know the listing ids that are affected by this as well as the payloads you are sending to those listings so I can try to duplicate the issue on our end.

**Comment by VasilVelikov** [comment]
Hi @etsyachristensen ,
Sorry for the late reply but I have missed your message.

To reproduce send PUT request to https://openapi.etsy.com/v3/application/shops/22006962/listings/1234181138 with body with the following data:

- 'title' : 'Happy Halloween Tumbler, Halloween Png, Skinny Tumbler Svg, Best Selling Png, 20 Oz Tumbler Wrap'
- 'description' : 'Happy Halloween Tumbler, Halloween Png, Skinny Tumbler Svg, Best Selling Png, 20 Oz Tumbler Wrap\n\nThese are digital files of printable png downloads - no physical product will be shipped!\n\nBuy 2 get 3. Apply coupon code 3FOR2 on checkout. Items must be purchased together for a discount\nBuy 10 with 50% OFF. Apply coupon code 10SHOP on checkout. Items must be purchased together for a discount\n\n◆What you will receive:\n•2 PNG files \n•very high resolution of 300 dpi\n\n◆Size:\n20 oz\n\n◆Two available shapes:\n20 oz Tapered\n20 oz Straight\n\nThere is no watermark on the original file!\n\nThe image can be resized to fit whatever project you require it for, you\'re not limited to just skinny tumblers! \n\n◆ How to manage:\nYou will receive your file immediately after purchase. Please make sure you have the required software and knowledge to use this graphic before making your purchase. You can manage my products on a laptop or computer, using graphic software such as Photoshop, Illustrator, or free alternatives such as Gimp or Picasa.\n\n◆ Commercial use:\nIf you would like to print transfers, please see the \'Commercial License Listing\' on the main shop page. Credit is not required for small commercial use.\nOne license applies for one item.\n\n◆ Copyright\nBuying an artwork doesn\'t transfer its copyrights.\n\nRefunds are not available on digital downloads.\n\nAll designs are the intellectual property of Titi Pretty Art and may not be copied, distributed, shared, or resold.\n\nThank you for choosing Titi Pretty Art!'
- 'tags' : '20 oz tumbler wrap,best selling png,gothic tumbler wrap,halloween png,halloween png files,halloween tumbler,happy halloween,horror tumbler,scary doll svg,scary tumbler wrap,skinny tumbler svg,tumbler designs,tumbler png'

Note that the issue should be reproducible for any listing from the same shop and any description.

**Comment by namlv94** [comment]
i still get this error too. Looks like it's still unresolved

**Comment by VasilVelikov** [comment]
It is hard to experiment on my side because these are third party listings and I can't risk changing them by mistake.
However, I am 99% sure that the change doesn't go through and a subsequent getListing would return unchanged values.

**Comment by VasilVelikov** [comment]
This is great, everything works as expected now. Thanks for the quick fix!
P.S. I love your continuous deployment flow :)
