### ISSUE TITLE
[FEATURE]: Add item price and discount information to getReceipt endpoint data

### ISSUE THREAD

**Issue by thisisjake** [etsy/open-api#475]
### Is there an existing issue for this?

- [x] I have searched the existing tickets

### Current Endpoint Design

There is presently no ability to determine how much an individual item was sold for when one or more discount(s) are applied.

When an order only contains one product it is easy to determine this as it is a simple math problem. If however an order includes two different products it becomes less clear, particularly if those two products have the same regular price.

In addition since we can't determine what coupon the customer used as it is not provided with the API, we can't implement a method of determining which items were discounted.

### Proposed Endpoint Design Change

getShopReceipt should ideally provide a per item price that an individual item has been sold for, it should also provide a coupon.

If both can't be provided, at least providing one would help to resolve this problem.

### Why are you proposing this change?

It's important from an accounting and sales tracking/forecasting perspective to understand how much each product sells for at an item level. At present, we are manually calculating this information and then inputing it into our database which breaks up what should be an automatic process.

**Comment by thisisjake** [comment]
Hello,

It's been about two weeks since this was posted, any chance of a response?

Thank you.

**Comment by etsyachristensen** [comment]
Apologies @thisisjake. I added it to our queue of issues to review and resolve. I just haven't be able to get onto this one yet.

**Comment by thisisjake** [comment]
@etsyachristensen no problem, thanks for letting me know it's in the queue. Appreciate it.

**Comment by etsyachristensen** [comment]
I have added `buyer_coupon_discount` and `shop_coupon_discount` to the transaction object in the receipts. The transaction represents a specific product so the discount amount represents the amount discounted on that specific product in the receipt.

**Comment by thisisjake** [comment]
@etsyachristensen thank you, much appreciated.

**Comment by Esatyilmaz0** [comment]
> I have added `buyer_coupon_discount` and `shop_coupon_discount` to the transaction object in the receipts. The transaction represents a specific product so the discount amount represents the amount discounted on that specific product in the receipt.


Hi i don't access this property why?
