### ISSUE TITLE
[BUG]: Empty `product_data` in the `getShopReceipts` endpoint

### ISSUE THREAD

**Issue by main24** [etsy/open-api#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`product_data` attribute of orders transactions provides original (not formatted) options and values of the ordered variations which helps with identifying the variation strictly rather then using fuzzy match on formatted values (as id of variations are being changes with every inventory update) and avoid unnecessary calls to API. As a result it helps to make sure that imported orders contain correct products for further fulfillment and manage products inventory (i.e. available quantity) correctly.

This attribute is presented in V2 list orders endpoint response. [Recently](https://github.com/etsy/open-api/issues/254) it has been added to the `getShopReceipt`. According to the [documentation](https://developer.etsy.com/documentation/reference/#operation/getShopReceipts) this attribute should appear in the `getShopReceipts` as well, however it is blank there (although it's not blank in the `getShopReceipt` response).

Is it possible to return `product_data` in the `getShopReceipts` the same way as it's done for `getShopReceipt`?

Thanks in advance.

### Steps to reproduce

1. Create an order;
2. Request a list of orders via `getShopReceipts` of V3 API;
3. Check order transactions: `product_data` is null there.

Not providing a specific order ids here as it isn't related to a specific order -- any order can be chosen.

### Expected behavior

`product_data` should contain inventory data of the ordered variation, the same way as it is implemented for `getShopReceipt` endpoint and according to the [documentation](https://developer.etsy.com/documentation/reference/#operation/getShopReceipts).

**Comment by etsyachristensen** [comment]
This should be doable @main24 . I've added it to our list of development tasks.

**Comment by main24** [comment]
Thank you @etsyachristensen, really appreciate that!

**Comment by etsyachristensen** [comment]
This has been added @main24 .

**Comment by main24** [comment]
Great news, huge thank you @etsyachristensen!
