### ISSUE TITLE
[FEATURE]: View scopes

### ISSUE THREAD

**Issue by DemiImp** [etsy/open-api#477]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I just ran into an issue where Etsy gave back an error "insufficient_scope" when trying to add an image.  I honestly don't know how that's possible, since we've always have requested the **listings_w** scope.

So to help debug the issue, I wanted to catch "insufficient_scope" errors and query the scopes the token has access to.  This is not a feature in v3.  Because of this, I have no way of determining whether the error I received is:

1. an API bug (aka: we DO have listings_w permission and erroneously got "insufficient_scope" error)
2. an [API v2 to v3 upgrade bug](https://github.com/etsy/open-api/issues/450)
3. or that somehow the token just does not have the listings_w permission (both in v2 and v3)

### Describe the solution you'd like

I would like an API request that returns all the scopes that the token has access to.

### Describe any alternatives you've considered

The only other alternative I can think of is to start making API requests without the express permission of the users encountering the issues -- and potentially changing their shops -- just to help me figure out what permissions we actually have access to.  That is a breach of trust, probably against the API terms, and is just a pretty awful solution for everyone involved (including Etsy).

**Comment by etsyachristensen** [comment]
This endpoint has been created. https://developers.etsy.com/documentation/reference/#operation/tokenScopes

**Comment by diogogomeswww** [comment]
@etsyachristensen is this endpoint on production?

We're having the same problem. Getting insufficient_scope errors after exchanging the v2 for v3 tokens.

**Comment by DemiImp** [comment]
@etsyachristensen - Thank you so much for implementing this endpoint so quickly!

Could you update the API documentation's Response Sample to include a response sample?

I was surprised to find out v3 uses a POST instead of a GET.  Is that intentional?  Usually POST is for creating/setting and GET is for retrieving data.  API v2 uses a GET.

**Comment by etsyachristensen** [comment]
Yes. It is a POST endpoint because you can't pass the token as a get input parameter with our architecture. For security sake, it will get stripped off. A post is more secure.

Unfortunately, the documentation is auto-generated. Because this endpoint returns nothing more than an simple exploded array of strings, it doesn't know what to generate. An example would be:
```
{
    "scopes": [
        "email_r",
        "listings_r",
        "listings_w",
        "listings_d",
        "transactions_r",
        "transactions_w"
    ]
}
```

**Comment by etsyachristensen** [comment]
For security reasons, once the request has passed through the gateway, we don't have access to the access token in the header. Thus we have to have it as a form input.

**Comment by DemiImp** [comment]
Ah, that's what you meant.  I understand now.  Thank you.

**Comment by diogogomeswww** [comment]
@etsyachristensen thank you for your quick reply and for the new endpoint.

Just one more question:
I can retrieve ShippingProfiles with my V2 token and using the v2 endpoint.
Using the v3 token (by using the endpoint to exchange the v2 token to v3 token) on the get shipping profiles endpoint is returning an `insufficient scopes` error.

Is this a bug?
I should have the same scopes, right?
