### ISSUE TITLE
[DOCS] incorrect email address provided to submit whitelisted URLs for redirect

### ISSUE THREAD

**Issue by turboturtleD** [etsy/open-api#48]
Haven't had much luck getting in touch with developer@etsy.com anyway, but the wrong email is actually listed here:

https://www.etsy.com/developers/documentation/getting_started/oauth2#section_redirect_urls

(it is suggested developer**s**@etsy.com is the correct address) It's possible I'm mistaken, but when I tried to use that email address I just got a bounce.  The href link is also incorrect.

**Comment by capndesign** [comment]
Thanks for writing in! First, that `href` is definitely broken. We’ll get it fixed!

You are right that `developer@etsy.com` is the address we’ve been using. As of yesterday, we put in an alias to point all email sent to `developers@etsy.com` to the correct address. I just tested it with my external email account and it seems okay. Are you seeing the same thing?

**Comment by turboturtleD** [comment]
I'm still have not received any emails back from developer@etsy.com or developers@etsy.com.  I've sent daily emails for about two weeks (the same email), so.... just gonna close this one, but it's hard to help dev with you guys if you don't answer your email.
