### ISSUE TITLE
[DOCS]: Receipt Object - Status Enum Inconsistency

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference/#operation/getShopReceipts

### What would you like to change?

In the description of the receipt object, there are two lists of possible statuses.

Enum: "paid" "completed" "open" "payment processing" "canceled"
The current order status string. One of: Open, Paid, Completed, Payment Processing.

The second list does not have a "canceled" status listed in it. Why is that?

### Why are you proposing this change?

This may be a typo and one of the lists of statuses needs to change. In this case, I propose that the typo be corrected.

Or, if this is not a typo, I propose that the difference between these two lists be explained.

**Comment by etsyachristensen** [comment]
@NathanConroyOrd You are correct. That's a documentation error. That said, we are looking at adding canceled orders to the output. Not sure when that will happen. In the meantime, I'll take a look at the documentation.

**Comment by etsyachristensen** [comment]
@NathanConroyOrd I misspoke. We already have the canceled status in there. It was just left out of the documentation for the input type. We'll fix the docs.

**Comment by NathanConroyOrd** [comment]
Thank you!

**Comment by sowsinsk** [comment]
Regarding receipt statuses, it would also be helpful to have an explanation for what each status means (or when it would occur). For example, what is the difference between an "open" order and a "paid" order?

Thank you!
