### ISSUE TITLE
[DOCS]: Details on Receipt Statuses

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference/#operation/getShopReceipts

### What would you like to change?

In the description of a 200 response from the getShopReceipts method, an enum is given listing the possible receipt statuses.

I can't find a detailed description of what each receipt status means and how one status can change into another. For instance, the difference between `paid` receipts and `open` receipts isn't clear to me. And how can a `paid` receipt become an `open` receipt (or vice-versa)?

Would Etsy add these details to the docs? Or if the details are documented somewhere else, would it be possible to link to it in the response description?

### Why are you proposing this change?

It would help in understanding the API and how to design a system to use it.

**Comment by etsyachristensen** [comment]
We can work on adding something, but the `open` status means an order that is placed, but not yet paid. This likely won't happen unless the seller has some offline method of payment. I'm honestly not sure if this is even possible anymore so it may just be legacy.

Orders typically start out as 'open', then go to 'payment processing' (which again is a very short-lived status), to `paid` and finally to `completed` once shipped.

At the moment, there is no mechanism for 3rd party apps to change the order status. Stores do have the ability to create custom order statuses and they are able to change orders to those statuses via the Etsy UI. We are investigating the possibility of adding the ability to change status to those custom statuses, but there's no timeline on that at the moment.

**Comment by NathanConroyOrd** [comment]
Thank you!

**Comment by NathanConroyOrd** [comment]
@etsyachristensen 

This leads me to another question. For users who are migrating from the v2 API to the v3 API, it would be helpful to know the definitions of the v2 receipt statuses as well.

As far as I can tell, v2 receipt statuses are listed here https://www.etsy.com/developers/documentation/reference/receipt#method_findallshopreceiptsbystatus, but I cannot find exactly what these statuses mean. For instance, what's the difference between an `unpaid` receipt and an `open` one here? Is the v2 `open` receipt status equivalent to the v3 `open` receipt status?

Thank you!

**Comment by etsyachristensen** [comment]
This was done a while back. Sorry for not updating the ticket. The definitions are here: https://developers.etsy.com/documentation/essentials/definitions

**Comment by atvvarna** [comment]
Hello,

as stores can create custom order statuses trough Etsy UI, is it possible to get list of all shop statuses and sort the orders by those statuses.
For example client have 'In progress', 'Done' statuses and I would like to sort the orders by 'Done'.

**Comment by Gareth064** [comment]
@atvvarna I can't find it now, but I'm certain there was an issue or discussion which talked about the custom statuses and Etsy said they have no plans to allow them to be returned in the API

**Comment by atvvarna** [comment]
@Gareth064 sad to hear that.
Do you know of any option where I can sort the orders by those custom statuses (if I know the exact status value)?

**Comment by Gareth064** [comment]
@atvvarna unfortunately the custom statuses aren't included in the response from any endpoint. The API has no idea they exist.

**Comment by atvvarna** [comment]
Sad to hear that as it's esential for stores that creat the product after the order is placed (most hand made stores).

**Comment by Gareth064** [comment]
Yep. This is how my wife's business works too.
To combat this lack of data from the API, I am ignoring the custom statuses in Etsy and building a Status/Workflow into my app (I'm building her) so she manages her orders in my app and moves them along with statuses defined by my app.

**Comment by atvvarna** [comment]
@Gareth064
I was thinking in doing the same but most of our clients want to use both APP and Etsy UI.
Hope Etsy devs make it available soon.
