### ISSUE TITLE
[DOCS]: Details on getShopReceipts `was_paid`, `was_shipped`, `was_delivered`

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference/#operation/getShopReceipts

### What would you like to change?

For the v3 API's getShopReceipts method, one can filter receipts by these three boolean flags:
```
was_paid - When true, the seller recieved payment for the product(s) in this receipt.
was_shipped - When true, the seller shipped the product(s) in this receipt.
was_delivered - When true, returns receipts that have been delivered.
```

I'd like more detail on two things:

1. Is it meaningful to set these flags to `false`? So that, for example, `was_paid=False` returns all unpaid receipts.
2. Does `was_paid=True` include also shipped and delivered receipts? If that is the case, to get receipts that were paid but not shipped, should I pass in `was_paid=True` and `was_shipped=False`? And to get receipts that were shipped but not delivered, should I pass in `was_shipped=True` and `was_delivered=False`?

### Why are you proposing this change?

It's not entirely clear what to expect in the API response.

**Comment by etsyachristensen** [comment]
@NathanConroyOrd We have updated the documentation. These are considered to be one or the other or neither. So when false, will only return receipts where that field is false. They are considered AND clauses as well so if all three are false, it would be receipts where NOT paid AND NOT shipped AND NOT delivered. Hope that helps.
