### ISSUE TITLE
[BUG]: Open Api v3 updateListing 500 Server Error

### ISSUE THREAD

**Issue by namlv94** [etsy/open-api#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Open Api v3 updateListing 500 Server Error

### Steps to reproduce

update draft product with api: https://developers.etsy.com/documentation/reference/#operation/updateListing.
data body: 
{"title": "simple product123", "description": "sdfds", "tags": "", "item_weight": 0, "item_length": 0, "item_width": 0, "item_height": 0, "item_weight_unit": "kg", "item_dimensions_unit": "in", "who_made": "collective", "when_made": "2020_2022", "is_supply": false, "taxonomy_id": 1429, "shop_section_id": null, "shipping_template_id": 134338378153}

### Expected behavior

response with status code 200

**Comment by etsyachristensen** [comment]
@chucuoinb Are you passing in the blank tags field to remove tags? And the dimension fields are all zeros. Is that intentional? If so, the listing will have to be a fixed shipping profile. Also, in v3, the field is `shipping_profile_id` not `shipping_template_id`.

**Comment by assaflei** [comment]
Hi, @etsyachristensen I encountered similar behavior now with a listing I try to update
I only send description, listing_id and state (changing state from edit to active)

These are the result headers that might allow further tracing..
x-cloud-trace-context:
'6bee13d4761852d8556a59cbcd655d88/5888947654427419131;o=0'
x-etsy-request-uuid:
'Eu_enU4cPeKTA8e0TS531iWIUv0f'

Can you advice?

**Comment by assaflei** [comment]
@etsyachristensen appreciate your response here..

**Comment by etsyachristensen** [comment]
@assaflei What is the listing id? I looked at this yesterday (from memory) and the error returned was that it could not transition from edit to active. There's something with the listing preventing it from being activated. I don't recall what that was and now the uuid isn't appearing in our logs (we only have 7 days retention available). Do you have a more recent UUID and listing id?

**Comment by etsyachristensen** [comment]
Disregard that. Sorry. I forgot to change the date range in the logs. Doh!

The listing can't be renewed because the shop is currently in vacation mode.

**Comment by assaflei** [comment]
@etsyachristensen Issue hasn't been resolved yet, are you familiar with that?

**Comment by etsyachristensen** [comment]
has the shop been taken out of vacation mode?

**Comment by assaflei** [comment]
No its still in that mode

**Comment by etsyachristensen** [comment]
Ok. I will work on getting it to not return a 500 error, but it won't allow updating the listing when in vacation mode.

**Comment by assaflei** [comment]
Preventing updates is fine and expected,
Thanks
