### ISSUE TITLE
[BUG]: Property with PK does not exist

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes, when invoking [this API](https://developers.etsy.com/documentation/reference/#operation/getListingsByShop) for inactive listings (state: inactive) I get this error response: 
{statusCode: 404, data: {error: Property with PK .... does not exist} (I can share the PK value offline)
Can you explain what is the meaning of this error?

### Steps to reproduce

Invoking [this API](https://developers.etsy.com/documentation/reference/#operation/getListingsByShop) for inactive listings (state: inactive) for any shop

### Expected behavior

A list of inactive listings (if exist) will be returned

**Comment by etsyachristensen** [comment]
@assaflei I will need the shop ID where this occurring. I'm not able to duplicate it on our end. That error indicates that the primary key association for that property is not pointing to a valid record in another table. I'll need to go through the inactive listings for the shop to find out which listing is doing it. The PK id isn't a private detail and would be meaningless to anyone else so you can feel free to share it here. It will help to have that value as well as the shop ID. Thanks.

**Comment by nmrdxt** [comment]
Happens here as well, the same PK value (17521439), first noticed it 4 days ago, but in the last 24 hours it has been exploding. I'm seeing this error returning for various endpoints, for many shops.
