### ISSUE TITLE
Existing From Developer Mode

### ISSUE THREAD

**Issue by AyseBusraKoc** [etsy/open-api#488]
I have accidentally take my Etsy shop HANDEAVOUR to developer mode while I was trying to get an API code for a separate app for a standalone website.

Can you please remove me and my shop out of developer mode, I have spent a week now sitting in  Pending status and despite my numerous emails and complaints to devoloper team or help team no one is answering! I am losing sales and time by not being viewed in search. Please take my shop HANDEAVOUR from developer mode to normal sale mode, and de-indexed my shop again on Etsy.

Best regards.

**Comment by AyseBusraKoc** [comment]
I meant "index my shop again on Etsy". Sory about this.

**Comment by etsyachristensen** [comment]
@AyseBusraKoc I've turned this over to our support team to review. Not sure why you haven't had a response yet, but as the API team, we don't have the permissions to change app statuses or limits. We have to turn those requests over to the support team. You should hear back shortly.

**Comment by AyseBusraKoc** [comment]
My problem is solved last night. Thank you very much for your precious interest and support. 
Best regards.
