### ISSUE TITLE
[FEATURE]: Support for Etsy Pattern (aka channels)

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#489]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I can't tell if this is a documentation issue or something missing from the API. How can we specify channels when publishing or updating listings?

I'd like to be able to create listings that are Pattern-only. Or update draft listings to put them in Pattern.

### Describe the solution you'd like

Perhaps some parameter to create/update listing that allows channels to be specified?

**Comment by etsyachristensen** [comment]
Pattern has been removed from API support. OpenAPI V3 does not allow you to create/update listings in Pattern. This can only be set via the Etsy Shop Manager.

**Comment by stickfigure** [comment]
Can you give us some idea of where Etsy is going with that? Is this something to be supported by the API in the future, or is Etsy winding down Patterns? 

We just discovered Patterns recently. It actually seems pretty cool as a Shopify replacement and could be of interest to our merchants, but I can't really tell if this is viable or a good idea.

**Comment by etsyachristensen** [comment]
We truly appreciate your interest in Pattern. We are evaluating the feedback and are considering it as part of our product roadmap.
