### ISSUE TITLE
[ENDPOINT] Add country to getShop response

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#49]
**Current Endpoint Design**
It would be good to know where the shop is based. eg. US, UK, DE, etc

**Proposed Endpoint Design Change**
Add `country` to the response.

**Why are you proposing this change?**
For comparing shops that a local and abroad. Some of our customers have expressed difficulty in competing with other shops on price point. If we can help them understanding the location of other shops, we can help them with pricing their products. While this info is easy to gather from the public site, it would be great to expose in the API too (save our customers a few clicks) and gives us the ability to do a lot more for sellers.

**Comment by harjas** [comment]
Hi @benjymouse! Thank you for this suggestion. We'll look into this and get back to you soon!

**Comment by benjymouse** [comment]
I see `shop_location_country_iso` and its working nicely, thanks guys.
