### ISSUE TITLE
[FEATURE]: Tariff number in Api

### ISSUE THREAD

**Issue by chucuoinb** [etsy/open-api#490]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Recently I am developing an app for shop owners. And I really need to work with the Tariff number field. But I don't find it in the API, am I missing something?
https://prnt.sc/h2qKSQ3Iy1Ec

### Describe the solution you'd like

I hope Etsy can add a Tariff number to the API

**Comment by etsyachristensen** [comment]
At this time, we are not planning to add the tariff information to the OpenAPI.
