### ISSUE TITLE
[DOCS]: Links in reference OAS documentation are outdated

### ISSUE THREAD

**Issue by jon-chambers** [etsy/open-api#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/reference/

### What would you like to change?

Click all the links. Most of them don't go where you'd expect them to. Many of them link back directly to where themselves.

### Why are you proposing this change?

I keep clicking these links thinking I'll get clarification on their meaning, but instead I'm redirected to the page I'm already on.

**Comment by etsyachristensen** [comment]
@jon-chambers - I'm just adding some comments here for internal issue tracking. If you have any other examples, please feel free to add them.

**Some examples:**
- In `createDraftListing` endpoint docs, the shipping_profile_id description has a link to Shipping Profile, but it needs to be updated.
- Same issue in `getShopShippingProfile` and other Shop Shipping Profile endpoints.

**Comment by etsyachristensen** [comment]
@jon-chambers These links have been corrected. Thanks again for pointing those out!
