### ISSUE TITLE
[FEATURE]: auto-renew should make more sense

### ISSUE THREAD

**Issue by jon-chambers** [etsy/open-api#493]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

"should_auto_renew | booleanWhen true, renews a listing for four months upon expriation. If set to true when previously false, etsy.com renews the listing before it expires, but the renewal period starts immidiately rather than extending the listing's expiration date. Any unused time remaining on the listing is lost. Renewals result in charges to a user's bill."

### Describe the solution you'd like

Spelling mistakes aside... what?

The renewal period starts... when?

IMMEDIATELY!?

Why?

When answering, forget backend limitations. Whatever system you're dealing with, you shouldn't have such limitations, or you should be better at hiding them. In code, anything is possible. Often messy, but always possible.

Think of this from an artist's perspective. They've got a painting for sale, previously they wanted to not auto-renew, but two days have past and they've changed their mind. They come to you, a customer service representative of Etsy, and apologise for the previous error, but they have decided that auto-renew IS the best way forward. They'd just like to undo that error that was made during creation, and have it auto-renew just before it expires.

And here you are, representative of Etsy, the intelligent, fair, and just platform, that always charges artists exactly what they should pay, and not a cent more. You are ready to explain to this artist, who knows nothing about how computers work, what the auto-renew policy is, and why it is so.

Explain.

### Additional context

I lied. 

I didn't search the existing tickets. I'm not even on payroll. What are you going to do? 

Fire me? 

Ignore my suggestions?

I don't even own shares in Etsy. I don't care if you guys fail. I owe you nothing.

Searching existing tickets is your job. Not mine.

If you ban me from posting feedback, that's probably for the best. I waste too much of my workday writing this stuff anyway.

**Comment by Gareth064** [comment]
What a dumb way to ask something. No-one is going to listen to you when you write messages like that. This is a technical place to discuss a technical API layer on top of a very old and complex system. No-one needs you to write a story then get super defensive/passive aggressive before anyone from Etsy gets a chance to respond to you story.

**Comment by jon-chambers** [comment]
I don't care anymore. So long as my competitors are struggling with this also, it gives me the competitive advantage against them.

This isn't even an issue I want fixed. My backend is fully automated. I'm not going to make mistakes like forgetting to auto-renew. So it's in my best interest that you keep this bug in.

I'm not asking for anything. Make a note to never fix this. It doesn't bother me. It's just all the other users on Etsy I'm feeling sorry for.

I am not your co-worker, I am Etsy's client. A worn out client that has just spent a full day migrating from V2 to V3, and I'm still not even close to finished. My sales contribute to the pool of money that pays your wages.

I notice a problem that is costing Etsy reputation and sales, but I'm not allowed to report it until I do some homework first? Forget it! Keep the bug in! I'm over this!
