### ISSUE TITLE
[ENDPOINT]: Proposed design change for getPropertiesByTaxonomyId

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#494]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Currently, you are able to send values and value_ids for a specific property, let's say **craft type** (**47626759760**) this is restricted in the UI to **max 5 values selected**, but in the API there is no property indicating this limit neither the put property endpoint is limiting the number of values accepted (i have hit this with **6 values**). this lead to a problem in the UI because the UI gets in an inconsistent state marking an error due to the excess of values selected (**6 values**)

Put properties request:
```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/18976342/listings/1230249643/properties/47626759760' \
--header 'x-api-key: xxxxxxx' \
--header 'Authorization: Bearer xxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxx.; user_prefs=xxxxxxx.' \
--data-raw '{
    "value_ids": [533,541,542,547,532,550],
    "values": ["Bookbinding","Collage", "Crewel", "Doll making", "Dyeing & batik","Embroidery"]
}'
```

get listing properties response:
```
{
    "count": 1,
    "results": [
        {
            "property_id": 47626759760,
            "property_name": "Craft type",
            "scale_id": null,
            "scale_name": null,
            "value_ids": [
                550,
                541,
                532,
                542,
                533,
                547
            ],
            "values": [
                "Embroidery",
                "Collage",
                "Dyeing & batik",
                "Crewel",
                "Bookbinding",
                "Doll making"
            ]
        }
    ]
}
```

UI error after loading the listing:
<img width="680" alt="Screen Shot 2022-05-27 at 16 15 12" src="https://user-images.githubusercontent.com/3578401/170790376-4cf28c3c-0a64-4c4a-98c6-5c9645c79df6.png">

### Proposed Endpoint Design Change

include a number indicating the limit per property in the property endpoint:
[getPropertiesByTaxonomyId](https://developers.etsy.com/documentation/reference/#operation/getPropertiesByTaxonomyId):
```
{
"property_id": 1,
"name": "string",
"display_name": "string",
"scales": [],
"is_required": true,
"supports_attributes": true,
"supports_variations": true,
"is_multivalued": true,
"possible_values": [],
"selected_values": [],
"max_items_selected": 5
}
```

### Why are you proposing this change?

UI problems and inconsistencies, corrupted listings

**Comment by etsyachristensen** [comment]
Good catch @yovasx2. Just to make sure I'm on the same page with you, are you talking about calling `updateListingProperty` endpoint where you're able to add more values/value ids to a listing property than the UI allows? I think the solution will be to add a hard-set limit of 5 value/value id combos per property per listing and have the documentation reflect that. I don't know that we need to have the get endpoints for the taxonomy return any max counts since we'll have the limit reflected on the update endpoint.

**Comment by yovasx2** [comment]
you got the problem but I think hard code it to 5 is arbitrary, some attributes are having a limit of 3 some 5, it varies, API v2 is giving an option called **maximumValuesAllowed**:

Endpoint: https://openapi.etsy.com/v2/taxonomy/seller/get

```
"isRequired": true,
"displayName": "Craft type",
"maximumValuesAllowed": 5,
"version": "3b39b4a",
"taxonomyNode": 6246,
"userInputValidator": null
```

**Comment by etsyachristensen** [comment]
Oh ok I see. I've never seen that max allowed values. I'll have to find out what that's all about and make sure we address this.

**Comment by etsyachristensen** [comment]
There is now a `max_values_allowed` data point in the array for the properties.

**Comment by amitshuklaCedcoss** [comment]
> There is now a `max_values_allowed` data point in the array for the properties.

@etsyachristensen can u make it little more clear that this new index (**max_values_allowed**)  will only work when any attribute is **is_multivalued**  or it will ve applied always?
![image](https://user-images.githubusercontent.com/25526103/172820669-1d5d4b71-0a34-4d37-865e-8fbc402f0b64.png)

thanks

**Comment by yovasx2** [comment]
please reopen this because for 11245 taxonomy the value is null instead of 5, @etsyachristensen
