### ISSUE TITLE
[BUG]: getShopByOwnerUserId returning a single shop but user can have many shops

### ISSUE THREAD

**Issue by diogogomeswww** [etsy/open-api#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An user can have many shops, so this endpoint should return an array of Shops, instead of a single Shop.
The V2 endpoint `getUser` with the `includes=Shops` returns an array of shops.

How can I retrieve all shops own by an user?

### Steps to reproduce

Call the endpoint: getShopByOwnerUserId
https://developers.etsy.com/documentation/reference/#operation/getShopByOwnerUserId 

### Expected behavior

Receive an array of Shops.

**Comment by etsyachristensen** [comment]
@diogogomeswww I can't really speak to what the V2 `getUser` endpoint was doing for you. But I can say that Etsy policy is that any single user can only have 1 shop. The user can create separate user accounts under different email addresses but that still only leaves one shop per user. If you were somehow able to get multiple shops per user in V2, you won't be able to in V3.
