### ISSUE TITLE
[BUG]: Cannot get user shops list

### ISSUE THREAD

**Issue by nikolajevs86** [etsy/open-api#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We cannot get shops list of some users. For example, for user: 648736420 it returns an error:
{
    "error": "Could not find a shop for user with user_id = 648736420"
}

It seems like the store does not exist at all or the store is the draft state.
Is it possible to know what is the reason and it is for example in the draft state, then return specific error message or error code?

### Steps to reproduce

1. Execute query to GET {{baseUrl}}/v3/application/users/648736420/shops
2. Error received

### Expected behavior

If the problem is that store is in the draft state then ideally it would be expected to get shop details with a field that it is not active yet.
Or if it was not created at all, then return an empty list [].

**Comment by daryayermakova** [comment]
@etsyachristensen Thanks for your description. 
We would like to know a bit more. Before certain time draft shops were returned in the response. Could you say when it was changed and for what purpose? Or was it for v3 always?
And when you say `disabled` do you mean draft shop (shop with not finished first activities to be active, like add payment and so on)?

Additional user id example for checking (if they have the shop at all): 
648722366

**Comment by etsyachristensen** [comment]
@daryayermakova I just checked that other user id. It does have a shop but it has not yet been confirmed:
![image](https://user-images.githubusercontent.com/83842847/174128370-756de050-bc84-40d3-bd2f-f3d4b4683aa3.png)

I've checked our code and there has not been any change to the system for returning shops. I am able to call `getShop` on both of those two shops: 36116546 (user id 648722366) and 648736420 from your original post. They do show up just fine.

Are you still having issues fetching these shops?

**Comment by daryayermakova** [comment]
@etsyachristensen 
If I execute query to `GET {{baseUrl}}/v3/application/users/648722366/shops` I get the error response
```
{
    "error": "Could not find a shop for user with user_id = 648722366"
}
```
But the request `GET {{baseUrl}}/v3/application/shops/36116546` returns the shop data

**Comment by etsyachristensen** [comment]
Ok this is fixed!
