### ISSUE TITLE
[DOCS]: Listing Response State Field Enum Unclear

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/getListing

### What would you like to change?

For the 200 response schema for the
```
GET /v3/application/listings/{listing_id}
```
endpoint, the docs say this about the `state` field:

```
Enum: "active" "inactive" "sold_out" "draft" "expired"
An enumerated string from any of: active or inactive. Note:
Setting a draft listing to active will also publish the listing on
etsy.com. Setting a sold out listing to active will update the
quantity to 1 and renew the listing on etsy.com.
```

There are two sets of `state`s here: `"active" "inactive" "sold_out" "draft" "expired"` and `active or inactive`. It would help if the docs mentioned only the one set that's actually being used.

### Why are you proposing this change?

Currently, the documentation is unclear about what to expect in the response.

**Comment by etsyachristensen** [comment]
Sorry for the confusion @NathanConroyOrd . Our documentation on this version of the API can be confusing. It's auto generated from our code and we are still fine tuning somethings. We re-used field strings on some of these so in a GET you may seem notations like this that actually pertain to the PUTs and see fields saying they are required on the GET statements when those are the returned fields. We have a backlog issue to go through and clean up these elements. Hoping to get to it soon.
