### ISSUE TITLE
[getListing]: Make the Inventory > Product > Property Values less complex

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#507]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Property values are split into 2 arrays "value_ids" and "values"

![image](https://user-images.githubusercontent.com/22307223/174435181-8b96f9a5-66c6-4540-97ab-43beb3a71d24.png)

### Proposed Endpoint Design Change

Update this to make it less complex and return 1 array of a "Value" object

![image](https://user-images.githubusercontent.com/22307223/174435194-97dd689b-9842-45d1-849f-a544398bc0f3.png)

### Why are you proposing this change?

This seems complex and from what I can tell we have to make sure that the index of the values in the 2 arrays are aligned with each other when we read them out.

It feels like you could implement this at the API layer (the part you control) without having to make any changes to the internal systems.

**Comment by etsyachristensen** [comment]
That would actually be really great @Gareth064. I don't know if this is doable at this time, but I'll certainly pass this up to our team that handles the inventory system. Would love to have it this way though as it makes it more clear what id goes to which value.

**Comment by assaflei** [comment]
Hi @etsyachristensen,
The new addition seems to break the update api
I now suddenly get this message when updating inventory:
Array contains invalid keys: value_pairs

Can you advice?

**Comment by etsyachristensen** [comment]
It *shouldn't* be a breaking change. I guess your process is different. I'll update the notes. We can't make the change on the server-side at the moment.

**Comment by etsyachristensen** [comment]
When being used to update the inventory or property values yes.

**Comment by assaflei** [comment]
I'll work on a hotfix...

I must say that I truly think that if an API (https://developer.etsy.com/documentation/reference/#operation/updateListingInventory) stops working due to **this** change, it means its a breaking change and it needs to be fixed at the backend
If I field is only meant for ease of read or usage, it shouldn't be relevant to any sanitization during listing updates

**Comment by etsyachristensen** [comment]
It seemed like such as simple addition that would only help. I hadn't anticipated the affect on updating inventory. It passed all our tests but we already have our tests setup to pass in the correct information. I don't know if other developers are using the same flow you are (pulling inventory and re-posting it) or if they are just assembling it each time. I'll continue to monitor. If we see a spike in errors, we may have to roll this one back.

**Comment by etsyachristensen** [comment]
Ok great thanks @assaflei. Sorry for the trouble!

**Comment by chanpory** [comment]
Just looked at my Etsy store to see why many of my items were "sold out", even though I had been using the API to update quantity. Checked my logs and saw a bunch of errors that say `Array contains invalid keys: value_pairs`. 

This was quite frustrating since I was losing some sales. Shouldn't the API just ignore invalid keys? Updating quantity for a listing is already cumbersome as it is using the API.

**Comment by etsyachristensen** [comment]
@Gareth064 I may need to revert this change. It seems to be causing more issues than it's solving. It may have to be done in a new endpoint or something. @assaflei will reverting this break the work you did to account for the change? I don't want to break something new by taking this out.

**Comment by assaflei** [comment]
Hi @etsyachristensen it will require a small adjustment I will update
Thanks for notifying

**Comment by etsyachristensen** [comment]
OK Ill get the revert process started shortly and get it into production probably in the next hour or two.

**Comment by etsyachristensen** [comment]
Ok this change is reverted. Sorry for the problems everyone.
