### ISSUE TITLE
[BUG]: getListingsByShop returning incorrect shipping_profile_id <- on Thursday it was correct.

### ISSUE THREAD

**Issue by thisisjake** [etsy/open-api#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

getListingsByShop returning incorrect shipping_profile_id, this was functioning correctly on Thursday US time however it is now returning shipping profile ids that are either invalid or at least do not exist on our shop.

As a result of this change, our inventory is no longer updating automatically so this is a rather urgent problem for us.

### Steps to reproduce

Query
https://openapi.etsy.com/v3/application/shops/{shop_id}/listings

Returns incorrect shipping_profile_id for listings

### Expected behavior

Should return correct shipping_profile_ids 

Please see the below examples for returned values / expected returned values:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/casua/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/casua/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Listing   ID | API Shipping Profile ID | Shipping Profile ID (from Etsy   Site) | API Shipping Profile Name | Shipping Profile Name (from Etsy   Site)
-- | -- | -- | -- | --
745040067 | 79719208521 | 73951113893 | null | FBA/Kantsu Shipping
202281068 | 5576532760 | 73951113893 | null | FBA/Kantsu Shipping
871133449 | 108418216110 | 73951113893 | null | FBA/Kantsu Shipping
567676274 | 51361767573 | 73951113893 | null | FBA/Kantsu Shipping
591385912 | 55914870145 | 90336833977 | null | Kantsu Only

</body>

</html>

The shipping profile ids matched the Etsy website just a few days ago.

**Comment by etsyachristensen** [comment]
@thisisjake I have a fix for this, but it needs to be tested. It may not go out into production until tomorrow.

**Comment by thisisjake** [comment]
@etsyachristensen thank you.

**Comment by etsyachristensen** [comment]
This should be corrected now @thisisjake .

**Comment by thisisjake** [comment]
@etsyachristensen thank you, appears to be functioning correctly now.
