### ISSUE TITLE
[FEATURE]: I'm trying to get the product attached video

### ISSUE THREAD

**Issue by namlv94** [etsy/open-api#509]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Describe the solution you'd like

I'm trying to get the product attached videoI'm trying to get the product attached video but can't find that in the API. Am I missing something or not?

**Comment by etsyachristensen** [comment]
No you aren't missing anything. At the moment, the OpenAPI does not support the product video functionality. We hope to build this out soon.

**Comment by etsyachristensen** [comment]
The listing video management has just been added: https://developers.etsy.com/documentation/reference#tag/ShopListing-Video
