### ISSUE TITLE
[FEATURE] Listing Videos

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#51]
**Is your feature request related to a problem? Please describe.**
New endpoints to allow us to view and manage a seller's listing videos.

**Describe the solution you'd like**
deleteListingVideo: delete a video from listing
getListingVideo: get video info from a listing
uploadListingVideo: upload a video to a listing
getListings: include field that contains video ID for one or more listings

**Describe alternatives you've considered**
There is no alternative that I'm aware of.

**Additional context**
n/a

**Comment by NellyGzzA** [comment]
Hi @benjymouse! 👋  Thank you so much for this proposal! :)
This is something we also think could be really helpful for other users. We hope to be able to address it soon.

**Comment by etsyachristensen** [comment]
The listing video management has just been added: https://developers.etsy.com/documentation/reference#tag/ShopListing-Video
