### ISSUE TITLE
[BUG]: getListingByShop is returning duplicated listings and the shop manager is reflecting this wrong number

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

By hitting getListingsByShop (https://developers.etsy.com/documentation/reference/#operation/getListingsByShop)
I get the next products twice in the 3 pages:
```
  '1236565342': 2,
  '1236565350': 2,
  '1236565352': 2,
  '1236565356': 2,
  '1236565358': 2,
  '1236565360': 2,
  '1236565362': 2,
  '1236565364': 2,
  '1236565366': 2,
  '1236565368': 2,
  '1236565370': 2,
  '1236565372': 2,
  '1236565374': 2,
```

the endpoint is saying there are 271 listings but after filtering duplicates vela gets 258, for example 1236565350 appears with offset 0, limit 100 and offset 100, limit 100,
I compared the creation timestamps and both seem to belong to the same listing then I can call it duplicate, I cannot compare with v2 API because this customer is having oauth2 token:
Here the timestamps:
```
// offset 0
"state": "active",
"creation_timestamp": 1655136412,
"created_timestamp": 1655136412,
"ending_timestamp": 1665677212,
"original_creation_timestamp": 1655136410,
"last_modified_timestamp": 1655750782,
"updated_timestamp": 1655750782,
"state_timestamp": 1655136411,

// offset 100
"state": "active",
"creation_timestamp": 1655136412,
"created_timestamp": 1655136412,
"ending_timestamp": 1665677212,
"original_creation_timestamp": 1655136410,
"last_modified_timestamp": 1655750782,
"updated_timestamp": 1655750782,
"state_timestamp": 1655136411,

```
I think Etsy is showing in shop manager 271 and vela shows 258 + 13 duplicates, I think API and UI have an error

### Steps to reproduce

hit getListingsby shop for this shop: 35133698

### Expected behavior

The endpoint must return distinct listing ids and the shop manager must reflect this number to match with us

### Additional context

This is another affected shop: 26238801
1232 Active listings in Vela vs 1240 active listings in Etsy

**Comment by yovasx2** [comment]
further details:
apart form the duplication spotted above, we also noticed there are some products in etsy not deliver through the endpoint mentioned above:

here is the list:
| title  | listing_id  |
|---|---|
 | 80 Years Loved Birthday White Gold Forever Love Necklace | 1250496465 | 
 | A Lifetime with You Is the Best Gift White Gold Forever Love Necklace | 1250496485 |
 | All You Need Is Love White Gold Forever Love Necklace | 1250496479 |
 | Cheers to 100 Years White Gold Forever Love Necklace | 1250496483 |
 | I love You Sucker White Gold Forever Love Necklace | 1250496477 |
 | I Love You to the Moon and Back White Gold Forever Love Necklace | 1250496469 |
 | I Want You Today Tomorrow and the Rest of My Life White Gold Forever Love Necklace | 1250496463 |
 | Live Laugh Love Roses White Gold Forever Love Necklace  |1250496473 |
 | Love Letters White Gold Forever Love Necklace  |1250496475 |
 | PERSONALIZED Monogram Outdoor Address Wall Art Sign, Birthday Idea, Unique Gift | 1252016013 |
 | Positive MAMA Affirmations White Gold Forever Love Necklace | 1250496481 |
 | This is No Path to Happiness, Happiness is the Path White Gold Forever Love Necklace | 1250496459 |
 | You Complete Me White Gold Forever Love Necklace | 1250496471 |
 | You Light Up My Life White Gold Forever Love Necklace | 1250496487 |

**Comment by etsyachristensen** [comment]
@yovasx2 We found the issue and have posted a fix.

**Comment by yovasx2** [comment]
> @yovasx2 We found the issue and have posted a fix.

I checked the shops that report this and seems to be fixed, thx a lot for your help :)
