### ISSUE TITLE
[BUG] CreateDraftListing failing with images array_too_short: 

### ISSUE THREAD

**Issue by zubairyou** [etsy/open-api#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/createDraftListing

### What would you like to change?

I am having this error while creating the listing [
    {
        "path": "/images",
        "type": "array_too_short",
        "message": "cannot be less than 1 items"
    }
]

In documentation images field is optional 

### Why are you proposing this change?

N/A

**Comment by zubairyou** [comment]
![image](https://user-images.githubusercontent.com/17173019/174821468-36ce99ca-3e59-431b-aa21-a30f032b9a36.png)

**Comment by zubairyou** [comment]
@etsyachristensen above for your reference how I am calling this API .

**Comment by etsyachristensen** [comment]
@zubairyou You need to check `is_supply` and set to either true or false. If `when_made` and `who_made` are included, `is_supply` must be included. If any of those 3 are included all three need to be provided.

**Comment by etsyachristensen** [comment]
@zubairyou Were you able to resolve by including the `is_supply`, `when_made` and `who_made`? I'm hoping to look at this more today. Please let me know.

**Comment by zubairyou** [comment]
@etsyachristensen Yes issue has been resolved after updating my profile information updating the card details. Thanks for your help
