### ISSUE TITLE
[BUG]: [Etsy] Receipts API response updated_timestamp is not getting updated when there is an update on refund

### ISSUE THREAD

**Issue by ravi18969** [etsy/open-api#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created one order and after that I'm processing partial refund on it. The next day again I have processed partial refund on the same order. However when I checked through the receipts API the **updated_timestamp** has not been updated. 

For reference please check with the below endpoint:
**receiptId: 2511062124
shopId: 20659437**

https://openapi.etsy.com/v3/application/shops/20659437/receipts/2511062124

### Steps to reproduce

1. Place one order with multiple items and note down its **updated_timestamp** by calling "Get shop receipts by receipt Id"
2. Go to action and process partial refund by either reducing quantity/removing item.
3. Again make above API call to check through this receipt **updated_timestamp**
4. Repeat step 2 multiple times to check if updated_timestamp is getting updated or not.

### Expected behavior

We are expecting whenever there is an update in receipts including processing of refund this **updated_timestamp** should be updated with the latest epoch timings.

**Comment by etsyachristensen** [comment]
This is actually expected. The receipt object itself doesn't change. The refund doesn't change the original receipt object. You can see a created_timestamp in the refund array of the receipt object.

**Comment by ravi18969** [comment]
In our requirement we fetch receipts from a particular time based on the updated_timestamp. So even if there are any changes in receipt we fetch it again and update mapping at our end with all the values.
The Problem is if this updated_timestamp is not updated when there are any changes in refund then we will miss those receipts and we won't be able to update refunded amount and might calculate wrong tax against that receipts.

Can we have some work around which will make this working or we can have separate refund API?

**Comment by ravi18969** [comment]
@etsyachristensen thanks for quick reply and it will be very helpful if this will be resolved on priority. Otherwise to get latest refunds receipts we have to make multiple API calls.

Sequence of APIs call
1.  getShopPaymentAccountLedgerEntries  --> Passing all these enteryIds to next API call to get payment adjustment
2. getPaymentAccountLedgerEntryPayments --> get unique receipts from the response
3. getShopReceipts --> getting receipt by receipt Id. (We need to fetch each receipts by receipt Id) 

Due to these many API calls to get refunds receipts we might reach API limit per second. 

See if you could provide another solution to fetch refunds based on last_updated time

**Comment by etsyachristensen** [comment]
@ravi18969 We have made the change to the receipt endpoints to ensure that the updated_timestamp is returned with the latest activity on the receipt (refund/transaction etc). See https://github.com/etsy/open-api/releases/tag/3.0.0-general-release-2022-07-19

**Comment by etsyachristensen** [comment]
Apologies @ravi18969. At this time the only change is to make the receipt updated_timestamp return the most recent value. We are not changing the get date range as this is not something we are able to do right now.

**Comment by Gareth064** [comment]
Hi @etsyachristensen , can you confirm what you mean by this?
`We are not changing the get date range`

If the receipts `updated_timestamp` is updated to show that something has changed, like a partial refund, then why wouldn't the `min_last_modified` query param not pick up on that change to the `updated_timestamp`?

Am I misunderstanding both you and ravi here? 😄

**Comment by etsyachristensen** [comment]
I mean that we aren't changing how the `min_last_modified` parameter works. Currently, it works off the actual receipt object updated_timestamp which does not ever change. In the endpoint we are overriding the receipt updated timestamp with the latest date from the related objects. Changing this would require searching through the related objects for updated dates and running the entire endpoint in reverse basically. We just aren't prepared to do that at the moment.

**Comment by Gareth064** [comment]
So when we do a `get` and include that `min_last_modified` query param, it is looking at the original `updated_timestamp`, but when a receipt object is returned, you are replacing the `updated_timestamp` with max stamp from one of the transactions inside the receipt (if its different)

If so then I don't believe the change that's been made helps us, and probably the same for the guys on the other issues that were tagged regarding this, because we want to be able to return receipts using the `min_last_modifed` query when that receipt\order\object has had anything changed on it... like a refund (or a cancellation too?).

**Comment by ravi18969** [comment]
Yes that make sense instead of replacing timestamp dynamically it has to be updated on actual receipt so that when we pass these query params it should work.
In current case we still won't be able to use this feature as it doesn't serves our purpose.

**Comment by Gareth064** [comment]
@etsyachristensen Can this be reopened please as the change put in doesn't solve the actual issue (and the other issues tagged previously)?

When we make a call to the ```getShopReceipts``` endpoint and pass in a value for the ```min_last_modified``` parameter then we need the results to include Receipts/Orders where the following events have happened on them since they were created.

Cancelled
Refunded Fully
Refunded Partially
Expected Ship Date changed

For any 3rd-party developer partner who uses the API for "Order Management" in their own platform (which is probably a high percentage) then this functionality is crucial

**Comment by ravi18969** [comment]
@etsyachristensen any update on this? Did you open a new bug for this issue?

**Comment by ravi18969** [comment]
@etsyachristensen Its been more than a month now but no update yet? Shall I open a new bug for this one?
