### ISSUE TITLE
[FEATURE]: Coupon / Discount Codes

### ISSUE THREAD

**Issue by matteogiani** [etsy/open-api#514]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I need the Coupon creation and update endpoint available in v2 to be available in v3 of the API in order to be able to create, update and delete coupon codes for a specific shop.

### Describe the solution you'd like

Implement the coupon endpoint in v3

**Comment by etsyachristensen** [comment]
At the moment, the Coupon/Discount features are considered retired. This isn't necessarily permanent, but it was not considered for the V3 migration. We do have this on the board as something to discuss so it may come out of retirement.
https://developers.etsy.com/documentation/migration/retired-resources
