### ISSUE TITLE
[DOCS]: How to derive receipt_id from order_id (https://www.etsy.com/your/orders/sold/new?order_id=2121xxxxx)

### ISSUE THREAD

**Issue by MSiUK2021** [etsy/open-api#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference/#tag/Shop-Receipt

### What would you like to change?

An explanation on how to get the receipt_id from a given order_id.

### Why are you proposing this change?

Would be helpful to anyone who wants to get the details of a specific receipt using order_id from website.

**Comment by Gareth064** [comment]
Hey @MSiUK2021 - I'm pretty sure that Order_id (from the website) is the same as the Receipt_id from the API.

**Comment by etsyachristensen** [comment]
@Gareth064 is correct. order_id is the same as receipt_id.
