### ISSUE TITLE
[DOCS]: Documented Translation Schema doesn't include "compliance_summary"

### ISSUE THREAD

**Issue by Gareth064** [etsy/open-api#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://www.etsy.com/openapi/generated/oas/3.0.0.json

### What would you like to change?

When translations are returned with a Listing (the only endpoint i've used so far) there is a string called "compliance_summary" in the results. But this isn't mentioned anywhere in the Docs or the AOS file.

![image](https://user-images.githubusercontent.com/22307223/176224841-64d6de58-8420-4555-a933-546580573f0a.png)

### Why are you proposing this change?

Make the documentation and AOS more accurate.

**Comment by etsyachristensen** [comment]
That should not be there. I'll see about removing it.

**Comment by etsyachristensen** [comment]
@Gareth064 This has been fixed. That compliance_summary array will no longer appear.
