### ISSUE TITLE
[BUG]: getUser returning NULL first_name & last_name

### ISSUE THREAD

**Issue by Allen209** [etsy/open-api#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A few months back, I updated my V2 openapi.etsy.com/v2/users calls to use the V3 getUser endpoint. It worked fine for months. As of 6/23/22, the V3 getUser endpoint started retuning NULL for the first_name & last_name.  

### Steps to reproduce

```
function GetUserNameV3($api_key,$login_name,$userID,&$userName){

  $userName = $login_name;
  $etsy_API_request = "https://openapi.etsy.com/v3/application/users/$userID";
  $token = Get_Token();
  $header = array('Content-Type' => 'application/x-www-form-urlencoded; charset=utf-8', 'x-api-key' => $api_key, 'Authorization' => 'Bearer ' . $token);
  $response = wp_remote_post($etsy_API_request, array('timeout' => '10', 'method' => 'GET', 'headers' => $header));
  
  if( $response['response']['code'] == 200 ){
      
    $result = json_decode($response['body']);  
  
    if($userName != null){
      $userName = $result->first_name;    
    }
       
  }

}
```

Here is a snippet of the response

```
["first_name"]=>
NULL
["last_name"]=>
NULL
["create_timestamp"]=>
int(1520638749)
["created_timestamp"]=>
int(1520638749)
```

### Expected behavior

I expect first_name & last_name to be populated after a V3 getUser call as it was working prior to 6/23/22.

**Comment by etsyachristensen** [comment]
The endpoint was changed to secure the user data. When you call getUser, if you are requesting a user other than the user that is oauthed, the personally identifiable information will be redacted.
