### ISSUE TITLE
[DOCS]: updateListingInventory changes offering_id and product_id

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/reference#operation/updateListingInventory

### What would you like to change?

In requests to your `updateListingInventory` endpoint, I've seen listings' `product_id`s and `offering_id`s change as a result. Is this expected behavior?

I could not find any documentation around this. If this is not a bug, would you describe this behavior in your docs?

Also, I'm curious if this endpoint is idempotent. Will identical `PUT` requests result in the same `product_id`s and `offering_id`s in the response?

### Why are you proposing this change?

It would be helpful if users were forewarned about this behavior in the docs.

**Comment by etsyachristensen** [comment]
Correct. The product_id and offering_id change with each update. This is intentional because we have to maintain history of inventory changes. I apologize that it's not documented. I'll add this as a task to take care of.

**Comment by NathanConroyOrd** [comment]
If SKUs are not set for each of a listing's variations, is there any persistent, unique identifier for products and offerings?

**Comment by NathanConroyOrd** [comment]
Also, if a store changes the quantity of a listing's variations in the store's admin page, does this change the `offering_id` and `product_id`s associated with the listing?

**Comment by AWAlemu** [comment]
My team observed that `property_value` `value_ids` also change, in addition to `product_id` and `offering_id`, after each request submitted to the `updateListingInventory` endpoint.

---

The behavior of `updateListingInventory` is a major breaking change with significant impact on the ecosystem of solutions that support Etsy sellers.

In addition, this hinders interoperability with Etsy, which limits the ecosystem of solutions that support Etsy sellers. This negatively impacts Etsy shoppers' overall experience.

For example, it creates major problems to Etsy sellers who use our system, because it breaks listing/variation to product mapping and vice versa. It will break order fulfillment as well as inventory and price updates. It will also cause overselling and underselling.

---

With this behavior change, the best option Etsy leaves us with is using SKUs, however this is a sub-optimal solution because Etsy allows unreliable use of SKUs as unique variation identifiers. 
- Etsy doesn't require SKUs when creating or updating variations
- Etsy allows duplicate use of SKUs across listings
- Etsy allows using the same SKU to all variations of a listing

Moreover, without proper enforcement of requiring unique SKUs, Etsy would be loosely relying on the sellers to correctly and fully SKU their variations. Relying on the manual effort of sellers is less than ideal. It is very common to see sellers mix up, omit or duplicately use SKUs, which creates big problems.

---

All the major sales channels such as Amazon, Walmart, Shopify, etc. offer reliable and consistent variation identifiers.

For example, Amazon and Walmart enforce SKU requirement and uniqueness, which makes managing product mapping and updating inventory and price using SKU very reliable. In addition, Shopify provides reliable `variant_id` and `inventory_item_id` to update variants' and their inventory.

---

Does Etsy has plans to provide 100% reliable and consistent variations' identifiers?

**Comment by DevBrent** [comment]
@etsyachristensen This is a major, breaking, and undocumented change and I hope your team will reconsider. The impacts to some sellers will be catastrophic in terms of hours or days spent rewiring their Etsy catalog to workaround this new behavior.

We've noticed the behavior has changed over the last week and hope that identifiers can stay stable but we're quite scared for our Etsy sellers right now.

**Comment by DevBrent** [comment]
Maybe Etsy can clarify how their checkout works when a quantity update is made part-way through checkout? Is the cart abandoned or do they have a Krabby Patty formula to re-map and item associated with a now-dead offering_id, product_id, and product_value value_ids.

**Comment by DevBrent** [comment]
Related? https://github.com/etsy/open-api/issues/405#issuecomment-1109885797

**Comment by etsyachristensen** [comment]
Sorry all. I was out of office on Friday and yesterday. I'm not sure I follow as to the breaking change. To my knowledge nothing was changed. I will check in with our other teams to see if anything was pushed that would cause a change.

**Comment by etsyachristensen** [comment]
> Also, if a store changes the quantity of a listing's variations in the store's admin page, does this change the `offering_id` and `product_id`s associated with the listing?

Yes I believe it will. Again, this has to do with maintaining a snapshot of a listing's inventory at any given time.

**Comment by Gareth064** [comment]
The next big feature in my app was going to be inventory management but from reading through this issue I am really reluctant to even start to try to implement this.

We definitely need a static Id for each listing/variation that we can use to sync with the app. Like others have said, unless Etsy makes the SKU a mandatory field (and somehow forces every seller to retrospectively update all their listings) then this is going to be impossible.

**Comment by AWAlemu** [comment]
@[etsyachristensen](https://github.com/etsyachristensen) The behavior change is between the V2 updateInventory and V3 updateListingInventory APIs.

Unlike the V2 updateInventory API, we've observed that the V3 updateListingInventory changes the `offering_id`, `product_id`, or product `property_values` `value_ids` as well as `value_pairs` `id`.

Below is an example JSON diff screenshot that shows change in variation identifiers before (left) and after (right) updateListingInventory request to update price. Notice the change in `offering_id`, `product_id` and `property_values` `value_ids` and `value_pairs` `id`.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/15066043/177374449-54c7f236-3c6f-4902-99e3-456f46af546a.png">

**Comment by etsyachristensen** [comment]
> Related? [#405 (comment)](https://github.com/etsy/open-api/issues/405#issuecomment-1109885797)

No this would not be related. This change only had to do with the process of creating an inventory record when creating a listing and with preventing the use of "quantity" and "price" in the updateListing endpoint. it did not change the `updateListingInventory` endpoint.

**Comment by etsyachristensen** [comment]
@AWAlemu, @Gareth064, @NathanConroyOrd and @DevBrent Can you all try the update again and let me know if you're still having this issue? We reverted a change the other day and we're having trouble duplicating it. I think that MIGHT have fixed it. But want to be sure. Thanks!

**Comment by AWAlemu** [comment]
@[etsyachristensen](https://github.com/etsyachristensen) Thank you for the update! We noticed that the variation identifiers were not changing in our more recent tests.

Is the reverted change permanent? And, can we rely on the understanding that the V3 `updateListingInventory` will not change any of the following identifiers in the future: `offering_id`, `product_id`, or product `property_values` `value_ids` as well as `value_pairs` `id`?

**Comment by etsyachristensen** [comment]
The revert is permanent, BUT the product_id and offering_ids will still change. They always have. But the property ids and value ids should not.

**Comment by AWAlemu** [comment]
Great! Consistent `property_id` and `value_ids` will suffice for our purposes. We can rely on those as permanent variation identifier.

Thank you very much for your help!

**Comment by Gareth064** [comment]
@AWAlemu are you syncing listings with your app? If so, then how do you do it with just consistent property_id and value_id?

I'm struggling a bit with this one I think.

**Comment by NathanConroyOrd** [comment]
In my testing, the `offering_id`s and `product_id`s do not change - as they did not change in v2.

Here's what I'm doing for my testing: I'm essentially copying all the fields from the listing's products. Then I change only the offering quantities. Then I send all that information back in the update request, and the `offering_id`s and `product_id`s do not change.

Will this behavior continue?

**Comment by etsyachristensen** [comment]
I wouldn't count on it continuing 100% reliably. I think if you change other values in the variants the product_id and or offering_id may change.

**Comment by Gareth064** [comment]
Is this idea then when updating a listing, say for example the description, before we make the request we keep a copy of the original product id and when we get a response we can update the whole item completely overwriting what we had, including the product_id?

**Comment by NathanConroyOrd** [comment]
Thank you @etsyachristensen for you quick responses!

I'm not clear on what you mean. Can you elaborate? Is it simply that changing other aspects of products may change the `offering_id`s and `product_id`s. Or do you mean that -- in the future -- inventory-only updates may change the identifiers?. What kinds of updates change the IDs and what will keep them the same?

**Comment by etsyachristensen** [comment]
@Gareth064 yes if you want to use the product id or offering id as the keys, yes you could do it that way. I would say store the id you want to use locally on your system. Then, when you do an inventory update, you can update that with the new id (if applicable).

**Comment by etsyachristensen** [comment]
@NathanConroyOrd I've seen product and offering ids change for various reasons - all having to do with adding/removing variations and offerings. They should only change when making calls to the updateListingInventory endpoint. Updating the listing itself won't cause the ids to change.

**Comment by AWAlemu** [comment]
@[Gareth064](https://github.com/Gareth064) We merge all the `value_ids` of a product's `property_values` into a single array, sort and CSV concat them to form a unique identifier.

And, we do something similar with order transaction variations' `value_id`.

This is less than ideal, but it has been reliable for us.

Over the years, Etsy has made advancements such added things such as support for SKUs and `product_id`, but we never trusted these identifiers to be reliable.
