### ISSUE TITLE
[DOCS]: Open API v3 - property value update

### ISSUE THREAD

**Issue by yugri** [etsy/open-api#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/updateListingProperty

### What would you like to change?

I want misleading OpenAPI documentation to be changed.

REQUEST BODY SCHEMA: `application/x-www-form-urlencoded`
needs to be changed to
REQUEST BODY SCHEMA: `application/json`

OR changes in server behavior are required in another case.

### Why are you proposing this change?

Because if I follow documentation and set the **Content-Type** header to `application/x-www-form-urlencoded` server process my request and return HTTP 200 that's OK. But in case I send a list of property values...

it updates only the last one (Needlepoint in this case). Try it:

```python
import os

import requests

from requests import PreparedRequest, Request

s = requests.Session()

headers = {
        "x-api-key": os.getenv("API_KEY"),
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": f"Bearer {os.getenv('ACCESS_TOKEN')}",
        "Host": "openapi.etsy.com",
    }

def update_listing_property(shop_id: int, listing_id: int, property_id: int, value_ids: List[int],
                                             values: List[str], scale_id: int = None):
    """Update listing property on Etsy."""
    payload = {
          "value_ids": value_ids,
          "values": values,
          "scale_id": scale_id
    }
    req = Request(
          "PUT",
          build_url(f"/application/shops/{shop_id}/listings/{listing_id}/properties/{property_id}"),
          headers=self.headers,
          data=payload,
     )
     return req.prepare()

update_props_request = update_listing_property(
      SHOP_ID, 1260983339, 47626759760, [597, 544, 550, 556, 573],
      ['Beading', 'Cross stitch', 'Embroidery', 'Framing', 'Needlepoint']
  )
result = s.send(update_props_request)
```

If I set **Content-Type** header to `application/json` the issue has gone.

Thank you.

**Comment by etsyachristensen** [comment]
@yugri I don't know the language you are using for the code above, but if I'm reading this correctly, you are sending an actual array. In the case of `x-www-form-urlencoded` you actually should be sending a simple comma delimited list of values or ids. For example:
value_ids = "597, 544, 550, 556, 573",
values = "Beading,Cross stitch,Embroidery,Framing,Needlepoint"
