### ISSUE TITLE
updateListingInventory Problem

### ISSUE THREAD

**Issue by Esatyilmaz0** [etsy/open-api#525]
Hi, I'm trying exactly 8 hours and I can't update the products sku in my listings how can I update it? missing error input parameter: products

Test Json:

{"products": [{"sku": "", "offerings": [{"price": 1200.0, "quantity": 1, "is_enabled": true}], "property_values": [{"property_id": 200, "property_name": "Primary color", "scale_id": null, "value_ids": [51995096597], "values": ["Beige"]}]}, {"sku": "", "offerings": [{"price": 1000.0, "quantity": 1, "is_enabled": true}], "property_values": [{"property_id": 200, "property_name": "Primary color", "scale_id": null, "value_ids": [51985709075], "values": ["Bronze"]}]}]}

**Comment by etsyachristensen** [comment]
I'm closing this for now. If you still have issues, please post your full payload as requested.
