### ISSUE TITLE
[BUG]: Error 500 message when using getShopByOwnerUserId

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling [getShopByOwnerUserId](https://developer.etsy.com/documentation/reference/#operation/getShopByOwnerUserId) api for a user that doesn't have a shop, the call returns a server error ({"error":"Server Error"})

User id for example: 658470679

### Steps to reproduce

Invoke getShopByOwnerUserId api

### Expected behavior

Response should be informative message

**Comment by etsyachristensen** [comment]
@assaflei When I try to call that endpoint with your example id, I get a 404 error:
```
{
    "error": "Could not find a shop for user with user_id = 658470679"
}
```

**Comment by etsyachristensen** [comment]
Thanks @assaflei. What is the name of your app? I can find it from that I think. Is user 658470679 one of your users?

**Comment by assaflei** [comment]
The name is shopupz-inventory-sync-app
And yes, its one of my users

Thanks

**Comment by etsyachristensen** [comment]
I just tested with your key and the oauth 1 token for that user. I get a proper response of the user's shop data. (info redacted below)
```
{
    "shop_id": ________,
    "shop_name": "ActualShopNameHere",
    "user_id": _____________,
    "create_date": 1656206906,
    "created_timestamp": 1656206906,
    "title": null,
    "announcement": null,
    "currency_code": "USD",
    "is_vacation": false,
    "vacation_message": null,
    "sale_message": null,
    "digital_sale_message": null,
    "update_date": 1656207125,
    "updated_timestamp": 1656207125,
    "listing_active_count": 0,
    "digital_listing_count": 0,
    "login_name": "koxqbs0md3t7oy29",
    "accepts_custom_requests": false,
    "vacation_autoreply": null,
    "url": "https://www.etsy.com/shop/ActualShopNameHere",
    "image_url_760x100": null,
    "num_favorers": 0,
    "languages": [
        "en-US"
    ],
    "icon_url_fullxfull": null,
    "is_using_structured_policies": false,
    "has_onboarded_structured_policies": false,
    "include_dispute_form_link": false,
    "is_direct_checkout_onboarded": false,
    "is_etsy_payments_onboarded": false,
    "is_opted_in_to_buyer_promise": false,
    "is_calculated_eligible": true,
    "is_shop_us_based": true,
    "transaction_sold_count": 0,
    "shipping_from_country_iso": "US",
    "shop_location_country_iso": null,
    "policy_welcome": null,
    "policy_payment": null,
    "policy_shipping": null,
    "policy_refunds": null,
    "policy_additional": null,
    "policy_seller_info": null,
    "policy_update_date": 0,
    "policy_has_private_receipt_info": false,
    "has_unstructured_policies": false,
    "policy_privacy": null,
    "review_average": null,
    "review_count": null
}
```

**Comment by etsyachristensen** [comment]
Here's the full curl (minus the bearer token and key)
```
curl --location --request GET 'https://api.etsy.com/v3/application/users/658470679/shops' \
--header 'x-api-key: ___key______' \
--header 'Authorization: Bearer ___token_____' \
```

**Comment by assaflei** [comment]
@etsyachristensen 
Interesting, I think there is a different behavior here

For this specific shop a bearer token is required
For other shops I use this method without the bearer, only with the x-api-key field and it works 
Only this shop returns an 500 error 

Looking at the [documentation](https://developer.etsy.com/documentation/reference/#operation/getShopByOwnerUserId) there is no need to provide bearer tokens here. Only the api key is required
Can you try invoking the api without the bearer token and see what happens

Also if using bearer is required, the documentation should be updated as well

**Comment by Gareth064** [comment]
Does it matter that @assaflei is using _openapi.etsy_ in his url?
![image](https://user-images.githubusercontent.com/22307223/178124699-a6edd5d0-1c11-489c-8e90-4ad5dc93e722.png)

Where @etsyachristensen is using _api.etsy_
![image](https://user-images.githubusercontent.com/22307223/178124736-00eac298-aa79-4ef8-9e14-8b6bb50eda89.png)

**Comment by etsyachristensen** [comment]
@Gareth064 No the urls are interchangeable.

@assaflei For good practice, if you have a token for the current user you should include it in any api call you make (whether required by the endpoint or not) because it will help with your api call rate limits. Without the token the calls count against your app's maximum, but with the token it will count against that user's token. However, that's not relevant to the issue...

So what's happening is that this shop is not active. It's set in Draft in our system. With or without a token for any other shop/user, if you call that endpoint for that particular user, you should get:
```
{
    "error": "Could not find a shop for user with user_id = 658470679"
}
```

But since this is one of your users, if you query that endpoint for that user with the apikey for that user, it's going to see that you should own the shop data and it is trying to show you the data. But because you don't have the token, it's giving an error. We do need to fix that. It shouldn't give you a 500 error. But if you include the token for that same user, you should get the result I posted 3 days ago.

**Comment by assaflei** [comment]
Thanks for the update, it all makes sense, I'll update the logic on my side
Maybe you should include this input on the reference as well, which currently suggests putting api-key only in several api calls
Also great tip regarding avoiding quota limitation!
