### ISSUE TITLE
[FEATURE]: Add includes=Transactions param for receipts get APIs

### ISSUE THREAD

**Issue by KushGoyal** [etsy/open-api#527]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I reach the API rate limits because to save a receipt I have to fetch the transactions in a different requests. I see that listings can be fetched with an `includes` param which is supper convenient. If you can add `includes=Transactions` param for receipt get APIs it will be easy to fetch receipts in a single request and it will take much less number of requests to fetch order data.

### Describe the solution you'd like

Add `includes=Transactions` param for receipt get APIs. When this param is added to the url for fetching receipts data, the response will include a field called `transactions` which has the list of all transactions for the order.

I understand that transactions are paginated. But you can set a default limit for 10 transactions. Because most of the receipts will have less than 10 transactions.

**Comment by Gareth064** [comment]
You don't need to use an include with getShopReceipt or GetShopReceipts, as it already returns the transactions in the response.

Here is a snippet of the response documentation show there is an array of transactions returned.

![Screenshot_20220703-233528.png](https://user-images.githubusercontent.com/22307223/177059521-58efa2f7-dd80-4452-ada6-abf6c14f1611.png)

**Comment by KushGoyal** [comment]
I missed this when checking the docs. Thanks for the information. V3 api has improved the experience greatly. On a side note the update inventory request which needs the whole inventory object in a mess. If only the quantity needs to be changed the request should be simpler. I will check the docs open a separate issue for this.
