### ISSUE TITLE
[FEATURE]: Endpoint for recently ended listings

### ISSUE THREAD

**Issue by sampok** [etsy/open-api#528]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

The problem is that [the real-time feed v2 API](https://www.etsy.com/developers/documentation/getting_started/real_time_feeds) has not been implemented for v3 yet. It seems that the team is evaluating whether to implement real-time feed for v3. However, there seems to be alternative path that could be easier to implement:

With the recent (?) addition of sort_on 'updated' in v3 `findAllListingsActive` endpoint it should be possible to keep track of recently created, updated, and restored listings in selected taxonomies without a real-time feed API. However, one piece of information for efficient sync is missing: listings that have become recently unavailable.

### Describe the solution you'd like

A new ShopListing endpoint `findAllListingsRecentlyInactive`.

A list of listings that have recently become inactive on Etsy, paginated by their 'unavailable' timestamp. The only and default sort option is `unavailable_timestamp` descending (or `updated` if more feasible).

Query parameters
- limit: integer [1 ... 100]
- offset: integer
- taxonomy_id: integer

### Describe any alternatives you've considered

- Implementing a complete v3 real-time feed ([see proposal](https://github.com/etsy/open-api/issues/75)), would be a good alternative.
- Outside of this proposal and real-time feed v3 there isn't any way to sync unavailable listings by taxonomy.

**Comment by etsyachristensen** [comment]
@sampok Are you proposing to get all listings - regardless of who owns them - that have gone inactive? We can't do this unfortunately. If your app is querying on behalf of the shop owner you should be able to get this from the `[getListingsByShop](https://developers.etsy.com/documentation/reference#operation/getListingsByShop)` endpoint by using "inactive",  "sold_out" or "expired" as the state and then `sort_on` = updated and `sort_order` = desc.

**Comment by sampok** [comment]
Yes, I meant all listings by specific taxonomy ids.
If you implement the real-time feed for v3, that solves the problem, but I was thinking this could we an easier option and serve the same purpose. Can you share about your plans for the real-time feed v3?

**Comment by etsyachristensen** [comment]
At this point all I can say is that it's in discussion. We haven't decided on when/how/if it will be implemented.
