### ISSUE TITLE
[DOCS]: Quickstart documentation ambiguous regarding redirect_uri

### ISSUE THREAD

**Issue by cvanvlack** [etsy/open-api#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/tutorials/quickstart#implement-the-redirect_uri-route

### What would you like to change?

The Quickstart tutorial uses localhost entirely. In the section [Create the client landing page](https://developers.etsy.com/documentation/tutorials/quickstart#create-the-client-landing-page)  there is reference to the redirect URI. However, this should be an explicit step showing where to input the redirect URI and to use exactly `http://localhost:3003/oauth/redirect` as that is what the quickstart guide is telling you to do.

When you get to the "tip" at the end of [Implement the redirect_uri route](https://developers.etsy.com/documentation/tutorials/quickstart#implement-the-redirect_uri-route), it's not much of a tip because it doesn't tell you what to put in, despite the rest of the walkthrough assuming a particular value.

Also in the [Handling errors](https://developers.etsy.com/documentation/tutorials/quickstart#handling-errors) section, it says "If you followed every step of this tutorial, you likely ran into an error when implementing the welcome page as your code value had been used before." It's difficult to tell if you got everything working or you just broke it when the final step is an error message....

### Why are you proposing this change?

You'll save developers a LOT of time searching if you make it clear ALL of the steps.

You'll also help developers know when everything is working when the tutorial doesn't end in an error. If there's a single use token that needs to be regenerated then let people know so they can run it again without an error.

**Comment by ranouf** [comment]
Hi,

The option "Edit your callback URLs" is not unable on my side. Maybe I need a commercial access for that?

I asked to customer supper and ask for a commercial access even it's only for my personal purpose.
