### ISSUE TITLE
[ENDPOINT]: Proposed design change for getListingsByShop

### ISSUE THREAD

**Issue by namlv94** [etsy/open-api#532]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

for api v2 we can get the entire information of a product in one request using Associations. for api v3 can there be a similar design or not?

### Proposed Endpoint Design Change

can get all information like images, inventory, properties ... in one request

### Why are you proposing this change?

since each etsy app has a rate limit, we want to save the number of request calls to optimize our app

**Comment by namlv94** [comment]
Thank you very much for clarifying this issue for me. There's one more problem that I find lacking compared to api v2. It is related to getShopReceipts. Will I be able to get the Listings field like in v2? If not, can you add the has_variations field to the transaction?

**Comment by etsyachristensen** [comment]
We can't add the Listing object to the receipt, or even the listing id. The reason being is that a single receipt could cover multiple listings. The `getShopReceiptTransaction` and `getShopReceiptTransactionsByReceipt` endpoints will return the listing_id as well as the variation(s) selected by the buyer.

**Comment by namlv94** [comment]
for the updateListing endpoint, when setting the state of the product to inactive I get the error "There was a problem with /quantity : cannot be empty". I know it's because my product has zero inventory on etsy. Can Etsy skip the quantity check when I update the state to inactive? Because when the product is in the inactive state, the inventory quantity is not important

**Comment by etsyachristensen** [comment]
> for the updateListing endpoint, when setting the state of the product to inactive I get the error "There was a problem with /quantity : cannot be empty". I know it's because my product has zero inventory on etsy. Can Etsy skip the quantity check when I update the state to inactive? Because when the product is in the inactive state, the inventory quantity is not important

@namlv94 Please start new issues going forward when you have different things to address. It will make tracking these much easier for both of us. As for the problem listed above, see the new thread I started here: https://github.com/etsy/open-api/issues/538
