### ISSUE TITLE
[BUG]: uploadListingImage display order is reversed

### ISSUE THREAD

**Issue by namlv94** [etsy/open-api#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

uploadListingImage display order is reversed

### Steps to reproduce

uploadListingImage display order is reversed

### Expected behavior

uploadListingImage display order is reversed. although I can reverse engineer my list before importing to etsy. But I don't know if it's a bug or a change of api v3. In the docs, the "rank" field, I don't notice a difference from v2

**Comment by etsyachristensen** [comment]
When you are uploading, I assume you are doing one after another correct? What are you adding for `rank`? Each time you upload you should pass in the appropriate value for `rank` from 1 on up (where rank 1 is the first image). If you don't include rank or you always pass in 1 for rank, it will use the most recent upload as the primary image.

**Comment by namlv94** [comment]
I assign a rank to each image. Start from 1 and increase gradually

**Comment by namlv94** [comment]
I'm sure I'm using the correct endpoint you sent. Please see the body I have posted below. Please note that I am running a loop with the rank starting at 0, which corresponds to the index of an array of images that I want to upload. Can you make a request to check this?
**{
			'listing_id': product_id,
			'overwite': 'true',
			'rank': rank + 1
		}**

**Comment by etsyachristensen** [comment]
I assume that by "product_id" you're referring to your internal reference for our listing_id.
As for the "rank +1" I assume you're using 0 index internally and thus adding the 1 before sending the rank correct?

I have just tested the process myself and I'm not able to replicate the problem you are having.

I just tried the following procedures:
1. Created a new draft listing. I then uploaded 3 files, one at a time:
```
Image 1:
{
    "listing_id": listing_id,
    "overwrite": true,
    "rank": 1
}
Image 2:
{
    "listing_id": listing_id,
    "overwrite": true,
    "rank": 2
}
Image 3:
{
    "listing_id": listing_id,
    "overwrite": true,
    "rank": 3
}
```
The images showed up in the correct order.

2. Created a new draft listing. I then uploaded 3 files, one at a time (this time without `overwrite`):
```
Image 1:
{
    "listing_id": listing_id,
    "rank": 1
}
Image 2:
{
    "listing_id": listing_id,
    "rank": 2
}
Image 3:
{
    "listing_id": listing_id,
    "rank": 3
}
```
The images appeared in the correct order.

3. Created a new draft listing. I then uploaded 3 files, one at a time (this time passing in rank = 1 on each):
```
Image 1:
{
    "listing_id": listing_id,
    "rank": 1
}
Image 2:
{
    "listing_id": listing_id,
    "rank": 1
}
Image 3:
{
    "listing_id": listing_id,
    "rank": 1
}
```
In this case the images showed up in the reverse order.

I'm not sure if your system is property incrementing the rank value prior to sending.

Are you able to provide me with the response header `x-etsy-request_uuid` for each of the upload attempts so I can look up the calls in our logs?

**Comment by namlv94** [comment]
below are the request id that i uploaded the image for listing_id 1253852794
EuNnpmABnjx9s62DRRYJPbU_hMf7: rank 1
EuzlHdnrU5Wf--roPqDCpASy0X3a: rank 2
EucAqAib4Q6iz2QEnr2JTX3ZBKd8: rank 3
EuuLvuASJrxGzr9c4ibdP2sUD4f3: rank 4
Please check it out. There's one more thing I think you should know, all the responses I get after making an image upload request have rank=1

**Comment by namlv94** [comment]
Thank you for responding. I greatly appreciate your help, and also extend an apology. That was my mistake, the library I used to send the request was automatically ignoring the body when I attached a file, that's why the rank is always imported as 1.
