### ISSUE TITLE
[DOCS]: What is the "Money resource"?

### ISSUE THREAD

**Issue by NathanConroyOrd** [etsy/open-api#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://developers.etsy.com/documentation/reference#operation/updateListingInventory

### What would you like to change?

There's a line in the description of the updateListingInventory resource:
```
When setting a price, assign a float equal to amount divided by divisor as specified in the Money resource.
```

What is the "Money resource?" Is it this: https://www.etsy.com/developers/documentation/reference/money ? But isn't that the v2 API documentation? Perhaps a hyperlink would help.

### Why are you proposing this change?

I'm not clear on what the docs are referring to.

**Comment by etsyachristensen** [comment]
@NathanConroyOrd Good catch. We don't have a writeup on that in the V3 docs, though the V2 docs do pretty much apply. A Money resource is an array of data regarding a value such as price. This array consists of the `amount` (if USD it would be in cents), followed by a `divisor` (if in USD that would be 100 - 100 cents to each dollar) and the `currency_code` which is the string denoting the currency, such as "USD". For example, when fetching a listing inventory, the price array looks something like this:
```
"price": {
    "amount": 500,
    "divisor": 100,
    "currency_code": "USD"
}
```

Hopefully that helps. I'll see if we can get this written up in our V3 docs in the future.
