### ISSUE TITLE
[BUG]:  deleteListingImage returns 500 error

### ISSUE THREAD

**Issue by wild-arctic-fox** [etsy/open-api#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Method https://developers.etsy.com/documentation/reference/#operation/deleteListingImage returns 500 error.

### Steps to reproduce

1. call https://openapi.etsy.com/v3/application/shops/14280094/listings/1043207843/images/4053191169 DELETE method
2. received  500 status and  "error": "Server Error"
<img width="829" alt="image" src="https://user-images.githubusercontent.com/40433033/178762739-0c5e796a-d1fd-4c15-a5bd-0f4e13b9a429.png">
Tested also on listings (not working): 935510586, 1029250004

### Expected behavior

Expect to get 204 response code.

**Comment by etsyachristensen** [comment]
@wild-arctic-fox Can you provide me with the response header value for x-etsy-request-uuid? I can look in our logs for this error and try to figure out why you'd get that error.

**Comment by etsyachristensen** [comment]
Thanks! The error that's coming up is that the user doesn't exist in the call. This means that the authentication of the user isn't right or something. To debug this I will need a full copy of your entire curl that's being made to our system, including the auth token and x-api-key. Do not post it here, but please send it to developers@etsy.com and request that it be sent to me "Andrew Christensen" and reference this github issue. That way it will get in my inbox and I can review what is being sent so I can find out why it's acting strange.

Also what is the name of your app in the Etsy system?

**Comment by wild-arctic-fox** [comment]
@etsyachristensen Thank you! 
Your explanation helped me to understand that I used incorrect credentials. 
With right creds it works. Problem is solved.

**Comment by wild-arctic-fox** [comment]
@etsyachristensen Sent info as you asked! Thanks for help!
