### ISSUE TITLE
[BUG]: listing['creation_timestamp'] and image['creation_tgz'] are inconsistent

### ISSUE THREAD

**Issue by dbeleznay** [etsy/open-api#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ShopListings have the following properties
"creation_timestamp": 946684800,
"created_timestamp": 946684800,
"ending_timestamp": 946684800,
"original_creation_timestamp": 946684800,

And ListingImages have the properties
"creation_tsz": 0,
"created_timestamp": 0,

It seems like the pattern migrating from v2 to v3 was to replace all of the tgz with timestamps, but you missed the one for ListingImages.

The "created_timestamp" is consistent between both listings and images and could be used for both, but then the "original_creation_timestamp" is inconsistent because it uses the word creation rather than created.  Please consider adjusting one or the other to be the same.

### Steps to reproduce

Check the documentation for https://developers.etsy.com/documentation/reference#operation/getListingImage

### Expected behavior

I expect to be able to use creation_timestamp for both listings and images

**Comment by etsyachristensen** [comment]
@dbeleznay Just checked and the get listing image endpoints do return the `created_timestamp` field and `creation_tsz` will be removed in the future.
