### ISSUE TITLE
[BUG]: Oh dear, you cannot sell this item on Etsy.

### ISSUE THREAD

**Issue by namlv94** [etsy/open-api#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://prnt.sc/llOy-Jq5s2rJ
when i upload a product with information like this i get the above error. To fix it, I changed who_made, when_made. Can you tell me why this error occurs? And can the etsy side fix the error to make the response message easier to understand?

### Steps to reproduce

https://prnt.sc/llOy-Jq5s2rJ

### Expected behavior

Can you tell me why this error occurs? And can the etsy side fix the error to make the response message easier to understand?

**Comment by etsyachristensen** [comment]
@namlv94 I need the full payload you are sending to the API to debug this. You don't have to give the headers/credentials. If you can give me the CURL that would be helpful.

**Comment by namlv94** [comment]
payload: {"quantity": 95, "title": "Gay Male MLM Pride Belt", "description": "Gay Male MLM Pride Belt\nThis Gay Male MLM Pride Belt is a canvas woven belt custom made especially for Pride Shop NZ and is based on the male Gay Male MLM pride flag.\nMade from polyester this one size fits all belt is perfect for pulling your whole look together and is sure to catch people\u2019s eye. The size can be adjusted easily by removing the buckle, cutting the belt, and reattaching the buckle.\nSize: Tip to tip length: 140 cm (42 inches), Width: 4 cm, Buckle Width:\u00a03.8cm", "price": 19.0, "tags": "pride, belt, flag", "should_auto_renew": true, "state": "active", "who_made": "someone_else", "when_made": "2020_2022", "is_supply": false, "shop_section_id": 36534124, "taxonomy_id": 4, "shipping_profile_id": 130188166077, "item_weight": 0.13, "item_weight_unit": "kg", "item_dimensions_unit": "cm"}
response: [{"path":"\/marketplace","type":"invalid_marketplace","message":"Oh dear, you cannot sell this item on Etsy."}]
this is the payload I submitted and the response message from etsy.

**Comment by etsyachristensen** [comment]
What were the who_made and when_made settings when you got the error? That particular message means that how you had `who_made`, `when_made` and `is_supply` requires you to have a production partner defined as part of the creation.

**Comment by namlv94** [comment]
Where can I get a list of production partners? And can you tell me under what circumstances will cause the above error?

**Comment by namlv94** [comment]
I found production partners. The remaining question is when are we required to provide this list? Can you please clarify this?

**Comment by etsyachristensen** [comment]
At the moment, if a seller wants to sell something that is made by someone else, they MUST enter their Shop Manager interface and click on Settings on the left and then Production Partners. They then enter the production partner before creating a listing that will use that production partner.
