### ISSUE TITLE
[BUG]: Receiving 'Could not set a calculated shipping profile to the listing.' even though dimensions and weight are set.

### ISSUE THREAD

**Issue by nmrdxt** [etsy/open-api#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sending 'updateListing' PUT (or PATCH) requests, intending to only updating a product's state, so the payload only includes the 'state' property.

Receiving "Could not set a calculated shipping profile to the listing.  The listing is missing 'item_weight', 'item_length', 'item_width', 'item_height', 'item_weight_unit' or 'item_dimensions_unit'.".

The product does include all those properties, it seems like when processing the requests the original properties are not inherited.

### Steps to reproduce

Send a updateListing PUT request to a listing that has a calculated shipping profile, and has all its dimensions and weight properties set.

Payload should be:

`[
'state' => 'inactive'
]`

### Expected behavior

I'd expect that for simple product state updates I would not need to include all the dimensions and width properties and that those will be inherited from the original product.

### Additional context

As far as I can remember, it used to work okay.

**Comment by etsyachristensen** [comment]
@nmrdxt This issue has been fixed.
