### ISSUE TITLE
[BUG]: ShopListingWithAssociations#skus is empty instead of nulll

### ISSUE THREAD

**Issue by tjoyal** [etsy/open-api#545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In `ShopListingWithAssociations` the `skus` field is dynamic based on the request authentication.

The field type is set as `Array of strings Nullable`
With the following description: "A list of SKU strings for the listing. SKUs will only appear if the requesting user owns the shop."

When a valid Oauth2 is passed in, the behavior is as expected. An array of skus is returned.

When there is no valid Oauth2 passed in, the returned field is an empty array (`[]`) instead of the documented `null`.

### Steps to reproduce

Request `getListing` without an Oauth2 header.

### Expected behavior

For the response to be `skus: null`, properly signifying the values aren't available.

As opposed to `skus: []` which represent "there are no skus".

### Additional context

Related to https://github.com/etsy/open-api/issues/544 where the `getListing` endpoint is documented to not accept an Oauth2.

**Comment by etsyachristensen** [comment]
@tjoyal This is one of those areas where we've had to diverge from the OAS just a bit. The "nullable" notation on that field is in reference to INPUT. We have a ticket in our system to try to create different versions of the field names as input or output so we can remove the "required" and "nullable" from the documentation. Hopefully that will happen sometime in the future.
