### ISSUE TITLE
[BUG]: "Shops cannot create Listings in languages other than the Shop's primary language."

### ISSUE THREAD

**Issue by soohyungl** [etsy/open-api#547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm creating listings in English and my listings are listed in English. However, this isn't working properly and giving me a 400 with the message: "Shops cannot create Listings in languages other than the Shop's primary language."

No idea about the root cause, I've confirmed with support that my store's default language is English. 

### Steps to reproduce

1. create listing
2. get error message? 

### Expected behavior

Should create listing

**Comment by etsyachristensen** [comment]
@soohyungl What endpoint url are you posting your listing data to? The error you are getting is indicative of the old version 2 of the OpenAPI. If you are using an endpoint that includes "/v3/applications" and getting that error, I need some info:

1. The URL you're sending to.
2. What is the shop id?
3. What is the response header X-Etsy-Request-Uuid value?

**Comment by soohyungl** [comment]
This is a v2 issue, but currently our business requires us to use it. We're using this method: 
https://www.etsy.com/developers/documentation/reference/listing#method_createlisting

the shop id is 631601152

**Comment by etsyachristensen** [comment]
Ah ok thanks. Unfortunately, this Github board is only for V3 issues and discussion. You should post in the Google Group for V2 here: https://groups.google.com/g/etsy-api-v2
