### ISSUE TITLE
[BUG]:  refresh endpoint responding 500

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

from time to time the refresh endpoint is returning 500, but if I manually retry the payload logged then I get 200

The payload is this I removed 15 characters at the end to obfuscate the token:
```
curl --location --request POST 'https://openapi.etsy.com//v3/public/oauth/token' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxx.; user_prefs=xxxxxxx.' \
--data-raw '{
    "grant_type": "refresh_token",
    "client_id": "XXXXXXXXX",
    "refresh_token": "150897767.yrAnRm-_P1lhcG9sMdGyb_xya9MJ9rDEzZlIhkcTfgbGg2cVknMD-03jMg_nSSfKBGMQN-XXXXXXXXX"
}'
```

### Steps to reproduce

used the curl above which produces 500 error:

```
failed to update shop ID 51012 due to unknown error: {"message":"cannot POST /v3/public/oauth/token (500)","status":500,"text":"{\"error\":\"Server Error\"}\n","method":"POST","path":"/v3/public/oauth/token","url":"https://api.etsy.com/v3/public/oauth/token","params":{"grant_type":"refresh_token","client_id":"XXXXXXXXX","refresh_token":"150897767.yrAnRm-_P1lhcG9sMdGyb_xya9MJ9rDEzZlIhkcTfgbGg2cVknMD-03jMg_nSSfKBGMQN-XXXXXXXXX"}}
```

### Expected behavior

get 200 always

### Additional context

sometimes the same endpoint delivers 400 refresh_token is revoked how is this possible I revoked the app on shop manager's integrations and regenerated the connection to etsy and the old refresh token was giving me new tokens using the token endpoint (I noticed the new integration is not coming in the shop manager)

`659201498.m-T8K_znjSBNiKcjLJu_27J2Wo64tYYO_DpRwNSSJ2kEREaVx0vMpyPLXXXXXXXXXXXXXXXXXXXXXXX`

I noticed the prefix is different:
150897767 (500 error)
659201498 (400 error) Could u provide more info about this user_id, please?

**Comment by etsyachristensen** [comment]
@yovasx2 I just had a talk with my OAuth guy here and we poked and prodded and realized that the issue isn't our system returning a 500 error. The message you provided:
![image](https://user-images.githubusercontent.com/83842847/186975914-5559e120-d588-4a54-8b30-f981826f5626.png)

My guy thinks that it may be some kind of communication error and that your system isn't able to actually connect with ours. I'm not sure as I can't see if there are any headers returned when you are getting the error. If you do get the error from our side, can you provide the headers you are getting back?

The only other theory we have is that it appears in your curl that maybe the refresh token isn't getting url encoded.

**Comment by etsyachristensen** [comment]
@yovasx2 Are you still getting the issue?
