### ISSUE TITLE
[BUG]: shipment_notification_timestamp does not return real shipment notification date

### ISSUE THREAD

**Issue by mathieulesniak** [etsy/open-api#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there 👋 

When querying the shop [receipt endpoint](https://developer.etsy.com/documentation/reference/#operation/getShopReceipt), the `shipments` section of the result contains incorrect `shipment_notification_timestamp`.

For example, I marked an order as sent through Etsy UI, the customer received the shipment notification email on 2022-08-10 12:09:28 Europe/Paris (1660126168), whereas the API returns a `shipment_notification_timestamp` of 1660147200 (2022-08-10 18:00:00 Europe/Paris)

It seems that all of my `shipment_notification_timestamp` are set to 18:00:00, whatever the real shipment date was.

As a comparison, when using V2 API, I was relying on `shipping_details.shipment_date`, and it was the real shipment date.
(However, this v2 API section does not seems to be documented anymore)

### Steps to reproduce

1. Call https://openapi.etsy.com/v3/application/shops/{shop_id}/receipts/{receipt_id}
2. Note that `shipment_notification_timestamp` key is not set with the real shipment notification date

### Expected behavior

The real shipment notification date should be there, not a fixed hour timestamp

**Comment by etsyachristensen** [comment]
@mathieulesniak While the shipment_notification_timestamp comes out as a timestamp in the OpenAPI, it's really just a date field in our system. So the date returned is the DATE of the label, NOT the actual time. So our system will use a round hour for the time. I can't really say why it's picking 4pm EST (18:00 in Paris). It may have to do with some server settings for resolving the time. But it will likely always return the same time for every notification date stamp.
