### ISSUE TITLE
[BUG]: API getListing response is not correct

### ISSUE THREAD

**Issue by XanhZ** [etsy/open-api#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have already has listing images before but when I request get listing, response of field images is always null
![Screenshot from 2022-08-15 11-39-39](https://user-images.githubusercontent.com/61658597/184577865-cf4b85d4-e6e2-4c77-a05f-945416ab1f74.png)
Here is response from get listing images:
![Uploading Screenshot from 2022-08-15 11-40-20.png…]()

### Steps to reproduce

See response from request get listing

### Expected behavior

Add images to response

**Comment by nesh6** [comment]
add "includes": "Images" in your request. it will return images.

**Comment by XanhZ** [comment]
thanks it works for me
