### ISSUE TITLE
[ENDPOINT] Proposed design change for createListing - setting production partner

### ISSUE THREAD

**Issue by kievins** [etsy/open-api#56]
**Current Endpoint Design**
Currently there is no way to specify production partner for a listing using API. Same applies to update endpoint.

**Proposed Endpoint Design Change**
Allow to set this value.

**Why are you proposing this change?**
With current version of API, every time we create a product in Etsy, a customer must manually go and select production partner. This could easily be streamlined with this change.

**Comment by harjas** [comment]
Hi @kievins! This is a totally fair request. We can look into what can be done. Thanks for letting us know!

**Comment by stickfigure** [comment]
This seems to exist in the API right now? There's a production_partner_ids parameter to createDraftListing and updateListing. Can be closed?
