### ISSUE TITLE
[BUG]: Getting Error when setting inventory zero

### ISSUE THREAD

**Issue by Deepshikha-cedcoss** [etsy/open-api#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@etsyachristensen Is there any way to set inventory zero for inactive listing?

### Steps to reproduce

1- publish listing using createDraftListing And, then update state= active using  updateListing endpoint call
2- And, then inactive the listing using updateListing end point
3- And, now wants to set an inventory zero for inactive listing using [updateListingInventory](https://developers.etsy.com/documentation/reference/#operation/updateListingInventory) endpoint call but getting this ERROR "one offering must have greater than zero inventory"

### Expected behavior

for inactive listing, Etsy should accept the zero inventory on [updateListingInventory](https://developers.etsy.com/documentation/reference/#operation/updateListingInventory) endpoint call

**Comment by etsyachristensen** [comment]
No. There is no way in the API to zero out all of the inventory for a listing. There has be at least one item with at least a quantity of 1. The only other way to zero inventory is for the product to actually sell out on Etsy.com. To my knowledge there are no plans to change this.
