### ISSUE TITLE
[BUG]: getShopPaymentByReceiptId Buyer currency code is correct but shows shop currency values

### ISSUE THREAD

**Issue by scottjlaw** [etsy/open-api#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the V2 API this would return the values in the buyer's currency. 

In V3 it is returning the correct currency code, but the values are the shop currency values.

### Steps to reproduce

getShopPaymentByReceiptId on any order with a currency different to the shop currency

### Expected behavior

Return values in the correct currency

**Comment by etsyachristensen** [comment]
With our shift to managing tickets to the discussion board, we'll close this ticket out in favor of tracking it here: https://github.com/etsy/open-api/discussions/697

We are not dropping it, just moving the discussion.
