### ISSUE TITLE
[ENDPOINT]: Proposed design change for Cart

### ISSUE THREAD

**Issue by aziddy** [etsy/open-api#566]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Cart v2

https://www.etsy.com/developers/documentation/reference/cart

### Proposed Endpoint Design Change

Don't deprecated it in v3

### Why are you proposing this change?

I wanna use it to make a custom item configurator off the site that adds all the selected items to the user's Etsy cart

API v3 is looking like a nerfed version of v2 with OAuth2

**Comment by etsyachristensen** [comment]
We have added this to our list of future development possibilities. Closing the issue out for now to clean up the board. But it is on our internal tracking list.
