### ISSUE TITLE
[FEATURE]: Add Variations to Include Enum in v3 for the listings resource

### ISSUE THREAD

**Issue by ralfborchers** [etsy/open-api#568]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I could not find a replacement for listings/1234567/?includes=Variations to get all variations, but this is absolutely crucial for my integration and sure for others as well.

### Describe the solution you'd like

Please bring the possibility to v3 to get variations for a single listing with the same result payload as in v2.

### Describe any alternatives you've considered

Alternatively add the variations to the active listings paging results for a shop. This would be even easier than fetching the variations listing by listing.

**Comment by etsyachristensen** [comment]
@ralfborchers variations are returned as part of Inventory. If you do ?includes=Inventory you will get the variations.
