### ISSUE TITLE
[BUG]: Getting error image id 3631744977 is invalid while updating price/inventory using updateListingInventory API call

### ISSUE THREAD

**Issue by Deepshikha-cedcoss** [etsy/open-api#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello @etsyachristensen

 When the images are assigned to the listing as well as the image in the listing images for variant image linking. and later, deletes some of the images from the listing then how we can delete them from the variant linking option because the images that have been deleted are still existing so the "image id is invalid" error getting.
 
 Image id existing which has been deleted on this [getListingVariationImages](https://developers.etsy.com/documentation/reference/#operation/getListingVariationImages) call 
![image](https://user-images.githubusercontent.com/62876154/185747222-78d5e603-218e-4354-81b2-3b4b4ef9e9ca.png)

but image id not existing [getListing](https://developers.etsy.com/documentation/reference/#operation/getListing) endpoint call with **Images** association
![image](https://user-images.githubusercontent.com/62876154/185747342-0d3269bb-83d8-430e-ba6c-21996e522a54.png)

So, How we can unlink the image linking option for listing using the API endpoint?

### Steps to reproduce

1.  Upload the listing images using  this [uploadListingImage](https://developers.etsy.com/documentation/reference/#operation/uploadListingImage) endpoint
2.  And then, creates variation images on a listing using this [updateVariationImages](https://developers.etsy.com/documentation/reference/#operation/updateVariationImages)
3.  delete some of the images which were assigned to the listing variant using this [deleteListingImage](https://developers.etsy.com/documentation/reference/#operation/deleteListingImage)
4. but, the data of the imaged id which has been deleted is still existing on this [getListingVariationImages](getListingVariationImages) endpoint call

### Expected behavior

I think Etsy should give an API call to delete the image at the variant level. there are only two API calls right now ([getListingVariationImages](https://developers.etsy.com/documentation/reference/#operation/getListingVariationImages), [updateVariationImages](https://developers.etsy.com/documentation/reference/#operation/updateVariationImages)).

### Additional context

shop_id= 23032173
listing_id = [1034230543 , 1027957152]

@etsyachristensen you can this bug for these listing ids.
thanks

**Comment by etsyachristensen** [comment]
@Deepshikha-cedcoss This issue has been corrected. When you delete a listing image, it will now also remove any variation images.

**Comment by Deepshikha-cedcoss** [comment]
@etsyachristensen Thank you for the update. one more doubt how we will unlink without deleting the images of the variant from the API endpoint?

**Comment by Deepshikha-cedcoss** [comment]
> one more doubt how we will unlink without deleting the images of the variant from the API endpoint?

@etsyachristensen any update on this?
