### ISSUE TITLE
[FEATURE]: Holiday and Occasion Clarification

### ISSUE THREAD

**Issue by bitcrush-robin** [etsy/open-api#574]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I'm working for a client on an app that creates listings, and they have requested for their users to be able to set Holiday and Occasion properties for the listings.

I've been searching the documentation as best I can, but the only references I can find to these are relegated to [v2 documentation on listing properties](https://www.etsy.com/developers/documentation/getting_started/inventory#section_taxonomy), where they're listed as taxonomy, which I think is not true any more?

If there is an endpoint where we can pull the names and IDs for these properties, I can't find it!

### Describe the solution you'd like

An API endpoint for retrieving a list of properties with their IDs, and then one for retrieving the list of valid values per property, for cases like Holiday. Comparable to the dropdown menu when updating a listing on the main Etsy site.

### Describe any alternatives you've considered

I set the properties on a test listing and then used getListingProperties to see what the property IDs are.

Then I inspect-elemented the dropdown menus on the listing update page on the site, and extracted the ids and names from the HTML...

**Comment by etsyachristensen** [comment]
@bitcrush-robin We are using the taxonomy system. The list of properties is fully depended on on the category it is. So for instance `Paper & Party Supplies▸Paper▸Greeting Cards` you can set the Holiday option. This would come from the properties for that node.

So you'd call to [getSellerTaxonomyNodes](https://developers.etsy.com/documentation/reference#operation/getSellerTaxonomyNodes) to get all the categories.

Find the category you want to place the item in, such as 1261 above. Then call getPropertiesByTaxonomyId, passing taxonomy_id = 1261.

That would show you the properties available to that category:
Primary color
Secondary color
Occasion
Holiday
Etc...

Inside of each of the properties are the listed possible values. The list of possible values and even properties depends entirely on the category you choose. Some properties allow for custom values. Typically those will be obvious by the `max_values_allowed` being null and/or `supports_variations` being true.

I'm not sure if that helps, but hopefully it does.

**Comment by bitcrush-robin** [comment]
Actually that's very helpful, I couldn't work out how it was tied in to Taxonomy. The client's app doesn't use the category system right now - everything is in Accessories - so I'll get that updated and working properly. Thank you!

This can probably be closed, though you might take it as a request to update the documentation to make this clearer? But I think I have enough to go on, so thanks again.
