### ISSUE TITLE
[ENDPOINT]: Proposed design change for /users/:user_id/feedback should have in the V3

### ISSUE THREAD

**Issue by trungpv1601** [etsy/open-api#575]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Retired in the V3

### Proposed Endpoint Design Change

We should support as the V2 API: https://www.etsy.com/developers/documentation/reference/feedback

### Why are you proposing this change?

I think we should support the Feedback API for other purpose. Because It useful for the users.

I do not know it have problems with the policy and privacy laws or not.

But you guys should reviews and go forward with it.

Thank you so much.

**Comment by etsyachristensen** [comment]
Thanks @trungpv1601 . This has been added to our internal tracking for possible future development. Will close the ticket now to clean up the board. But it is in our radar.

**Comment by switmac** [comment]
plus one on this pls.
