### ISSUE TITLE
[FEATURE]: Get information if shop suspended

### ISSUE THREAD

**Issue by ToWorldMe** [etsy/open-api#578]
### Is there an existing ticket for this?

- [x] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Sometimes our shops go to suspend (and sometimes we don't get email about the reason). We are get this information only from our clients. 

### Describe the solution you'd like

If it possible, provide information about suspend (flag only or the reason too) to https://openapi.etsy.com/v3/application/shops/{shop_id} 

### Describe any alternatives you've considered

If shop does not suspended, but suspendeduser - provide it to user api

### Additional context

It help to save some api calls limit by app, because you don't need to do it if shop suspended. And this information can be provided to user.

**Comment by Deepshikha-cedcoss** [comment]
Hello @ToWorldMe 

do you have any idea how we can know whether the seller's Etsy shop is live or not? There is an index in [getShop](https://developers.etsy.com/documentation/reference/#operation/getShop) API which is **is_etsy_payments_onboarded** but I'm not quite sure that from this index we can know that.

**Comment by etsyachristensen** [comment]
@Deepshikha-cedcoss @ToWorldMe - Unfortunately there are no plans at this moment to add a status or status reason to the shop data endpoint. There are privacy issues involved here. The `is_etsy_payments_onboarded` is a setting for whether the seller has setup accepting payments through Etsy.

**Comment by etsyachristensen** [comment]
Sorry for the confusion, but this is actually by design. There's no way from the outside to know whether a shop is active or not. The stock your shop interface is there and put together this way to ensure that the seller completes setting up their shop.
