### ISSUE TITLE
[FEATURE] Webhooks

### ISSUE THREAD

**Issue by kievins** [etsy/open-api#58]
**Is your feature request related to a problem? Please describe.**
Our app requires keeping up to date with any changes to listings and orders. This requires performing regular syncing using the API. Much of this effort is wasted as only a small amount of listings or orders have changed sync the last time sync was performed.

**Describe the solution you'd like**
Etsy should implement webhooks and allow API users to subscribe for automatic updates that are relevant to their app. This would significantly reduce the need for app developers to make any API calls.

**Describe alternatives you've considered**
We have developed and currently use in production a sync functionality that connects to Etsy API on regular intervals and sync all the latest info. This results in making a very large amount of API calls that could be avoided.

**Additional context**
I believe that this would also provide better experience for app users as any changes in their orders, listings etc. would almost instantly propagate to their apps. No delays, no data refreshing etc. This should also help with reducing the overall incoming API call volume for Etsy API.

**Comment by shubham0804** [comment]
+1 webhooks would be extremely helpful

**Comment by benjymouse** [comment]
+1

**Comment by harjas** [comment]
Hi @kievins! 👋 Thank you so much for your feedback! We totally hear the need for webhooks. We've discussed it internally and we're happy to be hearing from y'all as well. There's been other requests too (#28 for example). 

We are looking into how we can support them but these investigations are still preliminary. We'll keep you updated on how things proceed.

**Comment by harjas** [comment]
@kievins I'll mark this issue as duplicate to #28 and close it, if that's okay?

**Comment by kievins** [comment]
Yes, thanks! I'm really glad that you are looking into this!

**Comment by Yagisanatode** [comment]
+1

**Comment by ambikeshkumargautam-cedcoss** [comment]
Yes, I'd like to mention getting the recipient from Etsy though webhook would be amazing, Whenever there'll be any purchase could be fetched by that webhook.
