### ISSUE TITLE
[BUG]: API updateListing Can't update price and quantity

### ISSUE THREAD

**Issue by lehoangnnx** [etsy/open-api#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need to update the price and quantity for the product without the variant, but according to the [documentation](https://developers.etsy.com/documentation/reference#operation/updateListing), I don't see the above 2 fields. So how can I update the price and quantity?

### Steps to reproduce

Make API call https://openapi.etsy.com/v3/application/shops/{shop_id}/listings/{listing_id} with `price` and `quantity` parameter

### Expected behavior

The expected result is that the `price` and `quantity` are updated as per the parameters passed

**Comment by etsyachristensen** [comment]
All product price and quantity changes are now done via the updateListingInventory endpoint (https://developers.etsy.com/documentation/reference#operation/updateListingInventory). This was a change made several months ago. You will need to first get the listing inventory, then make the necessary changes to the data as [outlined here](https://developers.etsy.com/documentation/tutorials/listings#updating-inventory). Then, send in the updated inventory with new price and quantity.
