### ISSUE TITLE
Questions regrading migration etsy v2 to V3 Apis  

### ISSUE THREAD

**Issue by Braj** [etsy/open-api#583]
Hello Etsy Support Team, 

We are working on etsy api migration from V2 to V3 Apis 
We are having few questions

- Will all Etsy v3 APIs be accessible from Oauth1.0 token?
- What is the tentative date of deprecating Oauth1.0?
- If we migrate any customer from OAuth1.0 to Oauth2.0 then both Oauth1.0 and OAuth2.0 token will work? or Oauth1.0 token will expire?

Please advise.

**Comment by etsyachristensen** [comment]
@Braj 

- OAuth 1.0 tokens are being deprecated. In the near future we won't create new OAuth 1.0 tokens at all.
- We don't have an a specific date set yet, but I would plan on probably before the end of the year. No guarantees though.
- OAuth 1.0 tokens will begin getting revoked automatically when the OAuth 2.0 tokens are generated, but for the moment both will remain valid for the time being.

I highly recommend just switching fully to OAuth 2.0 tokens.

**Comment by etsyachristensen** [comment]
FYI there's a token exchange endpoint. You can read about it here: https://developers.etsy.com/documentation/essentials/authentication#exchange-oauth-10-token-for-oauth-20-token

**Comment by aaronb-cg** [comment]
Pigging-backing on this: how feasible is it for us to upgrade to v3 piecemeal?
So we start with a bunch of accounts on v2 using OAuth 1.0. We then start by upgrading our calls to the ShopReceipts endpoint but our other calls e.g. to ShopListings remain on v2.
Is that possible? Or do we have to upgrade all our calls to all endpoints at once?

**Comment by etsyachristensen** [comment]
@aaronb-cg This is how many of the developers have gone about it. They continued to use the OAuth 1 tokens for the accounts and just updated the endpoints a bit at a time. You can still do that now but I'd urge you to complete the transition soon as V3 will stop accepting OAuth 1 tokens, I would guess around the beginning of the year. I don't know the schedule at the moment but that's an estimate.

**Comment by aaronb-cg** [comment]
@etsyachristensen fantastic, thanks for clarifying.
We will be starting this work imminently so hopefully will have it done in time.
