### ISSUE TITLE
[BUG]: diff between (v2) findAllShopListingsActive and (v3) findAllActiveListingsByShop ?

### ISSUE THREAD

**Issue by creharmony** [etsy/open-api#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm testing a migration from usign api v2 to using api v3 and there is some diff : cf reproduce steps.

### Steps to reproduce

- v2 used :  => **count:253**
```
https://openapi.etsy.com/v2/shops/creharmony/listings/active?api_key=xxx&language=fr&limit=100&offset=0&translate_keywords=true
https://openapi.etsy.com/v2/shops/creharmony/listings/active?api_key=xxx&language=fr&limit=100&offset=100&translate_keywords=true
https://openapi.etsy.com/v2/shops/creharmony/listings/active?api_key=xxx&language=fr&limit=100&offset=200&translate_keywords=true
```

- v3 used :  => **count:251**
```
https://openapi.etsy.com/v3/application/shops/10875986/listings/active?language=fr&limit=100&offset=0&translate_keywords=true
https://openapi.etsy.com/v3/application/shops/10875986/listings/active?language=fr&limit=100&offset=100&translate_keywords=true
https://openapi.etsy.com/v3/application/shops/10875986/listings/active?language=fr&limit=100&offset=200&translate_keywords=true
``` 

### Expected behavior

What I see is that I got some listing (2) are missing in v3 version of API.

I notice this one : **"listing_id":998493974***

recent actions:
- this listing were expired in aug and were re activated at the end of aug (Aug 29). 
- Now this listing is active. : https://www.etsy.com/fr/listing/998493974/collier-pointe-de-fleche-porte-bonheur?variation0=1999310269

As it is missing in v3 api I thoug that , there is maybe a "server side cache" issue somewhere? (for v3 only!)

### Additional context

Could you please confirm that this is an issue. 🙏 
This is a blocker for me for the migration

In advance thanks a lot. 👍 
(I ve to anser on some ticket and want to finish migration before givin my feedback)

**Comment by creharmony** [comment]
Second one (in diff) is following listing: `943798046` on etsy: https://www.etsy.com/fr/listing/943798046/collier-menottes-tour-de-cou-menottes

**Comment by etsyachristensen** [comment]
@creharmony I'm not certain if this is related but those two listings appear to have restrictions on them I believe for India. I'm not sure why. Are your API calls originating from India? I'm looking into how or why the restrictions are on those listings and if that might be the cause. I'm not sure why the V2 would show them but V3 won't. I assume we have the restrictions functionality applied to the V3 OpenAPI.

**Comment by creharmony** [comment]
thanks for your investigations

>Are your API calls originating from India?
no, originating from France

I noticed also that the getShop API return a correct count (today: 254) that is not the same of v3 API `listings/active` (today: 252)

**Comment by etsyachristensen** [comment]
@creharmony We went through the listings and found that those same two listings that aren't showing up are actually not showing because they are restricted due to mature content but aren't in a category (taxonomy) that is for mature content. The descriptions may have been flagged in our system as mature content so they are technically restricted from showing up. OpenAPI V2 did not abide by this restriction system. This is one of the reasons that V2 is being deprecated.

**Comment by etsyachristensen** [comment]
I should note that you can contact developers@etsy.com to have those two listings reviewed and maybe get them resolved. Unfortunately, there's nothing we can do in the API team to correct this behavior because it is expected.

**Comment by creharmony** [comment]
@etsyachristensen thanks 🙏 I've made an email to dev support (asking them "how to not reproduce" : that would be nice to add a documentation link right here to avoid this issue again in the future by me or other etsy api user)
