### ISSUE TITLE
[BUG]: “Made to Order” digital listings converted to “Instant download” after editing

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"Made-to-order download" digital listing is converted into "instant download" after editing listing with different title (PATCH endpoint)

### Steps to reproduce

1. Create a digital listing ("Made-to-order download") with when_made as "made to order"
2. Hit the PATCH endpoint to edit the title, adding a suffix
3. The listing in etsy will change from "Made-to-order download" to "instant download"

To validate data is good
5. The get listing endpoint is still returning when_made as "made to order"
6. The file listing endpoint is returning an empty array

### Expected behavior

keep the product as Made-to-order download

### Additional context

I compared the get response after corrupting the listing and the only change is in the title (suffix) and the timestamps, files endpoint still returns an empty array and the shop manager is keeping the "made to order" UI (no file upload allowed)
You can restore the product in the shop manager by selecting "made to order" in when made option and saving it

<img width="1352" alt="Screen Shot 2022-09-13 at 22 55 42" src="https://user-images.githubusercontent.com/3578401/190057581-d748a303-e7ba-4821-b7a8-412c8a7369a6.png">
<img width="1350" alt="Screen Shot 2022-09-13 at 23 08 22" src="https://user-images.githubusercontent.com/3578401/190057573-66b8ecf2-28b1-4bab-9246-d6cc51597aef.png">

**Comment by yovasx2** [comment]
probs related with https://github.com/etsy/open-api/issues/454

**Comment by etsyachristensen** [comment]
@yovasx2 I just tested this myself and I am not able to duplicate the problem.

I created a draft listing using the following curl data:
```
--data-urlencode 'quantity=1' 
--data-urlencode 'title=testing made to order download' 
--data-urlencode 'description=culpa dolore' 
--data-urlencode 'price=50' 
--data-urlencode 'who_made=i_did' 
--data-urlencode 'when_made=made_to_order'
--data-urlencode 'taxonomy_id=14'
--data-urlencode 'type=download'
--data-urlencode 'is_digital=true'
```

I then had to upload a photo to it in order to publish so that I could view it and see the "Made-to-order download" under delivery.

I then did an update using the PATCH update endpoint with the following cURL data:
```
--data-urlencode 'title=updating test for made to order'
```

I then viewed the listing and still see "Made-to-order download" in the delivery section.

I'm not sure what I'm doing differently from you.

Can you give me the content you are passing at each stage of the process?

**Comment by etsyachristensen** [comment]
@yovasx2 I still am not able to duplicate it. I tried in our development and production environments. I used shop manager to create a new listing with a single photo with:
Title - `Test string`
Who Made it? - `I Did`
What is it? - `A finished product`
Who made it? - `Made to Order`
Category - `Art & Collectibles / Drawing & Illustration / Digital`
Renewal - `Manual`
Type - `Digital`
Description - `Test description`
Price - `$10.00`
Quantity - `1`

Everything else I left alone as default or blank.

I then viewed the listing and see:
![image](https://user-images.githubusercontent.com/83842847/191066118-ba4d4458-8541-449a-ac30-a04e1df1880d.png)

I then use the API endpoint to update ONLY the title to:
`testing update to manually created digital listing`

I reload the listing page and see this in Delivery:
![image](https://user-images.githubusercontent.com/83842847/191066338-11d898bf-933b-4a5b-bb9f-2b020f95196c.png)

Is this happening for ALL shops or listings where you attempt this or is it specific to a particular user? Are you still able to duplicate it?

**Comment by yovasx2** [comment]
4 users reported and i showed u in SS a product belonging to our internal shop, the id is useful?

**Comment by yovasx2** [comment]
this is the payload of the active listing I created:
```
{
    "listing_id": 1308973537,
    "user_id": 187478679,
    "shop_id": 18976342,
    "title": "digital",
    "description": "digital",
    "state": "active",
    "creation_timestamp": 1663648386,
    "created_timestamp": 1663648386,
    "ending_timestamp": 1674192786,
    "original_creation_timestamp": 1663648385,
    "last_modified_timestamp": 1663648409,
    "updated_timestamp": 1663648409,
    "state_timestamp": 1663648385,
    "quantity": 1,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1308973537/digital",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "collective",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
        "amount": 100,
        "divisor": 100,
        "currency_code": "USD"
    },
    "taxonomy_id": 66,
    "production_partners": [],
    "skus": [],
    "shipping_profile": null,
    "shop": null,
    "images": null,
    "user": null,
    "translations": null,
    "inventory": null
}
```

**Comment by yovasx2** [comment]
the payload that changes the listing is:
curl:
```
curl --location --request PATCH 'https://openapi.etsy.com/v3/application/shops/18976342/listings/1308973537' \
--header 'x-api-key:' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "instant2",
    "item_weight_unit": "oz",
    "item_dimensions_unit": "in"
}'
```
response:
```
{
    "listing_id": 1308973537,
    "user_id": 187478679,
    "shop_id": 18976342,
    "title": "instant2",
    "description": "digital",
    "state": "active",
    "creation_timestamp": 1663648386,
    "created_timestamp": 1663648386,
    "ending_timestamp": 1674192786,
    "original_creation_timestamp": 1663648385,
    "last_modified_timestamp": 1663651486,
    "updated_timestamp": 1663651486,
    "state_timestamp": 1663648385,
    "quantity": 1,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1308973537/instant2",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "collective",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
        "amount": 3000,
        "divisor": 100,
        "currency_code": "USD"
    },
    "taxonomy_id": 66,
    "production_partners": [],
    "skus": []
}
```

**Comment by yovasx2** [comment]
also having the same bad change when u send units for weight or dimensions, the endpoint receives them but no update is made just the "instant" change:

```
curl --location --request PATCH 'https://openapi.etsy.com/v3/application/shops/18976342/listings/1308973537' \
--header 'x-api-key:' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "instant2",
    "item_weight_unit": "oz",
    "item_dimensions_unit": "in"
}'
```

**Comment by etsyachristensen** [comment]
Ahhhh Ok. That's what I was missing. I wasn't setting `type` in my PATCH. I was only changing the title. NOW I see it. Sure enough my test listing now says Instant Download. We'll get on this ASAP.

We'll look into the dimensions as well.

**Comment by yovasx2** [comment]
thanks @etsyachristensen, you are the best

**Comment by etsyachristensen** [comment]
@yovasx2 Ok I've just pushed a fix for this.

**Comment by yovasx2** [comment]
for both cases?
