### ISSUE TITLE
[BUG]: Tracking number required when attempting to complete an order

### ISSUE THREAD

**Issue by nmrdxt** [etsy/open-api#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When posting to createReceiptShipment with an array that does not include tracking_code and carrier_name (only send_bcc = false), Etsy responds with "A tracking number is required" error.

The merchant was able to complete the order on Etsy without including a tracking number.

Order ID is 2598717198, if needed.

Thanks!

### Steps to reproduce

Post to createReceiptShipment, with payload `[send_bcc' => false]`, some orders return with an errors of "A tracking number is required".

### Expected behavior

Since it was possible to complete order #2598717198 without a tracking number, I expect to be able to complete the order without a tracking number through the API as well.

**Comment by sowsinsk** [comment]
@nmrdxt We are able to post to createReceiptShipment without specifying a carrier / tracking code. We **are** specifying a `note_to_buyer` field, however. Maybe that is required in order to complete a shipment without tracking.

**Comment by etsyachristensen** [comment]
@sowsinsk You are correct. That is happening. We've added it to our list. Will try to correct this soon.

**Comment by etsyachristensen** [comment]
@sowsinsk we got some clarification from our fulfillment team. A change was instituted some time back that requires all orders in the US to require tracking codes and carriers if the order is over $10. We will be updating the OpenAPI documentation and adding appropriate return codes for this.

**Comment by sowsinsk** [comment]
@etsyachristensen thank you for the update. You mentioned that this is for US orders only. Does this mean we can continue using the createReceiptShipment endpoint without tracking codes/carriers for orders shipping _outside_ the US? This is how we are getting around issue #569 (our international shipping partner is not currently supported). Thank you!

**Comment by etsyachristensen** [comment]
Correct. For international orders (other than India) the tracking code and carrier are not required.

**Comment by sowsinsk** [comment]
Quick follow-up about this. The Etsy web admin console allows the selection of "Other" for the carrier, and a freeform tracking code. Is "Other" a valid option for the API for the carrier?

**Comment by etsyachristensen** [comment]
Yes, "other" should work just fine. This would allow you to also enter a tracking code.
