### ISSUE TITLE
[BUG]: Listings getting translated automatically when changes applied over them

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A customer reported all the listings were translated from french to english in the title, the tags, and the description (normal translation fields), when she update the listings via API (no further details), the shop is in french and the majority of listings are language en-US (API is not capable to modify this, and it doesn't match with the shop main one), some listings are having language MACHINE_en  (which is weird), none listing is having translations, all are null.

### Steps to reproduce

the user mentioned she updates tags, title, or description and then everything gets translated, we don't handle translations so my deduction is this is happening on your side or maybe another 3rd party app (not sure if it is the case but I don't think so),

We requested a change of default language for one of our internal shops to have more insight about translations issue and try to reproduce it in the future, this is the shop: 18976342, we requested to convert it into spanish

### Expected behavior

not to translate things automatically

### Additional context

shop id 18546390
the unique french product 1293375606 (the rest is english or MACHINE_en)

**Comment by yovasx2** [comment]
CC @jasonpincin @etsyachristensen this seems to be urgent people continue reporting this but nobody has provided details about the execution and I cannot reproduce it in the internal shops

**Comment by etsyachristensen** [comment]
Ok your shop is changed to Spanish. I had to add some strings to the titles and descriptions on all your listings so that our system would allow it.

**Comment by yovasx2** [comment]
> Ok your shop is changed to Spanish. I had to add some strings to the titles and descriptions on all your listings so that our system would allow it.

Thx a lot, let me know if u find something related with the translations issue
