### ISSUE TITLE
[FEATURE]: Preserve the ShopAbout endpoint

### ISSUE THREAD

**Issue by rajivraman** [etsy/open-api#595]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

I would like information that is only provided by the v2 ShopAbout endpoint.

### Describe the solution you'd like

Preserve the v2 ShopAbout endpoint.

### Describe any alternatives you've considered

None; the information is not accessible anywhere in the v3 API.

**Comment by etsyachristensen** [comment]
This is being tracked in the discussion board under Ideas category.
