### ISSUE TITLE
[BUG]: is_personalizable is returned as false when we sent true

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After creating a product draft and hit patch to update is_personalizable as true, the response is returned as false (only the first hit, GETs and subsequent PATCHes are correct)

### Steps to reproduce

create draft:

curl --location --request POST 'https://openapi.etsy.com/v3/application/shops/18976342/listings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "gio",
    "description": "gio",
    "quantity": 1,
    "price": 1,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": "false",
    "shipping_profile_id": 172246891939,
    "taxonomy_id": 1,
    "production_partner_ids": [],
    "item_weight_unit": "oz",
    "item_dimensions_unit": "in"
}'
hit update: 

curl --location --request PATCH 'https://openapi.etsy.com/v3/application/shops/18976342/listings/1296106626' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "7324876",
    "shop_id": 25203,
    "_hive_is_invalid": false,
    "_hive_invalid_reason": "null",
    "listing_id": 1295998516,
    "state": "draft",
    "modified_by_hive": true,
    "last_modified_tsz": null,
    "_hive_last_modified_tsz": 1663782194,
    "title": "gio",
    "description": "gio",
    "creation_tsz": null,
    "ending_tsz": null,
    "price": 1,
    "quantity": 1,
    "state_tsz": null,
    "taxonomy_id": 1,
    "section_id": null,
    "tags": [],
    "materials": [],
    "_hive_on_new_schema": false,
    "_hive_changed_properties": [
        "createProduct",
        "photos",
        "attributes"
    ],
    "_hive_last_sync": null,
    "templates": null,
    "images_count": 0,
    "should_auto_renew": "false",
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "made_to_order",
    "original_creation_tsz": null,
    "sales_profile_id": null,
    "is_complete": false,
    "is_copied": false,
    "is_digital": false,
    "production_partner_ids": [],
    "files": [],
    "item_weight_unit": "oz",
    "item_dimensions_unit": "in",
    "is_personalizable": true,
    "personalization_is_required": true,
    "personalization_char_count_max": 1,
    "personalization_instructions": "1",
    "shipping_profile_id": 172246891939,
    "type": "physical"
}'

### Expected behavior

get back the response matching with the sent data (is_personalizable)

**Comment by yovasx2** [comment]
today is not reproducible, but i got a video that proves it was yesterday

**Comment by etsyachristensen** [comment]
It was likely a caching issue yesterday. If it continues to happen let us know. But the system should refresh the cache for that listing after an update.

**Comment by yovasx2** [comment]
i cannot reproduce it anymore i will close this
