### ISSUE TITLE
[BUG]: URGENT insufficient_scope error in my API calls

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My Etsy app receives this error message for the last few hours: "error":"insufficient_scope","error_description":"Insufficient scope"

It started 18:22 UTC time
Nothing has changed from my side
I sent an email to developer@etsy.com as well
Can you help with urgently look into this from your end?

### Steps to reproduce

Perform any API call

### Expected behavior

Valid result

**Comment by x-bass** [comment]
+1 same issue

**Comment by RoeiKO** [comment]
We are having the same issue as well. Trying to call "users/*userId*/shops" results in the same error, however when calling POST "scopes" with the token, the response shows that we access to all the scopes.

**Comment by assaflei** [comment]
I can update that installing our app again by the affected shops solved the problem
It looks like a change done to the scope for shops that connected with us long time ago

**Comment by evangelosdaniil** [comment]
Hey @etsyachristensen, thank you for your response. We also face this issue when calling `users/userId/shops`. Our customers have authenticated to our platform without the `shop_r` scope because it was not required to get the user shops. Does this mean that our customers have to reconnect?

**Comment by thegoodbyte** [comment]
Hello Andrew,
I hope you are doing great!

I am getting tons of these emails and do not know how to
Unsubscribe . Could you please unsubscribe me?

Thanks!

**Comment by RoeiKO** [comment]
> 

Thanks for the reply! We do have shops_rw. Should we change it to shops_r and shops_w?

**Comment by etsyachristensen** [comment]
Yes please. OpenAPI V3 does not use the _rw naming convention. They need to be separate.

**Comment by RoeiKO** [comment]
> Yes please. OpenAPI V3 does not use the _rw naming convention. They need to be separate.

We currently use the v2 api to authenticate our users, and use token_exchange to work with the new API until we finish migrating all the functions on our end. We do have access for the shops_rw scope, we hoped it would've worked with the token_exchange as well. Anyways this is no longer an issue for us, we will work it out now that we understand what the problem is. Thank you for the quick help, much appreciated.

**Comment by peterlamber** [comment]
@etsyachristensen would have been great to get a heads up for these kind of changes, maybe like in the form of what has been done here https://github.com/etsy/open-api/issues/405

**Comment by maxim-skuvault** [comment]
> @etsyachristensen would have been great to get a heads up for these kind of changes, maybe like in the form of what has been done here #405

This is absolutely a must to notify API consumers **ahead of time**. It's ridiculous that they just changed security in production unannounced. In addition to https://github.com/etsy/open-api/issues/405 mentioned above, there's also https://github.com/etsy/open-api/discussions/categories/announcements (although it doesn't appear I can subscribe). A developer email list would be good too (we're yet to find one?!). Somewhere, anywhere🤦

**Comment by etsyachristensen** [comment]
@maxim-skuvault and @peterlamber you are correct. We should have put out comms but there was an internal mix-up. This is being rolled back shortly and we will re-introduce it later with proper notification. We will add the notification to the announcements. I'm not sure about an email list to be honest. I will have to check on that.

**Comment by etsyachristensen** [comment]
This change has been rolled back. We apologize for the inconvenience. If you've already adjusted for the change, you shouldn't need to do anything to change back. We will re-institute this scope change in the future after we have notified you of the date we expect to make the change live.

**Comment by maxim-skuvault** [comment]
> This change has been rolled back. We apologize for the inconvenience. If you've already adjusted for the change, you shouldn't need to do anything to change back. We will re-institute this scope change in the future after we have notified you of the date we expect to make the change live.

@etsyachristensen Thank you for responding and rolling this back
