### ISSUE TITLE
[DOCS] Clarification for "Making Requests" and Public Requests

### ISSUE THREAD

**Issue by turboturtleD** [etsy/open-api#60]
Looking at the getting started docs under Making Requests
(https://www.etsy.com/developers/documentation/getting_started/oauth2#section_making_requests)

It states:
"Requests other than those to URLs beginning with https://api.etsy.com/v3/public must also have an authorization header, with the value being Bearer <access token>. Public requests may include this header as well."

This is however pretty much the extent of information about making public calls.  I have not found any additional references to the public path: **https://api.etsy.com/v3/public** or how to use that as a base url to make any actual public endpoint requests.

It seems inferred that the public path could be used to access public endpoint resources, but not sure how one would structure a public request url due to lack of examples or further documentation beyond how to ping "https://api.etsy.com/v3/public/ping"

**What would you like to change?**
Please add an example for a public endpoint url, or clarify the purpose of the public base url

**Comment by harjas** [comment]
Hello @turboturtleD! Good catch! The v3 OpenAPI doesn't have any `/public` prefixed endpoints (anymore). They did exist temporarily while the API was in development. 

We'll update the OAuth documentation to remove any instances of `/public` endpoints. Let us know if there's anything else we can help clarify!

**Comment by turboturtleD** [comment]
I appreciate the insight on that.  Unfortunately, I am still unable to get a response from any endpoints besides  https://api.etsy.com/v3/public/ping or https://api.etsy.com/v3/member/ping from which I receive "pong" responses for both.  Every other endpoint I try to reach I receive body: '{"error":"Resource not found"}'.

Have not been able to get any response from developers@etsy.com for about a week.  Any additional insight provided would be tremendously appreciated.  Trying to work on a SDK for NodeJS, however without being able to get actual server responses, one can only get so far.

**Comment by jkassel** [comment]
I tried both https://openapi.tesy.com/v3 and https://api.etsy.com/v3 endpoints.  Include both x-api-key and Oauth in headers.  every response is {'error': 'Resource not found'}.  Any assistance would be appreciated.

**Comment by YodaBebe** [comment]
@jkassel I am having  the same issue. 

Currently I am just trying to request a public resource (listings) for testing - so only including my x-api-key in the headers. Also getting the same “Resource not found” response as you.

On the v3 homepage it says:

**If you would like to make requests to the Open API v3 endpoints, please fill out the intake form.**

Have you filled that out? Additionally, many endpoints are labeled as “access-controlled” and say that you must email the developer team for access. Have you done any of that? I have not - and am hoping it’s just a permission thing? I am a bit confused by the launch stages calendar.

**Comment by turboturtleD** [comment]
This is most likely a "permission thing".  It seems that everyone that has had this problem was able to resolve it when the Etsy admins add you to the whitelist.  As noted above, you would need to email the developer team for access, I would recommend including your API key in the email as well as your GitHub handle.

**Comment by YodaBebe** [comment]
@turboturtleD Thank you so much for your reply!! I filled out the access request form on the api 3 documentation site yesterday after I posted here. If I don’t get a response in a week or so I will try emailing as you suggested. Thanks again!
