### ISSUE TITLE
How to create an etsy app

### ISSUE THREAD

**Issue by janeyfang** [etsy/open-api#600]
I'm in https://www.etsy.com/developers/your-apps created 3 apps to prepare for my EPR order to be shipped, but none of them were approved, and there was no specific reason for the failure.Emailed the developer@etsy.com also received a reply.Tell me, what are the key factors for the approval of the etsy app app?

**Comment by tuan2061996** [comment]
me too :-(

**Comment by etsyachristensen** [comment]
If anyone is still having issues, please try your submission again.
