### ISSUE TITLE
[BUG]: update listing property property_id

### ISSUE THREAD

**Issue by jon-chambers** [etsy/open-api#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The property_id values seem to be completely random, and there is no way for my application to know which to submit

### Steps to reproduce

Starting with this call here: https://developer.etsy.com/documentation/reference/#operation/updateListingProperty

No links to where I find each value_id, but with some reverse engineering I have found a few.

I create a listing, and I notice the property id 102868017229 links to "Number of skeins" and the value for "1" is 111724299600.

This is performed by creating the listing, then performing this call here: https://developer.etsy.com/documentation/reference/#operation/getListingProperties

I can then change the number of skeins to "2" and get a new value of 111780639460. "3" returns 112304030246.

From there, I can analyse the pattern and note that

111724299600 = 1
111780639460 = 2
112304030246 = 3

So far so good, and hopefully I should be able to work out the corresponding value for 4. I cannot.

Meanwhile, 102448162292 corresponds to "Ribbon length", and the listing I created is for a 165m yarn. The value_id for "165" for "Ribbon length" is 112619026042.

I also sell yarns in lengths that are not 165m.

What is the correct way of determining the value_id for any given length of yarn?

### Expected behavior

property_id shouldn't be required at all

**Comment by etsyachristensen** [comment]
@jon-chambers This is an area of the system that gets deep in the weeds as it relates to inventory indirectly. Every property has a property_id and it will be required in order to update the property.

The values are a different animal. The value_ids are a unique id that is generated for your listing/property. These are not shared with other listings and other shops. There is no pattern to it.

When you are first updating a listing with properties, you can simply submit the values as a comma delimited list of values. So in your example for skeins it would be something like "1,2,3,4". When adding a new value to the array, use the `values` array and not the `value_ids` array. The `value_ids` are more useful when adding variations to your inventory. For the properties you can use the `value_ids` array if you have all the value_ids already.

**Comment by Gareth064** [comment]
The nuances of trying to use this API seem insanely complex. I think we are gonna need more "How to" documentation to explain all these things and include good examples!

**Comment by jon-chambers** [comment]
@etsyachristensen if this is correct, then the documentation is false.
https://developer.etsy.com/documentation/reference#operation/updateListingProperty
The documentation says that value_ids is **_required_**.

**Comment by etsyachristensen** [comment]
You are correct, but it's simply because at least one of them is required. The documentation engine doesn't do well with conditionally required items. We'll try to add a note to the docs to help reduce that confusion.

**Comment by jon-chambers** [comment]
@etsyachristensen it's worse than that. The documentation says "Each offering requires **_both_** a value **_and_** a value_id that are valid for a scale_id assigned to the listing or that you assign to the listing with this request."

I don't think the documentation engine wrote that sentence.

**Comment by jon-chambers** [comment]
![image](https://user-images.githubusercontent.com/55141624/196067230-6ead9d4c-b07a-4893-af66-bf36ec7e9f74.png)
Even the error message seems to suggest that value_ids ARE required. What am I doing wrong here?

**Comment by jon-chambers** [comment]
What am I doing wrong?
![image](https://user-images.githubusercontent.com/55141624/196296493-c07bab71-1a47-4a58-b7e7-27840c022173.png)
![image](https://user-images.githubusercontent.com/55141624/196296696-561cd87f-1363-4575-a899-ca1e814d025d.png)
![image](https://user-images.githubusercontent.com/55141624/196296833-ab048daa-305c-4663-828b-b91ea8e79d64.png)
The "attributes" message has a hyperlink to https://openapi.etsy.com/attributes which leads to a page that reads "not found"
I'm stuck.

**Comment by jon-chambers** [comment]
> My apologies @jon-chambers. I was mixing this up with updating inventory. 🤦
> 
> For updating the properties, all of the scale ids and their values/value_ids come from the taxonomy system. You would call to [getSellerTaxonomyNodes](https://developer.etsy.com/documentation/reference/#operation/getSellerTaxonomyNodes) and look for the appropriate category for the listing. So for Yarn, you'd be in taxonomy id 6243. You'd then call to [getPropertiesByTaxonomyId](https://developer.etsy.com/documentation/reference/#operation/getPropertiesByTaxonomyId) to get the possible properties, including custom properties. If the `scales` value is empty, there are no scale_ids to use so you can leave that out. If the possible_values is an empty array, this means that you can pass any value. For value_id I believe you can use an empty array in this case as there isn't already a value_id created for that value yet. If the properties do show a list of possible values, you can choose one or more of those values. If the `is_multivalued` is false you can only pass in a single value.

Almost. Empty arrays throw an error. It must be an integer greater than zero. "1" works. Could we have this call working without the "1" be a feature request? I can see how that would be a pain, but not as painful as writing the documentation around "value_ids: 1" everywhere.

There is absolutely no way I could have figured this out on my own without coming here. Maybe I'll get better at this one day, but figuring out this API from the documentation as written is well above my current skill level.

**Comment by jon-chambers** [comment]
> My apologies @jon-chambers. I was mixing this up with updating inventory. 🤦
> 
> For updating the properties, all of the scale ids and their values/value_ids come from the taxonomy system. You would call to [getSellerTaxonomyNodes](https://developer.etsy.com/documentation/reference/#operation/getSellerTaxonomyNodes) and look for the appropriate category for the listing. So for Yarn, you'd be in taxonomy id 6243. You'd then call to [getPropertiesByTaxonomyId](https://developer.etsy.com/documentation/reference/#operation/getPropertiesByTaxonomyId) to get the possible properties, including custom properties. If the `scales` value is empty, there are no scale_ids to use so you can leave that out. If the possible_values is an empty array, this means that you can pass any value. For value_id I believe you can use an empty array in this case as there isn't already a value_id created for that value yet. If the properties do show a list of possible values, you can choose one or more of those values. If the `is_multivalued` is false you can only pass in a single value.

Actually, my solution didn't work either.

Empty array throws an error. And 1... leads to the funniest error I have ever seen in my life! I'll c/p:

"property_id":102868017229,"property_name":"Number of skeins","scale_id":null,"scale_name":null,"value_ids":[1],"values":["Black"]} "

So, the number of skeins per qty, is "black". Black, is a perfectly acceptable integer, for describing the number of skeins that come with your order. This is because an id of "1" corresponds to "black".

It gets funnier, because I actually got it working as I mentioned before. It works, because I found that the id that corresponds to "1" is "111724299600".

So, according to Etsy:
1 = Black
2 = Blue
...
11 = Yellow
...
51 = Abaca
...
542 =Crewel
...
1031 = 1 Fingering & Sock
...
1222 = Yes
1223 = No
...
Then you keep going all the way to
111724299600 = 1
111780639460 = 2
112304030246 = 3

Thank you for the laugh. I'm glad I'm not developing from within Etsy.

**Comment by jon-chambers** [comment]
New information again... The error message was wrong.

`"error": "IDs must be >= 1, got 0"`

It is correct that 0, negative values, strings, and arrays throw errors, and that all errors direct to inputting positive integers, BUT leaving the field completely blank (which I never even thought could be a thing) runs the call exactly as intended!

I strongly recommend finding the function that throws `"error": "Missing input parameter: [value_ids]"` and have it not throw that error when value_ids are not required. My workflow is starting to enter "I never would have guessed this, and it's not in the documentation" territory. I have no idea how all the other devs are coping with this. I hope my skill will reach theirs one day.

**Comment by etsyachristensen** [comment]
Apologies for that confusion Jon. We will update our documentation to reflect that a blank value is expected for value_id when adding a new value.

**Comment by jon-chambers** [comment]
I wouldn't recommend that.

I understand the danger in updating a live system, as it can absolutely cripple projects written by developers who have moved on with their careers and cannot come back to maintain their work.

However, it is possible to update the system so it runs as expected when the value is blank, but stops throwing an error when it isn't blank. If you are practising test-first test driven development, that should be 5 minutes work to implement and maybe some overnight automated tests to check it won't break anything already developed, making it ready for deployment the following morning.

So instead of changing the documentation to match the system, change the system to match the documentation.

Otherwise, you're just advertising that your system is awkward to work with.
