### ISSUE TITLE
[DOCS]: getShopByOwnerUserId need token

### ISSUE THREAD

**Issue by VaneiLu** [etsy/open-api#608]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Link to Documentation Issue

https://developer.etsy.com/documentation/reference#operation/getShopByOwnerUserId

### What would you like to change?

The documentation does not show that the header requires a token, but this api need token actually.

### Why are you proposing this change?

Incomplete documentation can mislead other users.

**Comment by etsyachristensen** [comment]
@VaneiLu We had added the shops_r scope to the endpoint, but we realized that this was a breaking change and causing errors. We backed that out and put in a check to ensure that the user is logged in. This acts essentially as a token requirement without throwing a bad error. This way we can manage the return to not be as bad. We will eventually add the scope requirement, but need to schedule this in advance. When we do that, the documentation will update automatically.
