### ISSUE TITLE
[BUG]: No ApiKeyIndex for keystring= service=v2_prod

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling https://openapi.etsy.com/v2/oauth/request_token we are getting a new error message: 
No ApiKeyIndex for keystring= service=v2_prod

This is happening for the last few hours,
Can someone take a look and update ASAP

### Steps to reproduce

Invoke authentication flow based on version 2

### Expected behavior

Authentication successful

**Comment by asonix** [comment]
This is also affecting ShippingEasy

**Comment by mjec** [comment]
Hi folks, I'm on the API team at Etsy. Thanks for the report. We've verified the bug and are preparing a fix.

**Comment by mjec** [comment]
The fix for this is now in production. If you encounter this condition again, please reopen this bug. If you encounter other issues, don't hesitate to file a new bug report.

**Comment by asonix** [comment]
thank you!
