### ISSUE TITLE
[BUG]: For special user all (not ping, getScopes and refresh) requests show "Exceeded daily rate limit"

### ISSUE THREAD

**Issue by ToWorldMe** [etsy/open-api#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I do request for shop 37968246 from My application. For all another shop, what was authotized in app - all good. For this shop I got every time 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/6914579/193638788-ca685118-822c-428e-9e30-e70a6256d2ff.png">

### Steps to reproduce

1. Refresh token
2. do any request (non ping or getScopes - these work correct)
3. Get error

### Expected behavior

Get correct answer

### Additional context

It happen only with one shop. App id xxxxxx

**Comment by ToWorldMe** [comment]
Magically solved

**Comment by ToWorldMe** [comment]
Issue not solved: it happens on random api request

**Comment by etsyachristensen** [comment]
@ToWorldMe Is the id you gave a USER id or a SHOP id? If it's a shop, they don't have your app authorized on their account so any calls to any information on their shop would have to be public and would go against your global rate limit, not the limit for that user.

Second, I see your app listed as not yet approved so I'm not sure how you are able to make any api calls at all. Are you sure you gave me the right app id?

**Comment by ToWorldMe** [comment]
@etsyachristensen It is shop id. I have authorised token for this user, I can refresh it, request a scope, but can't request any information. Sometimes it start working, sometimes it stop working. I don't have any issues with other shops, I have an issue only with 37968246 shop id. And it is not stable: some request can start working (like a 2-3 - getShop & getTransactions) and after that I can get this error.

My app has Personal access

**Comment by etsyachristensen** [comment]
@ToWorldMe Is this still occurring for you? Apologies for the delay in getting back to you on this.

**Comment by ToWorldMe** [comment]
@etsyachristensen Problem solved. It happens sometimes with new users, but solved automatically after some time.
