### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by sdumper** [etsy/open-api#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Repeatedly getting refused access to my own shop when requesting API keys. Ive tried filling out the form 20 different ways and i always get refused. This access is for my own shops.

### Steps to reproduce

Create an application for a api access following trhe exact Etsy guidlines.
Submit wait a few days and get rejected for some random reason. Varies form invalid business use case to incorrect or invalid etsy url... 

### Expected behavior

Read only access granted to access my own shop

### Additional context

App name: Zipper

I am so frustrated....

**Comment by sdumper** [comment]
![image](https://user-images.githubusercontent.com/46971452/194891846-3a1314f1-bf32-4a0d-b6d7-519ff95e7cd4.png)

**Comment by etsyachristensen** [comment]
Someone will be reaching out to you directly about this issue.

**Comment by Gareth064** [comment]
@sdumper - if someone does reach out to directly, can you post back here what happened to get you moving?

You mention this was to access you own shop**s**. Does that mean you have more than one Etsy Shop? If so, then Etsy don't have the concept of one user multiple shops. So, if you created your app using an API key on one of your logins, then its technically only for the single shop which that login is associated to. The other shops you may own, which have a different login, will just be seen as you wanting to share your app with other users, and that might be where the App needs to be registered?
