### ISSUE TITLE
Shop Listings Views[FEATURE]: 

### ISSUE THREAD

**Issue by hbmemati** [etsy/open-api#618]
### Is there an existing ticket for this?

- [x] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

The number of views of the listings in the old v2 version is not visible in the v3 version.

### Describe the solution you'd like

Displaying the number of views of the listings. At the same time, while it is possible to exchange data much faster by specifying only certain information with fields, the response times are now longer due to unnecessary information.Fields section should come to v3 as well

**Comment by Gareth064** [comment]
You know, now that you mentioned it. I remember optimising my calls to v2 by using the Fields options on the call. It helped with response times significantly. I have not fully migrated to v3 yet, so I am hoping it isn't too much slower because it is returning everything.

**Comment by hbmemati** [comment]
> 

unfortunately much slower

**Comment by etsyachristensen** [comment]
@hbmemati The views request is already being tracked in #122 and the fields request is already being tracked in #209. We will close this in favor of tracking in those tickets.
