### ISSUE TITLE
[DOCS]: getUser BREAKING CHANGE (10/11/2022) and getReviewsByShop clarification

### ISSUE THREAD

**Issue by gerlv** [etsy/open-api#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Link to Documentation Issue

https://github.com/etsy/open-api/issues/405#issuecomment-1275082729

### What would you like to change?

Could you clarify if this affects the `getReviewsByShop`?

`getReviewsByShop` only returns a `buyer_user_id` which is used to request `getUser`, but from the example in the announcement, it looks like the request to `getUser` can only be made by the user (I.e. The requesting user matches the requested user).

Can we get user name + image by calling `getUser` with `buyer_user_id` from `getReviewsByShop`?

### Why are you proposing this change?

Add clarification about the getting user name + image from `getReviewsByShop`

**Comment by jasonpincin** [comment]
Good question. It does affect `getReviewsByShop` @gerlv - if you are the owner of the shop in question, you will be able to call `getUser` to fetch that information; otherwise, you will be unable to do so.
