### ISSUE TITLE
[BUG]: getListingsByListingIds and skus

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The result from [getListingsByListingIds](https://developer.etsy.com/documentation/reference#operation/getListingsByListingIds) returns an empty array of sku although the listing has variations with skus

The data is returned as expected when using [getListingsByShop](https://developer.etsy.com/documentation/reference#operation/getListingsByShop)

### Steps to reproduce

Invoke getListingsByListingIds with listing id 1250507006 or 933280792 for example

### Expected behavior

Object with array of skus containing sku values

**Comment by assaflei** [comment]
@etsyachristensen can you please advice?

**Comment by etsyachristensen** [comment]
@assaflei When you call to `getListingsByListingIds` are you passing a token that belongs to the user that owns the listings? The skus will only return for the owner of the listing. Calling getListingsByShop would return the skus because that is scoped  to the owner of the shop.

**Comment by assaflei** [comment]
@etsyachristensen when invoking the request I include Inventory data which includes sku in the internal items, does this mean that I use the owner?
In case the sku returns as part of the inventory object, why isn't it included in the item at the root of the result object?

**Comment by etsyachristensen** [comment]
When you care invoking the `getListingsByListingIds` you are adding `Inventory` to the "includes" parameter correct? So you are saying that the skus DO show up in that call inside of inventory but NOT at the listing object level? Can you give me an example shop/listing where you are seeing this?

**Comment by assaflei** [comment]
Sure, shop id: 23764243
listing id: 1320471793

**Comment by assaflei** [comment]
@etsyachristensen any updates?

**Comment by etsyachristensen** [comment]
@assaflei I just tested this and you are correct. We actually have a bug here in that the inventory should not be returning skus when included on the listing. I tried calling getListingInventory on that same listing and it does not have the SKUs in it because I am not the listing owner. We will correct this behavior.

**Comment by assaflei** [comment]
So the expected behavior is not to have skus at the root of the result object and in the internal children also?

**Comment by etsyachristensen** [comment]
Correct. The SKUs should only appear if the requesting (authenticated user with token) is the owner of the listing.

**Comment by assaflei** [comment]
So if I get the sku details in the inner objects, it means I'm using the authenticated user, right? 
And the skus should appear at the root as well aren't them?

**Comment by assaflei** [comment]
Thanks for clarifying,
I will now return to the issue I raised originally,
The skus are missing from the root object, is this a bug that will be handled?

**Comment by etsyachristensen** [comment]
If the call is being made to our system WITH an OAuth token that belongs to the owner of the listing, then yes the skus should be showing up. Can you post your full payload (but redact part of the auth token and api key)?

**Comment by assaflei** [comment]
```
curl --location --request GET 'https://openapi.etsy.com/v3/application/listings/batch?includes=Inventory&listing_ids=1320471793' \
--header 'Authorization: Bearer some_token' \
--header 'x-api-key: some_key' 
```

I hope that this is what you mean by the payload, skus array is empty while Inventory collection contains values of skus

**Comment by etsyachristensen** [comment]
Thank yeah. It actually might help to see the return headers, specifically the etsy-request-uuid variable. That will help me get to the bottom of this. Thanks!

**Comment by assaflei** [comment]
Here are the headers, update me if more are required
Thanks

```
X-Etsy-Request-Uuid: EuAxP4Eg-GeFL9YdLpjYKh8pWs0c
X-CLOUD-TRACE-CONTEXT: f0a59dc62fc252f2ee2d7109438c5fb6/9570295750204698170;o=0
```

**Comment by assaflei** [comment]
@etsyachristensen any updates?

**Comment by etsyachristensen** [comment]
@assaflei We are working on a fix.

**Comment by etsyachristensen** [comment]
@assaflei This fix has been deployed.

**Comment by assaflei** [comment]
Hi @etsyachristensen could this change affect this new bug?
https://github.com/etsy/open-api/issues/630

**Comment by nmrdxt** [comment]
Looks like after the recent update, inventory array in getListing (with Inventory included) is returning empty strings for SKUs, even though the listing is owned by the user.
