### ISSUE TITLE
[BUG]: cant find/get shopId in V3 of the APi

### ISSUE THREAD

**Issue by bilpor** [etsy/open-api#626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

using /shops/{shop_id}/receipts in V2 Shop_id was a string (the shop name) all worked. In V3, you changed this to an integer. I cannot finid or set this value anywhere. It was suggested that I use the call getShop, but that needs the shopId as well and if I knew that, then I wouldn't need to make that call. It was then suggested that I use getShopByOwnerUserId, the issue with that call is that that also wants an integer value for UserId and I have no way of setting or finding the integer value of the user.

Can someone give clear guidance on how I am supposed to get the shopId Which calls will give me this.

### Steps to reproduce

none, just trying to use a call that I cant get all information too

### Expected behavior

obtain shop details including the id

### Additional context

Please see dialogue between myself and Chris at Etsy Support request number 9611762

**Comment by Gareth064** [comment]
I added an answer to your discussion about this same topic #625

**Comment by devtronic** [comment]
The User Id is included in the access token (`user_id.token`)
Using the user id you can call `GET /users/{_userIdFromAccessToken}/shops` to retrieve the shop including the ids.

**Comment by etsyachristensen** [comment]
We are actually working on a new endpoint you can call that will return the user's id and the shop's id. Should be available soon. I wouldn't trust that the user_id in the token as that may change in the future.

**Comment by etsyachristensen** [comment]
We have just implemented a new endpoint that you can call after a user authorizes your app:

https://developers.etsy.com/documentation/reference#operation/getMe

This will return the shop_id and user_id for the given authenticated user.
