### ISSUE TITLE
[ENDPOINT]: Proposed design change for getShopReceipts

### ISSUE THREAD

**Issue by KushGoyal** [etsy/open-api#629]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

Cancelled orders are not included in the results for `getShopReceipts`. If an order is cancelled the `updated_timestamp` is also updated. But when filtering using `min_last_modified` the cancelled orders not present in the response.

### Proposed Endpoint Design Change

Cancelled orders should be included in the response of `getShopReceipts`.

### Why are you proposing this change?

Because of this I have to check the status of each order which results in a lot of requests. This is bad for both my server and Etsy server. Easy method would be to include orders of all status in the `getShopReceipts` response.

**Comment by chrisrogala** [comment]
There is already an open issue for this here: https://github.com/etsy/open-api/issues/604

I recommend adding any comments to that one and closing this issue.

Chris
