### ISSUE TITLE
[ENDPOINT]: Proposed design change for getUser

### ISSUE THREAD

**Issue by lelinhtinh** [etsy/open-api#632]
### Is there an existing issue for this?

- [X] I have searched the existing tickets

### Current Endpoint Design

In a recent update, the `is_seller` property has been removed.

### Proposed Endpoint Design Change

Return the `is_seller` property, or something that indicates the shop has stopped selling.

### Why are you proposing this change?

The shop is down but the API is still accessible - this consumes a lot of unnecessary requests, in my case: check new receipts.

**Comment by etsyachristensen** [comment]
@lelinhtinh This was a part of the breaking changes announced here: https://github.com/etsy/open-api/issues/405#issuecomment-1275082729. We will likely not return this value in the future.
