### ISSUE TITLE
[BUG]: sort order is not sorting correctly for find All Listings Active

### ISSUE THREAD

**Issue by switmac** [etsy/open-api#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I send a request to `{{baseUrl}}/v3/application/listings/active`
it provides the same order of results 
the sort `asc` `desc`  is not working properly

please note that is sorted on score

`ASC {{baseUrl}}/v3/application/listings/active?limit=100&keywords=Yoga Pants&sort_on=score&sort_order=asc` 
![image](https://user-images.githubusercontent.com/3896300/197669950-d4e91df5-4e53-4e6a-877e-781068331658.png)

`DESC {{baseUrl}}/v3/application/listings/active?limit=100&keywords=Yoga Pants&sort_on=score&sort_order=desc`
![image](https://user-images.githubusercontent.com/3896300/197669758-7c655db0-7453-47e6-9bfa-ff3dd696bd63.png)

### Steps to reproduce

1 Open postman or similar app
2 Send the sample API request provided above
3 Notice the result of the first 2 listings ids for desc and asc requests 
4 The results are the same

### Expected behavior

I am expecting the listing order of results for desc and asc to be different.

**Comment by etsyachristensen** [comment]
@switmac Apologies for the confusion. Our system doesn't actually do an ascending order sort on "score" (internally referred to as relevancy). So if you use "score" for `sort_on` it will always return the results in "desc" order. We will adjust the documentation accordingly as soon as we can.
