### ISSUE TITLE
[FEATURE]: Add batch Shops endpoint or modify existing getShop endpoint

### ISSUE THREAD

**Issue by switmac** [etsy/open-api#635]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

We are trying to get the updated data for the shops we have regularly 
as part of the monitoring whether there are shops that have changed or updated their data

we are currently using this endpoint 
[https://openapi.etsy.com/v3/application/shops/{shop_id}](https://openapi.etsy.com/v3/application/shops/%7Bshop_id%7D) getShop

however we run at about 100k shops daily
which is API call expensive
as 1 shop will mean 1 api call
doing so, to get the shop data alone will make 100k api calls
100k shops is not final value as it could be more

this will have our limit easily exhausted

in V2 we had a way to get these info without much api call by using the public endpoint
https://openapi.etsy.com/v2/users/$userids?includes=Shops,Profile

but in v3, there's no way to get this data using a public endpoint

### Describe the solution you'd like

providing a batch endpoint for getShop `https://openapi.etsy.com/v3/application/shops/batch`
that is same with batch listings which accepts 100 listing ids
per api call will greatly help us minimize 
the resource that we allocate to get the Shop's updated data

### Describe any alternatives you've considered

There's no other way to do this using a public endpoint

**Comment by etsyachristensen** [comment]
@switmac Unfortunately, this is not something we can support.

**Comment by switmac** [comment]
I see, ok @etsyachristensen 

how about for these items are these being considered?
these are alternative for this request

https://github.com/etsy/open-api/issues/196
https://github.com/etsy/open-api/discussions/662
