### ISSUE TITLE
[FEATURE]: Add ShopPromoCode endpoints to manage promo codes

### ISSUE THREAD

**Issue by sowsinsk** [etsy/open-api#636]
### Is there an existing ticket for this?

- [X] I have searched the existing tickets

### Is your feature request related to a problem? Please describe

Currently, there is no way to manage promo codes via the API.

### Describe the solution you'd like

We'd like the ability to programmatically manage shop promo codes. Other types of discounts (sales and targeted offers) are not in the scope of this request. The basic endpoints would be:

- `getShopPromoCode`
- `getShopPromoCodes`: list shop promo codes, with optional parameters (min/max start/end dates, promo_code, type of discount, etc)
- `createShopPromoCode`: add a new promo code to the shop
- `updateShopPromoCode`: update existing promo code

### Additional context

Managing promo codes via the API would open up the ability for creative uses for discounts like:

- targeted one-time offers sent to customers
- automatically rotating shop discounts
- ability for third-party software to create discounts to fulfill specific purposes (coupons included by third-party fulfillment service)

Thanks for your consideration!

**Comment by etsyachristensen** [comment]
This has been suggested in #53 . Will close this as a duplicate and you can track that ticket.
