### ISSUE TITLE
V3 link to get a token getting an error

### ISSUE THREAD

**Issue by gletech** [etsy/open-api#644]
We are trying to use this link to get a token. On any account it gets an error.

We contacted Etsy and they said the account was setup properly, and it may be a syntax error. They said to open a case here

https://www.etsy.com/oauth/connect?response_type=code&client_id=XX&redirect_url=https%3A%2F%2Fwww.gletech.com%2FEtsy%2Fetsy_authentication.cgi&scope=email_r+listings_d+listings_r+listings_w+profile_r+profile_w+transactions_r+&state=1666198348.3730_1666200285getLfofYSGMU&code_challenge=4tjCEmv6aK4yoW5uEkazgmP128anex7uV3N-2zdjw8o&code_challenge_method=S256

Any ideas would be appreciated

Thanks
Mike

**Comment by gletech** [comment]
The error I am getting is

The requested redirect URL is not permitted.

The URL for the callback is set properly

Etsy support has previously set the application domain and said it matches the callback URL

Thanks
Mike

**Comment by etsyachristensen** [comment]
@gletech Sorry for the delay in getting on this. Are you still experiencing the issue? Typically this error has to do with the redirect URL you provided. I don't know which app is yours so I can't look it up, but generally the URL provided in the callback urls on this page: https://www.etsy.com/developers/your-apps. Click the link that says "Edit your callback URLs" on the app you're setting up. If the www.gletech.com domain is not listed there, you will get that error.

**Comment by gletech** [comment]
Hi

When I started working to upgrade to V3 I contacted Etsy Developer support by email and they told me that the Application Domain was not set and they said they set it to https://www.gletech.com, which is the beginning of my callback URL

I have asked by email to double check it but they instead directed me here. All I know is I cannot get by the token process so I cannot develop the rest of the tools we need, and I have clients who want to sell on Etsy that have been asked to wait until V3 is ready for them.

Thank you
Mike
239-634-2172

**Comment by etsyachristensen** [comment]
Ok thanks @gletech Did you try that url I provided above and try to set the Callback URL? I wonder if maybe it wasn't entered properly. I don't have access to the support tickets so I'm not sure what your application id is. Or do you know what your user id is? I can look it up and make sure it's all setup correctly.

**Comment by gletech** [comment]
Hi

Yes, it is set to https://www.gletech.com/Etsy/etsy_authentication.cgi

And has been since before I contacted support.

Thanks
Mike

**Comment by etsyachristensen** [comment]
Ok got it. I've made one change. Can you try it again? The URL looks properly formatted in the request URL.

**Comment by gletech** [comment]
Thanks

I got the same error


An error occurred

The requested redirect URL is not permitted.

https://www.etsy.com/oauth/connect?response_type=code&client_id=XXXXXXXXXX&redirect_url=https%3A%2F%2Fwww.gletech.com%2FEtsy%2Fetsy_authentication.cgi&scope=email_r+listings_d+listings_r+listings_w+profile_r+profile_w+transactions_r+&state=1668604268.8311_1668634962JULP3QF8c74x&code_challenge=_D6qKDiYpO6HBoBFr_Q5AAvrS888YKsdi6xPUIku6oc&code_challenge_method=S256

Thanks
Mike

**Comment by etsyachristensen** [comment]
In your url, you are using `redirect_url` not `redirect_uri`. Can you try changing it to `redirect_uri` and see if that fixes it?

**Comment by gletech** [comment]
That was it, thank you for spotting that

Mike
