### ISSUE TITLE
[BUG] v2 updateListing, cannot update title or description

### ISSUE THREAD

**Issue by marcopaoletti** [etsy/open-api#65]
**Describe the bug**
I cannot change the title or the description of a listing while i can change the state with the same code. 
https://www.etsy.com/developers/documentation/reference/listing  updateListing.

**To Reproduce**
```
<?php

$access_token = ‘TOKEN’;
$access_token_secret = ‘TOKEN_SECRET’;

$api_key = ‘KEY’;
$secret = ‘SECRET’;


try {
$oauth = new Oauth($api_key, $secret);
$oauth->disableSSLChecks();
$oauth->setToken($access_token, $access_token_secret);
$url = “https://openapi.etsy.com/v2/listings/LISTINGID/“;

$params = array(
"title": "new title" 
);

$oauth->fetch($url, $params, OAUTH_HTTP_METHOD_PUT);
$json = $oauth->getLastResponse();
print_r(json_decode($json, true));

} catch (OAuthException $e) {
print_r($e);
error_log($e->getMessage());
error_log(print_r($oauth->getLastResponse(), true));
error_log(print_r($oauth->getLastResponseInfo(), true));
exit;
}

?>
```
I can provide JS code if needed.

**Expected behavior**
The title of the listing should change reflecting the parameters but is not.
Title and description are not changing while the state is changing correctly so it's not an auth problem.

**Screenshots**
The listing: https://www.etsy.com/listing/960458740/prodotto-a-caso?utm_source=nembol&utm_medium=api&utm_campaign=api 

The api response
<img width="1421" alt="Schermata 2021-03-04 alle 19 38 06" src="https://user-images.githubusercontent.com/12425959/110012886-4e8a2080-7d21-11eb-8030-f430774b6179.png">

The title should be "New title for github" but it's still the old one.

Love etsy btw <3 

?>

**Comment by MarcelloMorra** [comment]
I have the same problem. Do you have find the bug?

**Comment by etsyachristensen** [comment]
This has been fixed with a push this morning.
