### ISSUE TITLE
[BUG]: Array input malformed

### ISSUE THREAD

**Issue by davidtxum** [etsy/open-api#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Etsy team,

we are receiving an error when we are trying to update the value of a property (with no restrictions in the allowed values) with a string that contains an open parenthesis character.

Request: updateListingProperty (property 510)

Response:

```
{
    "error": "Array input test (2) is malformed"
}
```
when we insert "test (2)" in the param value.

Could this be a bug on your side?. This restriction is not reported in any place of  your documentation.

Regards

### Steps to reproduce

1. Send a updateListingProperty call to update the property 510 of a listing with the values as a string with a open parenthesis
2. We got the error _Array input "property value" malformed_.

### Expected behavior

We shouldn't receive an error since there is no restriction in the characters we can use in the string.

**Comment by etsyachristensen** [comment]
@davidtxum Can you provide an example of the payload you are sending? You can remove your api key and token of course, but if you can provide the listing id and property info, it will help us get to the bottom of this.

**Comment by davidtxum** [comment]
Hi,
This is an example: 

curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/31265926/listings/1336862075/properties/510' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <token>' \
--header 'x-api-key: <key>' \
--data-urlencode 'value_ids=' \
--data-urlencode 'values=test(2)'

**Comment by etsyachristensen** [comment]
Ah yeah ok. We'll mention it to our taxonomy team, but my guess is that the parenthesis characters aren't allowed.

**Comment by etsyachristensen** [comment]
@davidtxum After a bit of digging, we have confirmed that parenthesis aren't allowed in property values. We will add this info to our documentation.

**Comment by davidtxum** [comment]
Could you please give us the list of not allowed characters in that list?

**Comment by etsyachristensen** [comment]
It should be just the parenthesis characters I believe.
