### ISSUE TITLE
[FEATURE] / [CHANGE] Have the endpoint for finding listings by search term have the ability to actually roughly match how they show up on Etsy search results

### ISSUE THREAD

**Issue by williamgomberg** [etsy/open-api#66]
For as long as I could remember (and probably since the beginning), findAllListingsActive for keywords do not return results that match up with actual Etsy search. I would've assumed this is what sort_on=score was, but no. I know on the forums, people have complained about this for years, and I think it would be extremely useful if this could be addressed in v3. I can't speak for everyone, but I do strongly believe the inability to sort by relevancy in the way searches rank on etsy results makes the feature much less useful, and the ability to sort_on=score just has very little use to it.

Yes. I am aware of the personalization in Etsy search results. However, I am also aware, from testing, that the personalization, with the exception of products that simply do not ship to certain regions, do not vary in rank to such a tremendous point that this endpoint wouldn't be useful. Personalization could be applied from the account you're logged in to when pulling results, or however else, but I think this would be an amazing implementation and would likely get many people who currently scrape Etsy to start using the API.

**Comment by benjymouse** [comment]
+100 this would be very useful

**Comment by NellyGzzA** [comment]
Hi @williamgomberg ! 👋  Thank you so much for your feedback!
I've created a research ticket in order to dig more into this behavior so we can provide the expected functionality for this endpoint in v3.

**Comment by shubham0804** [comment]
+1. Would be very useful for me as well.

**Comment by williamgomberg** [comment]
Glad to hear it's being taken into consideration. I truly think it'll open a whole new scope of useability and stop scraping. Any update on if this will indeed be implemented? 👍 thank you :)

**Comment by benjymouse** [comment]
Would be great if we could add a parameter to specify a country so that the results roughly resemble what people in other countries see. For example, a parameter like `country=DE` that would only show results that are available to German shoppers.

**Comment by etsyachristensen** [comment]
@williamgomberg @shubham0804 This was actually fixed about a month ago or so. The endpoint now uses the same search mechanism as Etsyweb. If you still have any issues with the endpoint, please feel free to re-open the issue.

@benjymouse regarding your request about the country, could you post this as a separate issue if this is still something important to you?

**Comment by benjymouse** [comment]
@etsyachristensen It appears that sort_on=score was not implemented, or perhaps I am doing something wrong. Can you please advise? Thanks
