### ISSUE TITLE
[ENDPOINT] Proposed design change for User or getShop 

### ISSUE THREAD

**Issue by shubham0804** [etsy/open-api#68]
**Current Endpoint Design**
I need the country in which a shop is & it's transaction_sold_count, which I used to get from 'User/Profile(country_id,transaction_sold_count)' or 'User/Profile(transaction_sold_count)/Country' association on 'getShop' method of v2. Also, country of some shops is shown 'null' in api even though it is visible on Etsy using v2 endpoints.

**Proposed Endpoint Design Change**
It would be great if country and transaction_sold_count of a shop can be retrieved(without oAuth), since it is public data.

**Why are you proposing this change?**
Need it to run analytics on shops

**Comment by etsyachristensen** [comment]
@shubham0804 Just reviewing issues and cleaning up our list. Please re-open this issue if you do not have what you need now to satisfy this request.
