### ISSUE TITLE
[FEATURE] Add association data to getShopPaymentAccountLedgerEntries

### ISSUE THREAD

**Issue by missnicbic** [etsy/open-api#70]
**Is your feature request related to a problem? Please describe.**
When BillCharges was deprecated in favour of the account ledger methods, we lost the ability to see what the charge was linked to (we used to use the "type" and "associated type id" fields to do this). This resulted in our app losing the ability to associate fees to listings and receipts to calculate profitability.

**Describe the solution you'd like**
Add a method to getShopPaymentAccountLedgerEntries that allows us to see what receipt / listing the charge relates to.

**Describe alternatives you've considered**
We have attempted to derive the likely receipt that charges are associated with using timestamps, however, these can differ from the receipt by up to 60 seconds in some cases.

**Additional context**
Have spoken at length with Etsy API team about this when the change was made.

**Comment by Talie** [comment]
Second this feature request. Using timestamps is not viable - especially for ledger entries relating to 'auto_renew_expired' and 'listing'. If the listing is sold between the creation of the ledger entry and using the API to check the ledger, the listings timestamp is reset to the sale time and is no longer anywhere close to the 'auto_new_expired' time.

**Comment by samborambo305** [comment]
@etsyachristensen is there a way to get associate a ledger entry with a receipt? Apparently this was possible in V2. If this is not possible for V3 then from an accounting perspective, my users are not able to know whether or not certain transactions were impacted by marketplace facilitator sales taxes which would artificially boost the revenue component of a receipt.
