### ISSUE TITLE
Inventory Variation Listing

### ISSUE THREAD

**Issue by IanDanielM** [etsy/open-api#700]
When listing manually, one can create a new variation type, say 'Packagesize,' but I don't see anywhere in the API documentation or endpoints where I can create a variation type that will return the id as required in listing. Could you please advise?</div>

**Comment by IanDanielM** [comment]
Kindly answer instead of closing the issue?

**Comment by etsyachristensen** [comment]
I'm answering in the discussion. We are not using the issues board moving forward. Only the discussions. Please refrain from converting or creating issues.

**Comment by IanDanielM** [comment]
Okay,
