### ISSUE TITLE
[BUG] v3 get shop not working

### ISSUE THREAD

**Issue by straz** [etsy/open-api#72]
**Describe the bug**
I’m able to use your v2 API just fine to retrieve a shop listing. But the same request in v3 fails.

```
GET https://openapi.etsy.com/v2/shops/7177635?api_key=<secret>
200 OK
```

**To Reproduce**
When I make the same request with v3, it returns `404 Not found`

```
GET https://openapi.etsy.com/v3/application/shops/7177635  —headers x-api-key: <secret>
404 Not found
```

**Expected behavior**
I expect it to return `200 OK` with the shop details

**Comment by turboturtleD** [comment]
I get a 404 Not Found from all v3 endpoints.  I do get a "pong" response from `https://api.etsy.com/v3/member/ping` though.

**Comment by turboturtleD** [comment]
Unrelated issue for me I guess, just wasn't whitelisted with the client_id that I was trying to use.

**Comment by RichT-K** [comment]
I'm also receiving 404 on all non-auth calls.

Nomenclature is tough: In this issue alone I see <secret> substituting <api_key>, member substituting client_id whatever its supposed to be ie. the shop id???
New to v3 I'm having difficulty discerning what's being asked and what the solution is.

Is there a glossary of terms? 

Looking forward to interfacing with V3, soon.

**Comment by capndesign** [comment]
Hi @RichT-K! Have you requested access to the v3 endpoints yet? If not, we link to [this form](https://docs.google.com/forms/d/e/1FAIpQLSc4qzVlgjkzEkaQvpgX00xvJLjlomRoS-60G9ob_FqCfmbCrA/viewform) in the README. If you have and still need access, send a note to developer@etsy.com (with your Github username included) and I’ll make sure you get access right away.

I also realize no one responded to you yet, @straz. If you’re still having trouble, please write in!

**Comment by RichT-K** [comment]
Thanks for the quick reply.
Yes, a month or so ago and received confirmation it went through from Joey.
Rich

From Joey - Mar 9, 2021
You now have access to Open API v3 Endpoints

Hello there,
Thank you for your interest in accessing the alpha version of Etsy’s Open
API v3. We’ve authorized your application (and API keys) to make requests
to endpoints listed in our new reference documentation
<https://www.etsy.com/openapi/developers?campaign_label=iris_message_sends&utm_source=transactional&utm_campaign=iris_message_sends_010170_39203008399_0_0&utm_medium=email&utm_content=&email_sent=1615308070&euid=2MuZqtIZHRblsJRkVuB3ZNfk0q3O&x_eaid=7721bd0f22&link_clicked=0>
.

We’d like to remind you that your use of the alpha version of Etsy’s Open
API v3 is subject to Etsy’s Open API Developer Terms
<https://www.etsy.com/legal/policy/etsys-open-api-developer-terms-terms/1001713141442?campaign_label=iris_message_sends&utm_source=transactional&utm_campaign=iris_message_sends_010170_39203008399_0_0&utm_medium=email&utm_content=&email_sent=1615308070&euid=2MuZqtIZHRblsJRkVuB3ZNfk0q3O&x_eaid=7721bd0f22&link_clicked=1>.
The endpoints are still in development and could change with little or no
notice.

...
Thank you for your interest and enthusiasm in Etsy’s Open API. We can’t
wait to hear what you think!

Best,
Joey
Etsy Developer Support

**Comment by turboturtleD** [comment]
Glossary help:

"secret", "API Key", and "client_id" are all the same thing.

*member" is a literal and is actually part of a what appears to be now a deprecated test path `https://api.etsy.com/v3/member/ping`   which may or may not still work.

**Comment by RichT-K** [comment]
That's awfully confusing when in the
https://www.etsy.com/developers/register/preview:
When keystring is the api key and shared secret is what it is.
A glossary would help to clear things up.

KEYSTRINGg7...
SHARED SECRETth...

**Comment by RichT-K** [comment]
thanks - moving correspondence to developer @ etsy

**Comment by RichT-K** [comment]
This may be an administration setup issue rather than a bug since my issue has been resolved via a granting of access to my account to the api with my specific api_key. 

Thanks for the attention and account update!

**Comment by harjas** [comment]
@RichT-K closing this issue since this seems to be resolved. Let me know if you feel otherwise?
