### ISSUE TITLE
[ENDPOINT] Proposed design change for ShippingProfile: Delivery time

### ISSUE THREAD

**Issue by anssih** [etsy/open-api#73]
**Current Endpoint Design**
On Etsy website, shipping profile destinations can be configured with a "Shipping carrier" and "Delivery time", allowing customers to be shown an estimated delivery date on listing pages.

However, these are missing from the API ShippingProfile endpoints.

I'm only interested in "Delivery time" (with carrier set as "Other"), but others might want to set the carrier as well.

**Proposed Endpoint Design Change**
Add `min_delivery_days` and `max_delivery_days` to the ShippingProfile endpoints. Possibly also `carrier`.

**Why are you proposing this change?**
We want customers to know the estimated delivery date to reduce queries and disappointments, especially now with the pandemic slowing down international mail.

**Comment by harjas** [comment]
@anssih we've added both `min_delivery_day`, `max_delivery_days` and `carrier` to the shipping profiles:
https://www.etsy.com/openapi/developers#operation/createListingShippingProfile

Let me know how this goes for you! If things are looking good, I'll close the issue.

**Comment by harjas** [comment]
closing this issue since we now support carrier in the shipping profiles
