### ISSUE TITLE
[BUG] getListingInventory returns incorrect values for price_on_property array

### ISSUE THREAD

**Issue by turboturtleD** [etsy/open-api#82]
**Describe the bug**
When loading inventory data using getListingInventory for a listing with a custom property (513), the price_on_property array returns unexpected value [2].  Uncertain about the quantity and sku values, would have expected something like null or [ ].

**To Reproduce**
Make a request to the endpoint for item with varying prices based on a custom property value.

**Expected behavior**
Expected to return array of property_ids associated with the values that control price.  Expected to get [513], instead getting [2]

**JSON**: `{"products":[{"product_id":4640427622,"sku":"","is_deleted":false,"offerings":[{"offering_id":4507724927,"quantity":78,"is_enabled":true,"is_deleted":false,"price":{"amount":1095,"divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Options","scale_id":null,"scale_name":null,"value_ids":[72265205302],"values":["Loose (as pictured)"]}]},{"product_id":4408164793,"sku":"","is_deleted":false,"offerings":[{"offering_id":4620037712,"quantity":78,"is_enabled":true,"is_deleted":false,"price":{"amount":1495,"divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Options","scale_id":null,"scale_name":null,"value_ids":[2892311016],"values":["Gift Box"]}]},{"product_id":4640427638,"sku":"","is_deleted":false,"offerings":[{"offering_id":4507724939,"quantity":78,"is_enabled":true,"is_deleted":false,"price":{"amount":1595,"divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Options","scale_id":null,"scale_name":null,"value_ids":[11695797204],"values":["Add Custom Engraving"]}]},{"product_id":4640427640,"sku":"","is_deleted":false,"offerings":[{"offering_id":4507724941,"quantity":78,"is_enabled":true,"is_deleted":false,"price":{"amount":1995,"divisor":100,"currency_code":"USD"}}],"property_values":[{"property_id":513,"property_name":"Options","scale_id":null,"scale_name":null,"value_ids":[28255955019],"values":["Engraving + Box"]}]}],`**"price_on_property":[2]**`,"quantity_on_property":[1],"sku_on_property":[1]}`

**Comment by main24** [comment]
We experience the same issue, returns 0 when the V2 API returns array of property ids like `[200, 513]`.

Also [update listing inventory](https://developer.etsy.com/documentation/reference/#operation/updateListingInventory) requires list of ids, i.e. `[200, 513]`, rather than 0 or 1, however it expects to receive whole inventory with just updated values, like quantity. 

If 0, 1 and 2 are now expected values, could you please clarify usage of those values, i.e. how to map them to the correspondent property ids. This is absolutely important as it affects identification of variants and the logic of updating quantity and price. With V3 API it looks like it's impossible to update price/quantity without knowledge of how to deal with `*_on_property` values.

Thank you in advance.

**Comment by etsyachristensen** [comment]
We are looking at this now. We will try to get you a response very soon. Thank you for bringing this up.

**Comment by nepod1988** [comment]
If it helps: when listing has more than one property Etsy responses with correct *_on_property values

**Comment by etsyachristensen** [comment]
We have a fix in progress that just needs final testing. Hoping to get this out very soon. Sorry for the trouble.

**Comment by etsyachristensen** [comment]
Hey all. We pushed a change that should correct this. The *_on_property arrays will have just the property ids listed on the request. Please test and let me know if there are any issues.

**Comment by nepod1988** [comment]
does not work for me. 
 "price_on_property"=>[],
 "quantity_on_property"=>[],
 "sku_on_property"=>[]

**Comment by calunia** [comment]
Hello,
Same here, all fields are empty. I paste the body of the response, if it can help you.

`{"products":[{"product_id":7641022258,"sku":"","is_deleted":false,"offerings":[{"offering_id":7492450469,"quantity":1,"is_enabled":true,"is_deleted":false,"price":{"amount":2200,"divisor":100,"currency_code":"EUR"}}],"property_values":[]}],"price_on_property":[],"quantity_on_property":[],"sku_on_property":[],"listing":null}`

**Comment by etsyachristensen** [comment]
@calunia I'd like to look into this more with your listing. Can you email developers@etsy.com and provide your Shop ID and Listing ID for the above example you shared?

**Comment by turboturtleD** [comment]
Yeah, still no dice here.  Getting empty sets for price_on_prop when there is clearly price variation in the data.

`"{\"products\":[{\"product_id\":4672438105,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4883816020,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1295,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[88975186335],\"values\":[\"As Pictured\"]}]},{\"product_id\":4672438109,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4775651105,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1795,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[109781355221],\"values\":[\"Add Custom Engraving\"]}]}],\"price_on_property\":[],\"quantity_on_property\":[],\"sku_on_property\":[],\"listing\":null}"`

**Comment by etsyachristensen** [comment]
> Yeah, still no dice here. Getting empty sets for price_on_prop when there is clearly price variation in the data.
> 
> `"{\"products\":[{\"product_id\":4672438105,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4883816020,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1295,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[88975186335],\"values\":[\"As Pictured\"]}]},{\"product_id\":4672438109,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4775651105,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1795,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[109781355221],\"values\":[\"Add Custom Engraving\"]}]}],\"price_on_property\":[],\"quantity_on_property\":[],\"sku_on_property\":[],\"listing\":null}"`

Thanks @turboturtleD can you also email developers@etsy.com with the Shop ID and Listing ID and reference the Github Bug #82?

**Comment by turboturtleD** [comment]
> > Yeah, still no dice here. Getting empty sets for price_on_prop when there is clearly price variation in the data.
> > `"{\"products\":[{\"product_id\":4672438105,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4883816020,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1295,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[88975186335],\"values\":[\"As Pictured\"]}]},{\"product_id\":4672438109,\"sku\":\"\",\"is_deleted\":false,\"offerings\":[{\"offering_id\":4775651105,\"quantity\":994,\"is_enabled\":true,\"is_deleted\":false,\"price\":{\"amount\":1795,\"divisor\":100,\"currency_code\":\"USD\"}}],\"property_values\":[{\"property_id\":513,\"property_name\":\"Customization\",\"scale_id\":null,\"scale_name\":null,\"value_ids\":[109781355221],\"values\":[\"Add Custom Engraving\"]}]}],\"price_on_property\":[],\"quantity_on_property\":[],\"sku_on_property\":[],\"listing\":null}"`
> 
> Thanks @turboturtleD can you also email [developers@etsy.com](mailto:developers@etsy.com) with the Shop ID and Listing ID and reference the Github Bug #82?

Somehow my email got forwarded to trust and safety... you guys really have some kinks to work out with that email address.

**Comment by etsyachristensen** [comment]
Ok so the variations component to Etsy's system is by far one of the most complicated parts of our architecture due to the way it takes variations and creates individual products for each variation that is possible. Add to that, when prices, skus and quantity affect the variation options it becomes quite a tree of products. Most the folks that developed the V2 system have moved on to other teams or other jobs, hence we've been building the V3 API. I'm relatively new but trying my best to pick up the flag and run with it, so please bear with me. We are absolutely committed to making this element work as well as, or better than, the V2 API.

All that to say, I *believe* I have worked out the issue and I've posted an update to the api for the getListingInventory endpoint that should now return the appropriate property ids in the `on_property` arrays.

Please give it a try when you have a chance and let me know if you are still having trouble.

**Comment by turboturtleD** [comment]
It seems to be working correctly for me, as I am now getting expected values.  I'd like to leave this thread open to comment just a little longer, but as far as I'm concerned, this issue seems resolved.

**Comment by etsyachristensen** [comment]
Sure thing. I'll leave it open. But i'll add a label so we know not to keep reviewing unless we get some new posts. Thanks!
