### ISSUE TITLE
[BUG] findAllListingsActive not returning documented results

### ISSUE THREAD

**Issue by RichT-K** [etsy/open-api#88]
When querying findAllListingsActive with keywords=audubon results are returned with
with keywords(tags member ) fieldset having no value of "audubon".

Reproduce with the following query:
https://openapi.etsy.com/v3/application/listings/active?keywords=audubon&offset=0&limit=24

Expected:
A result containing ONLY listings with the keyword "audubon" in the tags member fieldset.

Actual (partial list showing the unexpected partial item):
{
            "listing_id": 737127995,
            "user_id": 39498977,
            "shop_id": 8773990,
            "title": "Morning Dove by Audubon, Fine Art Print, Poster, Birds, Kids, Animal, Nature, Home Decor, Gift, Wall Art, Accent, Not Framed, Not Matted",
            "description": "Back to the main page of this shop:\nhttps://www.etsy.com/shop/PremiumBoutique\n\nTITLE: Zenaida Macroura (Morning Dove)\nVintage illustration made by Audubon\nMEDIUM: Poster, Fine Art Print\nPRINT SIZES and PRICES: ...All Rights Reserved.",
            "state": "active",
            "tags": [
                "illustration",
                "vintage",
                "gift",
                "nature",
                "classic",
                "Christmas",
                "animal",
                "accent",
                "birthday gift",
                "kids",
                "nature lover gift",
                "bird",
                "morning dove"
            ],
...        }

I'm guessing there's a database process behind the scenes building a keyword set from record members like title, description, tags and others. Currently it hit and miss which records will be returned, the example above is record 8 in the first page of 24 results.

Queries returning records based on ambiguous or multi-field values should be clearly documented to better understand the expectations. 

A solution to this would be the addition of a tags parameter in the search and ONLY search tags. 
Additional options would be title, description, materials parameter to search on.

**Comment by jonbasebl5** [comment]
Hi @RichT-K thanks for the report! I was just looking into this and it looks like the current underlying functionality when a keyword is specified is that it searches across multiple fields (similar to how search works on etsy.com). So we can at least improve the documentation of these params to make it more clear what's happening.

So I can properly flesh out a spec on my side for your idea to search by tags (and other individual fields), can you provide any additional information about the current or potential functionality you'd provide in your app (to yourself, or other users) that would use this capability?

Thanks again!

**Comment by etsyachristensen** [comment]
@RichT-K I believe this has been fixed by this point. If you find that it isn't please re-open the issue by respondind to the comment above and provide the requested information.
