### ISSUE TITLE
An update on Open API v3

### ISSUE THREAD

**Issue by capndesign** [etsy/open-api#90]
Thank you so much to everyone who has been sharing feedback on Open API v3. It’s helped our team understand your priorities and we really appreciate your time and insights. 

We’ve moved our focus to preparing for the general release. That means our priority for development is on completing endpoints and fixing bugs. Our goal is to get v3 in your hands sooner so you can have as much time to migrate as possible.

We’d still love your feedback during this phase and it would be especially helpful if you can focus on finding bugs. We will continue to prioritize the new features you have requested and plan to start implementing them after core functionality is complete. We’ll share more details on our next release in the next month or two.

**Comment by shubham0804** [comment]
Thank you for the update. Kindly ensure that #61 & #92 are implemented

**Comment by missnicbic** [comment]
Can we possibly get some (rough) timeframes on when all v3 methods will be fully production ready and when v2 is slated to be deprecated? We need to plan development resource to handle this change so any dates you could share with us would be much appreciated.

**Comment by Dmarcotrigiano** [comment]
What stage is the API in? Your general release is scheduled to be within Q3 which begins in 15 days, but the API appears to be mostly access controlled. My client and I are waiting to hear back from developers@etsy.com for about a month now, with 5 emails sent pertaining to access for the Open API v3. Please provide us with an update so that we may carry on with our responsibilities.

**Comment by amandalik** [comment]
wa

**Comment by myw-ben** [comment]
@Dmarcotrigiano Were in exactly the same position. 4 outstanding emails with developers@etsy.com with zero response. 

Everything we read is pushing us to use v3, however, from what we can see, v3 is way off being ready for production. Half of the endpoints are still in Alpha, and say to email developers@ to get access, but there's no response from there.

@capndesign Is there any official update on this yet? It's having a real impact on businesses.

**Comment by harjas** [comment]
@Dmarcotrigiano and @myw-ben, we removed the gate to the alpha a few weeks ago. We're sorry you haven't received the replies you expected from developers@ but we're hard at work on getting to everything! Please bear with us.  🙏 

In the meantime, you should have access to OpenAPI v3 right now. Please let us know how that works for you!
