### ISSUE TITLE
[ENDPOINT] Proposed design change for getListing

### ISSUE THREAD

**Issue by shubham0804** [etsy/open-api#91]
**Current Endpoint Design**
The getListing endpoint of v3 does not accept an array of listing ids, unlike v2.

**_v2 Docs:_**
![etsy api listing](https://user-images.githubusercontent.com/52071475/115820160-ea7d0200-a41d-11eb-91ad-30c412b44d78.PNG)

**Proposed Endpoint Design Change**
Have the v3 endpoint accept an array of listing ids.

**Why are you proposing this change?**
Our code currently implements querying multiple listings using a single endpoint. Moreover it's easier and efficient do so as well.

**Comment by NicholasPegler-LW** [comment]
+1 
We use this to get the current state of the listings

**Comment by harjas** [comment]
Hi @NicholasPegler-LW and @shubham0804! Our intention here was to design the API to be more intuitive and conform to API design conventions common across this industry. As you can see, the `listing_id` parameter would make it seem that you're only querying a single `listing_id`. 

Can you work around with the current design? I understand that it results in more individual calls per `listing_id`. The other workaround could be that we add a new `getMultipleListings` endpoint that accepts multiple listing_ids but before that, could you also talk about what is the max number of listings that you're trying to query for with this endpoint?

**Comment by NicholasPegler-LW** [comment]
@harjas  Thank you for your response, `getMultipleListings` endpoint would certainly work.

Currently we limit to a max of 500 stock items, though if there are multiple listings attached to a single stock item that could easily quadruple.

**Comment by harjas** [comment]
Could you also talk about why you need to query with multiple listing IDs that querying individually would not suffice?

**Comment by benjymouse** [comment]
+1 for this

@harjas We find that batching 100 listing_id's together improves processing time by around 15x. This great for our customers who have questions they want answered in near real-time. A workaround for us would be to spawn new threads to achieve similar performance, though then we would need to be mindful of our API limits. We're open to this change, but from our perspective this is a regression that forces us to develop a new and less-than-elegant solution.

**Comment by shubham0804** [comment]
@harjas I agree with @benjymouse. We also query the current v2 endpoint for around 100 listing ids. An endpoint like `getMultipleListings` would get the job done. 

Kindly also look into implementing the same for #61, even though multiple listing ids is not supported in the `getLisintingInventory` of v2, having it in v3 would be great!

**Comment by etsyachristensen** [comment]
@shubham0804 Now that we have the `getListingsByListingIds` endpoint ([here](https://developers.etsy.com/documentation/reference#operation/getListingsByListingIds)) we are closing out this issue.
