### ISSUE TITLE
[ENDPOINT] Proposed design change for getShop

### ISSUE THREAD

**Issue by shubham0804** [etsy/open-api#92]
**Current Endpoint Design**
There is no way to get the transaction_sold_count of a shop in v3. Currently I'm using the getShop endpoint of v2 and the associations User/Profile to get the transaction_sold_count. There seems to be no way to use associations in v3.

**Proposed Endpoint Design Change**
Either add transaction_sold_count to the endpoint or implement associations, as was the case in v2 to retrieve the transaction_sold_count.

**Why are you proposing this change?**
The transaction_sold_count of a shop is visible on the Etsy website & should be available through the api as well.

**Comment by shubham0804** [comment]
Hi Etsy api team! 

I hope this issue is being considered & is under investigation.

**Comment by harjas** [comment]
Hi @shubham0804, we've made this change and its live for the `getShop` endpoint. Give it a spin and let us know!

**Comment by shubham0804** [comment]
@harjas It works now. This definitely solves one of the objections I had about v3. Thanks! If you could solve #61, I would have no issues migrating to v3

**Comment by harjas** [comment]
Closing since this has been fixed!
