### ISSUE TITLE
Sort listings by title and last update date

### ISSUE THREAD

**Issue by assaflei** [etsy/open-api#94]
Currently the API for getting listings details supports sorting by price, creation date and score (which is not understood from the [documentation](https://www.etsy.com/developers/documentation/reference/listing#method_findalllistingactive)) 

The context of my usage, which is for an inventory management app requires more flexibility.
Currently I have to get all listings and perform the sort on my side.

**Comment by harjas** [comment]
Hi @assaflei some of the listing endpoints now support sorting by update date. Let us know how this works for you:

https://developers.etsy.com/documentation/reference/#operation/getListingsByShop
https://developers.etsy.com/documentation/reference/#operation/findAllListingsActive
https://developers.etsy.com/documentation/reference/#operation/getListingsByShopSectionId

**Comment by etsyachristensen** [comment]
@assaflei If you have any issues with sorting, please feel free to reopen this issue.
