### ISSUE TITLE
[ENDPOINT] Proposed design change for <endpoint name here> 

### ISSUE THREAD

**Issue by ssaidaone** [etsy/open-api#95]
**Current Endpoint Design**
What in the current endpoint design do you think is missing or find confusing?

**Proposed Endpoint Design Change**
Add information about your proposed change.

**Why are you proposing this change?**
Please provide a reason for the change you're proposing.

**Comment by harjas** [comment]
@ssaidaone do you want to update this issue with more details? If not, I'll close this issue soon.

**Comment by harjas** [comment]
closing because this has no details
