### ISSUE TITLE
[BUG] Trouble accessing v3 API

### ISSUE THREAD

**Issue by benjymouse** [etsy/open-api#98]
**Describe the bug**
Unable to access v3 API. 

**To Reproduce**
Sorry to post here, but we are getting desperate and stressed.

We have been granted access to the v3 API but our developers need additional help to start testing. 

Over the past 14 days, we have sent several requests to developer@etsy.com and developers@etsy.com for new redirect URLs. To date we have not received any response. Are you guys receiving our emails? Someone please help.

**Comment by capndesign** [comment]
Hi @benjymouse. Sorry for all the trouble you’re having. I’m happy to help.

First, you should be able to edit your callback URLs by clicking on the title of your app at https://www.etsy.com/developers/your-apps. 

I’m also happy to just handle your requests in our API Support queue myself. It can be tough to map GitHub users to Etsy users, so the easiest way to make sure I can find if you is to send a new email, mention your github username, and I’ll take care of it today.

**Comment by benjymouse** [comment]
Thanks @capndesign - I've added those callback URLs as per your instruction. That was embarrassingly easy for me to do! :) 

I've sent you a note via the developer email - hopefully you can find me there. 

Thanks again and sorry for the 911.
