### ISSUE TITLE
Discord group [FEATURE] 

### ISSUE THREAD

**Issue by kbasali** [etsy/open-api#99]
**Is your feature request related to a problem? Please describe.**

We are going through a very difficult period for everyone because of the pandemic.

And we really appreciate your help and support, we understand that it may not be easy for you always too but it would be really good for us to get some more assistance from you because sometimes we are waiting for your reply to our email to develop the tool and for updates, and some of us are waiting for this reply for 1 month.

Unfortunately, this is not a very scalable situation for a startup.

Especially since you announced API v3, it has become more and more difficult to get answers from you.

Is it possible to ask questions directly and get quick answers with Discord or any similar categorizable chat platform?

Any platform could be even **ICQ** :)

**Comment by capndesign** [comment]
Hi there! If you’re waiting on responses from a request sent to developer@etsy.com, feel free to write again and mention your Github user account and I’ll make sure it gets answered quickly.

As for Discord, Etsy doesn’t have any plans to maintain any real-time chat support for our Open API. We do have a [Google Group](https://groups.google.com/g/etsy-api-v2) where you can ask other developers for advice.

**Comment by kbasali** [comment]
Hello  @capndesign.

I'm waiting for some answers for a month but as your adviced, I'll mention my name in the new emails.

**Comment by benjymouse** [comment]
@kbasali i have found stackoverflow quite handy, you could try there

**Comment by kbasali** [comment]
@benjymouse Thank you so much, I checked there but still, I can't find the answers that I'm looking for. 
Some of the questions include dilemma  :) :) 

@capndesign I've sent the email and my email title is "Requested by Matt Jacobs - Github kbasali"
I asked 7 lovely joyful questions to you or the team :
